src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country_of_Residence_GLBL__c</fullName>
        <description>Country of residence which may differ from the Country to be used for contract fee calculation.  Needed for Tax Purposes in Invoice.
Created by John A Adams 10/20/2013</description>
        <label>Country of Residence</label>
        <picklist>
            <picklistValues>
                <fullName>ES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AF</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Meeting_MERC__c.object
<CustomObject>
</CustomObject>

src/classes/MERC_AddTeamMembersController.cls
public with sharing class MERC_AddTeamMembersController {

	/*----  Search Fields & Dummy Account ---------*/
	public String  firstName			{ get; set; }
	public String  lastName 			{ get; set; }
	public String  email 				{ get; set; }
	public Account searchAccount 		{ get; set; }
	public String  territoryCode 		{ get; set; }
	public String  territoryId 			{ get; set; }
	public String  territoryDescription { get; set; }

	public List<SearchResult> searchResults = new List<SearchResult>();

	/*-- The meeting passed in the id param --*/
	private final Meeting_MERC__c meeting;

	private final Id employeeRecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND DeveloperName='Employee_GLBL' LIMIT 1].Id;

    /* The extension constructor initializes the private member
       variable acct by using the getRecord method from the standard
       controller.*/
    public MERC_AddTeamMembersController(ApexPages.StandardController stdController) {
        this.meeting = (Meeting_MERC__c)stdController.getRecord();
        searchAccount = new Account();
    }

    public void performSearch()
    {
    	searchResults.clear();
    	String queryString = buildAccountQueryString();

    	for (Account a: Database.query(queryString))
    	{
    		searchResults.add( new SearchResult(a));
    	}
    }

    private String buildAccountQueryString()
    {
    	String queryString = 'SELECT Id';
    	queryString += ' FROM Account WHERE RecordTypeId = :employeeRecordTypeId';
    	queryString += String.isNotBlank(firstName) ? ' AND FirstName LIKE \'' + firstName + '%\'' : '';
    	queryString += String.isNotBlank(lastName ) ? ' AND LastName LIKE \''  + lastName  + '%\'' : '';
    	queryString += String.isNotBlank(email) ? ' AND PersonEmail=:email' : '';
    	queryString += String.isNotBlank(searchAccount.Country_of_Residence_GLBL__c) ? ' AND Country_of_Residence_GLBL__c=:searchAccount.Country_of_Residence_GLBL__c' : '';

    	return queryString;
    }

    public class SearchResult
    {
    	public Account acct { get; private set; }

    	public SearchResult(Account a)
    	{
    		this.acct = a;
    	}
    }
}