src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Annual_CAP_Limit_MERC__c</fullName>
        <description>Stores the current years annual cap limit for formula calculations. Oliver Dunford 6th Nov 2013.</description>
        <label>Annual CAP Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Country_Code_MERC__c</fullName>
        <description>Country Code of Residence pulled from User to be used in the Meeting - Worker Country Code.  Created by John Adams on 12/9/2013</description>
        <formula>TEXT(Country_of_Residence_GLBL__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_of_Residence_GLBL__c</fullName>
        <description>Country of residence which may differ from the Country to be used for contract fee calculation.  Needed for Tax Purposes in Invoice.
Created by John A Adams 10/20/2013</description>
        <label>Country of Residence</label>
        <picklist>
            <picklistValues>
                <fullName>ES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AF</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/CAP_Settings_MERC__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Stores country specific annual cap.
Created by John A Adams 10/24/2013</description>
    <fields>
        <fullName>Annual_Amount_MERC__c</fullName>
        <description>Annual CAP value per country
Created by John A Adams 10/24/2013</description>
        <label>Annual Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Country_Code_MERC__c</fullName>
        <description>Stores the country name that CAP applies to.
Created by John A Adams 10/24/2013</description>
        <label>Country Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Currency_Code_MERC__c</fullName>
        <description>Maps the CAP Currency Code to the Country for calculations.  Created by Oliver Dunford 28th Oct 2013.</description>
        <label>Currency Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year_MERC__c</fullName>
        <description>Stores the year that the CAP value is applied.  Used text field as Data requires entry of day and month, and Number inserts a comma in value
Created by John A Adams 10/24/2013</description>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>CAP by Country</label>
</CustomObject>

src/classes/MERC_HcpCapLimitCalculator.cls
/**
 * @author Joseph Ferraro
 *
 * Responsible for calculating annual cap limit for HCP based on CAP_Settings_MERC__c Custom Setting data
 */


public with sharing class MERC_HcpCapLimitCalculator implements GLBL_TriggerHandler.HandlerInterface {

	public Boolean isActive() {
		return MERC_TriggerHandlerStateManager.isActive(MERC_HcpCapLimitCalculator.class);
	}

	public void handle() {
		if (Trigger.isInsert || Trigger.isUpdate) {
	    	execute(Trigger.new);
	   	}
	}

	void execute(List<Sobject> sobjects) {
		List<Account> accs = (List<Account>)sobjects;
		List<Account> accountsToProcess = new List<Account>();
		Set<String> countries = new Set<String>();
		for (Account a : accs) {
			if (Trigger.isInsert) {
				if (a.Country_of_Residence_GLBL__c != null)
					countries.add(a.Country_of_Residence_GLBL__c);
					accountsToProcess.add(a);
			} else if (Trigger.isUpdate) {
				if ((String)Trigger.oldMap.get(a.Id).get('Country_of_Residence_GLBL__c') != a.Country_of_Residence_GLBL__c) {
					if (a.Country_of_Residence_GLBL__c != null) {
						countries.add(a.Country_of_Residence_GLBL__c);
						accountsToProcess.add(a);
					} else {
						a.Annual_CAP_Limit_MERC__c = null;
					}
				}
			}
		}

		String currentYear = String.valueOf(Date.today().year());
		Map<String, List<CAP_Settings_MERC__c>> capMap = new Map<String, List<CAP_Settings_MERC__c>>();
		for (CAP_Settings_MERC__c capSetting : [SELECT 
													Annual_Amount_MERC__c, 
													Year_MERC__c,
													Country_Code_MERC__c, 
													Currency_Code_MERC__c
														FROM CAP_Settings_MERC__c 
															WHERE Country_Code_MERC__c in :countries AND Year_MERC__c = :currentYear]) {
			if (capMap.containsKey(capSetting.Country_Code_MERC__c)) {
				List<CAP_Settings_MERC__c> capList = capMap.get(capSetting.Country_Code_MERC__c);
				capList.add(capSetting);
				capMap.put(capSetting.Country_Code_MERC__c, capList);
			} else {
				List<CAP_Settings_MERC__c> capList = new List<CAP_Settings_MERC__c>{capSetting};
				capMap.put(capSetting.Country_Code_MERC__c, capList);
			}
		}

		for (Account a : accountsToProcess) {
			String accountCountry = a.Country_of_Residence_GLBL__c;
			List<CAP_Settings_MERC__c> capSettings = capMap.get(a.Country_of_Residence_GLBL__c);
			
			if (capSettings != null) {
				for (CAP_Settings_MERC__c capSetting : capSettings) {
					if (capSetting.Country_Code_MERC__c == accountCountry) {
						a.Annual_CAP_Limit_MERC__c = capSetting.Annual_Amount_MERC__c;
						break;
					}
				}
			}
		}
	}
}