src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Annual_CAP_Limit_MERC__c</fullName>
        <description>Stores the current years annual cap limit for formula calculations. Oliver Dunford 6th Nov 2013.</description>
        <label>Annual CAP Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Country_Code_MERC__c</fullName>
        <description>Country Code of Residence pulled from User to be used in the Meeting - Worker Country Code.  Created by John Adams on 12/9/2013</description>
        <formula>TEXT(Country_of_Residence_GLBL__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_of_Residence_GLBL__c</fullName>
        <description>Country of residence which may differ from the Country to be used for contract fee calculation.  Needed for Tax Purposes in Invoice.
Created by John A Adams 10/20/2013</description>
        <label>Country of Residence</label>
        <picklist>
            <picklistValues>
                <fullName>ES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/CAP_Settings_MERC__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Stores country specific annual cap.
Created by John A Adams 10/24/2013</description>
    <fields>
        <fullName>Annual_Amount_MERC__c</fullName>
        <description>Annual CAP value per country
Created by John A Adams 10/24/2013</description>
        <label>Annual Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Country_Code_MERC__c</fullName>
        <description>Stores the country name that CAP applies to.
Created by John A Adams 10/24/2013</description>
        <label>Country Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year_MERC__c</fullName>
        <description>Stores the year that the CAP value is applied.  Used text field as Data requires entry of day and month, and Number inserts a comma in value
Created by John A Adams 10/24/2013</description>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>CAP by Country</label>
</CustomObject>

src/classes/MERC_HcpCapLimitCalculatorTest.cls
@isTest
private class MERC_HcpCapLimitCalculatorTest {
	
	static List<Account> frenchAccounts;
	static List<Account> belgianAccounts;
	static List<Account> englishAccounts;

	static {
		MERC_TestFactory.loadCAPSettings();
		frenchAccounts = MERC_TestFactory.insertHcpAccountsInCountry(2, 'FR');
		belgianAccounts = MERC_TestFactory.insertHcpAccountsInCountry(1, 'BE');
		englishAccounts = MERC_TestFactory.insertHcpAccountsInCountry(1, 'GB');
	}

	@isTest static void test_should_calculate_cap_for_hcps() {
		CAP_Settings_MERC__c frenchCap = [SELECT Annual_Amount_MERC__c FROM CAP_Settings_MERC__c WHERE Year_MERC__c = '2014' AND Country_Code_MERC__c = 'FR']; 
		system.assertEquals(frenchCap.Annual_Amount_MERC__c, [SELECT Annual_CAP_Limit_MERC__c FROM Account WHERE Id in :frenchAccounts limit 1].Annual_CAP_Limit_MERC__c);
		
		CAP_Settings_MERC__c belgianCap = [SELECT Annual_Amount_MERC__c FROM CAP_Settings_MERC__c WHERE Year_MERC__c = '2014' AND Country_Code_MERC__c = 'BE']; 
		system.assertEquals(belgianCap.Annual_Amount_MERC__c, [SELECT Annual_CAP_Limit_MERC__c FROM Account WHERE Id in :belgianAccounts limit 1].Annual_CAP_Limit_MERC__c);

		CAP_Settings_MERC__c englishCap = [SELECT Annual_Amount_MERC__c FROM CAP_Settings_MERC__c WHERE Year_MERC__c = '2014' AND Country_Code_MERC__c = 'GB']; 
		system.assertEquals(englishCap.Annual_Amount_MERC__c, [SELECT Annual_CAP_Limit_MERC__c FROM Account WHERE Id in :englishAccounts limit 1].Annual_CAP_Limit_MERC__c);
	
		Account englishAccount = englishAccounts.get(0);
		englishAccount.Country_of_Residence_GLBL__c = 'FR';
		update englishAccount;
		system.assertEquals(frenchCap.Annual_Amount_MERC__c, [SELECT Annual_CAP_Limit_MERC__c FROM Account WHERE Id = :englishAccount.Id limit 1].Annual_CAP_Limit_MERC__c);
	}
	
}