src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Primary_Address_Country_GLBL__c</fullName>
        <description>Primary Address  Country Code copied from primary address
Created by John Adams on 11/13/2013</description>
        <label>Primary Address Country</label>
        <length>2</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Address_GLBL__c.object
<CustomObject>
    <description>Used to capture participant (speaker and attendee) addresses
Created by John A Adams 9/26/2013</description>
    <fields>
        <fullName>Account_GLBL__c</fullName>
        <description>Lookup between addresses and accounts
Created by John A Adams 9/27/2013</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses_GLBL</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Adrs_Cntry_Cd_GLBL__c</fullName>
        <description>Address Country Code
Customer ODS to Mercury Mapping
Created by John A Adams 11/4/2013</description>
        <label>Address Country Code</label>
        <picklist>
            <picklistValues>
                <fullName>AF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BW</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Priority_Rank_Nbr_GLBL__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Priority Rank Number
Customer ODS to Mercury Mapping
Created by John A Adams 11/4/2013</description>
        <label>Priority Rank Number</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>ADR-{000000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <recordTypes>
        <fullName>Mastered_Address</fullName>
        <active>true</active>
        <description>Mastered Addresses from Customer ODS</description>
        <label>Mastered Address</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MERC_AddressCountryStampTrigger.cls
/**
 * @author David Helmer
 *
 * Responsible for stamping the Country on related Accounts when the Country changes or the address is inserted for addresses
 * of record type Other
 */


public with sharing class MERC_AddressCountryStampTrigger implements GLBL_TriggerHandler.HandlerInterface {    
    public Boolean isActive() {
        return MERC_TriggerHandlerStateManager.isActive(MERC_AddressCountryStampTrigger.class);
    }

    public void handle() {
        if (Trigger.isInsert || Trigger.isUpdate) {
            Map<Id,String> countriesToAccounts = getCountriesToAccounts(Trigger.new);
            stampCountriesOnAccounts(countriesToAccounts);
        }
    }

    Map<Id,String> getCountriesToAccounts(List<Sobject> sobjects){
        Id masteredAddressRecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Address_GLBL__c' AND DeveloperName = 'Mastered_Address' LIMIT 1].Id;
        List<Address_GLBL__c> addresses = (List<Address_GLBL__c>)sobjects;
        Map<Id,String> countriesToAccounts = new Map<Id, String>();
        for(Address_GLBL__c address : addresses){
            if(address.RecordTypeId != masteredAddressRecordTypeId
                && address.Priority_Rank_Nbr_GLBL__c == 1){
                if (Trigger.isInsert){
                    countriesToAccounts.put(address.Account_GLBL__c, address.Adrs_Cntry_Cd_GLBL__c);
                } else if (Trigger.isUpdate && (String)Trigger.oldMap.get(address.Id).get('Adrs_Cntry_Cd_GLBL__c') != address.Adrs_Cntry_Cd_GLBL__c){
                    countriesToAccounts.put(address.Account_GLBL__c, address.Adrs_Cntry_Cd_GLBL__c);
                }
            }            
        }
        return countriesToAccounts;
    }

    void stampCountriesOnAccounts(Map<Id, String> countriesToAccounts) {
        Map<Id, Account> accountMap = new Map<Id,Account>([SELECT Id, Primary_Address_Country_GLBL__c FROM Account WHERE Id IN :countriesToAccounts.keySet()]);
        List<Account> accountsToUpdate = new List<Account>();
        for(Id accountId : countriesToAccounts.keySet()){
            if(accountMap.containsKey(accountId)){
                Account accountToUpdate = accountMap.get(accountId);
                accountToUpdate.Primary_Address_Country_GLBL__c = countriesToAccounts.get(accountId);
                accountsToUpdate.add(accountToUpdate);
            }
        }
        update accountsToUpdate;
    }
}