src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Academic_Qualifications_MERC__c</fullName>
        <description>To record academic qualifications of speakers 
Created by John A Adams 10/2/2013</description>
        <inlineHelpText>Please indicate your most relevant degrees/certifications: select all that applies. Note that Non-MD Health care professional includes: nurse, pharmacist, psychologist, dietician</inlineHelpText>
        <label>Academic Qualifications</label>
        <picklist>
            <picklistValues>
                <fullName>MD Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD non- specialist or GP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-MD Health care professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PhD non-MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MSc, BSc</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Service_Provider_Tier_MERC__c</fullName>
        <description>Stores the Service Provider Tier generated as a part of Mercury Use cases.  Created by Oliver Dunford 30th Oct 2013.</description>
        <label>Service Provider Tier</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Invoice_Line_Item_MERC__c.object
<CustomObject>
    <description>Object to store invoice line item information. Created on 9/28/2013 by KLorenti</description>
    <fields>
        <fullName>Invoice_MERC__c</fullName>
        <description>Master-Detail relationship to Invoice object. Created 9/28/2013 by KLorenti</description>
        <label>Invoice</label>
        <referenceTo>Invoice_MERC__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>VAT_Rate_MERC__c</fullName>
        <description>Tax Rate Percentage
Created by John A Adams 10/4/2013</description>
        <label>VAT Rate %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>IL-{000000}</displayFormat>
        <label>Invoice Line Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <recordTypes>
        <fullName>Ad_Hoc_Consulting</fullName>
        <active>true</active>
        <description>To represent ad hoc consulting engagements.</description>
        <label>Ad Hoc Consulting</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice_MERC__c.object
<CustomObject>
    <description>Object to store invoice header information, Integrates with SAP for HCP Payments : MERC : Created on 09/27/2013 by Katy Lorenti, Mavens Consulting</description>
    <fields>
        <fullName>Invoice_Attached_MERC__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag set by Drawloop when an Invoice has been created and attached.  This is used in validation rule to prevent Submit for Payment being set to Yes when no Invoice is present.
Created by John A Adams 1/6/2014</description>
        <label>Invoice Attached</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Meeting_MERC__c</fullName>
        <description>Lookup of Meeting 
Created by John A Adams 10/30/2013</description>
        <formula>Meeting_Participant_MERC__r.Meeting_MERC__r.Event_Id_MERC__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Meeting</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meeting_Participant_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to find the meeting Participant this invoice is for.
Created by John A Adams 10/4/2013</description>
        <label>Meeting Participant</label>
        <referenceTo>Meeting_Participant_MERC__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submit_for_Payment_MERC__c</fullName>
        <description>Used as final check before Invoice is submitted to SAP.  Created by Oliver Dunford 4th Nov 2013.</description>
        <inlineHelpText>A PDF Invoice must be generated and then uploaded before the record can be submitted for payment.</inlineHelpText>
        <label>Submit for Payment</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <recordTypes>
        <fullName>Credit_Note_Locked_MERC</fullName>
        <active>true</active>
        <description>Indicates a locked credit note</description>
        <label>Credit Note Locked</label>
    </recordTypes>
    <recordTypes>
        <fullName>Invoice_Locked_MERC</fullName>
        <active>true</active>
        <description>Record Type for a locked Invoice</description>
        <label>Invoice Locked</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Meeting_MERC__c.object
<CustomObject>
</CustomObject>

src/objects/Meeting_Participant_MERC__c.object
<CustomObject>
</CustomObject>

src/classes/MERC_AllocatedConsCapCalculatorBatchTest.cls
@isTest
private class MERC_AllocatedConsCapCalculatorBatchTest {
    
    static List<Meeting_MERC__c> meetings;
    static List<Account> accounts;
    static List<Meeting_Participant_MERC__c> participants;
    static List<Invoice_MERC__c> invoices;
    static List<Invoice_Line_Item_MERC__c> invoicelineitems;
    static User runningUser = MERC_TestFactory.getRunningUser();
    static User testUser = MERC_TestFactory.getTestingUser();
    static Id MeetingRecordTypeId =  [Select ID FROM RecordType WHERE SObjectType = 'Meeting_MERC__c' AND DeveloperName = 'Ad_Hoc_Consulting' LIMIT 1].Id;
    static Id InvoiceRecordTypeId =  [Select ID FROM RecordType WHERE SObjectType = 'Invoice_MERC__c' AND DeveloperName = 'Invoice_Locked_MERC' LIMIT 1].Id;
    static Id CreditNoteRecordTypeId =  [Select ID FROM RecordType WHERE SObjectType = 'Invoice_MERC__c' AND DeveloperName = 'Credit_Note_Locked_MERC' LIMIT 1].Id;
    static Id MeetingRecordTypeNonconsId = [Select ID FROM RecordType WHERE SObjectType = 'Meeting_MERC__c' AND DeveloperName = 'Meeting_Active' LIMIT 1].Id;   
    static {
        MERC_TestFactory.loadFMVSettings();
        System.runAs(runningUser) {
        MERC_TriggerHandlerStateManager.deactivateAll();
        accounts = MERC_TestFactory.insertHcpAccountsInCountry(1, 'GB'); //insert 5 accounts
        meetings = MERC_TestFactory.insertMeetings_CAP(1,NULL,'Registered'); //insert 2 meetings
        participants = MERC_TestFactory.insertParticipants_forLinetems(meetings.get(0).Id, accounts); //insert 5
        List<Account> accts = [SELECT Id, Service_Provider_Tier_MERC__c, Academic_Qualifications_MERC__c
                                     FROM Account
                                    WHERE Id IN :accounts];
        for (Account a : accts)
        {
                //values in loaded custom setting data will map to min=60, max=100 for a tier 3 phd non-md
                a.Service_Provider_Tier_MERC__c = 3;
                a.Academic_Qualifications_MERC__c = 'PhD non-MD';
        }
        update accts;
       
        invoices = MERC_TestFactory.insertInvoices(participants);       
        invoicelineitems = MERC_TestFactory.insertInvoiceLineItems(invoices.get(0).id,1);
        }
    MERC_TestFactory.loadFMVSettings();
    }

    @isTest static void testmethod1() {
            Date dt = Date.Today() -100;
            String sdt = string.valueof(dt);
            Meeting_MERC__c m = meetings.get(0);
            m.RecordTypeId = MeetingRecordTypeId;
            m.Meeting_Status_MERC__c = 'Active';
            m.Date_of_Event_MERC__c =Date.today()- 365;
            m.MERC_Meeting_Complete_Canceled_Clsd_Date__c = NULL;
            m.End_Date_of_Event_MERC__c= date.valueof(sdt)  ;
            update m;
            Test.startTest();
            Meeting_Participant_MERC__c Mp = participants.get(0);
            Mp.Types_of_Service_MERC__c = 'Consulting Project';
            update Mp;
            
            
            Invoice_Line_Item_MERC__c ILI = invoicelineitems.get(0);
            ILI.Consulting_Amount_MERC__c = 500.0;
            ILI.VAT_Rate_MERC__c = 1.0;
            Update ILI;
            
            Invoice_MERC__c Inv = invoices.get(0);
            update Inv;
            
            Invoice_Line_Item_MERC__c ILI1 = invoicelineitems.get(0);
            ILI1.Consulting_Amount_MERC__c = 400.0;
            ILI1.VAT_Rate_MERC__c = 2.0;
            Update ILI1;
            
            Invoice_MERC__c Inv1 = invoices.get(0);
            Inv1.Submit_for_Payment_MERC__c = 'Yes';
            Inv1.Invoice_Attached_MERC__c = True;
            Inv1.RecordTypeId = InvoiceRecordTypeId;
            update Inv1;
            
        system.debug('##End_Date_of_Event_MERC__c'+m.End_Date_of_Event_MERC__c);
        system.debug('####MERC_Meeting_End_Date_Inactive__c '+m.MERC_Meeting_End_Date_Inactive__c +'#####MERC_Meeting_out_of_six_months__c '+m.MERC_Meeting_out_of_six_months__c);
     
        MERC_AllocatedConsCapCalculatorBatch b = new MERC_AllocatedConsCapCalculatorBatch();
        Database.executeBatch(b);
        System.assertEquals(400, [SELECT MERC_Consulting_Contracted_Amt_excl_VAT__c FROM Invoice_MERC__c WHERE Id = :Inv1.Id].MERC_Consulting_Contracted_Amt_excl_VAT__c);
        Test.stopTest();
      
    }
    
    @isTest
    static void test_should_rollupcreditnote_of_consulting_type_meetings() {
        System.runAs(testUser) {
            Date dt = Date.Today() -100;
            String sdt = string.valueof(dt);
            Meeting_MERC__c m = meetings.get(0);
            m.RecordTypeId = MeetingRecordTypeId;
            m.Meeting_Status_MERC__c = 'Active';
            m.Date_of_Event_MERC__c =Date.today()- 365;
            m.MERC_Meeting_Complete_Canceled_Clsd_Date__c = NULL;
            m.End_Date_of_Event_MERC__c= date.valueof(sdt)  ;
            update m;
           
            Test.startTest();
            Meeting_Participant_MERC__c Mp = participants.get(0);
            Mp.Types_of_Service_MERC__c = 'Consulting Project';
            update Mp;
            
            Invoice_Line_Item_MERC__c ILI = invoicelineitems.get(0);
            ILI.Consulting_Amount_MERC__c = 500.0;
            ILI.VAT_Rate_MERC__c = 1.0;
            Update ILI;
            
            Invoice_MERC__c CN = invoices.get(0);
            CN.RecordTypeId = CreditNoteRecordTypeId;
            update CN;
            
            Invoice_Line_Item_MERC__c ILI1 = invoicelineitems.get(0);
            ILI1.Consulting_Amount_MERC__c = 400.0;
            ILI1.VAT_Rate_MERC__c = 2.0;
            Update ILI1;
            
            Invoice_MERC__c CN1 = invoices.get(0);
            CN1.Submit_for_Payment_MERC__c = 'Yes';
            CN1.Invoice_Attached_MERC__c = True;
            CN1.RecordTypeId = CreditNoteRecordTypeId;
            update CN1;
            
            MERC_AllocatedConsCapCalculatorBatch b = new MERC_AllocatedConsCapCalculatorBatch();
            Database.executeBatch(b);
            System.assertEquals(400, [SELECT MERC_Consulting_Contracted_Amt_excl_VAT__c FROM Invoice_MERC__c WHERE Id = :CN1.Id].MERC_Consulting_Contracted_Amt_excl_VAT__c);
            Test.stopTest();
            
            
              
       }
    
    }
    
}