src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country_of_Residence_GLBL__c</fullName>
        <description>Country of residence which may differ from the Country to be used for contract fee calculation.  Needed for Tax Purposes in Invoice.
Created by John A Adams 10/20/2013</description>
        <label>Country of Residence</label>
        <picklist>
            <picklistValues>
                <fullName>ES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AF</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status_MERC__c</fullName>
        <description>Status of Account. Created 10/4/2013 by KLorenti.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Validated by LMM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Meeting_Email_Send_MERC__c.object
<CustomObject>
    <description>Junction object used for custom ExactTarget Email integration for Meetings</description>
    <fields>
        <fullName>Meeting_MERC__c</fullName>
        <label>Meeting</label>
        <referenceTo>Meeting_MERC__c</referenceTo>
        <relationshipLabel>Meeting Email Sends</relationshipLabel>
        <relationshipName>Meeting_Email_Sends</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Send_Status__c</fullName>
        <label>Send Status</label>
        <picklist>
            <picklistValues>
                <fullName>Create Sender Profile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Create Send Definition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Start Send Definition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Send Status</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Send Created</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Meeting Email Send</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Meeting Email Send #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Email Sends</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Meeting_MERC__c.object
<CustomObject>
</CustomObject>

src/objects/Meeting_Participant_MERC__c.object
<CustomObject>
</CustomObject>

src/classes/MERC_MeetingRegistrationHandlerTest.cls
@isTest
private class MERC_MeetingRegistrationHandlerTest {
    @testSetup static void prepareConfiguration(){
        MERC_MarketingCloudTestUtility.insertConfiguration(true);
        MERC_MarketingCloudTestUtility.insertBusinessUnit();
        MERC_MarketingCloudTestUtility.insertSettings();
    }

    @isTest static void test_sendMeetingRegistrationConfirmations(){
        MERC_TriggerHandlerStateManager.deactivateAll();
        User testUser = MERC_MarketingCloudTestUtility.getUser();
        insert testUser;
        Meeting_MERC__c meeting = null;
        List<Account> personAccounts = null;
        List<Meeting_Participant_MERC__c> participants = null;

        System.runAs(testUser){
            MERC_TestFactory.adjustForSFDCSetMockBug = true;
            MERC_MarketingCloudTestUtility.adjustTime();
            meeting = MERC_MarketingCloudTestUtility.insertMeeting();
            personAccounts = MERC_ETTestUtils.CreatePersonAccountsWithRecordType(
                MERC_MarketingCloudTestUtility.RECORD_TYPE_STRING_HCP, 1);
            personAccounts[0].Country_of_Residence_GLBL__c = 'GB';
            insert personAccounts;

            participants = MERC_ETTestUtils.CreateParticipants(meeting, personAccounts);
            for(Meeting_Participant_MERC__c participant : participants){
                participant.Status_MERC__c = 'Invited';
            }
            insert participants;

            MERC_MockHttpResponseService mockResponseService = MERC_MarketingCloudTestUtility.MockRequestsForRegistrationConfirmationSend(
                testUser,
                meeting,
                participants,
                personAccounts);
            mockResponseService.addResponse(MERC_MarketingCloudTestUtility.getMockGetEmailFoldersAllRequest());  
            mockResponseService.addResponse(MERC_MarketingCloudTestUtility.getMockGetMyEmailsFolderRequest('8'));  
            mockResponseService.addResponse(MERC_MarketingCloudTestUtility.getMockGetGBEmailsRequest('10')); 
            mockResponseService.addResponse(MERC_MarketingCloudTestUtility.getClassificationsRequest());  
            Test.setMock(HttpCalloutMock.class, mockResponseService);

            Test.startTest();
            
            Meeting_Participant_MERC__c participant = participants[0];
            participant.Status_MERC__c = 'Accepted';
            participant.WS_Updt_Dt_MERC__c = Date.today();
            update participant;

            Test.stopTest();

            Meeting_Email_Send_MERC__c meetingEmailSend = [SELECT Id,
                                                                  Send_Status__c 
                                                             FROM Meeting_Email_Send_MERC__c
                                                            WHERE Meeting_MERC__c = :meeting.Id
                                                            LIMIT 1][0];
            System.assertEquals(MERC_MarketingCloudService.CreateSenderProfile, meetingEmailSend.Send_Status__c);
        }
    }
}