src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Bnft_Dsgn_Cd_GLBL__c</fullName>
        <description>Created to map to Customer ODS.Party.Benefit Designation Cd.  Created by Oliver Dunford 25th Oct</description>
        <label>Benefit Designation</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/CST_App_Menu_Pool_GLBL__c.object
<CustomObject>
    <description>This object is used to collect &amp; store the unique values of a particular source data set which is then subsequently used to populate the menu options in a related CST App Settings record.

Stamped GLBL because this data could be used by other applications as it reflects Account data and nothing specific to the Customer Search Tool</description>
    <fields>
        <fullName>Bnft_Dsgn_Cd_GLBL__c</fullName>
        <description>Holds distinct values collected from Account.Bnft_Dsgn_Cd_GLBL__c to populate the Account_Bnft_Dsgn_Cd_CUST__c field in the CST App Settings</description>
        <inlineHelpText>Holds distinct values collected from Account.Bnft_Dsgn_Cd_GLBL__c to populate the Account_Bnft_Dsgn_Cd_CUST__c field in the CST App Settings</inlineHelpText>
        <label>Bnft_Dsgn_Cd_GLBL__c</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>CST App Menu Pool</label>
    <nameField>
        <displayFormat>CSTPOOL-{0000}</displayFormat>
        <label>CST App Menu Pool Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CST App Menu Pools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CST_App_Settings_CUST__c.object
<CustomObject>
    <description>Holds application-wide settings for the Customer Search Tool</description>
    <label>CST App Settings</label>
    <nameField>
        <displayFormat>CSTAPP-{0000}</displayFormat>
        <label>CST App Settings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CST App Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CUST_RefreshLOVsControllerTest.cls
@isTest
private class CUST_RefreshLOVsControllerTest {

	private static CST_App_Settings_CUST__c   record;
	private static CUST_RefreshLOVsController controller;
	private static CUST_RefreshLOVsUtil util;
	
	static {
		record = CUST_TestFactory.insertAppSetting();
		controller = new CUST_RefreshLOVsController(new ApexPages.StandardController(record));
		util = new CUST_RefreshLOVsUtil();

		Test.setCurrentPage(Page.CUST_RefreshLOVs);
	}

//	@isTest 
	static void testConstructor() {
		System.assertNotEquals(null, controller.settings,'settings not initiated.');
	}

//	@isTest
	static void testConstructorError() {
		ApexPages.StandardController noRecordId = new ApexPages.StandardController(new CST_App_Settings_CUST__c());
		controller = new CUST_RefreshLOVsController(noRecordId);

		System.assert(!ApexPages.getMessages().isEmpty(),'Error message not passed back to page.');
	}

	@isTest
	static void refreshFields() {

		List<Account> accts = MERC_TestFactory.insertAccounts(3);

		String f = 'Bnft_Dsgn_Cd_GLBL__c';
		controller.fieldsToRefresh = f;
		accts = Database.query('SELECT Id, '+f+' FROM Account WHERE Id in :accts');

		List<String> newValues = new List<String>{'Othello','Desdemona','Iago'};
		Integer i = 0;
		String thisVal;
		for (Account a : accts) {
			a.put(f,newValues.get(i));
			i++;
			if (i>=newValues.size()) i = 0;
		}
		update accts;

		PageReference result = controller.refreshSelectedLOVs();

		System.assertEquals(null,result,'Diff PageRef returned: '+result);

		List<CST_App_Menu_Pool_GLBL__c> poolRecords = Database.query('SELECT Id, '+f+', '+util.getDateFieldName(f)+' FROM CST_App_Menu_Pool_GLBL__c');
		System.assert(!poolRecords.isEmpty());

		String SQL = 'SELECT '+f+' from Account where Id in :accts group by '+f; 
		AggregateResult[] aggResults = Database.query(SQL);

		for (AggregateResult ar : aggResults) {
			System.assert(poolRecords[0].Bnft_Dsgn_Cd_GLBL__c.contains((String) ar.get(f)),
				'pool record for '+f+' does not contain test value "'+(String) ar.get(f)+'"');
			System.assertEquals(Date.today(), poolRecords[0].get(util.getDateFieldName(f)));
		}
	}

	static void p(String m) {
		System.debug('\n\n\nYYZ - '+m+'\n\n\n\n');
	}
}