src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Consulting_Project_Paid_CAP_MERC__c</fullName>
        <description>Contains all Paid CAP for Consulting Projects.  Oliver Dunford 20th Jan 2014.</description>
        <label>Consulting Project Paid CAP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/objects/Invoice_Line_Item_MERC__c.object
<CustomObject>
    <description>Object to store invoice line item information. Created on 9/28/2013 by KLorenti</description>
    <fields>
        <fullName>Invoice_MERC__c</fullName>
        <description>Master-Detail relationship to Invoice object. Created 9/28/2013 by KLorenti</description>
        <label>Invoice</label>
        <referenceTo>Invoice_MERC__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>IL-{000000}</displayFormat>
        <label>Invoice Line Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice_MERC__c.object
<CustomObject>
    <description>Object to store invoice header information, Integrates with SAP for HCP Payments : MERC : Created on 09/27/2013 by Katy Lorenti, Mavens Consulting</description>
    <fields>
        <fullName>Consulting_Project_Amount_excl_VAT_MERC__c</fullName>
        <description>Used to roll up the total value of Consulting Projects for an Invoice record.  This excludes VAT and is used to calculate CAP at Account level for HCP&apos;s when engaged in Consulting Projects with Lilly.  This is rolled up from the Invoice and NOT the meeting participant for Consulting Projects. Oliver Dunford 7th Jan 2014.</description>
        <label>Consulting Project Amount (excl VAT)</label>
        <summarizedField>Invoice_Line_Item_MERC__c.Consulting_Amount_MERC__c</summarizedField>
        <summaryFilterItems>
            <field>Invoice_Line_Item_MERC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Consulting Project</value>
        </summaryFilterItems>
        <summaryForeignKey>Invoice_Line_Item_MERC__c.Invoice_MERC__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Invoice_Date_MERC__c</fullName>
        <description>Date Invoice is issued.
Created by John A Adams 10/20/2013</description>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Meeting_Participant_Account_Id_MERC__c</fullName>
        <formula>CASESAFEID(Meeting_Participant_MERC__r.Account_MERC__r.Id )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Meeting Participant Account Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meeting_Participant_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to find the meeting Participant this invoice is for.
Created by John A Adams 10/4/2013</description>
        <label>Meeting Participant</label>
        <referenceTo>Meeting_Participant_MERC__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submit_for_Payment_MERC__c</fullName>
        <description>Used as final check before Invoice is submitted to SAP.  Created by Oliver Dunford 4th Nov 2013.</description>
        <inlineHelpText>A PDF Invoice must be generated and then uploaded before the record can be submitted for payment.</inlineHelpText>
        <label>Submit for Payment</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <recordTypes>
        <fullName>Invoice_Invalid_MERC</fullName>
        <active>true</active>
        <description>Invoice record no longer valid, never submitted successfully for processing</description>
        <label>Invoice Invalid</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Meeting_Participant_MERC__c.object
<CustomObject>
</CustomObject>

src/classes/MERC_ConsultingProjectCapCalculator.cls
/**
* @author Joseph Ferraro
*
* Trigger handler that calculates Consulting_Project_Paid_CAP_MERC__c on Account based on an Account's participation in Consulting projects for the year
*/

public with sharing class MERC_ConsultingProjectCapCalculator implements GLBL_TriggerHandler.HandlerInterface {

    Schema.SobjectType triggeredSobjectType;

    public MERC_ConsultingProjectCapCalculator(Schema.SobjectType sobjectType) {
        this.triggeredSobjectType = sObjectType;
    }

    public Boolean isActive() {
        return true;
    }

    public void handle() {
        if (Trigger.isUpdate || Trigger.isUndelete) {
            execute(Trigger.new);
        } else if (Trigger.isDelete) {
            execute(Trigger.old);
        }
    }

    void execute(List<Sobject> sobjects) {
        List<Invoice_MERC__c> invoices;
        if (this.triggeredSobjectType == Invoice_MERC__c.sObjectType) {
            invoices = (List<Invoice_MERC__c>)sobjects;
        } else if (this.triggeredSobjectType == Invoice_Line_Item_MERC__c.sObjectType) {
            Set<Id> invoiceIds = new Set<Id>();
            for (Sobject lineItem : sobjects) {
                invoiceIds.add((Id)lineItem.get('Invoice_MERC__c'));
            }
            invoices = [SELECT ID, Meeting_Participant_Account_Id_MERC__c FROM Invoice_MERC__c WHERE ID in :invoiceIds];
        }

        if (invoices.size() == 0) return;

        Set<Id> meetingParticipantIds = new Set<Id>();
        Set<Id> accountIds = new Set<Id>();

        for (Invoice_MERC__c i : invoices)
            accountIds.add(i.Meeting_Participant_Account_Id_MERC__c);

        System.debug('>>>> '+accountIds);

        List<AggregateResult> results = [SELECT
                                            Meeting_Participant_MERC__r.Account_MERC__c inv_acc,
                                            Sum(Consulting_Project_Amount_excl_VAT_MERC__c) lre0
                                                FROM Invoice_MERC__c
                                                    WHERE
                                                        Meeting_Participant_MERC__r.Account_MERC__c IN :accountIds AND
                                                        Invoice_Date_MERC__c = THIS_YEAR AND
                                                        Submit_for_Payment_MERC__c = 'Yes' AND 
                                                        RecordType.DeveloperName != 'Invoice_Invalid_MERC'  /* Added by Namrata Aggarwal on 11/04/2015 for R14 Defect */
                                                            GROUP BY Meeting_Participant_MERC__r.Account_MERC__c];

        System.debug('>>>> '+results);

         Map<Id,AggregateResult> accResMap = new Map<Id,AggregateResult>(); 

         for(AggregateResult rset: results)
        { 
    if(rset.get('inv_acc')!= NULL){
        accResMap.put((ID)rset.get('inv_acc'),rset);  
        //accResMap.put(rset.Meeting_Participant_MERC__r.Account_MERC__c,rset); 
    }
         } 


            List<Account> accounts = new List<Account>();
            for(ID accntID: accountIds)
            {
            if(accResMap.containskey(accntID))
            {

            for (AggregateResult res : results){
                System.debug('========== '+res);
                Id masterRecId = (Id)res.get('inv_acc');
                if (masterRecId == null) {
                    System.debug(Logginglevel.WARN, 'No master record found for ID :' + masterRecId);
                    continue;
                }
                Object aggregatedDetailVal = res.get('lre0');
                Account a = new Account();
                a.Id = masterRecId;
                a.Consulting_Project_Paid_CAP_MERC__c = (Decimal)aggregatedDetailVal;
                accounts.add(a);
            }
        }
        else
        {
                Account acc = new Account();
                acc.Id = accntID;
                acc.Consulting_Project_Paid_CAP_MERC__c = 0;
                accounts.add(acc);
        }
        }

        update accounts;
    }
}