src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Academic_Qualifications_MERC__c</fullName>
        <description>To record academic qualifications of speakers 
Created by John A Adams 10/2/2013</description>
        <inlineHelpText>Please indicate your most relevant degrees/certifications: select all that applies. Note that Non-MD Health care professional includes: nurse, pharmacist, psychologist, dietician</inlineHelpText>
        <label>Academic Qualifications</label>
        <picklist>
            <picklistValues>
                <fullName>MD Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD non- specialist or GP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-MD Health care professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PhD non-MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MSc, BSc</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Calculate_Open_Meeting_Fees_MERC__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked the system will update all Fee calculations for Open Meetings.  This deals with the scenario whereby a Fee cannot calculate because a Tier does not exist, or a HCP is re-tiered and only new Meetings should have the new Tier applied. Created by Oliver Dunford 31st Oct 2013.</description>
        <inlineHelpText>Check this box to update all Meeting Participant Fee calculations based on a new or updated HCP Tier.  This will only update those meetings which do not have a Status of Closed or Cancelled.</inlineHelpText>
        <label>Calculate Open Meeting Fees</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Provider_Tier_MERC__c</fullName>
        <description>Stores the Service Provider Tier generated as a part of Mercury Use cases.  Created by Oliver Dunford 30th Oct 2013.</description>
        <label>Service Provider Tier</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Meeting_Day_MERC__c.object
<CustomObject>
    <description>Object to track days of meetings and ToV cost of each day. Created 10/10/2013 by KLorenti.</description>
    <fields>
        <fullName>Meeting_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship to Meeting. Created 10/10/2013 by KLorenti</description>
        <label>Meeting</label>
        <referenceTo>Meeting_MERC__c</referenceTo>
        <relationshipLabel>Meeting Days</relationshipLabel>
        <relationshipName>Meeting_Days</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Meeting Day</label>
    <nameField>
        <label>Meeting Day</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Meeting_MERC__c.object
<CustomObject>
</CustomObject>

src/objects/Meeting_Participant_MERC__c.object
<CustomObject>
</CustomObject>

src/classes/MERC_ParticipantFMVCalculatorTest.cls
@isTest
private class MERC_ParticipantFMVCalculatorTest {

    static User runningUser = MERC_TestFactory.getRunningUser();
    static User testUser = MERC_TestFactory.getTestingUser();
	static List<Meeting_MERC__c> meetings;
	static List<Account> accounts;
	static List<Meeting_Day_MERC__c> meetingDays;
	static List<Meeting_Participant_MERC__c> participants;
	static List<Meeting_Participant_MERC__c> participants2;

	static {
		MERC_TestFactory.loadFMVSettings();

		System.runAs(runningUser)
		{
	        MERC_TriggerHandlerStateManager.deactivateAll();
			accounts = MERC_TestFactory.insertHcpAccountsInCountry(5, 'GB'); //insert 5 accounts
			meetings = MERC_TestFactory.insertMeetings(2); //insert 2 meetings
			meetingDays = MERC_TestFactory.insertMeetingDays(meetings.get(0).Id, 3); //insert 3 days
			participants = MERC_TestFactory.insertParticipants(meetings.get(0).Id, accounts); //insert 5 participants
			participants2 = MERC_TestFactory.insertParticipants(meetings.get(1).Id, accounts); //insert 5 participants

			List<Account> accts = [SELECT Id, Service_Provider_Tier_MERC__c, Academic_Qualifications_MERC__c
			                         FROM Account
			                        WHERE Id IN :accounts];
			for (Account a : accts)
	 		{
	 			//values in loaded custom setting data will map to min=60, max=100 for a tier 3 phd non-md
	 			a.Service_Provider_Tier_MERC__c = 3;
	 			a.Academic_Qualifications_MERC__c = 'PhD non-MD';
	 		}
	 		update accts;
	        MERC_TriggerHandlerStateManager.activateAll();
		}

		MERC_TestFactory.loadFMVSettings();
	}

	@isTest static void test_should_stamp_fmv_rates_on_participant_update() {
		System.runAs(testUser)
		{
			Test.startTest();
			update participants;

			List<Meeting_Participant_MERC__c> updatedParticipants = [SELECT Id, Minimum_Rate_MERC__c, Maximum_Rate_MERC__c
			                                                           FROM Meeting_Participant_MERC__c
			                                                          WHERE Id IN :participants];
            for (Meeting_Participant_MERC__c p : updatedParticipants)
            {
            	System.assertEquals(60, p.Minimum_Rate_MERC__c);
            	System.assertEquals(100, p.Maximum_Rate_MERC__c);
            }
			Test.stopTest();
		}
	}

	@isTest static void test_should_stamp_fmv_rates_on_participant_on_account_update() {
		System.runAs(testUser)
		{
			List<Account> accts = [SELECT Service_Provider_Tier_MERC__c, Calculate_Open_Meeting_Fees_MERC__c
			                         FROM Account
			                        WHERE Id IN :accounts];
			for (Account a : accts)
			{
				a.Service_Provider_Tier_MERC__c       = 2; //change the tier so that maps to min=90, max=140;
				a.Calculate_Open_Meeting_Fees_MERC__c = true;
			}
			Test.startTest();
			update accts;

			List<Meeting_Participant_MERC__c> updatedParticipants = [SELECT Id, Minimum_Rate_MERC__c, Maximum_Rate_MERC__c
			                                                           FROM Meeting_Participant_MERC__c
			                                                          WHERE Id IN :participants];
            for (Meeting_Participant_MERC__c p : updatedParticipants)
            {
            	System.assertEquals(90, p.Minimum_Rate_MERC__c);
            	System.assertEquals(140, p.Maximum_Rate_MERC__c);
            }
			Test.stopTest();
		}
	}
}