src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status_MERC__c</fullName>
        <description>Status of Account. Created 10/4/2013 by KLorenti.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Validated by LMM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Daily_Attendance_TOV_MERC__c.object
<CustomObject>
    <description>Junction object between Meeting Days and Meeting Participants, stores a breakdown of Daily ToV which is picked up by the AODS Interface : MERC : Created on 10/10/2013 by John Adams, Mavens Consulting</description>
    <fields>
        <fullName>Meeting_Day_MERC__c</fullName>
        <description>Master Detail relationship from Daily Attendance to Meeting Day. Created 10/10/2013 by KLorenti.</description>
        <label>Meeting Day</label>
        <referenceTo>Meeting_Day_MERC__c</referenceTo>
        <relationshipLabel>Daily Attendance &amp; TOV</relationshipLabel>
        <relationshipName>Daily_Attendance_TOV</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Meeting_Participant_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master Detail relationship from Daily Attendance to Meeting Participant. Created 10/10/2013 by KLorenti.</description>
        <label>Meeting Participant</label>
        <referenceTo>Meeting_Participant_MERC__c</referenceTo>
        <relationshipLabel>Daily Attendance &amp; TOV</relationshipLabel>
        <relationshipName>Daily_Attendance_TOV_MERC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status_MERC__c</fullName>
        <description>Used to report across daily meeting attendance for HCP&apos;s. Oliver Dunford 6th Nov  2013.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Daily Attendance &amp; TOV</label>
    <nameField>
        <displayFormat>DA-{000000}</displayFormat>
        <label>Attendance #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Attendance &amp; TOV</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Meeting_Day_MERC__c.object
<CustomObject>
    <description>Object to track days of meetings and ToV cost of each day. Created 10/10/2013 by KLorenti.</description>
    <fields>
        <fullName>Meeting_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship to Meeting. Created 10/10/2013 by KLorenti</description>
        <label>Meeting</label>
        <referenceTo>Meeting_MERC__c</referenceTo>
        <relationshipLabel>Meeting Days</relationshipLabel>
        <relationshipName>Meeting_Days</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Meeting Day</label>
    <nameField>
        <label>Meeting Day</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Meeting_MERC__c.object
<CustomObject>
</CustomObject>

src/objects/Meeting_Participant_MERC__c.object
<CustomObject>
</CustomObject>

src/classes/MERC_MeetingTOVFinalValidationTest.cls
@isTest
private class MERC_MeetingTOVFinalValidationTest
{

    public static User runningUser; 
    public static User testUser ;
    public static Meeting_MERC__c meeting;
    public static List<Account> accounts;    
    public static List<Meeting_Participant_MERC__c> participants;
    public static List<Meeting_Day_MERC__c> meetingDayList;
    
    public static void initializedata(){
        runningUser = MERC_TestFactory.getRunningUser();
        testUser = MERC_TestFactory.getTestingUser();
        meeting = MERC_TestFactory.insertMeetings(1).get(0);  
        accounts = MERC_TestFactory.insertAccounts(1);
        participants = MERC_TestFactory.insertParticipants(meeting.Id, accounts);      
    }   
    
    static testMethod void test_meetingtovfinalvalidation()
    {
        initializedata();
    
        ID participantRecordTypeId = [Select ID FROM RecordType WHERE SObjectType = 'Meeting_Participant_MERC__c' AND DeveloperName = 'Merc_Service_Provider' LIMIT 1].Id;
        ID meetingRecordTypeId = [Select ID FROM RecordType WHERE SObjectType = 'Meeting_MERC__c' AND DeveloperName = 'Meeting_Active' LIMIT 1].Id;
        
        participants[0].RecordTypeId = participantRecordTypeId;
        participants[0].status_MERC__c = 'Approved' ;
    
        update participants[0];
        
        meeting.RecordTypeId = meetingRecordTypeId;
        meeting.Participant_ToV_Final_MERC__c = 'Yes';
    
        System.assertEquals('Approved', participants[0].status_MERC__c);
        System.assertEquals('Yes', meeting.Participant_ToV_Final_MERC__c);
        
        System.runAs(testUser) {
            try{
                 test.startTest();
                     update meeting;
                 test.stopTest();
            }
            catch(Exception e){
            
            }
        }
    }

    static testMethod void test_meetingtovfinalvalidation2()
    {
        initializedata();
        ID participantRecordTypeId = [Select ID FROM RecordType WHERE SObjectType = 'Meeting_Participant_MERC__c' AND DeveloperName = 'Merc_Service_Provider' LIMIT 1].Id;
        ID meetingRecordTypeId = [Select ID FROM RecordType WHERE SObjectType = 'Meeting_MERC__c' AND DeveloperName = 'Meeting_Active' LIMIT 1].Id;
        
        participants[0].RecordTypeId = participantRecordTypeId;
        participants[0].status_MERC__c = 'No Show' ;
        update participants[0];
    
        meeting.RecordTypeId = meetingRecordTypeId;
        meeting.Participant_ToV_Final_MERC__c = 'Yes';
    
        System.assertEquals('No Show', participants[0].status_MERC__c);
        System.assertEquals('Yes', meeting.Participant_ToV_Final_MERC__c);
        
        System.runAs(testUser) {        
            try{
                test.startTest();
                    update meeting;
                test.stopTest();
            }
            catch(Exception e){
            
            }
        }
    }
 
    static testMethod void test_meetingtovfinalvalidation3()
    {
        initializedata();
        test.startTest();
     
        ID participantRecordTypeId = [Select ID FROM RecordType WHERE SObjectType = 'Meeting_Participant_MERC__c' AND DeveloperName = 'Merc_Service_Provider' LIMIT 1].Id;
        ID meetingRecordTypeId = [Select ID FROM RecordType WHERE SObjectType = 'Meeting_MERC__c' AND DeveloperName = 'Meeting_Active' LIMIT 1].Id;
        
        participants[0].RecordTypeId = participantRecordTypeId;
        participants[0].status_MERC__c = 'No Show' ;
        update participants[0];
        
        //Add Daily attendance to meeting participant
        meetingDayList= MERC_TestFactory.insertMeetingDays(meeting .Id,1);
        Daily_Attendance_TOV_MERC__c mpDat= MERC_TestFactory.insertTov(meetingDayList[0].Id,participants[0].Id);
    
        meeting.RecordTypeId = meetingRecordTypeId;
        meeting.Participant_ToV_Final_MERC__c = 'Yes';
        
        System.assertEquals('No Show', participants[0].status_MERC__c);
        System.assertEquals('Yes', meeting.Participant_ToV_Final_MERC__c);
        
        System.runAs(testUser) {
            try{
                    update meeting; 
            }
            catch(Exception e){
            
            }
            test.stopTest(); 
        }       
    }              
}