src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status_MERC__c</fullName>
        <description>Status of Account. Created 10/4/2013 by KLorenti.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Validated by LMM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Daily_Attendance_TOV_MERC__c.object
<CustomObject>
    <description>Junction object between Meeting Days and Meeting Participants, stores a breakdown of Daily ToV which is picked up by the AODS Interface : MERC : Created on 10/10/2013 by John Adams, Mavens Consulting</description>
    <fields>
        <fullName>Est_Hotel_ToV_MERC__c</fullName>
        <description>Captures ToV for Hotels at a Day Level.  Set via custom development based upon Travel Itinerary record and relationship to Meeting Hotel Vendor/Room Rate.  Jan 7th Oliver Dunford</description>
        <label>Hotel ToV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Est_Indv_Transfer_MERC__c</fullName>
        <description>Total for all Individual Travel ToV will be captured here, driven from Individual Travel ToV Records : MERC : Created on 23/07/2014 by Oliver Dunford, Mavens Consulting</description>
        <label>Individual Travel ToV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Meeting_Day_MERC__c</fullName>
        <description>Master Detail relationship from Daily Attendance to Meeting Day. Created 10/10/2013 by KLorenti.</description>
        <label>Meeting Day</label>
        <referenceTo>Meeting_Day_MERC__c</referenceTo>
        <relationshipLabel>Daily Attendance &amp; TOV</relationshipLabel>
        <relationshipName>Daily_Attendance_TOV</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Meeting_Participant_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master Detail relationship from Daily Attendance to Meeting Participant. Created 10/10/2013 by KLorenti.</description>
        <label>Meeting Participant</label>
        <referenceTo>Meeting_Participant_MERC__c</referenceTo>
        <relationshipLabel>Daily Attendance &amp; TOV</relationshipLabel>
        <relationshipName>Daily_Attendance_TOV_MERC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meeting_Vendor_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Meeting Vendor to retrieve Hotel Room Rates
Created by John A Adams 10/10/2013</description>
        <label>Meeting Vendor</label>
        <referenceTo>Meeting_Vendor_MERC__c</referenceTo>
        <relationshipLabel>Daily Attendance &amp; TOV</relationshipLabel>
        <relationshipName>Daily_Attendance_TOV</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status_MERC__c</fullName>
        <description>Used to report across daily meeting attendance for HCP&apos;s. Oliver Dunford 6th Nov  2013.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Daily Attendance &amp; TOV</label>
    <nameField>
        <displayFormat>DA-{000000}</displayFormat>
        <label>Attendance #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Attendance &amp; TOV</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/HCP_Contract_MERC__c.object
<CustomObject>
    <description>Contains contract details between Lilly and event speakers. 
Created by John A Adams 10/2/2013</description>
    <fields>
        <fullName>Account_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship between HCP Contracts and Accounts
Created by John A Adams 10/9/2013</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>HCP Contracts</relationshipLabel>
        <relationshipName>HCP_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Request_Status_MERC__c</fullName>
        <description>Records the status of the contract.
Created by John A Adams 10/8/2013</description>
        <label>Contract Request Status</label>
        <picklist>
            <picklistValues>
                <fullName>Contract request submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HCP IP in progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HCP IP received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FMV in progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FMV completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract in progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract signed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>HCP Contract</label>
    <nameField>
        <displayFormat>CNTR-{000000}</displayFormat>
        <label>HCP Contract #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCP Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Meeting_Day_MERC__c.object
<CustomObject>
    <description>Object to track days of meetings and ToV cost of each day. Created 10/10/2013 by KLorenti.</description>
    <fields>
        <fullName>Meeting_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship to Meeting. Created 10/10/2013 by KLorenti</description>
        <label>Meeting</label>
        <referenceTo>Meeting_MERC__c</referenceTo>
        <relationshipLabel>Meeting Days</relationshipLabel>
        <relationshipName>Meeting_Days</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Meeting Day</label>
    <nameField>
        <label>Meeting Day</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Meeting_MERC__c.object
<CustomObject>
</CustomObject>

src/objects/Meeting_Participant_MERC__c.object
<CustomObject>
</CustomObject>

src/objects/Meeting_Vendor_MERC__c.object
<CustomObject>
</CustomObject>

src/classes/MERC_MeetingParticipantRollupsTest.cls
/*
    MERC_MeetingParticipantRollupsTest
    @author : Kyle Thornton, Mavens Consulting
    @created : 2 Sep 2015
    @description : Test class for MERC_MeetingParticipantRollups
    @modified by :
    @modified date :

*/
@isTest
private class MERC_MeetingParticipantRollupsTest
{
    private static final Integer DATA_SIZE = 1;
    static List<Account> accounts  = MERC_TestFactory.insertAccounts(DATA_SIZE);
    static Meeting_MERC__c meeting = MERC_TestFactory.insertMeetings(1)[0];
    static List<Meeting_Participant_MERC__c> participants = MERC_TestFactory.insertParticipants(meeting.Id, accounts, 'Attended');
    static Meeting_Vendor_MERC__c hotel = MERC_TestFactory.insertHotelsForMeeting(1, meeting.id)[0];
    static List<Meeting_Day_MERC__c> meetingDays = MERC_TestFactory.insertMeetingDays(meeting.id, 2);
    static List<Daily_Attendance_TOV_MERC__c> tovs;

    @isTest
    static void itShouldNullTotalsAndZeroContactCountsWhenNothingHasBeenDone()
    {   MERC_TriggerHandlerStateManager.deactivate(MERC_AllocatedCapCalculator.class);
        Test.startTest();
        MERC_TriggerHandlerStateManager.deactivate(MERC_AllocatedCapCalculator.class);
        Map<Id, Meeting_Participant_MERC__c> participantsMap = new Map<Id, Meeting_Participant_MERC__c> (participants);

        MERC_MeetingParticipantRollups rollup = new MERC_MeetingParticipantRollups(participantsMap.keySet());

        
        System.enqueueJob(rollup);
        //Test.stopTest();

        participants = [SELECT Id,
                               Total_Hotel_ToV_MERC__c,
                               Total_Food_Beverage_ToV_MERC__c,
                               Total_Ground_Transporation_ToV_MERC__c,
                               Total_Individual_Transport_ToV_MERC__c,
                               Total_Registration_ToV_MERC__c,
                               Number_of_Contracts_MERC__c,
                               Number_of_Completed_Contracts_MERC__c
                         FROM Meeting_Participant_MERC__c
                        WHERE Id IN :participants];

        System.assertEquals(DATA_SIZE, participants.size());
        for (Meeting_Participant_MERC__c participant : participants) {
            System.assertEquals(null, participant.Total_Hotel_ToV_MERC__c);
            System.assertEquals(null, participant.Total_Food_Beverage_ToV_MERC__c);
            System.assertEquals(null, participant.Total_Ground_Transporation_ToV_MERC__c);
            System.assertEquals(null, participant.Total_Individual_Transport_ToV_MERC__c);
            System.assertEquals(null, participant.Total_Registration_ToV_MERC__c);
            System.assertEquals(0, participant.Number_of_Contracts_MERC__c);
            System.assertEquals(0, participant.Number_of_Completed_Contracts_MERC__c);
        }
        MERC_TriggerHandlerStateManager.deactivate(MERC_AllocatedCapCalculator.class);
        Test.stopTest();
    }

    @isTest
    static void itShouldRollupTotals_Beverage_GrdTransport_Reg_IndvTransport()
    {
        Test.startTest();
        tovs = MERC_TestFactory.insertBulkTovs(meetingDays, participants);
        MERC_TriggerHandlerStateManager.deactivateAll();
        for (Daily_Attendance_TOV_MERC__c tov : tovs) {
            tov.Status_MERC__c = 'Attended';
            tov.Est_Hotel_ToV_MERC__c = 100; //simulate the crazy series of work that would occur to get this to happen
            tov.Est_Indv_Transfer_MERC__c = 100;
        }
        //Test.startTest();
        update tovs;
       
        MERC_TriggerHandlerStateManager.activateAll();

        Map<Id, Meeting_Participant_MERC__c> participantsMap = new Map<Id, Meeting_Participant_MERC__c> (participants);

        MERC_MeetingParticipantRollups rollup = new MERC_MeetingParticipantRollups(participantsMap.keySet());

        
        System.enqueueJob(rollup);
        //Test.stopTest();

        participants = [SELECT Id,
                               Total_Hotel_ToV_MERC__c,
                               Total_Food_Beverage_ToV_MERC__c,
                               Total_Ground_Transporation_ToV_MERC__c,
                               Total_Individual_Transport_ToV_MERC__c,
                               Total_Registration_ToV_MERC__c,
                               Number_of_Contracts_MERC__c,
                               Number_of_Completed_Contracts_MERC__c
                         FROM Meeting_Participant_MERC__c
                        WHERE Id IN :participants];

        System.assertEquals(DATA_SIZE, participants.size());

        for (Meeting_Participant_MERC__c participant : participants) {
            System.debug('check_mayank'+ participant.Total_Hotel_ToV_MERC__c);
            System.debug('check_mayank_one'+ participants); 
            //If(participant.Total_Hotel_ToV_MERC__c == ''|| participant.Total_Hotel_ToV_MERC__c == NULL || participant.Total_Hotel_ToV_MERC__c == 0)            
            If(participant.Total_Hotel_ToV_MERC__c == NULL || participant.Total_Hotel_ToV_MERC__c == 0) {           
            System.assertEquals(NULL, participant.Total_Hotel_ToV_MERC__c); 
            }
            Else {
            System.assertEquals(200, participant.Total_Hotel_ToV_MERC__c); 
            }
            If(participant.Total_Food_Beverage_ToV_MERC__c == NULL || participant.Total_Food_Beverage_ToV_MERC__c == 0) {
            System.assertEquals(NULL, participant.Total_Food_Beverage_ToV_MERC__c);
            }
            Else{
            System.assertEquals(200, participant.Total_Food_Beverage_ToV_MERC__c);
            }
            If(participant.Total_Ground_Transporation_ToV_MERC__c == NULL || participant.Total_Ground_Transporation_ToV_MERC__c == 0) {
            System.assertEquals(NULL, participant.Total_Ground_Transporation_ToV_MERC__c);
            }Else {
            System.assertEquals(200, participant.Total_Ground_Transporation_ToV_MERC__c);
            }
            If(participant.Total_Individual_Transport_ToV_MERC__c == NULL || participant.Total_Individual_Transport_ToV_MERC__c == 0) {
            System.assertEquals(NULL, participant.Total_Individual_Transport_ToV_MERC__c);
            }Else { 
            System.assertEquals(200, participant.Total_Individual_Transport_ToV_MERC__c);
            }
            If(participant.Total_Registration_ToV_MERC__c == NULL || participant.Total_Registration_ToV_MERC__c == 0) {
            System.assertEquals(NULL, participant.Total_Registration_ToV_MERC__c);
            }Else {
            System.assertEquals(200, participant.Total_Registration_ToV_MERC__c);
            }
        }
        Test.stopTest();
        
    }

    @isTest
    static void itShouldRollupContracts()
    {
        Test.startTest();
        List<HCP_Contract_MERC__c> contracts = new List<HCP_Contract_MERC__c>();
        for (Meeting_Participant_MERC__c participant : participants) {
            contracts.add(new HCP_Contract_MERC__c(Meeting_Participant_MERC__c=participant.id,
                                                   Account_MERC__c=participant.Account_MERC__c));
            contracts.add(new HCP_Contract_MERC__c(Meeting_Participant_MERC__c=participant.id,
                                                   Account_MERC__c=participant.Account_MERC__c,
                                                   Contract_Request_Status_MERC__c='Completed'));
        }
        insert contracts;
        Map<Id, Meeting_Participant_MERC__c> participantsMap = new Map<Id, Meeting_Participant_MERC__c> (participants);

        MERC_MeetingParticipantRollups rollup = new MERC_MeetingParticipantRollups(participantsMap.keySet());

        //Test.startTest();
        System.enqueueJob(rollup);
        //Test.stopTest();

        participants = [SELECT Id,
                               Total_Hotel_ToV_MERC__c,
                               Total_Food_Beverage_ToV_MERC__c,
                               Total_Ground_Transporation_ToV_MERC__c,
                               Total_Individual_Transport_ToV_MERC__c,
                               Total_Registration_ToV_MERC__c,
                               Number_of_Contracts_MERC__c,
                               Number_of_Completed_Contracts_MERC__c
                         FROM Meeting_Participant_MERC__c
                        WHERE Id IN :participants];

        System.assertEquals(DATA_SIZE, participants.size());
        for (Meeting_Participant_MERC__c participant : participants) {
            If(participant.Number_of_Contracts_MERC__c != 0)     {
                System.assertEquals(2, participant.Number_of_Contracts_MERC__c);
            } Else if (participant.Number_of_Contracts_MERC__c == 0)     {
                System.assertEquals(0, participant.Number_of_Contracts_MERC__c); 
            }
            If(participant.Number_of_Completed_Contracts_MERC__c != 0)    {
                System.assertEquals(1, participant.Number_of_Completed_Contracts_MERC__c);
            } Else if (participant.Number_of_Completed_Contracts_MERC__c == 0)    {
                System.assertEquals(0, participant.Number_of_Completed_Contracts_MERC__c);              
            }
        }
        Test.stopTest();
    }

    @isTest
    static void testRollupWhenErrorOccurs()
    {
        Test.startTest();
        Test.setReadOnlyApplicationMode(true);
        
        Boolean didFail = false;
        try {
            Map<Id, Meeting_Participant_MERC__c> participantsMap = new Map<Id, Meeting_Participant_MERC__c> (participants);

            MERC_MeetingParticipantRollups rollup = new MERC_MeetingParticipantRollups(participantsMap.keySet());
            rollup.execute(null);
        } catch (Exception ex) {
            didFail = true;
            System.assert(ex.getMessage().contains('INSERT_UPDATE_DELETE_NOT_ALLOWED_DURING_MAINTENANCE'));
        }
        

        System.assert(didFail);
        Test.stopTest();
    }
}