src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Prsnl_Nbr_GLBL__c</fullName>
        <description>Workforce ODS data. Created 10/17/2013 by KLorenti, Mavens Consulting</description>
        <label>Global ID</label>
        <length>8</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/CST_User_Settings_CUST__c.object
<CustomObject>
    <description>Holds user authorization settings for the Customer Search Tool. Every row reflects a single User/Country/Level combination. Users with access to multiple countries will have multiple rows in this table : MERC, CUST : Created on 02/11/2014 by Sean Harrison, Mavens Consulting</description>
    <fields>
        <fullName>Access_Status_CUST__c</fullName>
        <description>Contains the status of the access request</description>
        <inlineHelpText>Pending: Waiting on Approval
Denied: Manager denied Request
Approved: Access granted
Under Review: Under Audit Review
Expired: Access expired before it was reviewed</inlineHelpText>
        <label>Access Status</label>
        <picklist>
            <picklistValues>
                <fullName>New Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CST_User_CUST__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is a lookup to an Account record containing information for an Lilly employee or designate. Adding an Account here will authorize this user to utilized the Customer Search Tool</description>
        <inlineHelpText>This field is a lookup to an Account record containing information for an Lilly employee or designate. Adding an Account here will authorize this user to utilized the Customer Search Tool</inlineHelpText>
        <label>CST User</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CST User Settings</relationshipLabel>
        <relationshipName>CST_User_Settings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manager_Global_ID_CUST__c</fullName>
        <description>The Managers Global ID</description>
        <inlineHelpText>The Global ID of the Users Manager</inlineHelpText>
        <label>Manager Global ID</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>CST User Settings</label>
    <nameField>
        <displayFormat>CSTUS-{000000}</displayFormat>
        <label>CST User Settings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CST User Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CUST_UserSettingsWillExpireBatchableTest.cls
/**
 * @author Kyle Thornton
 *
 * Unit tests for CUST_UserSettingsWillExpireBatchable class
 */
@isTest
private class CUST_UserSettingsWillExpireBatchableTest {

	static List<Account> accounts = MERC_TestFactory.insertEmployeeAccounts(2);

	@isTest static void test_manager_is_blank() {
		Test.startTest();
		List<CST_User_Settings_CUST__c> settings = new List<CST_User_Settings_CUST__c>{
				new CST_User_Settings_CUST__c(Access_Status_CUST__c='Under Review',CST_User_CUST__c=accounts.get(0).Id),
				new CST_User_Settings_CUST__c(Access_Status_CUST__c='Under Review',CST_User_CUST__c=accounts.get(1).Id)
		};
		insert settings;

		CUST_UserSettingsWillExpireBatchable b = new CUST_UserSettingsWillExpireBatchable();
		Database.executeBatch(b);
		Test.stopTest();
	}

	@isTest static void test_manager_is_not_blank() {
		accounts.get(0).Prsnl_Nbr_GLBL__c = '123';
		accounts.get(1).Prsnl_Nbr_GLBL__c = '123';
		update accounts;

		List<CST_User_Settings_CUST__c> settings = new List<CST_User_Settings_CUST__c>{
				new CST_User_Settings_CUST__c(Access_Status_CUST__c='Under Review',CST_User_CUST__c=accounts.get(0).Id, Manager_Global_ID_CUST__c='123'),
				new CST_User_Settings_CUST__c(Access_Status_CUST__c='Under Review',CST_User_CUST__c=accounts.get(1).Id, Manager_Global_ID_CUST__c='123')
		};
		insert settings;

		Test.startTest();
		CUST_UserSettingsWillExpireBatchable b = new CUST_UserSettingsWillExpireBatchable();
		Database.executeBatch(b);
		Test.stopTest();

		System.assertEquals(2, [SELECT COUNT() FROM Account WHERE Flag_CST_Expire_Email_CUST__c='MANAGER']);
	}

	@isTest static void test_schedule() {
		Test.startTest();
		String CRON_EXP = '0 0 0 3 9 ? 2032';

      	// Schedule the test job
      	String jobId = System.schedule('testScheduledApex',
      									CRON_EXP,
         								new CUST_UserSettingsWillExpireBatchable());

		// Get the information from the CronTrigger API object
		CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime
		 				FROM CronTrigger WHERE id = :jobId];

		// Verify the expressions are the same
		System.assertEquals(CRON_EXP, ct.CronExpression);

		// Verify the job has not run
		System.assertEquals(0, ct.TimesTriggered);

		// Verify the next time the job will run
		System.assertEquals('2032-09-03 00:00:00',
		String.valueOf(ct.NextFireTime));

   		Test.stopTest();
	}
}