src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Allocated_CAP_MERC__c</fullName>
        <description>Committed money, but service not yet performed. After meeting owner final fee confirmation, which happens after HCP contract request by Meeting owner and shortly before contract preparation. Cap is released in case of cancellation.
 Created 10/08/2013 by KLorenti.</description>
        <inlineHelpText>Committed money, but service not yet performed. Cap is released in case of cancellation.</inlineHelpText>
        <label>Allocated CAP</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status_MERC__c</fullName>
        <description>Status of Account. Created 10/4/2013 by KLorenti.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Validated by LMM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/LookupRollupSummary_GLBL__c.object
<CustomObject>
    <description>Object defines a the fields on a child object to roll up to a parent object using Lookup Rollup functionality.

MERC : Created on 2014-05-27 by Joe Ferraro, Mavens Consulting</description>
    <fields>
        <fullName>Active_GLBL__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>For Realtime rollups can only be set when the Child Apex Trigger has been deployed.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AggregateOperation_GLBL__c</fullName>
        <inlineHelpText>Rollup operation.</inlineHelpText>
        <label>Aggregate Operation</label>
        <picklist>
            <picklistValues>
                <fullName>Sum</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Max</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Min</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Count</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>AggregateResultField_GLBL__c</fullName>
        <inlineHelpText>API name of the field that will store the result of the rollup on the Parent Object, e.g. AnnualRevenue</inlineHelpText>
        <label>Aggregate Result Field</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CalculationMode_GLBL__c</fullName>
        <inlineHelpText>Realtime mode requires an Apex Trigger to be deployed for the Child Object. Click Manage Child Trigger button to deploy.</inlineHelpText>
        <label>Calculation Mode</label>
        <picklist>
            <picklistValues>
                <fullName>Realtime</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Developer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ChildObject_GLBL__c</fullName>
        <inlineHelpText>API name of the Child Object, e.g. Opportunity</inlineHelpText>
        <label>Child Object</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldToAggregate_GLBL__c</fullName>
        <inlineHelpText>API name of the field on the Child Object that contains the value to rollup, e.g. Amount</inlineHelpText>
        <label>Field to Aggregate</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OverrideTriggerValidation_GLBL__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, developer will be required to connect to the Lookup service via Apex (no trigger will be created automatically).</description>
        <inlineHelpText>If checked, developer will be required to connect to the Lookup service via Apex (no trigger will be created automatically).</inlineHelpText>
        <label>Override Trigger Validation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ParentObject_GLBL__c</fullName>
        <inlineHelpText>API name of the Parent Object, e.g. Account</inlineHelpText>
        <label>Parent Object</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RelationshipCriteria_GLBL__c</fullName>
        <inlineHelpText>SOQL WHERE clause applied when querying Child Object records, e.g. Amount &gt; 200</inlineHelpText>
        <label>Relationship Criteria</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RelationshipField_GLBL__c</fullName>
        <inlineHelpText>API name of the Lookup field on the Child Object relating to the Parent Object, e.g. AccountId</inlineHelpText>
        <label>Relationship Field</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TreatZeroAsNull_GLBL__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If true, a zero calculation will be stamped as null</description>
        <inlineHelpText>If true, a zero calculation will be stamped as null</inlineHelpText>
        <label>TreatZeroAsNull</label>
        <type>Checkbox</type>
    </fields>
    <label>Lookup Rollup Summary</label>
    <nameField>
        <label>Lookup Rollup Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lookup Rollup Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Meeting_MERC__c.object
<CustomObject>
</CustomObject>

src/objects/Meeting_Participant_MERC__c.object
<CustomObject>
</CustomObject>

src/classes/MERC_HcpCapYearlyCalculationJobTest.cls
@isTest
private class MERC_HcpCapYearlyCalculationJobTest {

	static List<Account> accounts = MERC_TestFactory.insertAccounts(200);
	static Meeting_MERC__c meeting = MERC_TestFactory.insertMeetings(1).get(0);
	static List<Meeting_Participant_MERC__c> participants = MERC_TestFactory.insertParticipants(meeting.Id, accounts);
	static {
		update new Meeting_MERC__c(
					Id                                   =meeting.Id,
					Meeting_Status_MERC__c               ='Registered',
					City_of_Meeting_MERC__c              ='London',
					Number_of_Expected_Employees_MERC__c =10,
					Number_of_Expected_Non_HCP_MERC__c   =10,
					Number_of_Expected_Speakers_MERC__c  =10,
					Interaction_Type_MERC__c             ='Virtual',
					Planned_Budget_MERC__c               =10000
		);

		List<LookupRollupSummary_GLBL__c> lrs = new List<LookupRollupSummary_GLBL__c>();
		lrs.add( new LookupRollupSummary_GLBL__c(
				Active_GLBL__c                    = true,
				AggregateOperation_GLBL__c        = 'Sum',
				AggregateResultField_GLBL__c      = 'Allocated_CAP_MERC__c',
				CalculationMode_GLBL__c           = 'Developer',
				ChildObject_GLBL__c               = 'Meeting_Participant_MERC__c',
				FieldToAggregate_GLBL__c          = 'Final_Fee_MERC__c',
				Name                              = 'Allocated Cap Batch',
				OverrideTriggerValidation_GLBL__c = true,
				ParentObject_GLBL__c              = 'Account',
				RelationshipCriteria_GLBL__c      = 'Meeting_MERC__r.End_Date_of_Event_MERC__c = THIS_YEAR '
				                                  + 'AND Meeting_MERC__r.Meeting_Status_MERC__c IN(\'Registered\', \'Active\') '
				                                  + 'AND Include_CAP_Roll_Up_MERC__c = TRUE '
				                                  + 'AND Status_MERC__c NOT IN(\'Cancelled\', \'Rejected\', \'Declined\')',
				RelationshipField_GLBL__c         = 'Account_MERC__c',
				TreatZeroAsNull_GLBL__c           = false
		));
		insert lrs;
	}

	@isTest static void test_batch_job() {

		for (Meeting_Participant_MERC__c participant : participants) {
			participant.Final_Fee_MERC__c           = 100;
			participant.Include_CAP_Roll_Up_MERC__c = true;
			//participant.Proposed_Final_Fee_MERC__c = 0;
		}
		update participants;

		for (Account a : accounts) {
			a.Allocated_CAP_MERC__c = null;
		}
		update accounts;

		//System.assertEquals(1,[SELECT COUNT() FROM Account WHERE Allocated_CAP_MERC__c=null]);

		Test.startTest();
       	MERC_HcpCapYearlyCalculationJob m = new MERC_HcpCapYearlyCalculationJob();
       	Database.executeBatch(m);
       	Test.stopTest();

       	System.debug([select Allocated_CAP_MERC__c from account]);
       	System.assertEquals(200,[SELECT COUNT() FROM Account WHERE Allocated_CAP_MERC__c=100.0], [select Allocated_CAP_MERC__c from account]);
	}
}