src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status_MERC__c</fullName>
        <description>Status of Account. Created 10/4/2013 by KLorenti.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Validated by LMM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Daily_Attendance_TOV_MERC__c.object
<CustomObject>
    <description>Junction object between Meeting Days and Meeting Participants, stores a breakdown of Daily ToV which is picked up by the AODS Interface : MERC : Created on 10/10/2013 by John Adams, Mavens Consulting</description>
    <fields>
        <fullName>Meeting_Day_MERC__c</fullName>
        <description>Master Detail relationship from Daily Attendance to Meeting Day. Created 10/10/2013 by KLorenti.</description>
        <label>Meeting Day</label>
        <referenceTo>Meeting_Day_MERC__c</referenceTo>
        <relationshipLabel>Daily Attendance &amp; TOV</relationshipLabel>
        <relationshipName>Daily_Attendance_TOV</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Meeting_Participant_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master Detail relationship from Daily Attendance to Meeting Participant. Created 10/10/2013 by KLorenti.</description>
        <label>Meeting Participant</label>
        <referenceTo>Meeting_Participant_MERC__c</referenceTo>
        <relationshipLabel>Daily Attendance &amp; TOV</relationshipLabel>
        <relationshipName>Daily_Attendance_TOV_MERC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status_MERC__c</fullName>
        <description>Used to report across daily meeting attendance for HCP&apos;s. Oliver Dunford 6th Nov  2013.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Daily Attendance &amp; TOV</label>
    <nameField>
        <displayFormat>DA-{000000}</displayFormat>
        <label>Attendance #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Attendance &amp; TOV</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Meeting_Day_MERC__c.object
<CustomObject>
    <description>Object to track days of meetings and ToV cost of each day. Created 10/10/2013 by KLorenti.</description>
    <fields>
        <fullName>Meeting_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship to Meeting. Created 10/10/2013 by KLorenti</description>
        <label>Meeting</label>
        <referenceTo>Meeting_MERC__c</referenceTo>
        <relationshipLabel>Meeting Days</relationshipLabel>
        <relationshipName>Meeting_Days</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Meeting Day</label>
    <nameField>
        <label>Meeting Day</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Meeting_MERC__c.object
<CustomObject>
</CustomObject>

src/objects/Meeting_Participant_MERC__c.object
<CustomObject>
</CustomObject>

src/classes/MERC_DailyAttendanceControllerTest.cls
/**
 * @author Joseph Ferraro
 *
 * Asserts functionality for daily attendance/tov controller functionality found in MERC_DailyAttendanceController
 */

@isTest
private class MERC_DailyAttendanceControllerTest {

	static User testUser = MERC_TestFactory.getRunningUser();
	static List<Meeting_MERC__c> meetings;
	static List<Account> accounts;
	static List<Meeting_Day_MERC__c> meetingDays;
	static List<Meeting_Participant_MERC__c> participants;

	static {
		accounts = MERC_TestFactory.insertAccounts(5); //insert 5 accounts
		meetings = MERC_TestFactory.insertMeetings(2); //insert 2 meetings
		meetingDays = MERC_TestFactory.insertMeetingDays(meetings.get(0).Id, 3); //insert 3 days
		participants = MERC_TestFactory.insertParticipants(meetings.get(0).Id, accounts, 'Accepted'); //insert 5 participants
	}

	@isTest static void basic_daily_attendance_test() {
		System.runas(testUser) {
			Meeting_MERC__c mtg = meetings.get(0);

			PageReference p = Page.MERC_DailyAttendance;
			p.getParameters().put('id', mtg.Id);
			Test.setCurrentPage(p);

			Test.startTest();

			ApexPages.StandardSetController setController = new ApexPages.StandardSetController(new List<Daily_Attendance_TOV_MERC__c>());
			MERC_DailyAttendanceController c = new MERC_DailyAttendanceController(setController);
			c.upsertMissingTovRecords();
			c = new MERC_DailyAttendanceController(setController);

			System.assertEquals(null, c.changeDay());
			System.assert(c.refreshParticipants);

			c.selectedMeetingDayId = c.meetingDays.get(0).Id;

			System.assertEquals(mtg.Id, c.meeting.Id);
			System.assertEquals(meetingDays.size(), c.getMeetingDayOptions().size());
			System.assertEquals(participants.size(), c.participants.size());

			c.participants.get(0).selected = True;
			c.setSelectedToAttended();
			System.assertEquals('Attended', [SELECT Status_MERC__c FROM Daily_Attendance_TOV_MERC__c WHERE Id = :c.participants.get(0).tov.Id].Status_MERC__c);

			c.participants.get(1).selected = True;
			c.setSelectedToNoShow();
			System.assertEquals('No Show', [SELECT Status_MERC__c FROM Daily_Attendance_TOV_MERC__c WHERE Id = :c.participants.get(1).tov.Id].Status_MERC__c);

			// c.participants.get(0).tov.Status_MERC__c = 'No Show';
			// ApexPages.currentPage().getParameters().put('tovRecordId', c.participants.get(0).tov.Id);
			// c.updateTov();
			// System.assertEquals('No Show', [SELECT Status_MERC__c FROM Daily_Attendance_TOV_MERC__c WHERE Id = :c.participants.get(0).tov.Id].Status_MERC__c);

			Test.stopTest();
		}
	}

	@isTest static void all_attended_test() {
		System.runas(testUser) {
			Meeting_MERC__c mtg = meetings.get(0);

			PageReference p = Page.MERC_DailyAttendance;
			p.getParameters().put('id', mtg.Id);
			Test.setCurrentPage(p);

			Test.startTest();

			ApexPages.StandardSetController setController = new ApexPages.StandardSetController(new List<Daily_Attendance_TOV_MERC__c>());
			MERC_DailyAttendanceController c = new MERC_DailyAttendanceController(setController);
			c.upsertMissingTovRecords();
			c = new MERC_DailyAttendanceController(setController);

			c.selectedMeetingDayId = c.meetingDays.get(0).Id;

			System.assertEquals(mtg.Id, c.meeting.Id);
			System.assertEquals(meetingDays.size(), c.getMeetingDayOptions().size());
			System.assertEquals(participants.size(), c.participants.size());

			c.participants.get(0).selected = True;
			c.setSelectedToAttended();
			System.assertEquals('Attended', [SELECT Status_MERC__c FROM Daily_Attendance_TOV_MERC__c WHERE Id = :c.participants.get(0).tov.Id].Status_MERC__c);

			c.selectedMeetingDayId = c.meetingDays.get(1).Id;
			c.participants.get(0).selected = True;
			c.setSelectedToAttended();
			System.assertEquals('Attended', [SELECT Status_MERC__c FROM Daily_Attendance_TOV_MERC__c WHERE Id = :c.participants.get(0).tov.Id].Status_MERC__c);

			c.selectedMeetingDayId = c.meetingDays.get(2).Id;
			c.participants.get(0).selected = True;
			c.setSelectedToAttended();
			System.assertEquals('Attended', [SELECT Status_MERC__c FROM Daily_Attendance_TOV_MERC__c WHERE Id = :c.participants.get(0).tov.Id].Status_MERC__c);

			System.assertEquals('Attended', [SELECT Status_MERC__c FROM Meeting_Participant_MERC__c WHERE Id = :c.participants.get(0).tov.Meeting_Participant_MERC__c].Status_MERC__c);
			Test.stopTest();
		}
	}

	@isTest static void some_attended_test() {
		System.runAs(testUser) {
			Meeting_MERC__c mtg = meetings.get(0);

			PageReference p = Page.MERC_DailyAttendance;
			p.getParameters().put('id', mtg.Id);
			Test.setCurrentPage(p);

			Test.startTest();

			ApexPages.StandardSetController setController = new ApexPages.StandardSetController(new List<Daily_Attendance_TOV_MERC__c>());
			MERC_DailyAttendanceController c = new MERC_DailyAttendanceController(setController);
			c.upsertMissingTovRecords();
			c = new MERC_DailyAttendanceController(setController);

			c.selectedMeetingDayId = c.meetingDays.get(0).Id;

			System.assertEquals(mtg.Id, c.meeting.Id);
			System.assertEquals(meetingDays.size(), c.getMeetingDayOptions().size());
			System.assertEquals(participants.size(), c.participants.size());

			c.participants.get(0).selected = True;
			c.setSelectedToAttended();
			System.assertEquals('Attended', [SELECT Status_MERC__c FROM Daily_Attendance_TOV_MERC__c WHERE Id = :c.participants.get(0).tov.Id].Status_MERC__c);

			c.selectedMeetingDayId = c.meetingDays.get(1).Id;
			c.participants.get(0).selected = True;
			c.setSelectedToAttended();
			System.assertEquals('Attended', [SELECT Status_MERC__c FROM Daily_Attendance_TOV_MERC__c WHERE Id = :c.participants.get(0).tov.Id].Status_MERC__c);

			c.selectedMeetingDayId = c.meetingDays.get(2).Id;
			c.participants.get(0).selected = True;
			c.setSelectedToNoShow();
			System.assertEquals('No Show', [SELECT Status_MERC__c FROM Daily_Attendance_TOV_MERC__c WHERE Id = :c.participants.get(0).tov.Id].Status_MERC__c);

			c.selectedMeetingDayId = c.meetingDays.get(1).Id;
			c.participants.get(0).tov.Status_MERC__c = 'No Show';
			c.saveAll();
			System.assertEquals('No Show', [SELECT Status_MERC__c FROM Daily_Attendance_TOV_MERC__c WHERE Id = :c.participants.get(0).tov.Id].Status_MERC__c);

			c.selectedMeetingDayId = c.meetingDays.get(2).Id;
			c.participants.get(0).tov.Status_MERC__c = 'Attended';
			ApexPages.currentPage().getParameters().put('tovRecordId', c.participants.get(0).tov.Id);
			c.updateTov();
			System.assertEquals('Attended', [SELECT Status_MERC__c FROM Daily_Attendance_TOV_MERC__c WHERE Id = :c.participants.get(0).tov.Id].Status_MERC__c);

			System.assertEquals('Attended', [SELECT Status_MERC__c FROM Meeting_Participant_MERC__c WHERE Id = :c.participants.get(0).tov.Meeting_Participant_MERC__c].Status_MERC__c);
			Test.stopTest();
		}
	}

	@isTest static void no_show_test() {
		System.runAs(testUser) {
			Meeting_MERC__c mtg = meetings.get(0);

			PageReference p = Page.MERC_DailyAttendance;
			p.getParameters().put('id', mtg.Id);
			Test.setCurrentPage(p);

			Test.startTest();

			ApexPages.StandardSetController setController = new ApexPages.StandardSetController(new List<Daily_Attendance_TOV_MERC__c>());
			MERC_DailyAttendanceController c = new MERC_DailyAttendanceController(setController);
			c.upsertMissingTovRecords();
			c = new MERC_DailyAttendanceController(setController);

			c.selectedMeetingDayId = c.meetingDays.get(0).Id;

			System.assertEquals(mtg.Id, c.meeting.Id);
			System.assertEquals(meetingDays.size(), c.getMeetingDayOptions().size());
			System.assertEquals(participants.size(), c.participants.size());

			c.participants.get(0).selected = True;
			c.setSelectedToNoShow();
			System.assertEquals('No Show', [SELECT Status_MERC__c FROM Daily_Attendance_TOV_MERC__c WHERE Id = :c.participants.get(0).tov.Id].Status_MERC__c);

			c.selectedMeetingDayId = c.meetingDays.get(1).Id;
			c.participants.get(0).selected = True;
			c.setSelectedToNoShow();
			System.assertEquals('No Show', [SELECT Status_MERC__c FROM Daily_Attendance_TOV_MERC__c WHERE Id = :c.participants.get(0).tov.Id].Status_MERC__c);

			c.selectedMeetingDayId = c.meetingDays.get(2).Id;
			c.participants.get(0).selected = True;
			c.setSelectedToNoShow();
			System.assertEquals('No Show', [SELECT Status_MERC__c FROM Daily_Attendance_TOV_MERC__c WHERE Id = :c.participants.get(0).tov.Id].Status_MERC__c);

			System.assertEquals('No Show', [SELECT Status_MERC__c FROM Meeting_Participant_MERC__c WHERE Id = :c.participants.get(0).tov.Meeting_Participant_MERC__c].Status_MERC__c);
			Test.stopTest();
		}
	}

	@isTest static void testExceptions() {
		System.runAs(testUser) {
			Meeting_MERC__c mtg = meetings.get(0);

			PageReference p = Page.MERC_DailyAttendance;
			p.getParameters().put('id', mtg.Id);
			Test.setCurrentPage(p);

			Test.startTest();

			ApexPages.StandardSetController setController = new ApexPages.StandardSetController(new List<Daily_Attendance_TOV_MERC__c>());
			MERC_DailyAttendanceController c = new MERC_DailyAttendanceController(setController);
			c.upsertMissingTovRecords();
			c = new MERC_DailyAttendanceController(setController);

			c.selectedMeetingDayId = c.meetingDays.get(1).Id;
			//remove one tov record
			delete new Daily_Attendance_TOV_MERC__c(Id=c.participants.get(0).tov.id);
			c = new MERC_DailyAttendanceController(setController);

			//prevent any updates to the system and force errors on DML
			Test.setReadOnlyApplicationMode(true);
			c.upsertMissingTovRecords();
			System.assert(c.hasError);
			System.assertEquals(2, ApexPages.getMessages().size());

			c.selectedMeetingDayId = c.meetingDays.get(0).Id;

			c.participants.get(0).selected = true;
			c.setSelectedToNoShow();
			System.assertEquals(3, ApexPages.getMessages().size(), ApexPages.getMessages());

			c.participants.get(0).selected = true;
			c.setSelectedToAttended();
			System.assertEquals(3, ApexPages.getMessages().size(), ApexPages.getMessages());

			c.saveAll();
			System.assertEquals(3, ApexPages.getMessages().size());

			ApexPages.currentPage().getParameters().put('tovRecordId', c.participants.get(0).tov.Id);
			c.updateTov();
			System.assertEquals(3, ApexPages.getMessages().size());

			Test.stopTest();
		}
	}

}