src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country_of_Residence_GLBL__c</fullName>
        <description>Country of residence which may differ from the Country to be used for contract fee calculation.  Needed for Tax Purposes in Invoice.
Created by John A Adams 10/20/2013</description>
        <label>Country of Residence</label>
        <picklist>
            <picklistValues>
                <fullName>ES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AF</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Meeting_Day_MERC__c.object
<CustomObject>
    <description>Object to track days of meetings and ToV cost of each day. Created 10/10/2013 by KLorenti.</description>
    <fields>
        <fullName>Meeting_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship to Meeting. Created 10/10/2013 by KLorenti</description>
        <label>Meeting</label>
        <referenceTo>Meeting_MERC__c</referenceTo>
        <relationshipLabel>Meeting Days</relationshipLabel>
        <relationshipName>Meeting_Days</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meeting_Time_Zone_MERC__c</fullName>
        <formula>text(Meeting_MERC__r.Meeting_Time_Zone_MERC__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Meeting Time Zone</label>
        <type>Text</type>
    </fields>
    <label>Meeting Day</label>
    <nameField>
        <label>Meeting Day</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Meeting_MERC__c.object
<CustomObject>
</CustomObject>

src/objects/Mercury_Settings_MERC__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Custom Settings for the Mercury Project mostly related to the operation of the Customer Search Tool, Veeva integration, Budget and Invoice processing.</description>
    <fields>
        <fullName>Budget_Edit_Validation_MERC__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When checked, active/archived budgets cannot be modified.</description>
        <inlineHelpText>When checked, active/archived budgets cannot be modified.</inlineHelpText>
        <label>Budget Edit Validation</label>
        <type>Checkbox</type>
    </fields>
    <label>Mercury Settings</label>
</CustomObject>

src/classes/MERC_UtilTest.cls
@isTest
private class MERC_UtilTest {
	static User testUser = MERC_TestFactory.getRunningUser();
	static
	{
		MERC_TestFactory.insertMercuryCustomSettings();
		MERC_TestFactory.loadTimeZoneFieldMapSettings();
	}

	@isTest static void exercise_utility_methods()
	{

		System.runAs(testUser)
		{
			MERC_Util.disableBudgetEditValidation();
			System.assertEquals(false, Mercury_Settings_MERC__c.getOrgDefaults().Budget_Edit_Validation_MERC__c);

			MERC_Util.enableBudgetEditValidation();
			System.assertEquals(true, Mercury_Settings_MERC__c.getOrgDefaults().Budget_Edit_Validation_MERC__c);

			String picklistValue = MERC_Util.getTimeZonePicklistValueForCurrentUser(Meeting_MERC__c.Meeting_Time_Zone_MERC__c.getDescribe());
			System.assertEquals('Greenwich Mean Time (GMT)', picklistValue);

			System.assert( MERC_Util.getPicklistValues(Account.Country_of_Residence_GLBL__c.getDescribe()).size() > 0);

			System.assert( MERC_Util.getPicklistValues(Account.Country_of_Residence_GLBL__c.getDescribe(),true).size() > 1);

			List<SelectOption> options = MERC_Util.getCSTPicklistValuesForFieldName('Affiliation_Role_Types_CUST__c', false);
			System.assert(options.size() > 0);
			List<SelectOption> optionsWithDefault = MERC_Util.getCSTPicklistValuesForFieldName('Affiliation_Role_Types_CUST__c', true);
			System.assert(optionsWithDefault.size() == options.size()+1);

			Account a = MERC_TestFactory.insertAccounts(1).get(0);
			System.assertEquals('Account', MERC_Util.getSobjectAPIName(a));

			System.assert(MERC_Util.getTimeZoneFieldMapForObject('Meeting_MERC__c').size() > 0);
			System.assert(MERC_Util.getStampFieldMapForObject('Meeting_MERC__c').size() > 0);

			System.assert(MERC_Util.getFieldSetFieldList('Meeting_Day_MERC__c', new List<String>{'Meeting_Day_Manager_Columns_MERC'}).size() > 0);

			PageReference pageRef = Page.Get_Started;
			pageRef.getParameters().put('test','value');
			Test.setCurrentPage(pageRef);

			System.assertEquals('value', MERC_Util.getUrlParam('test'));

			System.assert( MERC_Util.getFieldSetLabels(Meeting_MERC__c.SobjectType,new List<String> {'Meeting_Date_Time_Edit_MERC'}).size() > 0);
		}
	}
}