src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country_of_Residence_GLBL__c</fullName>
        <description>Country of residence which may differ from the Country to be used for contract fee calculation.  Needed for Tax Purposes in Invoice.
Created by John A Adams 10/20/2013</description>
        <label>Country of Residence</label>
        <picklist>
            <picklistValues>
                <fullName>ES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AF</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Merge_History_GLBL__c.object
<CustomObject>
    <description>Capture history for account merges. Created 10/17/2013 by KLorenti, Mavens Consulting</description>
    <label>Merge History</label>
    <nameField>
        <displayFormat>HIST-{000000}</displayFormat>
        <label>Merge History #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merge History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MERC_MergedAccountsController.cls
public with sharing class MERC_MergedAccountsController {

	/* this list of accounts that have been merged and need manual intervention */
	public List<SelectableAccount> mergedAccounts { get; set; }

	/* the list of related lists for the selected account */
	public List<RelatedList>    relatedLists   { get; set; }

	/* The account that a user has selected to work on */
	public Id activeAccountId    { get; set; }
	public Account activeAccount { get; private set; }

	public MERC_MergedAccountsController() {
		mergedAccounts = new List<SelectableAccount>();
		activeAccount  = new Account();
		//List<Merge_History_GLBL__c> unprocessedMerges =
		for (Account a : [SELECT Id, Name, Country_of_Residence_GLBL__c, IsPersonAccount FROM Account Limit 10])
		{
			mergedAccounts.add( new SelectableAccount(a));
		}
	}

	public ApexPages.StandardSetController setController {
		get
		{
			String query = 'Select Id, Name FROM Account Order By Name limit 10';
			if(setController == null) {
				setController = new ApexPages.StandardSetController(Database.getQueryLocator( query ));
				// sets the number of records in each page set
				setController.setPageSize(5);
			}
		return setController;
		}
		set;
	}

	public void selectAccount()
	{
		System.debug('###### activeAccountId ' + activeAccountId);
	}

	public void markAccountsAsComplete()
	{
		System.debug('\n\n\n        STARTING LOOP\n\n\n');
		for (SelectableAccount wa : mergedAccounts)
		{
			System.debug('\n\n' + wa);
			if (wa.selected)
			{
				System.debug('\n\n' + wa.detail.Name);
				//wa.selected = false;
			}
		}
	}

	/* Holds this list of accounts with a selected boolean so that
	   Users can mark an account as completed */
	public class SelectableAccount
	{
		public Account detail   { get; set; }
		public Boolean selected { get; set; }

		public SelectableAccount(Account a)
		{
			this.detail   = a;
			this.selected = false;
		}
	}

	/* a generic sObject with a selected attribute */
	public class WrappedSObject
 	{
 		public SObject detail   { get; private set; }
 		public Boolean selected { get; set; }
 	}

 	/* represents two sets of relates lists. the winning records list
 	   (for reference) and the losing records list with the records that
 	   can be moved to the winning record */
 	public class RelatedList
 	{
 		public List<SObject>        winningObjectList { get; private set; }
 		public List<WrappedSObject> losingObjectList  { get; private set; }
		private Id winningRecordId;

		public RelatedList(Id winningRecordId)
		{
			this.winningRecordId   = winningRecordId;
			this.winningObjectList = new List<SObject>();
			this.losingObjectList  = new List<WrappedSObject>();
		}

		public void moveRecordsToWinner()
		{
			for (WrappedSObject wo : losingObjectList)
			{
				if (wo.selected)
				{
					//TODO: reparent/copy record to winner
				}
			}
		}
 	}
}