src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CODS_End_Date_GLBL__c</fullName>
        <description>Contains date that HCP was ended in Customer OCS.  RMAT on watching for this date will adjust Status field.
Created by John A Adams 10/23/2013</description>
        <label>CODS End Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

src/objects/LookupChild_GLBL__c.object
<CustomObject>
    <fields>
        <fullName>LookupParent_GLBL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lookup Parent</label>
        <referenceTo>LookupParent_GLBL__c</referenceTo>
        <relationshipLabel>Lookup Children</relationshipLabel>
        <relationshipName>LookupChildren</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Lookup Child</label>
    <nameField>
        <label>Lookup Child Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lookup Children</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LookupParent_GLBL__c.object
<CustomObject>
    <description>Object used to help tests classes for the Lookup Rollup Summary funcationality. MERC : Created on 2014-06-03 by Kyle Thornton, Mavens Consulting

https://github.com/afawcett/declarative-lookup-rollup-summaries/blob/master/rolluptool/src/objects/LookupParent__c.object</description>
    <fields>
        <fullName>Total_GLBL__c</fullName>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Lookup Parent</label>
    <nameField>
        <label>Lookup Parent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lookup Parents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/LookupRollupSummary_GLBL__c.object
<CustomObject>
    <description>Object defines a the fields on a child object to roll up to a parent object using Lookup Rollup functionality.

MERC : Created on 2014-05-27 by Joe Ferraro, Mavens Consulting</description>
    <fields>
        <fullName>Active_GLBL__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>For Realtime rollups can only be set when the Child Apex Trigger has been deployed.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AggregateOperation_GLBL__c</fullName>
        <inlineHelpText>Rollup operation.</inlineHelpText>
        <label>Aggregate Operation</label>
        <picklist>
            <picklistValues>
                <fullName>Sum</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Max</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Min</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Count</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>AggregateResultField_GLBL__c</fullName>
        <inlineHelpText>API name of the field that will store the result of the rollup on the Parent Object, e.g. AnnualRevenue</inlineHelpText>
        <label>Aggregate Result Field</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CalculateJobId_GLBL__c</fullName>
        <inlineHelpText>This field is used by the system when using the Calculate button to track if a calculation job is already running. Clear this field if the system reports the calculate job is already running and you known this is not the case.</inlineHelpText>
        <label>Calculate Job Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CalculationMode_GLBL__c</fullName>
        <inlineHelpText>Realtime mode requires an Apex Trigger to be deployed for the Child Object. Click Manage Child Trigger button to deploy.</inlineHelpText>
        <label>Calculation Mode</label>
        <picklist>
            <picklistValues>
                <fullName>Realtime</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Developer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ChildObject_GLBL__c</fullName>
        <inlineHelpText>API name of the Child Object, e.g. Opportunity</inlineHelpText>
        <label>Child Object</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldToAggregate_GLBL__c</fullName>
        <inlineHelpText>API name of the field on the Child Object that contains the value to rollup, e.g. Amount</inlineHelpText>
        <label>Field to Aggregate</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentObject_GLBL__c</fullName>
        <inlineHelpText>API name of the Parent Object, e.g. Account</inlineHelpText>
        <label>Parent Object</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RelationshipCriteria_GLBL__c</fullName>
        <inlineHelpText>SOQL WHERE clause applied when querying Child Object records, e.g. Amount &gt; 200</inlineHelpText>
        <label>Relationship Criteria</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RelationshipField_GLBL__c</fullName>
        <inlineHelpText>API name of the Lookup field on the Child Object relating to the Parent Object, e.g. AccountId</inlineHelpText>
        <label>Relationship Field</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Lookup Rollup Summary</label>
    <nameField>
        <label>Lookup Rollup Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lookup Rollup Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LookupRollupSummaryLog_GLBL__c.object
<CustomObject>
    <fields>
        <fullName>ErrorMessage_GLBL__c</fullName>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ParentId_GLBL__c</fullName>
        <externalId>true</externalId>
        <label>Parent Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ParentObject_GLBL__c</fullName>
        <label>Parent Object</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <label>Lookup Rollup Summary Log</label>
    <nameField>
        <label>Lookup Rollup Summary Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lookup Rollup Summary Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LookupRollupSummaryScheduleItems_GLBL__c.object
<CustomObject>
    <description>Object used to set up schedules for the Lookup Rollup Summary funcationality. MERC : Created on 2014-05-27 by Joe Ferraro, Mavens Consulting</description>
    <fields>
        <fullName>LookupRollupSummary_GLBL__c</fullName>
        <label>Lookup Rollup Summary</label>
        <referenceTo>LookupRollupSummary_GLBL__c</referenceTo>
        <relationshipLabel>Lookup Rollup Summary Schedule Items</relationshipLabel>
        <relationshipName>Lookup_Rollup_Summary_Schedule_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ParentId_GLBL__c</fullName>
        <label>Parent Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Lookup Rollup Summary Schedule Item</label>
    <nameField>
        <label>Lookup Rollup Summary Schedule Item Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lookup Rollup Summary Schedule Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GLBL_RollupServiceTest3.cls
/**
 * Copyright (c) 2013, Andrew Fawcett
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, 
 *   are permitted provided that the following conditions are met:
 *
 * - Redistributions of source code must retain the above copyright notice, 
 *      this list of conditions and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright notice, 
 *      this list of conditions and the following disclaimer in the documentation 
 *      and/or other materials provided with the distribution.
 * - Neither the name of the Andrew Fawcett, nor the names of its contributors 
 *      may be used to endorse or promote products derived from this software without 
 *      specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
 *  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
 *  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL 
 *  THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
 *  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 *  OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 *  OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 *  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**/

/**
 * Tests the RollupService methods, note the LREngine is test independently via TestLREngine
 **/
@IsTest
private with sharing class GLBL_RollupServiceTest3 
{		
	static Schema.SObjectField ACCOUNT_SLA_EXPIRATION_DATE;
	static Schema.SObjectField ACCOUNT_NUMBER_OF_LOCATIONS;		
	static
	{
		// Dynamically resolve these fields, if they are not present when the test runs, the test will return as passed to avoid failures in subscriber org when packaged
		Map<String, Schema.SObjectField> accountFields = Schema.SObjectType.Account.fields.getMap();
		ACCOUNT_SLA_EXPIRATION_DATE = accountFields.get('CODS_End_Date_GLBL__c');
		ACCOUNT_NUMBER_OF_LOCATIONS = accountFields.get('NumberOfEmployees');
	}
	
	//private testmethod static void testCalculateJob()
	//{		
	//	// Test supported?
	//	if(!GLBL_TestContext.isSupported())
	//		return;
		
	//	// Insert parents
	//	Schema.SObjectType parentType = Schema.getGlobalDescribe().get('LookupParent_GLBL__c');
	//	SObject parentA = parentType.newSObject();
	//	parentA.put('Name', 'ParentA');
	//	SObject parentB = parentType.newSObject();
	//	parentB.put('Name', 'ParentB');
	//	SObject parentC = parentType.newSObject();
	//	parentC.put('Name', 'ParentC');
	//	List<SObject> parents = new List<SObject> { parentA, parentB, parentC };
	//	insert parents;
		
	//	// Insert children
	//	Schema.SObjectType childType = Schema.getGlobalDescribe().get('LookupChild_GLBL__c');
	//	List<SObject> children = new List<SObject>();
	//	for(SObject parent : parents)		
	//	{
	//		String name = (String) parent.get('Name');
	//		SObject child1 = childType.newSObject();
	//		child1.put('LookupParent_GLBL__c', parent.Id);
	//		child1.put('Amount_GLBL__c', 20);
	//		children.add(child1);				
	//		SObject child2 = childType.newSObject();
	//		child2.put('LookupParent_GLBL__c', parent.Id);
	//		child2.put('Amount_GLBL__c', 20);
	//		children.add(child2);				
	//		if(name.equals('ParentA') || name.equals('ParentB'))
	//		{
	//			SObject child3 = childType.newSObject();
	//			child3.put('LookupParent_GLBL__c', parent.Id);
	//			child3.put('Amount_GLBL__c', 2);
	//			children.add(child3);				
	//		}
	//	}
	//	insert children;

	//	// Create rollup AFTER the data exists		
	//	LookupRollupSummary_GLBL__c rollupSummary = new LookupRollupSummary_GLBL__c();
	//	rollupSummary.Name = 'Test Rollup';
	//	rollupSummary.ParentObject_GLBL__c = 'LookupParent_GLBL__c';
	//	rollupSummary.ChildObject_GLBL__c = 'LookupChild_GLBL__c';
	//	rollupSummary.RelationShipField_GLBL__c = 'LookupParent_GLBL__c';
	//	rollupSummary.FieldToAggregate_GLBL__c = 'Amount_GLBL__c';
	//	rollupSummary.AggregateOperation_GLBL__c = GLBL_RollupSummaries.AggregateOperation.Sum.name();
	//	rollupSummary.AggregateResultField_GLBL__c = 'Total_GLBL__c';
	//	rollupSummary.Active_GLBL__c = true;
	//	rollupSummary.CalculationMode_GLBL__c = 'Scheduled';	
	//	insert rollupSummary;
		
	//	// Run rollup calculate job
	//	Test.startTest();		
	//	Id jobId = GLBL_RollupService.runJobToCalculate(rollupSummary.Id);
	//	rollupSummary = [select Id, CalculateJobId_GLBL__c from LookupRollupSummary_GLBL__c where Id  = :rollupSummary.Id];
	//	System.assertEquals(jobId, rollupSummary.CalculateJobId_GLBL__c); // Assert job id captured
	//	try { 
	//		// Assert not possible to start another
	//		GLBL_RollupService.runJobToCalculate(rollupSummary.Id);
	//		System.assert(false, 'Expected an exception');
	//	} catch (Exception e) {
	//		System.assert(e.getMessage().equals('A calculate job for rollup \'Test Rollup\' is already executing. If you suspect it is not aleady running try clearing the Calculate Job Id field and try again.'));
	//	}			 
	//	Test.stopTest();
	//	// Assert job id cleared
	//	rollupSummary = [select Id, CalculateJobId_GLBL__c from LookupRollupSummary_GLBL__c where Id  = :rollupSummary.Id];
	//	System.assertEquals(null, rollupSummary.CalculateJobId_GLBL__c);  

	//	// This should not generate any schedule items		
	//	System.assertEquals(0, [select id from LookupRollupSummaryScheduleItems_GLBL__c].size());
		
	//	// Assert rollups 
	//	Map<Id, SObject> assertParents = new Map<Id, SObject>(Database.query('select id, Total_GLBL__c from LookupParent_GLBL__c'));
	//	System.assertEquals(42, (Decimal) assertParents.get(parentA.id).get('Total_GLBL__c'));
	//	System.assertEquals(42, (Decimal) assertParents.get(parentB.id).get('Total_GLBL__c'));
	//	System.assertEquals(null, (Decimal) assertParents.get(parentC.id).get('Total_GLBL__c'));		
		
	//	// Assert scheduled items and log records
	//	List<LookupRollupSummaryLog_GLBL__c> logs = [select id, ParentId_GLBL__c, ParentObject_GLBL__c, ErrorMessage_GLBL__c from LookupRollupSummaryLog_GLBL__c];
	//	System.assertEquals(parentC.Id, logs[0].ParentId_GLBL__c);
	//	System.assertEquals('LookupParent_GLBL__c', logs[0].ParentObject_GLBL__c);
	//	System.assertEquals(1, logs.size());
	//	System.assertEquals('The answer is not 42! : FIELD_CUSTOM_VALIDATION_EXCEPTION (Total_GLBL__c)', logs[0].ErrorMessage_GLBL__c);		
	//}

	private testmethod static void testCalculateJobNotActive()
	{		
		// Test supported?
		if(!GLBL_TestContext.isSupported())
			return;
		
		// Insert parents
		Schema.SObjectType parentType = Schema.getGlobalDescribe().get('LookupParent_GLBL__c');
		SObject parentA = parentType.newSObject();
		parentA.put('Name', 'ParentA');
		SObject parentB = parentType.newSObject();
		parentB.put('Name', 'ParentB');
		SObject parentC = parentType.newSObject();
		parentC.put('Name', 'ParentC');
		List<SObject> parents = new List<SObject> { parentA, parentB, parentC };
		insert parents;
		
		// Insert children
		Schema.SObjectType childType = Schema.getGlobalDescribe().get('LookupChild_GLBL__c');
		List<SObject> children = new List<SObject>();
		for(SObject parent : parents)		
		{
			String name = (String) parent.get('Name');
			SObject child1 = childType.newSObject();
			child1.put('LookupParent_GLBL__c', parent.Id);
			child1.put('Amount_GLBL__c', 20);
			children.add(child1);				
			SObject child2 = childType.newSObject();
			child2.put('LookupParent_GLBL__c', parent.Id);
			child2.put('Amount_GLBL__c', 20);
			children.add(child2);				
			if(name.equals('ParentA') || name.equals('ParentB'))
			{
				SObject child3 = childType.newSObject();
				child3.put('LookupParent_GLBL__c', parent.Id);
				child3.put('Amount_GLBL__c', 2);
				children.add(child3);				
			}
		}
		insert children;

		// Create rollup AFTER the data exists		
		LookupRollupSummary_GLBL__c rollupSummary = new LookupRollupSummary_GLBL__c();
		rollupSummary.Name = 'Test Rollup';
		rollupSummary.ParentObject_GLBL__c = 'LookupParent_GLBL__c';
		rollupSummary.ChildObject_GLBL__c = 'LookupChild_GLBL__c';
		rollupSummary.RelationShipField_GLBL__c = 'LookupParent_GLBL__c';
		rollupSummary.FieldToAggregate_GLBL__c = 'Amount_GLBL__c';
		rollupSummary.AggregateOperation_GLBL__c = GLBL_RollupSummaries.AggregateOperation.Sum.name();
		rollupSummary.AggregateResultField_GLBL__c = 'Total_GLBL__c';
		rollupSummary.Active_GLBL__c = false;
		rollupSummary.CalculationMode_GLBL__c = 'Scheduled';	
		insert rollupSummary;
		
		// Run rollup calculate job
		Test.startTest();		
		try { 
			// Assert not possible to start another
			GLBL_RollupService.runJobToCalculate(rollupSummary.Id);
			System.assert(false, 'Expected an exception');
		} catch (Exception e) {
			System.assert(e.getMessage().equals('The rollup must be Active before you can run a Calculate job.'));
		}			 
		Test.stopTest();
	}
	
	private testmethod static void testDeveloperAPI()
	{		
		// Test supported?
		if(!GLBL_TestContext.isSupported())
			return;
		
		// Create rollup		
		LookupRollupSummary_GLBL__c rollupSummary = new LookupRollupSummary_GLBL__c();
		rollupSummary.Name = 'Test Rollup';
		rollupSummary.ParentObject_GLBL__c = 'LookupParent_GLBL__c';
		rollupSummary.ChildObject_GLBL__c = 'LookupChild_GLBL__c';
		rollupSummary.RelationShipField_GLBL__c = 'LookupParent_GLBL__c';
		rollupSummary.FieldToAggregate_GLBL__c = 'Amount_GLBL__c';
		rollupSummary.AggregateOperation_GLBL__c = GLBL_RollupSummaries.AggregateOperation.Sum.name();
		rollupSummary.AggregateResultField_GLBL__c = 'Total_GLBL__c';
		rollupSummary.Active_GLBL__c = true;
		rollupSummary.CalculationMode_GLBL__c = GLBL_RollupSummaries.CalculationMode.Developer.name();	
		insert rollupSummary;
		
		// Insert parents
		Schema.SObjectType parentType = Schema.getGlobalDescribe().get('LookupParent_GLBL__c');
		SObject parentA = parentType.newSObject();
		parentA.put('Name', 'ParentA');
		SObject parentB = parentType.newSObject();
		parentB.put('Name', 'ParentB');
		SObject parentC = parentType.newSObject();
		parentC.put('Name', 'ParentC');
		List<SObject> parents = new List<SObject> { parentA, parentB, parentC };
		insert parents;
		
		// Insert children
		Schema.SObjectType childType = Schema.getGlobalDescribe().get('LookupChild_GLBL__c');
		List<SObject> children = new List<SObject>();
		for(SObject parent : parents)		
		{
			String name = (String) parent.get('Name');
			SObject child1 = childType.newSObject();
			child1.put('LookupParent_GLBL__c', parent.Id);
			child1.put('Amount_GLBL__c', 20);
			children.add(child1);				
			SObject child2 = childType.newSObject();
			child2.put('LookupParent_GLBL__c', parent.Id);
			child2.put('Amount_GLBL__c', 20);
			children.add(child2);				
			if(name.equals('ParentA') || name.equals('ParentB'))
			{
				SObject child3 = childType.newSObject();
				child3.put('LookupParent_GLBL__c', parent.Id);
				child3.put('Amount_GLBL__c', 2);
				children.add(child3);				
			}
		}
		insert children;
		
		// Assert nothing has changed on db 
		Map<Id, SObject> assertParents = new Map<Id, SObject>(Database.query('select id, Total_GLBL__c from LookupParent_GLBL__c'));
		System.assertEquals(null, (Decimal) assertParents.get(parentA.id).get('Total_GLBL__c'));
		System.assertEquals(null, (Decimal) assertParents.get(parentB.id).get('Total_GLBL__c'));
		System.assertEquals(null, (Decimal) assertParents.get(parentC.id).get('Total_GLBL__c'));		
				
		// Call developer API
		List<SObject> masterRecords = GLBL_RollupService.rollup(children);

		// Assert nothing has changed on db 
		assertParents = new Map<Id, SObject>(Database.query('select id, Total_GLBL__c from LookupParent_GLBL__c'));
		System.assertEquals(null, (Decimal) assertParents.get(parentA.id).get('Total_GLBL__c'));
		System.assertEquals(null, (Decimal) assertParents.get(parentB.id).get('Total_GLBL__c'));
		System.assertEquals(null, (Decimal) assertParents.get(parentC.id).get('Total_GLBL__c'));		
		
		// Assert rollups produced
		assertParents = new Map<Id, SObject>(masterRecords);
		System.assertEquals(3, masterRecords.size()); 
		System.assertEquals(42, (Decimal) assertParents.get(parentA.id).get('Total_GLBL__c'));
		System.assertEquals(42, (Decimal) assertParents.get(parentB.id).get('Total_GLBL__c'));
		System.assertEquals(40, (Decimal) assertParents.get(parentC.id).get('Total_GLBL__c'));		
	}	
	
	
	/**
	 * https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/23
	 */
	private testmethod static void testDateRollupDeleteChild()
	{
		// Test supported?
		if(!GLBL_TestContext.isSupported())
			return;
		
		// Configure rollup
		LookupRollupSummary_GLBL__c rollupSummary = new LookupRollupSummary_GLBL__c();
		rollupSummary.Name = 'Total Opportunities greater than 200 into Annual Revenue on Account';
		rollupSummary.ParentObject_GLBL__c = 'Account';
		rollupSummary.ChildObject_GLBL__c = 'Opportunity';
		rollupSummary.RelationShipField_GLBL__c = 'AccountId';
		rollupSummary.RelationShipCriteria_GLBL__c = null;
		rollupSummary.FieldToAggregate_GLBL__c = 'CloseDate';
		rollupSummary.AggregateOperation_GLBL__c = 'Max';
		rollupSummary.AggregateResultField_GLBL__c = 'CODS_End_Date_GLBL__c';
		rollupSummary.Active_GLBL__c = true;
		rollupSummary.CalculationMode_GLBL__c = 'Realtime';
		insert new List<LookupRollupSummary_GLBL__c> { rollupSummary };
		
		// Test data
		Account account = new Account();
		account.Name = 'Test Account';
		account.AnnualRevenue = 0;
		insert account;
		Opportunity opp = new Opportunity(); 
		opp.Name = 'Test Opportunity';
		opp.StageName = 'Open';
		opp.CloseDate = System.today();
		opp.AccountId = account.Id;
		opp.Amount = 100;
		insert opp;
		
		// Assert rollup
		Id accountId = account.Id;
		System.assertEquals(System.today(), Database.query('select CODS_End_Date_GLBL__c from Account where Id = :accountId')[0].get(ACCOUNT_SLA_EXPIRATION_DATE));
		
		// Delete Opportunity
		delete opp;
		
		// Assert rollup
		System.assertEquals(null, Database.query('select CODS_End_Date_GLBL__c from Account where Id = :accountId')[0].get(ACCOUNT_SLA_EXPIRATION_DATE));								 	
	}
	
	/**
	 * https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/23
	 */
	private testmethod static void testDateRollupInsertConditionalChild()
	{
		// Test supported?
		if(!GLBL_TestContext.isSupported())
			return;
		
		// Configure rollup
		LookupRollupSummary_GLBL__c rollupSummary = new LookupRollupSummary_GLBL__c();
		rollupSummary.Name = 'Total Opportunities greater than 200 into Annual Revenue on Account';
		rollupSummary.ParentObject_GLBL__c = 'Account';
		rollupSummary.ChildObject_GLBL__c = 'Opportunity';
		rollupSummary.RelationShipField_GLBL__c = 'AccountId';
		rollupSummary.RelationShipCriteria_GLBL__c = 'CloseDate < TODAY';
		rollupSummary.FieldToAggregate_GLBL__c = 'CloseDate';
		rollupSummary.AggregateOperation_GLBL__c = 'Max';
		rollupSummary.AggregateResultField_GLBL__c = 'CODS_End_Date_GLBL__c';
		rollupSummary.Active_GLBL__c = true;
		rollupSummary.CalculationMode_GLBL__c = 'Realtime';
		insert new List<LookupRollupSummary_GLBL__c> { rollupSummary };
		
		// Test data
		Account account = new Account();
		account.Name = 'Test Account';
		account.AnnualRevenue = 0;
		insert account;
		Opportunity opp = new Opportunity(); 
		opp.Name = 'Test Opportunity';
		opp.StageName = 'Open';
		opp.CloseDate = System.today();
		opp.AccountId = account.Id;
		opp.Amount = 100;
		insert opp;
		
		// Assert rollup
		Id accountId = account.Id;
		System.assertEquals(null, Database.query('select CODS_End_Date_GLBL__c from Account where Id = :accountId')[0].get(ACCOUNT_SLA_EXPIRATION_DATE));
		
		// Delete Opportunity
		delete opp;
		
		// Assert rollup
		System.assertEquals(null, Database.query('select CODS_End_Date_GLBL__c from Account where Id = :accountId')[0].get(ACCOUNT_SLA_EXPIRATION_DATE));								 	
	}
	
	//private testmethod static void testRollupWithInAccessibleParent()
	//{
	//	// Test supported?
	//	if(!GLBL_TestContext.isSupported())
	//		return;
		
	//	// Configure rollup
	//	LookupRollupSummary_GLBL__c rollupSummary = new LookupRollupSummary_GLBL__c();
	//	rollupSummary.Name = 'Test Rollup';
	//	rollupSummary.ParentObject_GLBL__c = 'LookupParent_GLBL__c';
	//	rollupSummary.ChildObject_GLBL__c = 'LookupChild_GLBL__c';
	//	rollupSummary.RelationShipField_GLBL__c = 'LookupParent_GLBL__c';
	//	rollupSummary.FieldToAggregate_GLBL__c = 'Amount_GLBL__c';
	//	rollupSummary.AggregateOperation_GLBL__c = GLBL_RollupSummaries.AggregateOperation.Sum.name();
	//	rollupSummary.AggregateResultField_GLBL__c = 'Total_GLBL__c';
	//	rollupSummary.Active_GLBL__c = true;
	//	rollupSummary.CalculationMode_GLBL__c = 'Realtime';	
	//	insert rollupSummary;
				
	//	// Insert parents
	//	Schema.SObjectType parentType = Schema.getGlobalDescribe().get('LookupParent_GLBL__c');
	//	SObject parentA = parentType.newSObject();
	//	parentA.put('Name', 'ParentA');
	//	insert parentA;
		
	//	// Insert children
	//	Schema.SObjectType childType = Schema.getGlobalDescribe().get('LookupChild_GLBL__c');
	//	SObject child1 = childType.newSObject();
	//	child1.put('LookupParent_GLBL__c', parentA.Id);
	//	insert child1;
		
	//	// Assert rollup		
	//	Map<Id, SObject> assertParents = new Map<Id, SObject>(Database.query('select id, Total_GLBL__c from LookupParent_GLBL__c'));
	//	System.assertEquals(null, (Decimal) assertParents.get(parentA.id).get('Total_GLBL__c'));
					
	//	// Create test user
	//	User testUser = null;
	//	System.runAs ( new User(Id = UserInfo.getUserId()) ) {
 //			testUser = createUser();
	//	}
		
	//	//// Test data insert children as new user (who cannot see the parent)
	//	//System.runAs(testUser)
	//	//{
	//	//	// Ensure this user can read it (the Sharing setting for LookupParent_GLBL__c is Public Read Only)
	//	//	assertParents = new Map<Id, SObject>(Database.query('select id, Total_GLBL__c from LookupParent_GLBL__c'));
	//	//	System.assertEquals(null, (Decimal) assertParents.get(parentA.id).get('Total_GLBL__c'));
			
	//	//	// Attempt to indirectly via rollup trigger to update parent record
	//	//	child1.put('Amount_GLBL__c', 42);
	//	//	update child1;
	//	//}
		
	//	//// Assert rollup
	//	//assertParents = new Map<Id, SObject>(Database.query('select id, Total_GLBL__c from LookupParent_GLBL__c'));
	//	//System.assertEquals(42, (Decimal) assertParents.get(parentA.id).get('Total_GLBL__c'));
	//}
	
	/**
	 * Create test user
	 **/
	private static User createUser()
	{
		// Can only proceed with test if we have a suitable profile
		List<Profile> testProfiles = [Select Id From Profile where Name='Standard User' limit 1];
		if(testProfiles.size()!=1)
			return null; 		

		// Can only proceed with test if we can successfully insert a test user 
		String testUsername = System.now().format('yyyyMMddhhmmss') + '@testorg.com';
		User testUser = new User(Alias = 'test1', Email='testuser1@testorg.com', EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', LocaleSidKey='en_US', ProfileId = testProfiles[0].Id, TimeZoneSidKey='America/Los_Angeles', UserName=testUsername);
		try {
			insert testUser;
			
			// Assign permission sets
			Set<String> psNames = new Set<String> { 'LookupRollupSummariesFull', 'LookupRollupSummariesTest' };
			List<PermissionSet> ps = [select Id from PermissionSet where Name in :psNames];
			insert new List<PermissionSetAssignment> {
				new PermissionSetAssignment(AssigneeId = testUser.Id, PermissionSetId = ps[0].Id),
				new PermissionSetAssignment(AssigneeId = testUser.Id, PermissionSetId = ps[1].Id) };
		} catch (Exception e) {
			return null;
		}		
		return testUser;
	}	
}