src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status_MERC__c</fullName>
        <description>Status of Account. Created 10/4/2013 by KLorenti.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Validated by LMM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Meeting_Process_Logic_MERC__c.object
<CustomObject>
    <description>Stores business logic for processing Mercury Meeting Process and Task automation for Delegate Management and other activities : MERC : Created on 19/06/2015 by Oliver Dunford, Mavens Consulting</description>
    <fields>
        <fullName>Create_New_Process_MERC__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to trigger the creation of a new process : MERC : Created on 22/06/2015 by Oliver Dunford, Mavens Consulting</description>
        <label>Create New Process</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Create_New_Task_MERC__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the creation of a Task is needed : MERC : Created on 22/06/2015 by Oliver Dunford, Mavens Consulting</description>
        <label>Create New Task</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description_MERC__c</fullName>
        <description>The overall description for what the logic does : MERC : Created on 22/06/2015 by Kyle Thornton, Mavens Consulting</description>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Initiate_Delegate_Management_MERC__c</fullName>
        <description>Indicates what state the Initiate Delegate Management field should be on the parent meeting in order for this logic to run: MERC : Created on 19/06/2015 by Kyle Thornton, Mavens Consulting</description>
        <label>Initiate Delegate Management</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Meeting_Participant_Status_MERC__c</fullName>
        <description>The Status of the Meeting Participant for which this logic should be run : MERC : Created on 22/06/2015 by Kyle Thornton, Mavens Consulting</description>
        <label>Meeting Participant Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interested in Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invited</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>New_Due_Date_Direction_MERC__c</fullName>
        <description>Indicates whether to add or subtract days from the &quot;New Due Date Relative To&quot; field : MERC : Created on 01/07/2015 by Kyle Thornton, Mavens Consulting</description>
        <label>New Due Date Direction</label>
        <picklist>
            <picklistValues>
                <fullName>After</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Before</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>New_Task_Due_Date_Days_MERC__c</fullName>
        <description>The number of days from today/completed date that the new task should be due : MERC : Created on 22/06/2015 by Oliver Dunford</description>
        <label>New Task Due Date Days</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>New_Task_Due_Date_Relative_to_MERC__c</fullName>
        <description>The api name of the field on the current object which the due date is relative to. e.g. if value is &apos;Meeting_Start_Date_MERC__c&apos; and record type is MERC_Meeting_Process then date is relative to the Meeting start date on the process object : MERC : Created on 01/07/2015 by Kyle Thornton, Mavens Consulting</description>
        <label>New Task Due Date Relative to</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Task_Name_MERC__c</fullName>
        <description>Sets the Task Name of the Task being created : MERC : Created on 22/06/2015 by Oliver Dunford, Mavens Consulting</description>
        <label>New Task Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Task_Status_MERC__c</fullName>
        <description>Sets the Status of any created Task records : MERC : Created on 22/06/2015 by Oliver Dunford, Mavens Consulting</description>
        <label>New Task Status</label>
        <picklist>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed - Continue Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed - Process Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed - Process Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed - Unresponsive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Process_MERC__c</fullName>
        <description>Inidicates which Process the rule belongs to : MERC : Created on 22/06/2015 by Kyle Thornton, Mavens Consulting</description>
        <label>Process</label>
        <picklist>
            <picklistValues>
                <fullName>Pre-Meeting Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel Proposal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Veeva_Meeting_Participant_MERC__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates the rule should be run only when the meeting participatnt came from Veeva: MERC : Created on 22/06/2015 by Kyle Thornton, Mavens Consulting</description>
        <label>Veeva Meeting Participant</label>
        <type>Checkbox</type>
    </fields>
    <label>Meeting Process Logic</label>
    <nameField>
        <displayFormat>MPL-{0000}</displayFormat>
        <label>Meeting Progress Logic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Process Logic</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Meeting_Process_MERC__c.object
<CustomObject>
    <description>Groups to-do items for all meeting management functions : MERC : Created on 17/06/2015 by Kyle Thornton, Mavens Consulting</description>
    <fields>
        <fullName>Meeting_Participant_MERC__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Associates the Meeting Process to a specific meeting participant : MERC : Created on 17/06/2015 by Kyle Thornton, Mavens Consulting</description>
        <label>Meeting Participant</label>
        <referenceTo>Meeting_Participant_MERC__c</referenceTo>
        <relationshipLabel>Meeting Processes</relationshipLabel>
        <relationshipName>Meeting_Processes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process_Type_MERC__c</fullName>
        <description>Indicates the type of process : MERC : Created on 17/06/2015 by Kyle Thornton, Mavens Consulting</description>
        <label>Process Type</label>
        <picklist>
            <picklistValues>
                <fullName>Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel Proposal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Meeting Information</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Meeting Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Meeting_Tasks_MERC__c.object
<CustomObject>
    <description>Captures to-do items for all meeting management functions : MERC : Created on 21/04/2015 by Oliver Dunford, Mavens Consulting</description>
    <fields>
        <fullName>Meeting_MERC__c</fullName>
        <description>Pulls down the meeting id. Used in trigger to pass to the lockedrecordhandler : MERC :  Created on 23/04/2015 by Kyle Thornton, Mavens Consulting</description>
        <formula>Meeting_Process_MERC__r.Meeting_Participant_MERC__r.Meeting_MERC__c</formula>
        <label>Meeting</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meeting_Participant_MERC__c</fullName>
        <description>Pulls the meeting partcipant Id down to the Task : MERC : Created on 17/06/2015 by Kyle Thornton, Mavens Consulting</description>
        <formula>Meeting_Process_MERC__r.Meeting_Participant_MERC__c</formula>
        <label>Meeting Participant</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meeting_Process_MERC__c</fullName>
        <description>Relates a meeting task to it&apos;s parent process : MERC : Created on 17/06/2015 by Kyle Thornton, Mavens Consulting</description>
        <label>Meeting Process</label>
        <referenceTo>Meeting_Process_MERC__c</referenceTo>
        <relationshipLabel>Meeting Tasks</relationshipLabel>
        <relationshipName>Meeting_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Process_Type_MERC__c</fullName>
        <description>Indicates the meeting type : MERC : Created on 22/06/2015 by Kyle Thornton, Mavens Consulting</description>
        <formula>TEXT(Meeting_Process_MERC__r.Process_Type_MERC__c)</formula>
        <label>Process Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Status_MERC__c</fullName>
        <description>Stores the Status of each Task, drives automation : MERC : Created on 21/04/2015 by Oliver Dunford, Mavens Consulting</description>
        <inlineHelpText>The Status of the current Meeting Task.  For example, &quot;Completed&quot; would indicate that you have completed a Follow Up task by contacting the HCP.  There may be several Follow Up tasks for each Process.</inlineHelpText>
        <label>Task Status</label>
        <picklist>
            <picklistValues>
                <fullName>Incomplete</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed - Continue Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed - Process Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed - Process Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed - Unresponsive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Meeting Task</label>
    <nameField>
        <label>Meeting Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Travel_Itinerary_MERC__c.object
<CustomObject>
    <fields>
        <fullName>Status_MERC__c</fullName>
        <description>If the HCP cancels travel or does not use it, the record can be Cancelled.  This then removes any ToV from the associated meeting for that HCP.  Oliver Dunford 11th June 2014.</description>
        <inlineHelpText>If the HCP cancels attendance, or the ToV attributed to this record should not be reported within Mercury due to a No Show, the record can be updated to Cancelled.  Confirmed records are reportable.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Proposal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ticketed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/MERC_MeetingProcessLogicHandlerTest.cls
@isTest
private class MERC_MeetingProcessLogicHandlerTest {

	static List<Meeting_MERC__c> meetings;
	static List<Account> accounts;
	static List<Meeting_Participant_MERC__c> participants;
	static List<Travel_Itinerary_MERC__c> proposals;

	static {
		meetings     = Merc_TestFactory.insertMeetings(1);
		accounts     = Merc_TestFactory.insertAccounts(200);
		participants = Merc_TestFactory.insertParticipants(meetings[0].Id, accounts, 'Approved');
	}

	/**** SCENARIO : Process being created should spawn new task ****/
	@isTest
	static void newProcessShouldCreateNewTask() {
		givenAProcessLogicRecordForPreMeetingInformation();

		Test.startTest();
		whenPreMeetingInformationProcessCreatedFor(participants);
		Test.stopTest();

		expectTasksToBeCreatedForProcessesFor(participants);
	}

	private static void givenAProcessLogicRecordForPreMeetingInformation() {
		//create a rule that spawns task when process is created
		Id mpTypeId = Schema.SObjectType.Meeting_Process_Logic_MERC__c.getRecordTypeInfosByName().get('Meeting Process').getRecordTypeId();
		insert new Meeting_Process_Logic_MERC__c(Description_MERC__c = 'New Pre-Meeting Information Process Created',
												 RecordTypeId = mpTypeId,
												 Process_MERC__c = 'Pre-Meeting Information',
												 Create_New_Task_MERC__c = true,
												 New_Task_Name_MERC__c = 'Send Pre-Meeting Information',
												 New_Task_Status_MERC__c = 'Incomplete',
			                                     New_Task_Due_Date_Days_MERC__c = 7,
			                                     New_Due_Date_Direction_MERC__c = 'Before',
			                                     New_Task_Due_Date_Relative_to_MERC__c = 'Meeting_Start_Date_MERC__c');
        //clear the cached rules
		MERC_MeetingProcessLogicHandler.meetingProcessLogicRecordsByType = null;
	}

	private static void whenPreMeetingInformationProcessCreatedFor(List<Meeting_Participant_MERC__c> mps) {
		List<Meeting_Process_MERC__c> processes = new List<Meeting_Process_MERC__c>();

		for (Meeting_Participant_MERC__c participant : mps) {
			processes.add(new Meeting_Process_MERC__c(Name='Send Pre-Meeting Info',
				                                      Process_Type_MERC__c = 'Pre-Meeting Information',
				                                      Meeting_Participant_MERC__c = participant.id));
		}

		insert processes;
	}

	private static void expectTasksToBeCreatedForProcessesFor(List<Meeting_Participant_MERC__c> mps) {
		System.assertEquals(mps.size(), [SELECT Id
	                                       FROM Meeting_Tasks_MERC__c
	                                      WHERE Meeting_Process_MERC__r.Meeting_Participant_MERC__c IN : mps].size());
	                                        //AND Name = 'Send Pre-Meeting Information'
	                                        //AND Task_Status_MERC__c = 'Incomplete'].size());
	}

	/**** SCENARIO: participant updated to invited should spawn the registration process ****/
	@isTest
	static void invitedParticipantsShouldGetRegProcessCreated() {
		givenAProcessLogicRecordForInvitedMercuryParticipant();
		givenTheMeetingHasInitiateDelegateManagement('Yes');

		Test.startTest();
		whenTheParticipantsStatusBecomes('Invited');

		Test.stopTest();

		expectProcessToBeCreatedFor(participants, 'Registration');
	}

	private static void givenAProcessLogicRecordForInvitedMercuryParticipant() {
		//create a rule that initates the reg process when the (Mercury) participants are invited.
		Id mpTypeId = Schema.SObjectType.Meeting_Process_Logic_MERC__c.getRecordTypeInfosByName().get('Meeting Participant').getRecordTypeId();
		insert new Meeting_Process_Logic_MERC__c(Description_MERC__c = 'Mercury Meeting Participant is Invited',
												 RecordTypeId = mpTypeId,
												 Initiate_Delegate_Management_MERC__c = 'Yes',
			                                     Meeting_Participant_Status_MERC__c = 'Invited',
			                                     Veeva_Meeting_Participant_MERC__c = false,
			                                     Process_MERC__c = 'Registration',
			                                     Create_New_Process_MERC__c = true,
			                                     New_Process_MERC__c = 'Registration');
		//clear the cached rules
		MERC_MeetingProcessLogicHandler.meetingProcessLogicRecordsByType = null;
	}

	private static void givenTheMeetingHasInitiateDelegateManagement(String status) {
		meetings[0].Initiate_Delegate_Management_MERC__c = status;
		update meetings[0];
	}

	private static void whenTheParticipantsStatusBecomes(String status) {
		for (Meeting_Participant_MERC__c participant : participants) {
			participant.Status_MERC__c = status;
			//this box would be checked via
			participant.Evaluate_Meeting_Process_Logic_MERC__c = true;
		}
		update participants;
	}

	private static void expectProcessToBeCreatedFor(List<Meeting_Participant_MERC__c> mps, String processType) {
		List<Meeting_Process_MERC__c> processes = [SELECT Process_Type_MERC__c
		                                             FROM Meeting_Process_MERC__c
		                                            WHERE Meeting_Participant_MERC__c IN :mps
		                                              AND Process_Type_MERC__c = :processType];

		System.assertEquals(mps.size(), processes.size(), processType + ' Processes not created correctly');
	}


	/***** SCENARIO : Travel Proposal moving to Ready For Proposal kicks off process *****/
	@isTest
	private static void travelProposalReadyForProposalKicksOffProcess() {
		//once lookup rollup summaries are gone this might be possible to remove.
		MERC_TriggerHandlerStateManager.deactivateAll();
		MERC_TriggerHandlerStateManager.activate(MERC_MeetingProcessLogicHandler.class);

		givenTheMeetingHasInitiateDelegateManagement('Yes');
		givenAProcessLogicRecordForTravelProposalReady();

		givenTravelProposalsAreInDraft(participants);
		Test.startTest();
		whenTravelProposalsAreReadyForProposal();
		Test.stopTest();

		expectProcessToBeCreatedFor(participants, 'Travel Proposal');
	}

	private static void givenAProcessLogicRecordForTravelProposalReady() {
		//create a rule that initates the travel process when the travel propoasl is ready for propsal
		Id mpTypeId = Schema.SObjectType.Meeting_Process_Logic_MERC__c.getRecordTypeInfosByName().get('Travel Proposal').getRecordTypeId();
		insert new Meeting_Process_Logic_MERC__c(Description_MERC__c = 'First Travel Proposal Ready for Proposal',
												 RecordTypeId = mpTypeId,
												 First_Travel_Proposal_MERC__c = 'TRUE',
			                                     Travel_Proposal_Status_MERC__c = 'Ready for Proposal',
			                                     Process_MERC__c = 'Travel Proposal',
			                                     Create_New_Process_MERC__c = true,
			                                     New_Process_MERC__c = 'Travel Proposal');
		//clear the cached rules
		MERC_MeetingProcessLogicHandler.meetingProcessLogicRecordsByType = null;
	}

	private static void givenTravelProposalsAreInDraft(List<Meeting_Participant_MERC__c> mps) {
		Id proposalRtId = Schema.SObjectType.Travel_Itinerary_MERC__c.getRecordTypeInfosByName().get('Travel Proposal').getRecordTypeId();
		proposals = new List<Travel_Itinerary_MERC__c>();
		for (Meeting_Participant_MERC__c mp : mps) {
			proposals.add( new Travel_Itinerary_MERC__c(RecordTypeId = proposalRtId,
				                                        Meeting_Participant_MERC__c = mp.Id,
				                                        Status_MERC__c = 'Draft',
				                                        Account_MERC__c = mp.Account_MERC__c,
				                                        Proposal_Counter_MERC__c = 1));
		}
		insert proposals;
	}

	private static void whenTravelProposalsAreReadyForProposal() {
		for (Travel_Itinerary_MERC__c proposal : proposals) {
			proposal.Status_MERC__c = 'Ready for Proposal';
		}
		update proposals;
	}

}