src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status_MERC__c</fullName>
        <description>Status of Account. Created 10/4/2013 by KLorenti.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Validated by LMM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Daily_Attendance_TOV_MERC__c.object
<CustomObject>
    <description>Junction object between Meeting Days and Meeting Participants, stores a breakdown of Daily ToV which is picked up by the AODS Interface : MERC : Created on 10/10/2013 by John Adams, Mavens Consulting</description>
    <fields>
        <fullName>Meeting_Day_MERC__c</fullName>
        <description>Master Detail relationship from Daily Attendance to Meeting Day. Created 10/10/2013 by KLorenti.</description>
        <label>Meeting Day</label>
        <referenceTo>Meeting_Day_MERC__c</referenceTo>
        <relationshipLabel>Daily Attendance &amp; TOV</relationshipLabel>
        <relationshipName>Daily_Attendance_TOV</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Meeting_Participant_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master Detail relationship from Daily Attendance to Meeting Participant. Created 10/10/2013 by KLorenti.</description>
        <label>Meeting Participant</label>
        <referenceTo>Meeting_Participant_MERC__c</referenceTo>
        <relationshipLabel>Daily Attendance &amp; TOV</relationshipLabel>
        <relationshipName>Daily_Attendance_TOV_MERC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meeting_Vendor_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Meeting Vendor to retrieve Hotel Room Rates
Created by John A Adams 10/10/2013</description>
        <label>Meeting Vendor</label>
        <referenceTo>Meeting_Vendor_MERC__c</referenceTo>
        <relationshipLabel>Daily Attendance &amp; TOV</relationshipLabel>
        <relationshipName>Daily_Attendance_TOV</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status_MERC__c</fullName>
        <description>Used to report across daily meeting attendance for HCP&apos;s. Oliver Dunford 6th Nov  2013.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Daily Attendance &amp; TOV</label>
    <nameField>
        <displayFormat>DA-{000000}</displayFormat>
        <label>Attendance #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Attendance &amp; TOV</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Meeting_Day_MERC__c.object
<CustomObject>
    <description>Object to track days of meetings and ToV cost of each day. Created 10/10/2013 by KLorenti.</description>
    <fields>
        <fullName>Date_MERC__c</fullName>
        <description>Date of the Meeting Day. Created 10/10/2013 by KLorenti.</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Meeting_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship to Meeting. Created 10/10/2013 by KLorenti</description>
        <label>Meeting</label>
        <referenceTo>Meeting_MERC__c</referenceTo>
        <relationshipLabel>Meeting Days</relationshipLabel>
        <relationshipName>Meeting_Days</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Meeting Day</label>
    <nameField>
        <label>Meeting Day</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Meeting_MERC__c.object
<CustomObject>
</CustomObject>

src/objects/Meeting_Participant_MERC__c.object
<CustomObject>
</CustomObject>

src/objects/Meeting_Vendor_MERC__c.object
<CustomObject>
</CustomObject>

src/objects/Travel_Itinerary_MERC__c.object
<CustomObject>
    <fields>
        <fullName>Status_MERC__c</fullName>
        <description>If the HCP cancels travel or does not use it, the record can be Cancelled.  This then removes any ToV from the associated meeting for that HCP.  Oliver Dunford 11th June 2014.</description>
        <inlineHelpText>If the HCP cancels attendance, or the ToV attributed to this record should not be reported within Mercury due to a No Show, the record can be updated to Cancelled.  Confirmed records are reportable.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Proposal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ticketed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/MERC_DailyAttendanceControllerStressTest.cls
/**
 * @author Joseph Ferraro
 * Stress tests (for larger meetings) daily attendance/tov controller functionality found in MERC_DailyAttendanceController
 */

@isTest
private class MERC_DailyAttendanceControllerStressTest {

	static List<Meeting_MERC__c> meetings;
	static List<Account> accounts;
	static List<Meeting_Day_MERC__c> meetingDays;
	static List<Meeting_Participant_MERC__c> participants;
	static List<Meeting_Vendor_MERC__c> hotels;
	static MERC_DailyAttendanceController controller;
	static List<Travel_Itinerary_MERC__c> hotelItineraries;
	static Meeting_MERC__c meeting;
	static User testUser = MERC_TestFactory.getTestingUser();
	static User runningUser = MERC_TestFactory.getRunningUser();

	static {

		MERC_TriggerHandlerStateManager.deactivateAll();

		System.runAs(testUser) {
			accounts = MERC_TestFactory.insertAccounts(100); //insert 100 accounts
			meetings = MERC_TestFactory.insertMeetings(1); //insert 1 meetings
			meeting = meetings.get(0);
			meetingDays = MERC_TestFactory.insertMeetingDays(meeting.Id, 3); //insert 3 days
			hotels = MERC_TestFactory.insertHotelsForMeeting(2, meeting.Id);
			participants = MERC_TestFactory.insertParticipants(meeting.Id, accounts,'Accepted');
			hotelItineraries = MERC_TestFactory.insertHotelItineraries(participants, meetingDays.get(0).Date_MERC__c, meetingDays.get(2).Date_MERC__c);
		}
	}

	static void selectDay(Integer dayNumber) {
		controller.selectedMeetingDayId = controller.meetingDays.get(dayNumber-1).Id;
	}

	static void selectParticipants(Integer numberOfParticipants) {
		for (Integer i = 0; i < numberOfParticipants; i++) {
			controller.participants.get(i).selected = True;
		}
	}

	@isTest
	static void run_stress_test() {

		PageReference p = Page.MERC_DailyAttendance;
		p.getParameters().put('id', meeting.Id);
		Test.setCurrentPage(p);
		MERC_TriggerHandlerStateManager.activateAll();
		Test.startTest();

		//load controller
		ApexPages.StandardSetController setController = new ApexPages.StandardSetController(new List<Daily_Attendance_TOV_MERC__c>());
		controller = new MERC_DailyAttendanceController(setController);
		controller.upsertMissingTovRecords();

		controller = new MERC_DailyAttendanceController(setController); //not sure why we need to do this, if we don't we get 0 participants in our controller

		System.runAs(testUser) {
			selectDay(1);

			System.assertEquals(meeting.Id, controller.meeting.Id,'meeting id doesn\'t match the controller record id');
			System.assertEquals(meetingDays.size(), controller.getMeetingDayOptions().size(),'unexpected meetingDays size.');
			System.assertEquals(participants.size(), controller.participants.size(),'unexpected participants size.');

			selectParticipants(33);
			controller.setSelectedToAttended();
			System.assertEquals(33, [SELECT count() FROM Daily_Attendance_TOV_MERC__c WHERE Status_MERC__c = 'Attended' AND Meeting_Participant_MERC__c in :participants]);

			selectParticipants(4);
			controller.setSelectedToNoShow();
			System.assertEquals(4, [SELECT count() FROM Daily_Attendance_TOV_MERC__c WHERE Status_MERC__c = 'No Show' AND Meeting_Participant_MERC__c in :participants]);

		}

		Test.stopTest();
	}
}