src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Primary_Address_Country_GLBL__c</fullName>
        <description>Primary Address  Country Code copied from primary address
Created by John Adams on 11/13/2013</description>
        <label>Primary Address Country</label>
        <length>2</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Address_GLBL__c.object
<CustomObject>
    <description>Used to capture participant (speaker and attendee) addresses
Created by John A Adams 9/26/2013</description>
    <fields>
        <fullName>Adrs_Cntry_Cd_GLBL__c</fullName>
        <description>Address Country Code
Customer ODS to Mercury Mapping
Created by John A Adams 11/4/2013</description>
        <label>Address Country Code</label>
        <picklist>
            <picklistValues>
                <fullName>AF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>ADR-{000000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MERC_AddressCountryStampTriggerTest.cls
@isTest
private class MERC_AddressCountryStampTriggerTest {
	
	@isTest static void test_should_set_country_on_insert() {
		List<Account> accounts = MERC_TestFactory.insertAccounts(2);

		System.assertEquals(NULL, accounts[0].Primary_Address_Country_GLBL__c);
		System.assertEquals(NULL, accounts[1].Primary_Address_Country_GLBL__c);

		Address_GLBL__c address0 = MERC_TestFactory.insertAddressWithCountry(accounts[0],'US');

		accounts = [SELECT Id, Primary_Address_Country_GLBL__c FROM Account WHERE Id IN :accounts];
		System.assertEquals('US', accounts[0].Primary_Address_Country_GLBL__c);
		System.assertEquals(NULL, accounts[1].Primary_Address_Country_GLBL__c);
	}

	@isTest static void test_should_set_country_on_update() {
		List<Account> accounts = MERC_TestFactory.insertAccounts(2);

		System.assertEquals(NULL, accounts[0].Primary_Address_Country_GLBL__c);
		System.assertEquals(NULL, accounts[1].Primary_Address_Country_GLBL__c);

		Address_GLBL__c address0 = MERC_TestFactory.insertAddressWithCountry(accounts[0],'US');

		accounts = [SELECT Id, Primary_Address_Country_GLBL__c FROM Account WHERE Id IN :accounts];
		System.assertEquals('US', accounts[0].Primary_Address_Country_GLBL__c);
		System.assertEquals(NULL, accounts[1].Primary_Address_Country_GLBL__c);

		address0.Adrs_Cntry_Cd_GLBL__c = 'GB';
		update address0;

		accounts = [SELECT Id, Primary_Address_Country_GLBL__c FROM Account WHERE Id IN :accounts];
		System.assertEquals('GB', accounts[0].Primary_Address_Country_GLBL__c);
		System.assertEquals(NULL, accounts[1].Primary_Address_Country_GLBL__c);
	}
}