src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Mdl_Nm_GLBL__c</fullName>
        <description>Workforce ODS data. Created 10/18/2013 by KLorenti, Mavens Consulting</description>
        <label>Middle Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Address_GLBL__c.object
<CustomObject>
    <description>Used to capture participant (speaker and attendee) addresses
Created by John A Adams 9/26/2013</description>
    <fields>
        <fullName>Adrs_Cntry_Cd_GLBL__c</fullName>
        <description>Address Country Code
Customer ODS to Mercury Mapping
Created by John A Adams 11/4/2013</description>
        <label>Address Country Code</label>
        <picklist>
            <picklistValues>
                <fullName>AF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BW</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>City_GLBL__c</fullName>
        <description>Records city information for address
Created by John A Adams 9/27/2013</description>
        <label>City Name</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_1_Adrs_Txt_GLBL__c</fullName>
        <description>Mastered Address Information from ODS.  Oliver Dunford 26th Nov 2013.</description>
        <label>Address Line 1</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>St_Cd_GLBL__c</fullName>
        <description>Maps to Customer ODS.ST_CD (Region). Created by Oliver Dunford 25th Oct 2013</description>
        <label>Region Code</label>
        <picklist>
            <picklistValues>
                <fullName>State 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>State 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>State 3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Zip_Postal_Code_GLBL__c</fullName>
        <description>Zip or Postal Code information for address
Created by John A Adams 9/27/2013</description>
        <label>Zip / Postal Code</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>ADR-{000000}</displayFormat>
        <label>Address</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PersonSearchResultMockMVN.cls
/*
* PersonSearchControllerMVN
* Created By: Kai Amundsen
* Created Date: April 5, 2013
* Last Modified Date: April 5, 2013
* Description: Mock class used to store search results for person search.
*/

public without sharing class PersonSearchResultMockMVN {
	//Account Fields
	public String acctId {get; set;}
	public String lastName {get; set;}
	public String firstName {get; set;}
	public String middleName {get; set;}
	public String recordType {get; set;}

	//Address Fields
	public String addrId {get; set;}
	public String addressLine1 {get; set;}
	public String city {get; set;}
	public String state {get; set;}
	public String zipCode {get; set;}
	public String country {get; set;}

	private Account theAccount;
	private Address_GLBL__c theAddress;

	public PersonSearchResultMockMVN() {
		this(new Account(),new Address_GLBL__c());
	}

	public PersonSearchResultMockMVN(Account acct) {
		this(acct,new Address_GLBL__c());
	}

	public PersonSearchResultMockMVN(Address_GLBL__c addr) {
		this(new Account(),addr);
	}

	public PersonSearchResultMockMVN(Account acct, Address_GLBL__c addr) {
		theAccount = acct;
		theAddress = addr;

		acctId = acct.Id;
		lastName = acct.LastName;
		firstName = acct.FirstName;
		middleName = acct.Mdl_Nm_GLBL__c;
		recordType = acct.RecordTypeId;

		addrId = addr.Id;
		addressLine1 = addr.Line_1_Adrs_Txt_GLBL__c;
		city = addr.City_GLBL__c;
		state = addr.St_Cd_GLBL__c;
		zipCode = addr.Zip_Postal_Code_GLBL__c;
		country = addr.Adrs_Cntry_Cd_GLBL__c;
	}

	public Account getAccount() {
		theAccount.LastName = lastName;
		theAccount.FirstName = firstName;
		theAccount.Mdl_Nm_GLBL__c = middleName;
		return theAccount;
	}

	public Address_GLBL__c getAddress() {
		theAddress.Line_1_Adrs_Txt_GLBL__c = addressLine1;
		theAddress.City_GLBL__c = city;
		theAddress.St_Cd_GLBL__c = state;
		theAddress.Zip_Postal_Code_GLBL__c = zipCode;
		theAddress.Adrs_Cntry_Cd_GLBL__c = country;
		return theAddress;
	}

	public void setAccount(Account acct) {
		theAccount = acct;

		acctId = acct.Id;
		lastName = acct.LastName;
		firstName = acct.FirstName;
		middleName = acct.Mdl_Nm_GLBL__c;
	}

	public void setAddress(Address_GLBL__c addr) {
		theAddress = addr;

		addrId = addr.Id;
		addressLine1 = addr.Line_1_Adrs_Txt_GLBL__c;
		city = addr.City_GLBL__c;
		state = addr.St_Cd_GLBL__c;
		zipCode = addr.Zip_Postal_Code_GLBL__c;
		country = addr.Adrs_Cntry_Cd_GLBL__c;
	}
}