src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Cntry_Cd_GLBL__c</fullName>
        <description>Party Country Code
Customer ODS to Mercury Mapping
Created by John A Adams 11/4/2013</description>
        <label>Party Country Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_MERC__c</fullName>
        <description>Status of Account. Created 10/4/2013 by KLorenti.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Validated by LMM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Meeting_Day_MERC__c.object
<CustomObject>
    <description>Object to track days of meetings and ToV cost of each day. Created 10/10/2013 by KLorenti.</description>
    <fields>
        <fullName>Meeting_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship to Meeting. Created 10/10/2013 by KLorenti</description>
        <label>Meeting</label>
        <referenceTo>Meeting_MERC__c</referenceTo>
        <relationshipLabel>Meeting Days</relationshipLabel>
        <relationshipName>Meeting_Days</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Meeting Day</label>
    <nameField>
        <label>Meeting Day</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Meeting_MERC__c.object
<CustomObject>
</CustomObject>

src/objects/Meeting_Participant_MERC__c.object
<CustomObject>
</CustomObject>

src/objects/Meeting_Products_MERC__c.object
<CustomObject>
    <description>Junction object to create many-to-many relationship between Meetings and Products. Created 10/4/2013 by KLorenti.</description>
    <fields>
        <fullName>Meeting_MERC__c</fullName>
        <description>Master Detail Relationship between Products and Meeting. Created 10/4/2013 by KLorenti.</description>
        <label>Meeting</label>
        <referenceTo>Meeting_MERC__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Meeting_Products</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_MERC__c</fullName>
        <description>Master-Detail from Meeting to Product. Created 10/4/2013 by KLorenti.</description>
        <label>Product</label>
        <referenceTo>Product_Group_GLBL__c</referenceTo>
        <relationshipLabel>Meetings</relationshipLabel>
        <relationshipName>Meeting_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Meeting Product</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Product/Topic  #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Meeting_Tasks_MERC__c.object
<CustomObject>
    <description>Captures to-do items for all meeting management functions : MERC : Created on 21/04/2015 by Oliver Dunford, Mavens Consulting</description>
    <fields>
        <fullName>Meeting_MERC__c</fullName>
        <description>Pulls down the meeting id. Used in trigger to pass to the lockedrecordhandler : MERC :  Created on 23/04/2015 by Kyle Thornton, Mavens Consulting</description>
        <formula>Meeting_Process_MERC__r.Meeting_Participant_MERC__r.Meeting_MERC__c</formula>
        <label>Meeting</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meeting_Participant_MERC__c</fullName>
        <description>Pulls the meeting partcipant Id down to the Task : MERC : Created on 17/06/2015 by Kyle Thornton, Mavens Consulting</description>
        <formula>Meeting_Process_MERC__r.Meeting_Participant_MERC__c</formula>
        <label>Meeting Participant</label>
        <type>Text</type>
    </fields>
    <label>Meeting Task</label>
    <nameField>
        <label>Meeting Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product_Group_GLBL__c.object
<CustomObject>
    <description>Object to store Product Information, mastered Product Group records from Material ODS : MERC : Created on 09/27/2013 by Katy Lorenti, Mavens Consulting</description>
    <fields>
        <fullName>Cntry_Cd_GLBL__c</fullName>
        <description>Unique code which describes the country which uses the translated names on this record.
Created by John A Adams 11/1/2013</description>
        <label>Country Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Crt_Dt_GLBL__c</fullName>
        <description>This represents the date on which the record was initially created in the Material Master Hub database.
Created by John A Adams 11/1/2013</description>
        <label>ODS Created Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Dialect_Nm_GLBL__c</fullName>
        <description>Language dialect of the translated data.
Created by John A Adams 11/1/2013</description>
        <label>Dialect Name</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grp_Prps_Cd_GLBL__c</fullName>
        <description>Classification of the purpose of a product grouping.   
Created by John A Adams 11/1/2013</description>
        <label>Purpose Code</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lst_Pblsh_Dt_GLBL__c</fullName>
        <description>This represents the date on which information was last published for this record to the Material ODS.  This date will be populated when the record is initially created in the ODS or when it is updated.  This is one of the two fields that would be used for delta detection of changes to the Material ODS.  
Created by John A Adams 11/1/2013</description>
        <label>Last Publish Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Updt_Dt_GLBL__c</fullName>
        <description>This represents the date on which the record was last updated in the Material Master Hub database. 
Created by John A Adams 11/1/2013</description>
        <label>ODS Updated Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Product Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MERC_LockedRecordHandlerTest.cls
@isTest
private class MERC_LockedRecordHandlerTest {
    
    static List<Meeting_MERC__c> meetings;
    static List<Account> accounts;
    static List<Meeting_Day_MERC__c> meetingDays;
    static List<Meeting_Participant_MERC__c> participants;
    static List<Meeting_Tasks_MERC__c> tasks;

    static {
        accounts = MERC_TestFactory.insertAccounts(5); //insert 5 accounts
        meetings = MERC_TestFactory.insertMeetings(2); //insert 2 meetings
        meetingDays = MERC_TestFactory.insertMeetingDays(meetings.get(0).Id, 3); //insert 3 days
     
    }

    @isTest static void test_should_prevent_meeting_related_updates() {
            Test.startTest();
          participants = MERC_TestFactory.insertParticipants(meetings.get(0).Id, accounts, 'Accepted'); //insert 5 participants
        tasks = MERC_TestFactory.insertMeetingTask(participants.get(0).Id);
        
    
        Meeting_MERC__c meeting = meetings.get(0);
        meeting.Lock_Meeting_MERC__c = true;
        update meeting;

        meeting.Name = 'a different name';
        try {
            update meeting;
        } catch(System.DmlException e) {
            system.assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION, Operation Failed:  The record is locked due to the meeting being closed.  Please contact Customer Meeting Services for Assistance'));
        }

        Meeting_Participant_MERC__c participant = participants.get(0);
        participant.Status_MERC__c = 'a different status';
        try {
            update participant;
        } catch(System.DmlException e) {
            system.assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION, Operation Failed:  The record is locked due to the meeting being closed.  Please contact Customer Meeting Services for Assistance'));
        }

        Meeting_Tasks_MERC__c task = tasks.get(0);
        task.Name = 'a different name';
        try {
            update task;
        } catch(System.DmlException e) {
            system.assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION, Operation Failed:  The record is locked due to the meeting being closed.  Please contact Customer Meeting Services for Assistance'));
        }
   Test.stopTest();
    }


    @isTest static void test_should_prevent_meeting_related_updates_Participant() {
            Test.startTest();
          participants = MERC_TestFactory.insertParticipants(meetings.get(0).Id, accounts, 'Accepted'); //insert 5 participants
        tasks = MERC_TestFactory.insertMeetingTask(participants.get(0).Id);
        
    
        Meeting_MERC__c meeting = meetings.get(0);
        meeting.Lock_Meeting_MERC__c = true;
        update meeting;

        Meeting_Participant_MERC__c participant = participants.get(0);
        participant.Status_MERC__c = 'a different status';
        try {
            update participant;
        } catch(System.DmlException e) {
            system.assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION, Operation Failed:  The record is locked due to the meeting being closed.  Please contact Customer Meeting Services for Assistance'));
        }

   Test.stopTest();
    }

@isTest static void test_should_prevent_meeting_related_updates_Task() {
            Test.startTest();
          participants = MERC_TestFactory.insertParticipants(meetings.get(0).Id, accounts, 'Accepted'); //insert 5 participants
        tasks = MERC_TestFactory.insertMeetingTask(participants.get(0).Id);
        
    
        Meeting_MERC__c meeting = meetings.get(0);
        meeting.Lock_Meeting_MERC__c = true;
        update meeting;

        Meeting_Tasks_MERC__c task = tasks.get(0);
        task.Name = 'a different name';
        try {
            update task;
        } catch(System.DmlException e) {
            system.assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION, Operation Failed:  The record is locked due to the meeting being closed.  Please contact Customer Meeting Services for Assistance'));
        }
   Test.stopTest();
    }

    @isTest static void test_should_successfully_insert_meeting_products() {
      
      
                    Test.startTest();
          participants = MERC_TestFactory.insertParticipants(meetings.get(0).Id, accounts, 'Accepted'); //insert 5 participants
        tasks = MERC_TestFactory.insertMeetingTask(participants.get(0).Id);
        
    
      
        Meeting_MERC__c meeting = MERC_TestFactory.insertMeetings(1)[0];
        
        Product_Group_GLBL__c product = new Product_Group_GLBL__c();
        product.Cntry_Cd_GLBL__c = 'ZZ';
        product.Crt_Dt_GLBL__c = Date.today();
        product.Dialect_Nm_GLBL__c = 'Enlgish';
        product.Grp_Prps_Cd_GLBL__c = 'MKTP';
        product.Lst_Pblsh_Dt_GLBL__c = Date.today();
        product.Updt_Dt_GLBL__c = Date.today();
        insert product;


        Meeting_Products_MERC__c products = new Meeting_Products_MERC__c();
        products.Meeting_MERC__c = meeting.Id;
        products.Product_MERC__c = product.Id;
        insert products;
        Test.stopTest();

        //check to makes sure record inserted.
        System.assertEquals(1, [SELECT Id FROM Meeting_Products_MERC__c WHERE Id = :products.Id].size());
    }
}