src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Efctv_End_Dt_GLBL__c</fullName>
        <description>End Date
Customer ODS to Mercury Mapping
Created by John A Adams 11/4/2013</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Party_Rcrd_Typ_Cd_GLBL__c</fullName>
        <description>Party Record Type Code
Customer ODS to Mercury Mapping
Created by John A Adams 11/4/2013</description>
        <label>Party Record Type Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prim_Affil_Addr_City_GLBL__c</fullName>
        <description>Primary Affiliation Address City.  Created by John Adams on 12/9/2013</description>
        <label>Primary Affiliation Address City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prim_Affil_Addr_Country_GLBL__c</fullName>
        <description>Primary Affiliation Address Country</description>
        <label>Primary Affiliation Address Country</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prim_Affil_Addr_Line1_GLBL__c</fullName>
        <description>Primary Affiliation Address Line 1
Created by John Adams on 12/9/2013</description>
        <label>Primary Affiliation Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prim_Affil_Addr_Line2_GLBL__c</fullName>
        <description>Primary Affiliation Address Line 2 
Created by John Adams on 12/9/2013</description>
        <label>Primary Affiliation Address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prim_Affil_HCO_GLBL__c</fullName>
        <description>Primary Affiliation HCO Name. Created by John Adams on 12/9/2013</description>
        <label>Primary Affiliation HCO Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prim_Affil_Pstl_Cd_Extnsn_GLBL__c</fullName>
        <description>Primary Affiliate Postal Code Extension
Created by John A Adams 12/12/2013</description>
        <label>Primary Affiliate Postal Code Extension</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Addr_City_GLBL__c</fullName>
        <description>Primary Address City copied from primary address
Created by John Adams on 11/13/2013</description>
        <label>Primary Address City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Addr_Line1_GLBL__c</fullName>
        <description>To be copied form from Address_GLBL.Name of &quot;primary&quot; address
Created by John Adams on 11/13/2013</description>
        <label>Primary Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Addr_Line2_GLBL__c</fullName>
        <description>To be copied from Line_2_Adrs_Txt_GLBL__c of &quot;primary&quot; address
Created by John Adams on 11/13/2013</description>
        <label>Primary Address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Address_Country_GLBL__c</fullName>
        <description>Primary Address  Country Code copied from primary address
Created by John Adams on 11/13/2013</description>
        <label>Primary Address Country</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_HCO_GLBL__c</fullName>
        <description>Primary HCO/Affiliation Name 
Created by John Adams on 11/13/2013</description>
        <label>Primary HCO</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Pstl_Cd_Extnsn_GLBL__c</fullName>
        <description>Postal Code or Zip Extension
Created by John A Adams 12/11/2013</description>
        <label>Primary Postal Code Extension</label>
        <length>32</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Affiliation_GLBL__c.object
<CustomObject>
    <description>Object to track affiliations between accounts for searching purposes. Created 10/17/2013 by KLorenti, Mavens Consulting</description>
    <fields>
        <fullName>Account_Cust_Id_GLBL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Affiliate Account
Customer ODS to Mercury Mapping
Created by John A Adams 11/5/2013</description>
        <label>Affiliate Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Affiliations (Affiliate Account)</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_GLBL__c</fullName>
        <description>Used to help indicate direction of influence. Created 10/17/2013 by KLorenti, Mavens Consulting</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Affiliations</relationshipLabel>
        <relationshipName>Affiliations_To</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Afltn_Party_Rcrd_Typ_Cd_GLBL__c</fullName>
        <description>Affiliate Party Record Type Code
Customer ODS to Mercury Mapping
Created by John A Adams 11/5/2013</description>
        <label>Affiliate Party Record Type Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Efctv_End_Dt_GLBL__c</fullName>
        <description>End Date
Customer ODS to Mercury Mapping
Created by John A Adams 11/5/2013</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Party_Cntry_Cd_GLBL__c</fullName>
        <description>Party Country Code
Customer ODS to Mercury Mapping
Created by John A Adams 11/5/2013</description>
        <label>Party Country Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Party_Rcrd_Typ_Cd_GLBL__c</fullName>
        <description>Party Record Type Code
Customer ODS to Mercury Mapping
Created by John A Adams 11/5/2013</description>
        <label>Party Record Type Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority_Rank_Nbr_GLBL__c</fullName>
        <description>Priority Rank Number
Customer ODS to Mercury Mapping</description>
        <label>Priority Rank Number</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rltnshp_Typ_Cd_GLBL__c</fullName>
        <description>Maps to Customer.ODS.Relationship Type field. Created by Oliver Dunford 25th Oct 2013
Relationship Type Code
Customer ODS to Mercury Mapping</description>
        <label>Relationship Type Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Affiliation #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MERC_PrimaryAffiliation.cls
/**
 * @author Jyoti Gaur
 *
 * For populating affiliated HCO info onto corresponding HCP account
 */
 
public with sharing class MERC_PrimaryAffiliation implements GLBL_TriggerHandler.HandlerInterface {
    public boolean isActive() {
        return MERC_TriggerHandlerStateManager.isActive(MERC_PrimaryAffiliation.class);
    }
    public void handle() {
        if (Trigger.isInsert || Trigger.isUpdate || Trigger.isUndelete) {
            execute(Trigger.new);
        } /*else if (Trigger.isDelete) {
            execute(Trigger.old);
        }*/
    }
    public void execute(List<SObject> sobjects){
    List<Id> accids= new List<Id>();
    Map<id,id> map_of_affiliated_childs_cust_id = new Map<id,id>();
    Map<id,id> map_of_affiliated_parent_account_glbl_c = new Map<id,id>();
    Map<Id,Account> Map_of_Account = new Map<Id,Account>();
    Map<Id,Affiliation_GLBL__c> Map_of_Affiliation = new Map<Id,Affiliation_GLBL__c>();
    List<Account> acclist_parent=new List<Account>();
    List<Account> acclist_child =new List<Account>();
    List<Account> acclist =new List<Account>();
    List<Account> Account_update= new List<Account>();
    SET<Account> Accounts_for_update = new SET<Account>();
    System.debug('@@Size'+ sobjects.size());

    // Primary affiliation condition
    for(Affiliation_GLBL__c aff1:(List<Affiliation_GLBL__c>)sobjects){
    
      if(aff1.Efctv_End_Dt_GLBL__c != null && aff1.Priority_Rank_Nbr_GLBL__c== 1){
          Date sysdate = (Date)System.today();
          Date endDate = date.newinstance(aff1.Efctv_End_Dt_GLBL__c.year(), aff1.Efctv_End_Dt_GLBL__c.month(), aff1.Efctv_End_Dt_GLBL__c.day());
        if(aff1.Account_Cust_Id_GLBL__c != null && sysdate < endDate){
            map_of_affiliated_childs_cust_id.put(aff1.id,aff1.Account_Cust_Id_GLBL__c);
            map_of_affiliated_parent_account_glbl_c.put(aff1.id,aff1.Account_GLBL__c);  
            Map_of_Affiliation.put(aff1.id,aff1);     
        }
        }

    }
        
    //For storing all accounts associated to inserted/updated Affiliation
    try{
        acclist_parent = [select id,name,Primary_HCO_GLBL__c,Prim_Affil_Pstl_Cd_Extnsn_GLBL__c,Party_Rcrd_Typ_Cd_GLBL__c,Prim_Affil_HCO_GLBL__c,Prim_Affil_Addr_Country_GLBL__c,Prim_Affil_Addr_City_GLBL__c,Prim_Affil_Addr_Line1_GLBL__c,Prim_Affil_Addr_Line2_GLBL__c,Primary_Address_Country_GLBL__c,Primary_Addr_City_GLBL__c,Primary_Pstl_Cd_Extnsn_GLBL__c,Primary_Addr_Line1_GLBL__c,Primary_Addr_Line2_GLBL__c from account where id in:map_of_affiliated_parent_account_glbl_c.values()];
        acclist_child = [select id,Primary_HCO_GLBL__c,Prim_Affil_Pstl_Cd_Extnsn_GLBL__c,Party_Rcrd_Typ_Cd_GLBL__c,Prim_Affil_HCO_GLBL__c,Prim_Affil_Addr_Country_GLBL__c,Prim_Affil_Addr_City_GLBL__c,Prim_Affil_Addr_Line1_GLBL__c,Prim_Affil_Addr_Line2_GLBL__c,Primary_Address_Country_GLBL__c,Primary_Addr_City_GLBL__c,Primary_Pstl_Cd_Extnsn_GLBL__c,Primary_Addr_Line1_GLBL__c,Primary_Addr_Line2_GLBL__c from account where id in:map_of_affiliated_childs_cust_id.values()];
        acclist.addall(acclist_child);
        acclist.addall(acclist_parent);
   
    For(account acc:acclist){
            Map_of_Account.put(acc.id,acc);
        }
    // assigning parent affiliated account values to child affiliated account   
    for(Id affiliation_ID:map_of_affiliated_childs_cust_id.keyset()){
            Affiliation_GLBL__c aff_obj = Map_of_Affiliation.get(affiliation_ID);
            if((aff_obj.Rltnshp_Typ_Cd_GLBL__c =='PCAF'  && aff_obj.Afltn_Party_Rcrd_Typ_Cd_GLBL__c == 'HCP' && aff_obj.Party_Rcrd_Typ_Cd_GLBL__c == 'HCO' && aff_obj.Party_Cntry_Cd_GLBL__c != 'US') || (aff_obj.Party_Rcrd_Typ_Cd_GLBL__c == 'HCO' && aff_obj.Party_Cntry_Cd_GLBL__c == 'US' && aff_obj.Afltn_Party_Rcrd_Typ_Cd_GLBL__c == 'HCP')){
            Account Child_Account = Map_of_Account.get(map_of_affiliated_childs_cust_id.get(affiliation_ID));
            Account Parent_Account = Map_of_Account.get(map_of_affiliated_parent_account_glbl_c.get(affiliation_ID));
            Child_Account.Primary_HCO_GLBL__c=Parent_Account.id;
            Child_Account.Prim_Affil_HCO_GLBL__c=Parent_Account.Name;
            Child_Account.Prim_Affil_Addr_Country_GLBL__c=Parent_Account.Primary_Address_Country_GLBL__c;
            Child_Account.Prim_Affil_Addr_City_GLBL__c= Parent_Account.Primary_Addr_City_GLBL__c;
            Child_Account.Prim_Affil_Pstl_Cd_Extnsn_GLBL__c= Parent_Account.Primary_Pstl_Cd_Extnsn_GLBL__c;
            Child_Account.Prim_Affil_Addr_Line1_GLBL__c= Parent_Account.Primary_Addr_Line1_GLBL__c;
            Child_Account.Prim_Affil_Addr_Line2_GLBL__c= Parent_Account.Primary_Addr_Line2_GLBL__c;
            system.Debug( Child_Account);
            Accounts_for_update.add(Child_Account);
            }
        
    }
     system.debug('Accounts for update-----'+Accounts_for_update);
     
    Account_update.addAll(Accounts_for_update);
    }catch(exception e){
        if (Apexpages.currentPage() != null) {
        ApexPages.addMessages(e);
        }
    }
    // update child accounts
	if(Account_update != null && Account_update.size()>0){
    update Account_update; 
	}
    }
}