src/objects/ACED_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>Choose from the list of programs in the lookup table the one this activity belongs to</inlineHelpText>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>$User.ACED_HUB__c</field>
                <operation>equals</operation>
                <valueField>ACED_Programs__c.HUB__c</valueField>
            </filterItems>
            <filterItems>
                <field>$User.ACED_HUB__c</field>
                <operation>equals</operation>
                <value>ACE HUB</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACED_Programs__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Assests_Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <displayFormat>AS-{00000}</displayFormat>
        <label>Activity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACED_KPO__c.object
<CustomObject>
    <fields>
        <fullName>MOT__c</fullName>
        <inlineHelpText>This is a helptext for MOT</inlineHelpText>
        <label>MOT</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>$User.ACED_HUB__c</field>
                <operation>equals</operation>
                <valueField>ACED_MOT__c.HUB__c</valueField>
            </filterItems>
            <filterItems>
                <field>$User.ACED_HUB__c</field>
                <operation>equals</operation>
                <value>ACE HUB</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACED_MOT__c</referenceTo>
        <relationshipLabel>KPO&apos;s</relationshipLabel>
        <relationshipName>KPO_s</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>KPO</label>
    <nameField>
        <label>KPO Short Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KPO&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACED_KPO_Metric__c.object
<CustomObject>
    <fields>
        <fullName>Asset_Activity__c</fullName>
        <inlineHelpText>This is a helptext for Asset/Activity</inlineHelpText>
        <label>Asset/Activity</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>$User.ACED_HUB__c</field>
                <operation>equals</operation>
                <valueField>ACED_Activity__c.Program__r.HUB__c</valueField>
            </filterItems>
            <filterItems>
                <field>$User.ACED_HUB__c</field>
                <operation>equals</operation>
                <value>ACE HUB</value>
            </filterItems>
            <infoMessage>Only activities belonging to same HUB will be displayed</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACED_Activity__c</referenceTo>
        <relationshipLabel>KPO Metrics</relationshipLabel>
        <relationshipName>KPO_Metrics</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>KPO__c</fullName>
        <inlineHelpText>This is a helptext for KPO</inlineHelpText>
        <label>KPO</label>
        <referenceTo>ACED_KPO__c</referenceTo>
        <relationshipLabel>KPO Metrics</relationshipLabel>
        <relationshipName>KPO_Metrics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>KPO Metric</label>
    <nameField>
        <displayFormat>KM-{00000}</displayFormat>
        <label>KPO Metric ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPO Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACED_Program_MOT__c.object
<CustomObject>
    <fields>
        <fullName>MOT__c</fullName>
        <inlineHelpText>This is a helptext for MOT</inlineHelpText>
        <label>MOT</label>
        <referenceTo>ACED_MOT__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Program_MOTs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>This is a helptext for Program</inlineHelpText>
        <label>Program</label>
        <referenceTo>ACED_Programs__c</referenceTo>
        <relationshipLabel>MOTs</relationshipLabel>
        <relationshipName>Program_MOTs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Program MOT</label>
    <nameField>
        <displayFormat>MOT-{0000}</displayFormat>
        <label>Program MOT ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program MOTs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ACED_KPO_Metric_TriggerHandler.cls
/* Class Name  : Test_ACED_KPO_Metric_TriggerHandler
* Description  : Test Class for ACED_KPO_Metric_TriggerHandler
* Created By   : Mrudula 
* Created Date : 9/22/2014
* Modification Log:  
* --------------------------------------------------------------------------------------------------------------------------------------
* Developer                Date                 Modification ID        Description 
* ---------------------------------------------------------------------------------------------------------------------------------------

*/

public class ACED_KPO_Metric_TriggerHandler{

    public static void createProgramMOTRec(List<ACED_KPO_Metric__c> lNewKPO_Metrics){
        
         set<Id> sProgramIds=new Set<Id>();
         map<string,Id> mExistingProgramMOTKPOMetrics=new map<string,Id>();
         String strExistingProgramMOTs='';
        // map<id,String> mExistingProgramMOTs=new map<id,String>();
         List<ACED_Program_MOT__c> lProgramMOTsTobeInserted=new List<ACED_Program_MOT__c>();
        
         for(ACED_KPO_Metric__c newMetric:[select Asset_Activity__c,Asset_Activity__r.Program__c,KPO__c,KPO__r.MOT__c from ACED_KPO_Metric__c 
                                          where id in:lNewKPO_Metrics]){
              
             sProgramIds.add(newMetric.Asset_Activity__r.Program__c);  
         }
         
         for(ACED_Program_MOT__c existingProgramMOTwithCurrentProgram:[select Program__c,MOT__c from ACED_Program_MOT__c where Program__c in :sProgramIds]){
         
         //creating a map with "Program+Mot" combination as key as this would be unique from the  existing records   
              mExistingProgramMOTKPOMetrics.put(existingProgramMOTwithCurrentProgram.Program__c+'-'+existingProgramMOTwithCurrentProgram.MOT__c,existingProgramMOTwithCurrentProgram.id);
         }
         
         for(ACED_KPO_Metric__c newMetric:[select Asset_Activity__c,Asset_Activity__r.Program__c,KPO__c,KPO__r.MOT__c from ACED_KPO_Metric__c 
                                          where id in:lNewKPO_Metrics]){
             //If the key is not present that means combination not exist then creating the records   
             if(!mExistingProgramMOTKPOMetrics.containskey(newMetric.Asset_Activity__r.Program__c+'-'+newMetric.KPO__r.MOT__c)){                          
                 ACED_Program_MOT__c newPMOT=new ACED_Program_MOT__c(Program__c=newMetric.Asset_Activity__r.Program__c,MOT__c=newMetric.KPO__r.MOT__c);
                 lProgramMOTsTobeInserted.add(newPMOT);
             }
             
         }
         if(!lProgramMOTsTobeInserted.isempty()){
                          
                 Database.SaveResult[] lInsertResults = Database.insert(lProgramMOTsTobeInserted, false); 
                 
                 for(Integer i=0;i<lInsertResults.size();i++){
                     if (!lInsertResults.get(i).isSuccess()){
                        // DML operation failed
                       // Database.Error error = lInsertResults.get(i).getErrors().get(0); 
                        lProgramMOTsTobeInserted.get(i).adderror(label.ACED_ErrorMessage);//failed record from the list
                       // ACED_Utility.createErrorRecord(error.getMessage(),error.getMessage(),userInfo.getName()); 
                        }  }
         }
             
    }
    
}