src/objects/ACED_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Assets__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Asset that this activity is using; the asset should be available in the asset portfolio. Leave it blank if the activity does not make use of an asset</inlineHelpText>
        <label>Asset</label>
        <referenceTo>ACED_Asset__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Assests_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>Choose from the list of programs in the lookup table the one this activity belongs to</inlineHelpText>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>$User.ACED_HUB__c</field>
                <operation>equals</operation>
                <valueField>ACED_Programs__c.HUB__c</valueField>
            </filterItems>
            <filterItems>
                <field>$User.ACED_HUB__c</field>
                <operation>equals</operation>
                <value>ACE HUB</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACED_Programs__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Assests_Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <displayFormat>AS-{00000}</displayFormat>
        <label>Activity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACED_Asset__c.object
<CustomObject>
    <label>Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACED_Asset_Actual__c.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <label>Asset</label>
        <referenceTo>ACED_Asset__c</referenceTo>
        <relationshipLabel>Asset Actuals</relationshipLabel>
        <relationshipName>Asset_Actuals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <picklist>
            <picklistValues>
                <fullName>January</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>February</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>March</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>April</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>May</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>June</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>July</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>August</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>September</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>October</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>November</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>December</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Asset Actual</label>
    <nameField>
        <displayFormat>AA-{0000}</displayFormat>
        <label>Asset Actual Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Actuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACED_Deliveries__c.object
<CustomObject>
    <fields>
        <fullName>Activity__c</fullName>
        <inlineHelpText>Activity this delivery belongs to</inlineHelpText>
        <label>Activity</label>
        <referenceTo>ACED_Activity__c</referenceTo>
        <relationshipLabel>Deliveries</relationshipLabel>
        <relationshipName>Deliveries1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <formula>HYPERLINK( &apos;/&apos;&amp;Activity__r.Program__c ,  Activity__r.Program__r.Name,&apos;_blank&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is a helptext for Program</inlineHelpText>
        <label>Program</label>
        <type>Text</type>
    </fields>
    <label>Delivery</label>
    <nameField>
        <displayFormat>DE-{000000}</displayFormat>
        <label>Deliveries ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACED_Delivery_Actual_Line__c.object
<CustomObject>
    <fields>
        <fullName>Delivery_Actuals__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is a helptext for Delivery Actuals</inlineHelpText>
        <label>Delivery Actuals</label>
        <referenceTo>ACED_Delivery_Actuals__c</referenceTo>
        <relationshipLabel>Delivery Actual Lines</relationshipLabel>
        <relationshipName>Delivery_Actual_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>This is a helptext for Value</inlineHelpText>
        <label>Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Delivery Actual Line</label>
    <nameField>
        <displayFormat>AID-{0000}</displayFormat>
        <label>Attribute ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Actual Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACED_Delivery_Actuals__c.object
<CustomObject>
    <fields>
        <fullName>Delivery__c</fullName>
        <inlineHelpText>This is a helptext for Delivery</inlineHelpText>
        <label>Delivery</label>
        <referenceTo>ACED_Deliveries__c</referenceTo>
        <relationshipLabel>Delivery Actuals</relationshipLabel>
        <relationshipName>Delivery_Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <inlineHelpText>This is a helptext for Month</inlineHelpText>
        <label>Month</label>
        <picklist>
            <picklistValues>
                <fullName>January</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>February</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>March</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>April</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>May</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>June</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>July</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>August</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>September</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>October</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>November</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>December</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>This is a helptext for Value</inlineHelpText>
        <label>Value</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Delivery Actuals</label>
    <nameField>
        <displayFormat>DA-{00000}</displayFormat>
        <label>Delivery  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Actuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACED_Programs__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Test_ACED_Delivery_Actuals_TriggerHndlr.cls
@isTest(SeeAllData=false)
public class Test_ACED_Delivery_Actuals_TriggerHndlr{

    static testMethod void createDeliveryActuals() {    
       User runAsUser = ACED_DataFactory.createUser('ACED_Digital_Dashboard_Owner');            
       System.runAs(runAsUser) {
           Test.startTest(); 
               List<ACED_Delivery_Actuals__c> lineActuals = new List<ACED_Delivery_Actuals__c>();   
               List<ACED_Deliveries__c> ldelActs = ACED_DataFactory.createDeliveries(100);
               Set<Id> delActualIds = new Set<Id>(); 
               for(ACED_Deliveries__c del : ldelActs){
                ACED_Delivery_Actuals__c DelAct = New ACED_Delivery_Actuals__c();
                DelAct.Delivery__c=del.Id;       
                lineActuals.add(DelAct);
               }
               for(ACED_Deliveries__c delActLine : ldelActs){
                    delActualIds.add(delActLine.Id);
               } 
               insert lineActuals;
               List<ACED_Delivery_Actuals__c> insertedLineActuals = [Select Id,Delivery__r.Activity__r.Assets__c, Month__c, Delivery__r.Activity__r.program__r.Year__c from ACED_Delivery_Actuals__c];
               ACED_Delivery_Actuals_TriggerHandler.UpsertAggregatedAssetActuals(insertedLineActuals);
               delete [Select id from ACED_Delivery_Actuals__c where id in : delActualIds];            
               //Assert deletion successful
               system.assert([Select id from ACED_Delivery_Actuals__c where id in : delActualIds].size()==0); 
           Test.stopTest();   
        }  
    }
    
    static testMethod void deleteDeliveryActuals() {    
       User runAsUser = ACED_DataFactory.createUser('ACED_Digital_Dashboard_Owner');            
       System.runAs(runAsUser) {
           Test.startTest(); 
               List<ACED_Delivery_Actual_Line__c> ldelActs = ACED_DataFactory.createDeliveryActualLines(100); 
               ACED_Asset_Actual__c AssetAct = New ACED_Asset_Actual__c();        
               AssetAct.Asset__c= [Select Id from ACED_Asset__c LIMIT 1].Id;
               AssetAct.Month__c='March'; 
               AssetAct.Value__c=10;
               AssetAct.Year__c = string.valueof(system.now().year());
               insert AssetAct;
               
               Set<Id> delActualIds = new Set<Id>(); 
               for(ACED_Delivery_Actual_Line__c delActLine : ldelActs){
                    delActualIds.add(delActLine.Delivery_Actuals__c);
               } 
               ACED_Delivery_Actuals_TriggerHandler.DeleteAssetActualsonAsset([Select  Id,value__c,Delivery__r.Activity__r.Assets__c, Month__c, Delivery__r.Activity__r.program__r.Year__c from ACED_Delivery_Actuals__c]);
               delete [Select id from ACED_Delivery_Actuals__c where id in : delActualIds];            
               //Assert deletion successful
               system.assert([Select id from ACED_Delivery_Actuals__c where id in : delActualIds].size()==0); 
           Test.stopTest();   
        }  
    }
    
}