src/objects/ACED_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Assets__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Asset that this activity is using; the asset should be available in the asset portfolio. Leave it blank if the activity does not make use of an asset</inlineHelpText>
        <label>Asset</label>
        <referenceTo>ACED_Asset__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Assests_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>Choose from the list of programs in the lookup table the one this activity belongs to</inlineHelpText>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>$User.ACED_HUB__c</field>
                <operation>equals</operation>
                <valueField>ACED_Programs__c.HUB__c</valueField>
            </filterItems>
            <filterItems>
                <field>$User.ACED_HUB__c</field>
                <operation>equals</operation>
                <value>ACE HUB</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACED_Programs__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Assests_Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <displayFormat>AS-{00000}</displayFormat>
        <label>Activity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACED_Asset__c.object
<CustomObject>
    <fields>
        <fullName>ProfileId__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This is a helptext for ProfileId</inlineHelpText>
        <label>ProfileId</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACED_Deliveries__c.object
<CustomObject>
    <fields>
        <fullName>Activity__c</fullName>
        <inlineHelpText>Activity this delivery belongs to</inlineHelpText>
        <label>Activity</label>
        <referenceTo>ACED_Activity__c</referenceTo>
        <relationshipLabel>Deliveries</relationshipLabel>
        <relationshipName>Deliveries1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <inlineHelpText>Date when the delivery gets finalized</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PIM_Segment__c</fullName>
        <inlineHelpText>PIM segment targetted by the delivery. If the delivery targets all the Audience group then use All</inlineHelpText>
        <label>PIM Segment</label>
        <picklist>
            <picklistValues>
                <fullName>All</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not segmented</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patient Focus Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patient Idealist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scientific Innovator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Traditionalist</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <formula>HYPERLINK( &apos;/&apos;&amp;Activity__r.Program__c ,  Activity__r.Program__r.Name,&apos;_blank&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is a helptext for Program</inlineHelpText>
        <label>Program</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Provider of the database containing the Audience. It should had been defined previously in the Providers table</inlineHelpText>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Only Providers belonging to your HUB are displayed</errorMessage>
            <filterItems>
                <field>$User.ACED_HUB__c</field>
                <operation>equals</operation>
                <valueField>ACED_Providers__c.HUB__c</valueField>
            </filterItems>
            <filterItems>
                <field>$User.ACED_HUB__c</field>
                <operation>equals</operation>
                <value>ACE HUB</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACED_Providers__c</referenceTo>
        <relationshipLabel>Deliveries</relationshipLabel>
        <relationshipName>Deliveries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>Date when the delivery gets started</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Delivery</label>
    <nameField>
        <displayFormat>DE-{000000}</displayFormat>
        <label>Deliveries ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACED_Integration_Console__c.object
<CustomObject>
    <fields>
        <fullName>RN_Password__c</fullName>
        <label>Password</label>
        <length>50</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>RN_UserName__c</fullName>
        <inlineHelpText>This is a helptext for UserName</inlineHelpText>
        <label>UserName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RightNow_Admin_Email__c</fullName>
        <inlineHelpText>Enter multiple email ids seperated by ; 
Eg : mike@gmail.com;denny@yahoo.com</inlineHelpText>
        <label>RightNow Admin Email</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>WebTrends_Admin_Email__c</fullName>
        <inlineHelpText>Enter multiple email ids seperated by ;
Eg : mike@gmail.com;denny@yahoo.com</inlineHelpText>
        <label>WebTrends Admin Email</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>WebTrends_Service_URL__c</fullName>
        <inlineHelpText>This is a helptext for WebTrends Service URL</inlineHelpText>
        <label>WebTrends Service URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Web_Password__c</fullName>
        <inlineHelpText>This is a helptext for Password</inlineHelpText>
        <label>Password</label>
        <length>20</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Web_UserName__c</fullName>
        <inlineHelpText>This is a helptext for UserName</inlineHelpText>
        <label>UserName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Integration Console</label>
    <nameField>
        <label>Integration Console Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Console</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ACED_Programs__c.object
<CustomObject>
    <fields>
        <fullName>Year__c</fullName>
        <inlineHelpText>The year of the plan this program is going to be launch and tracked</inlineHelpText>
        <label>Year</label>
        <picklist>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACED_Providers__c.object
<CustomObject>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <picklist>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Provider</label>
    <nameField>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Test_ACED_WebTrendsScheduler.cls
/* Class Name  : Test_ACED_WebTrendsScheduler
* Description  : Test Class for ACED_WebTrendsScheduler
* Created By   : Deloitte Consulting
* Created Date :
* Modification Log:  
* --------------------------------------------------------------------------------------------------------------------------------------
* Developer                Date                 Modification ID        Description 
* ---------------------------------------------------------------------------------------------------------------------------------------

*/

@isTest(seealldata=false)
private class Test_ACED_WebTrendsScheduler {
    
    //Test method to test non program assets
    static testMethod void myUnitTest() {
        User runAsUser = ACED_DataFactory.createUser('ACED_Digital_Dashboard_Owner');
        System.runAs(runAsUser) {
            
            //Inserting integration console record
            ACED_Integration_Console__c oIntConsole =  new ACED_Integration_Console__c(Metrics__c='ga:newUsers,ga:users,ga:sessions',Web_UserName__c='tets@tet.com',RightNow_Admin_Email__c='uet@yryr.com',WebTrends_Admin_Email__c='777@77.com',Web_Password__c='8888',WebTrends_Service_URL__c='yryryr@uerur.com');
            oIntConsole.RN_UserName__c = 'tetete';
            oIntConsole.RN_Password__c = '12334';
            insert oIntConsole;
            
            ACED_Asset__c ast = ACED_DataFactory.createAssets(1)[0];
            ast.profileid__c = '12345678';
            Update Ast;
            Test.startTest();
                StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
                mock.setStaticResource('ACED_WebTrendsRepsonse');
                mock.setStatusCode(200); // Or other appropriate HTTP status code
                mock.setHeader('Content-Type', 'application/json'); // Or other appropriate MIME type like application/xml
                Test.setMock(HttpCalloutMock.class, mock);
                ACED_WebTrendsScheduler.InvokeWebTrends();
            Test.stopTest();    
                
                String CRON_EXP = '0 0 0 1 1 ? 2025';  
                String jobId = System.schedule('testScheduledApex', CRON_EXP, new ACED_WebTrendsScheduler() );
                CronTrigger ct = [select id, CronExpression, TimesTriggered, NextFireTime from CronTrigger where id = :jobId];
        
                System.assertEquals(CRON_EXP, ct.CronExpression); 
                System.assertEquals(0, ct.TimesTriggered);
        }
    }

    //Test method to test program assets    
    static testMethod void myUnitTest1() {
        User runAsUser = ACED_DataFactory.createUser('ACED_Digital_Dashboard_Owner');
        System.runAs(runAsUser) {
                        
            //Inserting integration console record
            ACED_Integration_Console__c oIntConsole =  new ACED_Integration_Console__c(Metrics__c='ga:newUsers',Web_UserName__c='tets@tet.com',WebTrends_Admin_Email__c='777@77.com',Web_Password__c='8888',WebTrends_Service_URL__c='yryryr@uerur.com');            
            insert oIntConsole;
            
            ACED_Asset__c ast = ACED_DataFactory.createProgramAssets(1)[0];
            ast.profileid__c = '12345678';
            Update ast;
            
             List<ACED_Activity__c> lActivities=ACED_DataFactory.createActivities(1);
             List<ACED_Activity__c>  lAct = [Select Program__r.Year__c,Assets__c from ACED_Activity__c where id=:lActivities[0].ID];
             lAct[0].Assets__c = ast.ID;
             update lAct;
             List<ACED_Providers__c> lProviders=ACED_DataFactory.createProviders(1); 
             
            //Inserting the delivery and assigning it to activity above. Inserting Delivery independently rather than from utility to insert delivery indication which is being inserted from trigger
            ACED_Deliveries__c Del= New ACED_Deliveries__c();
            Del.Activity__c=lAct[0].ID;
            Del.Provider__c=lProviders[0].ID;
            Del.Start_Date__c=System.today();
            Del.End_Date__c= date.newInstance(system.Today().year(), 12, 31);
            Del.PIM_Segment__c='Traditionalist';
            Insert Del;
            
            
            Test.startTest();
                StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
                mock.setStaticResource('ACED_WebTrendsRepsonse');
                mock.setStatusCode(200); // Or other appropriate HTTP status code
                mock.setHeader('Content-Type', 'application/json'); // Or other appropriate MIME type like application/xml
                Test.setMock(HttpCalloutMock.class, mock);
                ACED_WebTrendsScheduler.InvokeWebTrends();
            Test.stopTest();    
                
                String CRON_EXP = '0 0 0 1 1 ? 2025';  
                String jobId = System.schedule('testScheduledApex', CRON_EXP, new ACED_WebTrendsScheduler() );
                CronTrigger ct = [select id, CronExpression, TimesTriggered, NextFireTime from CronTrigger where id = :jobId];
        
                System.assertEquals(CRON_EXP, ct.CronExpression); 
                System.assertEquals(0, ct.TimesTriggered);
        }
    }
}