src/objects/ACED_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Assets__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Asset that this activity is using; the asset should be available in the asset portfolio. Leave it blank if the activity does not make use of an asset</inlineHelpText>
        <label>Asset</label>
        <referenceTo>ACED_Asset__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Assests_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <displayFormat>AS-{00000}</displayFormat>
        <label>Activity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACED_Asset__c.object
<CustomObject>
    <label>Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACED_Cost__c.object
<CustomObject>
    <fields>
        <fullName>Assets_Activity__c</fullName>
        <inlineHelpText>This is a helptext for Assest/Activity</inlineHelpText>
        <label>Assets/Activity</label>
        <referenceTo>ACED_Activity__c</referenceTo>
        <relationshipLabel>Actual Costs</relationshipLabel>
        <relationshipName>Costs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <inlineHelpText>This is a helptext for Cost</inlineHelpText>
        <label>Cost</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Cost</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Cost Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Costs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Test_ACED_Activities_TriggerHandler.cls
@isTest (SeeAllData = false)
public class Test_ACED_Activities_TriggerHandler {

    static testMethod void insertNewActvity() {
    
    //Declaring the User
    User runAsUser = ACED_DataFactory.createUser('ACED_Digital_Dashboard_Owner');
    
    System.runAs(runAsUser) {        
        Test.startTest();
        List<ACED_Activity__c> lActivitiesWithOutAssets = ACED_DataFactory.createActivitiesWithOutAssets(100); 
        List<ACED_Cost__c> lCost = new List<ACED_Cost__c> ();
        List<ACED_Asset__c> lAssets = ACED_DataFactory.createAssets(1);
        for(ACED_Activity__c oActivity : lActivitiesWithOutAssets){
        	ACED_Cost__c oCost  = new ACED_Cost__c(Assets_Activity__c=oActivity.Id,Cost__c=100);
        	oActivity.Assets__c = lAssets[0].Id;
        	lCost.add(oCost);
        }
        Insert lCost;
        ACED_Asset_TriggerHandler.bRecursiveCheck  =true;
        Update lActivitiesWithOutAssets;
        //assert all activities are not deleted from the program after update operation
        system.assert(lActivitiesWithOutAssets.size()>0);

        Delete lActivitiesWithOutAssets.remove(0);  
       
        Test.stopTest();
        
        
        } 
    }

}