src/objects/ACED_Asset_Indication__c.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <inlineHelpText>This is a helptext for Asset</inlineHelpText>
        <label>Asset</label>
        <referenceTo>ACED_Asset__c</referenceTo>
        <relationshipLabel>Asset Brand Indications</relationshipLabel>
        <relationshipName>Asset_Indications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Asset Brand Indication</label>
    <nameField>
        <displayFormat>AID-{0000}</displayFormat>
        <label>Asset Indication ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Brand Indications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Test_ACED_Asset_Actuals_TriggerHandler.cls
@isTest(SeeAllData=false)
public class Test_ACED_Asset_Actuals_TriggerHandler{

    static testMethod void insertNewAssetActuals() {
	    System.runAs( ACED_DataFactory.createUser('ACED_Digital_Dashboard_Owner')) {
		    Test.startTest();
		    List<ACED_Asset_Indication__c> lAssetActs = ACED_DataFactory.createAssetActualsWithInd(100);
		    //Assert the asset Indications have brand indication populated
		    system.assert([Select id, asset__c from ACED_Asset_Indication__c where id IN: lAssetActs limit 1].asset__c != null);
		    Test.stopTest();
	    }
	}
}