src/objects/ACED_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Affiliate__c</fullName>
        <formula>TEXT(Program__r.Affiliate__c)</formula>
        <inlineHelpText>This is a helptext for Affiliate</inlineHelpText>
        <label>Affiliate</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assets__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Asset that this activity is using; the asset should be available in the asset portfolio. Leave it blank if the activity does not make use of an asset</inlineHelpText>
        <label>Asset</label>
        <referenceTo>ACED_Asset__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Assests_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>Choose from the list of programs in the lookup table the one this activity belongs to</inlineHelpText>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>$User.ACED_HUB__c</field>
                <operation>equals</operation>
                <valueField>ACED_Programs__c.HUB__c</valueField>
            </filterItems>
            <filterItems>
                <field>$User.ACED_HUB__c</field>
                <operation>equals</operation>
                <value>ACE HUB</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ACED_Programs__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Assests_Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Asset status calculated from status of associated deliveries</description>
        <inlineHelpText>Indicates whether any of the deliveries of this activity have started (value is Executed) or not (value remain as Not Executed)</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Executed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Executed</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <displayFormat>AS-{00000}</displayFormat>
        <label>Activity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACED_Asset__c.object
<CustomObject>
    <fields>
        <fullName>Affiliate__c</fullName>
        <inlineHelpText>This is a helptext for Affiliate</inlineHelpText>
        <label>Affiliate</label>
        <picklist>
            <controllingField>HUB__c</controllingField>
            <picklistValues>
                <fullName>ACE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulgaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Croatia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cyprus &amp; Malta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Czech Republic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denmark</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>France</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Germany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greece</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hungary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ireland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Italy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Macedonia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Montengro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Netherlands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Norway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portugal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Romania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Serbia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Slovakia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Slovenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spain</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>HUB__c</fullName>
        <inlineHelpText>This is a helptext for HUB</inlineHelpText>
        <label>HUB</label>
        <picklist>
            <picklistValues>
                <fullName>ACE HUB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia HUB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada HUB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>France HUB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Germany HUB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Italy HUB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spain HUB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UK HUB</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>No_Activities__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This is a helptext for No Activities.
Indicates whether the asset is used in any activities.</inlineHelpText>
        <label>No Activities</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>This is a helptext for Status</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Under Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <recordTypes>
        <fullName>Non_Program_Asset</fullName>
        <active>true</active>
        <label>Non Program Asset</label>
    </recordTypes>
    <recordTypes>
        <fullName>Program_Asset</fullName>
        <active>true</active>
        <label>Program Asset</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACED_Asset_Indication__c.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <inlineHelpText>This is a helptext for Asset</inlineHelpText>
        <label>Asset</label>
        <referenceTo>ACED_Asset__c</referenceTo>
        <relationshipLabel>Asset Brand Indications</relationshipLabel>
        <relationshipName>Asset_Indications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Asset Brand Indication</label>
    <nameField>
        <displayFormat>AID-{0000}</displayFormat>
        <label>Asset Indication ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Brand Indications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACED_Deliveries__c.object
<CustomObject>
    <fields>
        <fullName>Activity__c</fullName>
        <inlineHelpText>Activity this delivery belongs to</inlineHelpText>
        <label>Activity</label>
        <referenceTo>ACED_Activity__c</referenceTo>
        <relationshipLabel>Deliveries</relationshipLabel>
        <relationshipName>Deliveries1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <formula>HYPERLINK( &apos;/&apos;&amp;Activity__r.Program__c ,  Activity__r.Program__r.Name,&apos;_blank&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is a helptext for Program</inlineHelpText>
        <label>Program</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Current status of the delivery. Has to be updated when the status of the delivery changes (i.e gets started, gets finalized…)</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Initiated</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Delivery</label>
    <nameField>
        <displayFormat>DE-{000000}</displayFormat>
        <label>Deliveries ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACED_Programs__c.object
<CustomObject>
    <fields>
        <fullName>HUB__c</fullName>
        <inlineHelpText>HUB this Program is owned by</inlineHelpText>
        <label>HUB</label>
        <picklist>
            <picklistValues>
                <fullName>ACE HUB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia HUB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada HUB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>France HUB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Germany HUB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Italy HUB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spain HUB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UK HUB</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StandAlone_Asset_Program_TF__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This is a helptext for StandAlone Program Flag_TF</inlineHelpText>
        <label>StandAlone Program Flag_TF</label>
        <type>Checkbox</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ACED_Asset_TriggerHandler.cls
public with sharing class ACED_Asset_TriggerHandler {
    
       
    Public static boolean bRecursiveCheck = true; 
    Public static String Non_Program_AssetRecodtypeId = ACED_Utility.mRecordType(ACED_Utility.oAssetName).get('Non_Program_Asset');
    Public static String Program_AssetRecodtypeId = ACED_Utility.mRecordType(ACED_Utility.oAssetName).get('Program_Asset');
        
    Public static void UpdateStandAloneCheckboxOnInsert(List<ACED_Asset__c> lAsset){
        for(ACED_Asset__c oAsset : lAsset){
            oAsset.No_Activities__c = true;
            oAsset.RecordtypeId = Non_Program_AssetRecodtypeId;
        }
    }
    
    Public static void CheckIfStandAloneAsset(List<ACED_Asset__c> lAsset){
        Set<Id> sAssetWithActivity = new Set<Id>();
        List<ACED_Asset__c> lAssetWithoutActivity = new List<ACED_Asset__c>();
        for(ACED_Activity__c oActivity : [Select id,Assets__c from ACED_Activity__c where Assets__c in: lAsset and Program__r.StandAlone_Asset_Program_TF__c = :false]){
            sAssetWithActivity.add(oActivity.Assets__c);
        }
        
        for(ACED_Asset__c oAsset : lAsset){
            if(!sAssetWithActivity.contains(oAsset.id)){
                if(oAsset.status__c == ACED_Utility.sAssetLiveStatus){
                    lAssetWithoutActivity.add(oAsset);
                }   
                oAsset.No_Activities__c = true;
                oAsset.RecordtypeId = Non_Program_AssetRecodtypeId;
            }
            else{
                oAsset.No_Activities__c = false;
                oAsset.RecordtypeId = Program_AssetRecodtypeId;
            }   
        }
            system.debug('$$$$$'+lAssetWithoutActivity);
            createStandAloneAsset(lAssetWithoutActivity);
    }
    
    Public static void createStandAloneAsset(List<ACED_Asset__c> lAsset){
            bRecursiveCheck = false;
            List<ACED_Asset__c> lAssetsVar = new List<ACED_Asset__c>();
            List<ACED_Deliveries__c> lDeliveries = new List<ACED_Deliveries__c>();
            List<ACED_Activity__c> lActivityInsert = new List<ACED_Activity__c>();
            List<ACED_Programs__c> lPrograms = new List<ACED_Programs__c>();
            Set<String> sProgramUpsertIds = new Set<String>();
            for(ACED_Asset__c oAsset : lAsset){
                if(oAsset.status__c == ACED_Utility.sAssetLiveStatus){
                    //Create Programs                                           
                    ACED_Programs__c oPrograms = new ACED_Programs__c();
                        oPrograms.StandAlone_Asset_Program_TF__c = true;
                        oPrograms.Name = oAsset.HUB__c+'- Program';
                        oPrograms.HUB__c = oAsset.HUB__c;
                        oPrograms.Affiliate__c = oAsset.Affiliate__c;
                        oPrograms.StandAlone_Asset_Upsert_TF__c = oAsset.HUB__c +'-'+system.Today().year();
                        oPrograms.Year__c = String.valueOf(system.Today().year());
                        
                        //This condition is added so that mulitple programs dont get added for upsert with same value and we would get duplicate id specified error
                        if(!sProgramUpsertIds.contains(oAsset.HUB__c +'-'+system.Today().year()))
                            lPrograms.add(oPrograms);
                        sProgramUpsertIds.add(oAsset.HUB__c +'-'+system.Today().year());
                    
                    //Create Activity
                    ACED_Activity__c oActivity = new ACED_Activity__c();
                        oActivity.Activity_Name__c  = oAsset.Name+' - Asset Only Performance -'+oAsset.HUB__c+'-'+system.Today().year();
                        oActivity.Assets__c = oAsset.id;
                        ACED_Programs__c oProg = new ACED_Programs__c();
                        oProg.StandAlone_Asset_Upsert_TF__c = oAsset.HUB__c +'-'+system.Today().year();
                        oActivity.Program__r = oProg;
                        oActivity.StandAlone_Asset_Upsert__c = oAsset.Id+'-'+oAsset.HUB__c +'-'+system.Today().year();
                        oActivity.Planned_Start_Date__c = date.newInstance(system.Today().year(), 1, 1);
                        oActivity.Planned_End_Date__c = date.newInstance(system.Today().year(), 12, 31);
                        lActivityInsert.add(oActivity);
                    
                    //Create Delivery
                    ACED_Deliveries__c oDelivery = new ACED_Deliveries__c();
                        ACED_Activity__c oActivityUpsrt= new ACED_Activity__c();
                        oActivityUpsrt.StandAlone_Asset_Upsert__c = oAsset.Id+'-'+oAsset.HUB__c +'-'+system.Today().year();
                        oDelivery.StandAlone_Asset__c = oAsset.Id;
                        oDelivery.start_date__c = system.today();
                        oDelivery.end_date__c = date.newInstance(system.Today().year(), 12, 31);
                        oDelivery.Activity__r = oActivityUpsrt;
                        oDelivery.Status__c = 'Started';
                        oDelivery.StandAlone_Upsert_Attribute__c = oAsset.Id+'-'+oAsset.HUB__c +'-'+system.Today().year();
                        lDeliveries.add(oDelivery);
                }
            }
            
                Upsert lPrograms StandAlone_Asset_Upsert_TF__c;
                Upsert lActivityInsert StandAlone_Asset_Upsert__c;
                Upsert lDeliveries StandAlone_Upsert_Attribute__c; 
    
    }
    
    Public static void validateActiveChildAssets(List<ACED_Asset__c> lAsset){
        Set<Id> sRegionalAssetIds = new Set<Id>();
        Map<Id,Decimal> mRelatedAssetCount = new Map<Id,Decimal>();
        //store all regional assets to the set whose status being changed to 'Retired'
        for(ACED_Asset__c oAsset : lAsset){
            if(oAsset.Is_Regional_Asset__c && oAsset.Status__c ==ACED_Utility.RetiredStatus){
                sRegionalAssetIds.add(oAsset.Id);
            }
        }
        //
        for(Aggregateresult oRelatedAsset : [Select Count(id) Nr,Regional_Asset__c from ACED_Asset__c where Regional_Asset__c in : sRegionalAssetIds AND Status__c Not IN : ACED_Utility.retiredStatuses group by Regional_Asset__c]){
            mRelatedAssetCount.put((id)oRelatedAsset.get('Regional_Asset__c'),(Decimal)oRelatedAsset.get('Nr'));
        }
            
        for(ACED_Asset__c oAsset : lAsset){
            if(mRelatedAssetCount.containskey(oAsset.Id) && mRelatedAssetCount.get(oAsset.Id)!=null && mRelatedAssetCount.get(oAsset.Id)>0 ){
                oAsset.addError(Label.ACED_Retire_Asset_Error_Msg);
            }
        }
        
    }
    
    Public Static Void AssetIndicationsDeleteUpdateOnStandAlone(Map<Id,ACED_Asset__c> mNewAssetIndications,Map<Id,ACED_Asset__c> mOldAssetIndications){
        Set<Id> sDeleteAssetIds = new Set<Id>();
        List<ACED_Asset_Indication__c> lDeleteAssetIndication = new List<ACED_Asset_Indication__c>();
        Set<Id> sUpdateAssetIndicationIds = new Set<Id>();
        List<ACED_Asset_Indication__c> lUpdateAssetIndication = new List<ACED_Asset_Indication__c>();
        
        for(ACED_Asset__c oAsset : mNewAssetIndications.Values()){
            If(oAsset.Asset_Indications__c >0 && oAsset.No_Activities__c==false)
                sDeleteAssetIds.add(oAsset.Id);
            If(mNewAssetIndications.get(oAsset.Id).Status__c == 'Live' && mNewAssetIndications.get(oAsset.Id).Status__c != mOldAssetIndications.get(oAsset.Id).Status__c)   
                sUpdateAssetIndicationIds.add(oAsset.Id);
        }
                
        for(ACED_Asset_Indication__c oAssetIndication : [Select Id,Asset__c from ACED_Asset_Indication__c where Asset__c In : sDeleteAssetIds or Asset__c In : sUpdateAssetIndicationIds]){
            if(sDeleteAssetIds.contains(oAssetIndication.Asset__c))
                lDeleteAssetIndication.add(oAssetIndication);
            else if(sUpdateAssetIndicationIds.contains(oAssetIndication.Asset__c))  
                lUpdateAssetIndication.add(oAssetIndication);
        }
        if(lDeleteAssetIndication.size()>0)
            Delete lDeleteAssetIndication;
        if(lUpdateAssetIndication.size()>0)
            Update lUpdateAssetIndication;
        
    } 
}