src/objects/ACED_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Channel this activity is using to distribute the content.</inlineHelpText>
        <label>Channel</label>
        <referenceTo>ACED_Channel__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Assests_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <displayFormat>AS-{00000}</displayFormat>
        <label>Activity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACED_Channel__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Attribute__c</fullName>
        <inlineHelpText>This is a helptext for Actual Attribute</inlineHelpText>
        <label>Actual Attribute</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACED_Channel_Attribute__c.object
<CustomObject>
    <fields>
        <fullName>Actual__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This is a helptext for Actual</inlineHelpText>
        <label>Actual</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Attribute_Name__c</fullName>
        <inlineHelpText>Enter the attribute here, dont use # for attributes since its auto concatenated</inlineHelpText>
        <label>Attribute Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <inlineHelpText>This is a helptext for Channel</inlineHelpText>
        <label>Channel</label>
        <referenceTo>ACED_Channel__c</referenceTo>
        <relationshipLabel>Channel Attributes</relationshipLabel>
        <relationshipName>Channel_Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Channel Attribute</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Attribute ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACED_Deliveries__c.object
<CustomObject>
    <fields>
        <fullName>Activity__c</fullName>
        <inlineHelpText>Activity this delivery belongs to</inlineHelpText>
        <label>Activity</label>
        <referenceTo>ACED_Activity__c</referenceTo>
        <relationshipLabel>Deliveries</relationshipLabel>
        <relationshipName>Deliveries1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Actual_Attribute__c</fullName>
        <formula>Activity__r.Channel__r.Actual_Attribute__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Actual Attribute</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <formula>Activity__r.Channel__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is a helptext for Channel</inlineHelpText>
        <label>Channel</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <inlineHelpText>Date when the delivery gets finalized</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PIM_Segment__c</fullName>
        <inlineHelpText>PIM segment targetted by the delivery. If the delivery targets all the Audience group then use All</inlineHelpText>
        <label>PIM Segment</label>
        <picklist>
            <picklistValues>
                <fullName>All</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not segmented</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patient Focus Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patient Idealist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scientific Innovator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Traditionalist</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>Date when the delivery gets started</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Delivery</label>
    <nameField>
        <displayFormat>DE-{000000}</displayFormat>
        <label>Deliveries ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACED_Integration_Console__c.object
<CustomObject>
    <fields>
        <fullName>RN_Password__c</fullName>
        <label>Password</label>
        <length>50</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>RN_UserName__c</fullName>
        <inlineHelpText>This is a helptext for UserName</inlineHelpText>
        <label>UserName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RightNow_Admin_Email__c</fullName>
        <inlineHelpText>Enter multiple email ids seperated by ; 
Eg : mike@gmail.com;denny@yahoo.com</inlineHelpText>
        <label>RightNow Admin Email</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>WebTrends_Admin_Email__c</fullName>
        <inlineHelpText>Enter multiple email ids seperated by ;
Eg : mike@gmail.com;denny@yahoo.com</inlineHelpText>
        <label>WebTrends Admin Email</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>WebTrends_Service_URL__c</fullName>
        <inlineHelpText>This is a helptext for WebTrends Service URL</inlineHelpText>
        <label>WebTrends Service URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Web_Password__c</fullName>
        <inlineHelpText>This is a helptext for Password</inlineHelpText>
        <label>Password</label>
        <length>20</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Web_UserName__c</fullName>
        <inlineHelpText>This is a helptext for UserName</inlineHelpText>
        <label>UserName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Integration Console</label>
    <nameField>
        <label>Integration Console Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Console</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ACED_RightNow_Country__c.object
<CustomObject>
    <fields>
        <fullName>Integration_Console__c</fullName>
        <inlineHelpText>This is a helptext for Integration Console</inlineHelpText>
        <label>Integration Console</label>
        <referenceTo>ACED_Integration_Console__c</referenceTo>
        <relationshipLabel>RightNow Countries</relationshipLabel>
        <relationshipName>RightNow_Countries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Report_ID__c</fullName>
        <label>Report ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RightNow_Service_URL__c</fullName>
        <inlineHelpText>This is a helptext for RightNow Service URL</inlineHelpText>
        <label>RightNow Service URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>RightNow Country</label>
    <nameField>
        <displayFormat>RNC-{000000}</displayFormat>
        <label>Country ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RightNow Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Test_ACED_RightNowScheduler.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(seealldata=false)
private class Test_ACED_RightNowScheduler {

    static testMethod void myUnitTest() {
        User runAsUser = ACED_DataFactory.createUser('ACED_Digital_Dashboard_Owner');
        System.runAs(runAsUser) {
        // Set mock callout class 
            
            ACED_Integration_Console__c oIntConsole =  new ACED_Integration_Console__c(Web_UserName__c='tets@tet.com',RightNow_Admin_Email__c='uet@yryr.com',WebTrends_Admin_Email__c='777@77.com',Web_Password__c='8888',WebTrends_Service_URL__c='yryryr@uerur.com');
            oIntConsole.RN_UserName__c = 'tetete';
            oIntConsole.RN_Password__c = '12334';
            oIntConsole.Metrics__c= 'Test Metrics';
            insert oIntConsole;
            
            ACED_RightNow_Country__c oRightNow = new ACED_RightNow_Country__c();
            oRightNow.RightNow_Service_URL__c = 'http://api.salesforce.com/foo/bar';
            oRightNow.Report_ID__c = '13252';
            oRightNow.Integration_Console__c = oIntConsole.Id;
            Insert oRightNow;
            
            ACED_Channel__c oChannel = ACED_DataFactory.createChannels(1)[0];
            ACED_Channel_Attribute__c oChannelAttributes = new ACED_Channel_Attribute__c();
            oChannelAttributes.Attribute_Name__c ='Opened';
            oChannelAttributes.actual__c = true;
            oChannelAttributes.channel__c = oChannel.id;
            Insert oChannelAttributes;
            
            oChannel.Actual_Attribute__c = 'Opened';
            Update oChannel;
            
            ACED_Activity__c oActivity =  ACED_DataFactory.createActivities(1)[0];      
            oActivity.channel__c = oChannel.id;
            update oActivity;
            
            ACED_Deliveries__c oDeliveries= New ACED_Deliveries__c();
            oDeliveries.Activity__c= oActivity.ID;
            oDeliveries.Start_Date__c=System.today();
            oDeliveries.End_Date__c=System.today()+45;
            oDeliveries.PIM_Segment__c='Traditionalist';
            insert  oDeliveries;
            
            Test.startTest();
                Test.setMock(HttpCalloutMock.class, new Test_ACED_RightNowMockResp());
                ACED_RightNowScheduler.InvokeRightNow();
            Test.stopTest();
            
            String CRON_EXP = '0 0 0 1 1 ? 2025';  
            String jobId = System.schedule('testScheduledApex', CRON_EXP, new ACED_RightNowScheduler() ); 
            
            CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered,NextFireTime FROM CronTrigger WHERE id = :jobId];
            
            //Assert job is now running for first time
            System.assertEquals(0, ct.TimesTriggered);
        }    
      
    }
}