src/objects/ACED_Asset_Indication__c.object
<CustomObject>
    <fields>
        <fullName>Brand_Indication__c</fullName>
        <inlineHelpText>This is a helptext for Brand Indication</inlineHelpText>
        <label>Brand Indication</label>
        <referenceTo>ACED_Brand_Indications__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Asset_Indications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Asset Brand Indication</label>
    <nameField>
        <displayFormat>AID-{0000}</displayFormat>
        <label>Asset Indication ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Brand Indications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Test_ACED_AssetInd_TriggerHandler.cls
/* Class Name  : Test_ACED_AssetIndications_TriggerHandler 
* Description  : Test Class for ACED_AssetIndications_TriggerHandler
* Created By   : Goutham
* Created Date : 10/1/2014
* Modification Log:  
* --------------------------------------------------------------------------------------------------------------------------------------
* Developer                Date                 Modification ID        Description 
* ---------------------------------------------------------------------------------------------------------------------------------------

*/
@isTest(SeeAllData=false)

//test class for ACED_AssetIndications_TriggerHandler
public class Test_ACED_AssetInd_TriggerHandler {

    //test method for ACED_AssetIndications_TriggerHandler
    static testMethod void insertAssetInd() {
    
        //Declaring the user with Digital dashboard owner Permission set
        User runAsUser = ACED_DataFactory.createUser('ACED_Digital_Dashboard_Owner');
            
    System.runAs(runAsUser) {
        
        Test.startTest();
            
            //Inserting a list of Asset Brandindications which fires trigger on asset brand indications
            list<ACED_Asset_Indication__c> lAssetInds = ACED_DataFactory.createAssetIndications(100);
            
            //System assert to check whether recordtypeof assets inserted
            //system.assertequals(lAssetInds[0].Brand_Indication__c,NULL); 
            
        Test.stopTest();
        
        
        
        }
      }   
}