src/objects/ACED_Brand_Indications__c.object
<CustomObject>
    <fields>
        <fullName>PRODUCT_GROUP_ID_GLBL__c</fullName>
        <label>PRODUCT_GROUP_ID_GLBL</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Brand Indication</label>
    <nameField>
        <label>Brand Indication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand Indications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product_Group_GLBL__c.object
<CustomObject>
    <description>Object to store Product Information, mastered Product Group records from Material ODS : MERC : Created on 09/27/2013 by Katy Lorenti, Mavens Consulting</description>
    <fields>
        <fullName>Product_Group_Id_GLBL__c</fullName>
        <description>A sequentially-assigned number, generated from a sequence MTM_PRD_GRP_ID_SEQ  uniquely identifies a product grouping.
Created by John A Adams 11/1/2013</description>
        <label>Product Group Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Product Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_ACED_CreateProducts.cls
/* Class Name  : Test_ACED_CreateProducts 
* Description  : Test Class for ACED_CreateProducts 
* Created By   : Goutham
* Created Date : 9/22/2014
* Modification Log:  
* --------------------------------------------------------------------------------------------------------------------------------------
* Developer                Date                 Modification ID        Description 
* ---------------------------------------------------------------------------------------------------------------------------------------

*/
@isTest(SeeAllData=false)

//test class for ACED_CreateProducts
public class Test_ACED_CreateProducts {

    //test method for ACED_CreateProducts
    static testMethod void createNewProduct() {
    
        //Declaring the user with Digital dashboard owner Permission set   
            User runAsUser = ACED_DataFactory.createUser('ACED_Digital_Dashboard_Owner');
                
        System.runAs(runAsUser) {
        
            Test.startTest();
                        
            //Inserting a list of Brandindications 
            List<ACED_Brand_Indications__c> lBrandIndications = ACED_DataFactory.createBrandIndication(1);
            
            //Inserting a  Products group 
            List<Product_Group_GLBL__c> lPrdGrp = ACED_DataFactory.createProdGroup(1);
                     
            //Creating brand indication and calling methods on VF page
            ApexPages.StandardController cnt = new ApexPages.StandardController(lBrandIndications[0]);
            ACED_CreateProducts  createProduct = New ACED_CreateProducts(cnt);
            createProduct.sProductSearch = lPrdGrp[0].Name;
            createProduct.CreateProductButton();
            createProduct.SearchProductcatalog();
            createProduct.ClearGSOLink();
            createProduct.oCreateBrandIndication = NULL;
            createProduct.CreateProductButton();           
            

            
            //System assert to check whether Product group ID is populated on Brand indication
            system.assertequals(lBrandIndications[0].PRODUCT_GROUP_ID_GLBL__c,lPrdGrp[0].Product_Group_Id_GLBL__c); 
            
            Test.stopTest();
            
            
            
            }
      }
    
    
    
}