src/objects/ACED_Channel__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Attribute__c</fullName>
        <inlineHelpText>This is a helptext for Actual Attribute</inlineHelpText>
        <label>Actual Attribute</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Potential_Attribute__c</fullName>
        <inlineHelpText>This is a helptext for Potential Attribute</inlineHelpText>
        <label>Potential Attribute</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACED_Channel_Attribute__c.object
<CustomObject>
    <fields>
        <fullName>Actual__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This is a helptext for Actual</inlineHelpText>
        <label>Actual</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Attribute_Name__c</fullName>
        <inlineHelpText>Enter the attribute here, dont use # for attributes since its auto concatenated</inlineHelpText>
        <label>Attribute Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <inlineHelpText>This is a helptext for Channel</inlineHelpText>
        <label>Channel</label>
        <referenceTo>ACED_Channel__c</referenceTo>
        <relationshipLabel>Channel Attributes</relationshipLabel>
        <relationshipName>Channel_Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Potential__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This is a helptext for Potential</inlineHelpText>
        <label>Potential</label>
        <type>Checkbox</type>
    </fields>
    <label>Channel Attribute</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Attribute ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ACED_Channel_TriggerHandler.cls
public with sharing class ACED_Channel_TriggerHandler {
    Public static void UpdateChannelActualNPotentialAttributes(List<ACED_Channel__c> lChannels){
        Map<Id,Map<String,String>> mChannelDetails = new Map<Id,Map<String,String>>();
        for(ACED_Channel_Attribute__c oChanneAttr : [Select Id,Attribute_Name__c,Channel__c,Actual__c,Potential__c from ACED_Channel_Attribute__c where Channel__c in : lChannels and (Actual__c = : true or Potential__c = : true)]){
            if(mChannelDetails.containskey(oChanneAttr.Channel__c) && mChannelDetails.get(oChanneAttr.Channel__c)!=null){
                if(oChanneAttr.Actual__c){
                    mChannelDetails.get(oChanneAttr.Channel__c).put('ACTUAL',oChanneAttr.Attribute_Name__c);
                }
                
                else if(oChanneAttr.Potential__c){
                    mChannelDetails.get(oChanneAttr.Channel__c).put('POTENTIAL',oChanneAttr.Attribute_Name__c);
                }   
            }
            else{
                if(oChanneAttr.Actual__c){
                    mChannelDetails.put(oChanneAttr.Channel__c,new Map<String,String>{'ACTUAL'=>oChanneAttr.Attribute_Name__c});
                }
                else if(oChanneAttr.Potential__c){
                    mChannelDetails.Put(oChanneAttr.Channel__c,new Map<String,String>{'POTENTIAL'=>oChanneAttr.Attribute_Name__c});
                }   
            }
        }
        
        for(ACED_Channel__c oChannel : lChannels){
            if(mChannelDetails.containskey(oChannel.Id) && mChannelDetails.get(oChannel.Id).containskey('ACTUAL'))
                oChannel.Actual_Attribute__c = mChannelDetails.get(oChannel.Id).get('ACTUAL');
            else
                oChannel.Actual_Attribute__c = null;    
            
            if(mChannelDetails.containskey(oChannel.Id) && mChannelDetails.get(oChannel.Id).containskey('POTENTIAL'))
                oChannel.Potential_Attribute__c = mChannelDetails.get(oChannel.Id).get('POTENTIAL');
            else
                oChannel.Potential_Attribute__c = null;             
        }
    }
}