src/objects/ACED_Asset__c.object
<CustomObject>
    <fields>
        <fullName>Total_Effort__c</fullName>
        <description>Total effort on related Brand Indications</description>
        <label>#Total Effort</label>
        <summarizedField>ACED_Asset_Indication__c.Effort__c</summarizedField>
        <summaryForeignKey>ACED_Asset_Indication__c.Asset__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACED_Asset_Actual__c.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <label>Asset</label>
        <referenceTo>ACED_Asset__c</referenceTo>
        <relationshipLabel>Asset Actuals</relationshipLabel>
        <relationshipName>Asset_Actuals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Asset Actual</label>
    <nameField>
        <displayFormat>AA-{0000}</displayFormat>
        <label>Asset Actual Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Actuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACED_Asset_Indication__c.object
<CustomObject>
    <fields>
        <fullName>Actual_eInteraction__c</fullName>
        <inlineHelpText>This is a helptext for Actual eInteraction</inlineHelpText>
        <label>Actual eInteraction</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <inlineHelpText>This is a helptext for Asset</inlineHelpText>
        <label>Asset</label>
        <referenceTo>ACED_Asset__c</referenceTo>
        <relationshipLabel>Asset Brand Indications</relationshipLabel>
        <relationshipName>Asset_Indications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Effort__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>This is a helptext for Effort</inlineHelpText>
        <label>Effort</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Effort_eInteraction__c</fullName>
        <inlineHelpText>This is a helptext for Effort eInteraction</inlineHelpText>
        <label>Effort eInteraction</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Asset Brand Indication</label>
    <nameField>
        <displayFormat>AID-{0000}</displayFormat>
        <label>Asset Indication ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Brand Indications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ACED_Asset_Actual_TriggerHandler.cls
/* Class Name  : ACED_DataFactory
* Description  : Class to update eInteraction values on Asset Brand Indication upon creating or updating Asset Actuals
* Created By   : Goutham
* Created Date : 
* Modification Log:  
* --------------------------------------------------------------------------------------------------------------------------------------
* Developer                Date                 Modification ID        Description 
* ---------------------------------------------------------------------------------------------------------------------------------------

*/

public with sharing class ACED_Asset_Actual_TriggerHandler {
    
    Public static void UpdateAssetIndicationWithInteractionValues(List<ACED_Asset_Actual__c> lAssetActuals){
    
    //Creating Map of Asset IDs and Sum of corresponding Asset actuals value Sum
    Map<ID,Decimal> mAssetToSum = New Map<ID,Decimal>();
    //Creating a list of Asset IDs
    List<ID> lAssets = New List<ID>();
    //Creating a lsit of asse indications
    List<ACED_Asset_Indication__c> lAssetInd = New List<ACED_Asset_Indication__c>();
    

    //Aggregate query to get the sum of value on related Asset actuals of an asset
                    for(AggregateResult oAssetAggregates : [SELECT Sum(Value__c) MonthlySum,Asset__c AssetIDs 
                                                           FROM ACED_Asset_Actual__c
                                                           WHERE Id in :lAssetActuals group by Asset__c]){
                                                           
                    mAssetToSum.put((Id)oAssetAggregates.get('AssetIDs'),(Decimal)oAssetAggregates.get('MonthlySum'));  
                    lAssets.add((Id)oAssetAggregates.get('AssetIDs'));
                                                                               
                    }
                    
     //Looping over all Asset Indications and updating eInteraction values                
                    for(ACED_Asset_Indication__c AssetIndUpdate: [SELECT Effort__c ,Asset__c,Asset__r.Total_Effort__c 
                                                           FROM ACED_Asset_Indication__c
                                                           WHERE Asset__c in :lAssets ]){
                    If(mAssetToSum.containskey(AssetIndUpdate.Asset__c)){ 
                    If(AssetIndUpdate.Asset__r.Total_Effort__c!=NULL && AssetIndUpdate.Asset__r.Total_Effort__c!=0){                                      
                    AssetIndUpdate.Actual_eInteraction__c=AssetIndUpdate.Effort__c * ((mAssetToSum.get(AssetIndUpdate.Asset__c))/100);
                    AssetIndUpdate.Effort_eInteraction__c=(AssetIndUpdate.Effort__c/(AssetIndUpdate.Asset__r.Total_Effort__c)) * (mAssetToSum.get(AssetIndUpdate.Asset__c));
                    lAssetInd.add(AssetIndUpdate); 
                    }                                     
                    }
                    }
                    Update(lAssetInd);
                    
    
    
    }
}