src/objects/ACED_Integration_Console__c.object
<CustomObject>
    <fields>
        <fullName>RN_Password__c</fullName>
        <label>Password</label>
        <length>50</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>RN_UserName__c</fullName>
        <inlineHelpText>This is a helptext for UserName</inlineHelpText>
        <label>UserName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RightNow_Admin_Email__c</fullName>
        <inlineHelpText>Enter multiple email ids seperated by ; 
Eg : mike@gmail.com;denny@yahoo.com</inlineHelpText>
        <label>RightNow Admin Email</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>WebTrends_Admin_Email__c</fullName>
        <inlineHelpText>Enter multiple email ids seperated by ;
Eg : mike@gmail.com;denny@yahoo.com</inlineHelpText>
        <label>WebTrends Admin Email</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>WebTrends_Service_URL__c</fullName>
        <inlineHelpText>This is a helptext for WebTrends Service URL</inlineHelpText>
        <label>WebTrends Service URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Web_Password__c</fullName>
        <inlineHelpText>This is a helptext for Password</inlineHelpText>
        <label>Password</label>
        <length>20</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Web_UserName__c</fullName>
        <inlineHelpText>This is a helptext for UserName</inlineHelpText>
        <label>UserName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Integration Console</label>
    <nameField>
        <label>Integration Console Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Console</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ACED_RightNow_Country__c.object
<CustomObject>
    <fields>
        <fullName>Integration_Console__c</fullName>
        <inlineHelpText>This is a helptext for Integration Console</inlineHelpText>
        <label>Integration Console</label>
        <referenceTo>ACED_Integration_Console__c</referenceTo>
        <relationshipLabel>RightNow Countries</relationshipLabel>
        <relationshipName>RightNow_Countries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Report_ID__c</fullName>
        <label>Report ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RightNow_Service_URL__c</fullName>
        <inlineHelpText>This is a helptext for RightNow Service URL</inlineHelpText>
        <label>RightNow Service URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>RightNow Country</label>
    <nameField>
        <displayFormat>RNC-{000000}</displayFormat>
        <label>Country ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RightNow Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ACED_RightNowScheduler.cls
Global class ACED_RightNowScheduler implements Schedulable{
     Global void execute(SchedulableContext sc) {     	
       InvokeRightNow();
     }
      
     Public static Void InvokeRightNow(){
     	
        Try{ 
			for(ACED_RightNow_Country__c oRightNow : [Select id,RightNow_Service_URL__c,Report_ID__c,Integration_Console__r.RightNow_Admin_Email__c,Integration_Console__r.RN_UserName__c,Integration_Console__r.RN_Password__c from ACED_RightNow_Country__c limit 8]){
			    ACED_RightNowUtility.ACED_RightNowUtility(oRightNow.RightNow_Service_URL__c,oRightNow.Report_ID__c,oRightNow.Integration_Console__r.RN_UserName__c,oRightNow.Integration_Console__r.RN_Password__c,oRightNow.Integration_Console__r.RightNow_Admin_Email__c);
			} 
            }catch(exception e){
            	ACED_Integration_Console__c oIntegration = [Select id,Web_UserName__c,RightNow_Admin_Email__c,WebTrends_Admin_Email__c,Web_Password__c,WebTrends_Service_URL__c from ACED_Integration_Console__c limit 1];
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                String[] toAddresses = oIntegration.RightNow_Admin_Email__c.normalizeSpace().split(';');
                mail.setToAddresses(toAddresses);
                mail.setSubject(Label.ACED_RightNow_SubjectLine);
                mail.saveAsActivity = false;
                mail.setPlainTextBody(Label.ACED_RightNow_EmailContent+'\n'+ e);
                mail.setHtmlBody(Label.ACED_Webtrends_EmailContent+'</br></br>' + e);
                Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
            }
     }
}