src/objects/ACED_Activity__c.object
<CustomObject>
    <label>Activity</label>
    <nameField>
        <displayFormat>AS-{00000}</displayFormat>
        <label>Activity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACED_Asset_Actual__c.object
<CustomObject>
    <fields>
        <fullName>Asset_Attribute_Upsert__c</fullName>
        <description>Used to upsert the collated results from delivery actuals. Format is AssetId+&apos;-&apos;+Year+&apos;-&apos;+Month</description>
        <externalId>true</externalId>
        <label>Asset Attribute Upsert</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <label>Asset</label>
        <referenceTo>ACED_Asset__c</referenceTo>
        <relationshipLabel>Asset Actuals</relationshipLabel>
        <relationshipName>Asset_Actuals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <picklist>
            <picklistValues>
                <fullName>January</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>February</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>March</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>April</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>May</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>June</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>July</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>August</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>September</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>October</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>November</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>December</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Asset Actual</label>
    <nameField>
        <displayFormat>AA-{0000}</displayFormat>
        <label>Asset Actual Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Actuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACED_Deliveries__c.object
<CustomObject>
    <fields>
        <fullName>Activity__c</fullName>
        <inlineHelpText>Activity this delivery belongs to</inlineHelpText>
        <label>Activity</label>
        <referenceTo>ACED_Activity__c</referenceTo>
        <relationshipLabel>Deliveries</relationshipLabel>
        <relationshipName>Deliveries1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <formula>HYPERLINK( &apos;/&apos;&amp;Activity__r.Program__c ,  Activity__r.Program__r.Name,&apos;_blank&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is a helptext for Program</inlineHelpText>
        <label>Program</label>
        <type>Text</type>
    </fields>
    <label>Delivery</label>
    <nameField>
        <displayFormat>DE-{000000}</displayFormat>
        <label>Deliveries ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ACED_Delivery_Actual_Line__c.object
<CustomObject>
    <fields>
        <fullName>Delivery_Actuals__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is a helptext for Delivery Actuals</inlineHelpText>
        <label>Delivery Actuals</label>
        <referenceTo>ACED_Delivery_Actuals__c</referenceTo>
        <relationshipLabel>Delivery Actual Lines</relationshipLabel>
        <relationshipName>Delivery_Actual_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>This is a helptext for Value</inlineHelpText>
        <label>Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Delivery Actual Line</label>
    <nameField>
        <displayFormat>AID-{0000}</displayFormat>
        <label>Attribute ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Actual Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ACED_Delivery_Actuals__c.object
<CustomObject>
    <fields>
        <fullName>Delivery__c</fullName>
        <inlineHelpText>This is a helptext for Delivery</inlineHelpText>
        <label>Delivery</label>
        <referenceTo>ACED_Deliveries__c</referenceTo>
        <relationshipLabel>Delivery Actuals</relationshipLabel>
        <relationshipName>Delivery_Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <inlineHelpText>This is a helptext for Month</inlineHelpText>
        <label>Month</label>
        <picklist>
            <picklistValues>
                <fullName>January</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>February</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>March</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>April</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>May</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>June</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>July</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>August</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>September</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>October</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>November</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>December</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>This is a helptext for Value</inlineHelpText>
        <label>Value</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Delivery Actuals</label>
    <nameField>
        <displayFormat>DA-{00000}</displayFormat>
        <label>Delivery  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Actuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ACED_Delivery_Actuals_TriggerHandler.cls
public class ACED_Delivery_Actuals_TriggerHandler{

    public static void DelDeliveryActualLinesOnDelivery(List<ACED_Delivery_Actuals__c> lDeliveryActuals){
        
        system.debug('#####'+lDeliveryActuals);
        list<ACED_Delivery_Actual_Line__c> lDeliveryActialLinesToBeDeleted = new list<ACED_Delivery_Actual_Line__c>();
        
        for(ACED_Delivery_Actual_Line__c oDeliveryActualLine : [SELECT ID,Delivery_Actuals__c from ACED_Delivery_Actual_Line__c where Delivery_Actuals__c  in :lDeliveryActuals]){
            lDeliveryActialLinesToBeDeleted.add(oDeliveryActualLine);
        }   
        Database.DeleteResult [] lDeleteResults = Database.Delete(lDeliveryActialLinesToBeDeleted,false); 
                 
                 for(Integer i=0;i<lDeleteResults.size();i++){
                     if (!lDeleteResults.get(i).isSuccess()){
                        // DML operation failed
                        lDeliveryActialLinesToBeDeleted[i].adderror(label.ACED_ErrorMessage);//failed record from the list
                        }
                  }
       // delete lDeliveryActialLinesToBeDeleted;
    }
    
    Public static void UpsertAggregatedAssetActuals(List<ACED_Delivery_Actuals__c> lDeliveryActuals){
        List<ACED_Asset_Actual__c> lAssetActuals = new List<ACED_Asset_Actual__c>();
        for(AggregateResult oDeliveryAggregates : [Select Sum(Value__c) MonthlySum,Month__c Month,Delivery__r.Activity__r.Assets__c AssetIds,Delivery__r.Activity__r.program__r.Year__c year from ACED_Delivery_Actuals__c where Id in :lDeliveryActuals group by Delivery__r.Activity__r.program__r.Year__c,Delivery__r.Activity__r.Assets__c,Month__c]){
            if(oDeliveryAggregates.get('AssetIds')!=null){
                ACED_Asset_Actual__c oAssetActuals = new ACED_Asset_Actual__c();
                oAssetActuals.Asset__c = (Id)oDeliveryAggregates.get('AssetIds');
                oAssetActuals.Asset_Attribute_Upsert__c = (String)oDeliveryAggregates.get('AssetIds')+'-'+(String)oDeliveryAggregates.get('year')+'-'+(String)oDeliveryAggregates.get('Month');
                oAssetActuals.Value__c = (Decimal)oDeliveryAggregates.get('MonthlySum');
                oAssetActuals.Year__c = (String)oDeliveryAggregates.get('year');
                oAssetActuals.Month__c = (String)oDeliveryAggregates.get('Month');
                lAssetActuals.add(oAssetActuals);
            }
        }
        
        if(!lAssetActuals.isempty()){
        		 Schema.SObjectField fUpsertfield = ACED_Asset_Actual__c.Asset_Attribute_Upsert__c;    
                   
                 Database.UpsertResult [] lUpsertResults = Database.upsert(lAssetActuals,fUpsertfield ,false); 
                 
                 for(Integer i=0;i<lUpsertResults .size();i++){
                     if (!lUpsertResults .get(i).isSuccess()){
                        // DML operation failed
                        lAssetActuals.get(i).adderror(label.ACED_ErrorMessage);//failed record from the list
                        }
                  }
         }
                 
 }
    
}