src/objects/Affiliation_GLBL__c.object
<CustomObject>
    <description>Object to track affiliations between accounts for searching purposes. Created 10/17/2013 by KLorenti, Mavens Consulting</description>
    <fields>
        <fullName>Priority_Rank_Nbr_GLBL__c</fullName>
        <description>Priority Rank Number
Customer ODS to Mercury Mapping</description>
        <label>Priority Rank Number</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Affiliation #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MERC_PrimaryAffiliationTest.cls
@isTest
private class MERC_PrimaryAffiliationTest {

    static List<Account> accounts;
    static List<Account> hcpaccounts;
    static List<Affiliation_GLBL__c> affiliations;
	static User testUser = MERC_TestFactory.getTestingUser();
    

    static {
        accounts = MERC_TestFactory.insertHcpAccountsInCountry(1, 'GB'); 
        hcpaccounts= MERC_TestFactory.insertAccounts(1);
        affiliations= MERC_TestFactory.newAffiliation(accounts[0],hcpaccounts[0]);
    }

    @isTest
    static void test_should_populate_primary_affilaition() {
	 System.runAs(testUser) {
        Test.startTest();
        MERC_PrimaryAffiliation pf= new MERC_PrimaryAffiliation();
        pf.isActive();
        pf.execute(affiliations);
        Test.stopTest();
		System.assertEquals(1, [Select Priority_Rank_Nbr_GLBL__c From Affiliation_GLBL__c WHERE ID = :affiliations[0].Id].Priority_Rank_Nbr_GLBL__c);
    }
	}

}