src/objects/Affiliation_GLBL__c.object
<CustomObject>
    <description>Object to track affiliations between accounts for searching purposes. Created 10/17/2013 by KLorenti, Mavens Consulting</description>
    <fields>
        <fullName>Account_GLBL__c</fullName>
        <description>Used to help indicate direction of influence. Created 10/17/2013 by KLorenti, Mavens Consulting</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Affiliations</relationshipLabel>
        <relationshipName>Affiliations_To</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Priority_Rank_Nbr_GLBL__c</fullName>
        <description>Priority Rank Number
Customer ODS to Mercury Mapping</description>
        <label>Priority Rank Number</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Affiliation #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Alternate_Id_GLBL__c.object
<CustomObject>
    <description>Stores Alternate ID&apos;s for Accounts. Created 10/17/2013 by KLorenti, Mavens Consulting</description>
    <fields>
        <fullName>Account_GLBL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship from Alternate ID to Account. Created 10/17/2013 by KLorenti, Mavens Consulting</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Alternate ID&apos;s</relationshipLabel>
        <relationshipName>Alternate_ID</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority_Rank_Nbr_GLBL__c</fullName>
        <description>Priority Rank Number
Customer ODS to Mercury Mapping
Created by John A Adams 11/4/2013</description>
        <label>Priority Rank Number</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Alternate ID</label>
    <nameField>
        <label>Alternate ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alternate ID&apos;s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Communication_Preference_GLBL__c.object
<CustomObject>
    <description>Object used to store Speakers consent and communication preferences.
Created by John A Adams 9/26/2013
Renamed Communication from Consent by John A Adams 10/7/2013
Renamed Communication Preference from Communication by JFerraro 10/17/2013</description>
    <fields>
        <fullName>Account_GLBL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associates consent decisions with the account
Created by John A Adams 9/27/2013</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Consent</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Communication Preference</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Communicaion Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communication Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Preferences_and_Consent_GLBL__c.object
<CustomObject>
</CustomObject>

src/objects/Speciality_MERC__c.object
<CustomObject>
    <description>Contains Health Care Provider speciality information 
Created by John A Adams 12/15/2013</description>
    <fields>
        <fullName>Account_GLBL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account
Created by John A Adams 12/15/2013</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Specialities</relationshipLabel>
        <relationshipName>Specialities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority_Rank_Nbr_GLBL__c</fullName>
        <description>Priority Rank Number
Created by John A Adams 12/15/2013</description>
        <label>Priority Rank Number</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Speciality</label>
    <nameField>
        <label>Speciality Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specialities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CUST_RefreshLOVsUtil.cls
global class CUST_RefreshLOVsUtil {

	public final String DATENAME = '_Capture_Date';
	public final String SUFFIX = '_GLBL__c';

	public CUST_RefreshLOVsUtil() {}

	public String getDateFieldName(String f) {
		String root = f.substring(0,f.indexOfIgnoreCase(SUFFIX));
		String dateFieldName = root+DATENAME+SUFFIX;
		if (dateFieldName.length()>40) dateFieldName = root.remove('_')+'Date'+SUFFIX;
		return dateFieldName;
	}

	public String getDateFieldNames(String fList) {
		String result = '';
		for (String f : fList.split(',')) result += getDateFieldName(f) + ',';
		return result.removeEnd(',');
	}

	public static String getCSVString(String key, Map<String, List<String>> m) {
		String result = '';
		if (m.containsKey(key)) {
			for (String s : m.get(key)) result += s + ',';
			result = result.removeEnd(',');
		}
		return result;
	}

	public static String getCSVString(List<String> vals) {
		String result = '';
		for (String s : vals) result += s + ',';
		return result.removeEnd(',');
	}

	public final Set<String> NOTGROUBABLE  = new Set<String>{'Priority_Rank_Nbr_GLBL__c'};
	public Boolean canGroupBy(String f) {
		return !NOTGROUBABLE.contains(f);
	}

	public void p(String m) {
		System.debug('\n\n\nYYZ - '+m+'\n\n\n\n');
	}

	global class ObjToken {
		public String       name {get; set;}
		public String       relation {get; set;}
		public String       filter {get; set;}
		public String       lookup {get; set;}
		public List<String> fields {get; set;}							
		public String       fieldsCSV {get{return (fields!=null) ? CUST_RefreshLOVsUtil.getCSVString(fields) : null;}}
		public String       abbreviation {get; 
							set{
								abbreviation = value;
								name = ABBREVIATIONS.get(abbreviation);
								relation = RELATIONS.get(abbreviation);
								filter = FILTERS.get(abbreviation);
								}
							}
		public Map<String, String> values {get; set;}

		public final Map<String,String> ABBREVIATIONS = new Map<String,String>{
				'a'=>'Account',
				'aff'=>'Affiliation_GLBL__c',
				'alt'=>'Alternate_Id_GLBL__c',
				'c'=>'Preferences_and_Consent_GLBL__c',
				's'=>'Specialty_MERC__c'
		};
		public final Map<String,String> RELATIONS = new Map<String,String>{
				'aff'=>'Affiliations_To__r',
				'alt'=>'Alternate_ID__r',
				'c'=>'Consent__r',
				's'=>'Specialities__r'
		};
		public final Map<String,String> FILTERS = new Map<String,String>{
				'aff'=>'CST_App_Menu_Flag_Affil_CUST__c',
				'c'=>'CST_App_Menu_Flag_Consent_CUST__c'
		};

		public ObjToken(String s) {
			abbreviation = s;
			if (s!='a') lookup = 'Account_GLBL__c';
		}
	}
}