src/objects/Agenda_Item_MERC__c.object
<CustomObject>
    <description>Used to construct and store Agendas for Meetings to be distributed to HCPs or displayed on the Web Service : MERC : Created on 09/26/2013 by John Adams, Mavens Consulting</description>
    <fields>
        <fullName>Meeting_MERC__c</fullName>
        <description>One to Many relationship with Meeting
Created by John A Adams 9/30/2013</description>
        <label>Meeting</label>
        <referenceTo>Meeting_MERC__c</referenceTo>
        <relationshipLabel>Agenda Items</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Meeting_Time_Zone_MERC__c</fullName>
        <formula>text(Meeting_MERC__r.Meeting_Time_Zone_MERC__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Meeting Time Zone</label>
        <type>Text</type>
    </fields>
    <label>Agenda Item</label>
    <nameField>
        <label>Agenda Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agenda Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Meeting_MERC__c.object
<CustomObject>
</CustomObject>

src/classes/MERC_AgendaItemNewEditController.cls
public with sharing class MERC_AgendaItemNewEditController {

	private final Agenda_Item_MERC__c agendaItem;
    ApexPages.StandardController stdController;
    MERC_TimeZoneCalculator tz = new MERC_TimeZoneCalculator('Agenda_Item_MERC__c');

    public MERC_AgendaItemNewEditController(ApexPages.StandardController c) {
        this.agendaItem = (Agenda_Item_MERC__c)c.getRecord();
        this.stdController = c;
    }

    //sets date/times based on meeting time/zone, for UX purposes
    public void setTimeZones() {
        tz.execute(new List<Sobject>{this.agendaItem}, false);
    }

    public Meeting_MERC__c meeting {
        get {
            return [SELECT ID, Name, Meeting_Time_Zone_MERC__C FROM Meeting_MERC__c WHERE ID = :this.agendaItem.Meeting_MERC__c];
        }
    }

    public PageReference save() {
        try {
            tz.execute(new List<Sobject>{this.agendaItem}, true); //sets date/times based on UTC, stamps static text with "user-friendly" date/time values
            if (this.agendaItem.Id == null) {
                insert this.agendaItem;
            } else {
                update this.agendaItem; 
            }
        } catch(Exception e) {
            return null;
        }
        return stdController.view();
    }

    public PageReference cancel() {
        return stdController.view();
    }

}