src/objects/Agenda_Item_MERC__c.object
<CustomObject>
    <description>Used to construct and store Agendas for Meetings to be distributed to HCPs or displayed on the Web Service : MERC : Created on 09/26/2013 by John Adams, Mavens Consulting</description>
    <fields>
        <fullName>Agenda_Item_Description_MERC__c</fullName>
        <description>Provide description for agenda item that will customer facing. Created 11/18/2013 by KLorenti, Mavens Consulting</description>
        <inlineHelpText>Please provide description of this agenda item to be displayed to the customer.</inlineHelpText>
        <label>Agenda Item Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>End_Time_MERC__c</fullName>
        <description>Date and time that session will end
Created by John A Adams 10/8/2013</description>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Meeting_MERC__c</fullName>
        <description>One to Many relationship with Meeting
Created by John A Adams 9/30/2013</description>
        <label>Meeting</label>
        <referenceTo>Meeting_MERC__c</referenceTo>
        <relationshipLabel>Agenda Items</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Session_Type_MERC__c</fullName>
        <description>Tracks type of session to track agenda details. Created 10/08/2013 by KLorenti.</description>
        <label>Session Type</label>
        <picklist>
            <picklistValues>
                <fullName>General Session</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Breakout Session</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Break</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lunch</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Time_MERC__c</fullName>
        <description>Start date and time of session
Created by John A Adams 10/8/2013</description>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Time_in_Meeting_Time_Zone_MERC__c</fullName>
        <description>This field is read-only, stamped by Apex in the time zone of the meeting. -JFerraro Dec 19, 2013</description>
        <label>Start Time (Meeting Time Zone)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Agenda Item</label>
    <nameField>
        <label>Agenda Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agenda Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Meeting_MERC__c.object
<CustomObject>
</CustomObject>

src/classes/MERC_AgendaItemNewEditControllerTest.cls
@isTest
private class MERC_AgendaItemNewEditControllerTest {
	
	static List<Meeting_MERC__c> mtgs;

	static {
		MERC_TestFactory.loadTimeZoneFieldMapSettings();
		mtgs = MERC_TestFactory.insertMeetings(1);
	}

	@isTest static void test_new_edit_form() {
		Meeting_MERC__c mtg = mtgs.get(0);
		Agenda_Item_MERC__c agendaItem = new Agenda_Item_MERC__c();
		agendaItem.Meeting_MERC__c = mtg.Id;

		PageReference agendaItemNewEditPage = Page.MERC_AgendaItemNewEdit;
		Test.setCurrentPage(agendaItemNewEditPage);
		Test.startTest();

		ApexPages.StandardController stdController = new ApexPages.StandardController(agendaItem);
		MERC_AgendaItemNewEditController controller = new MERC_AgendaItemNewEditController(stdController);
		controller.setTimeZones();

		agendaItem.Name = 'foo';
		agendaItem.Agenda_Item_Description_MERC__c = 'foo';
		agendaItem.Session_Type_MERC__c = 'foo';
		agendaItem.Start_Time_MERC__c = Datetime.now();
		agendaItem.End_Time_MERC__c = DateTime.now();

		PageReference p = controller.save();
		system.debug('p is: >>>>>> '+p);
		Test.stopTest();

		system.assertEquals(1, [SELECT count() FROM Agenda_Item_MERC__c WHERE Meeting_MERC__c = :mtg.Id]);
		system.assertNotEquals(null, [SELECT Start_Time_in_Meeting_Time_Zone_MERC__c FROM Agenda_Item_MERC__c WHERE Meeting_MERC__c = :mtg.Id].Start_Time_in_Meeting_Time_Zone_MERC__c);
	}

	@isTest static void test_agenda_builder() {
		Meeting_MERC__c mtg = mtgs.get(0);
		
		PageReference agendaBuilder = Page.MERC_AgendaBuilder;
		agendaBuilder.getParameters().put('id', mtg.Id);

		Test.setCurrentPage(agendaBuilder);

		Test.startTest();

		ApexPages.StandardSetController stdController = new ApexPages.StandardSetController(new List<Agenda_Item_MERC__c>());
		MERC_AgendaBuilderController controller = new MERC_AgendaBuilderController(stdController);
		controller.add();

		system.assertEquals(1, controller.children.size());

		GLBL_GenericRelatedListController.GenericSobjectWrapper sw = controller.children.get(0);
		sw.so.put('Name','foo');
		sw.so.put('Start_Time_MERC__c', DateTime.now());
		sw.so.put('End_Time_MERC__c', DateTime.now());
		controller.save();
		
		Test.stopTest();

		system.assertNotEquals(null, [SELECT Start_Time_in_Meeting_Time_Zone_MERC__c FROM Agenda_Item_MERC__c WHERE Meeting_MERC__c = :mtg.Id].Start_Time_in_Meeting_Time_Zone_MERC__c);
	}
	
}