src/objects/Agenda_Item_MERC__c.object
<CustomObject>
    <description>Used to construct and store Agendas for Meetings to be distributed to HCPs or displayed on the Web Service : MERC : Created on 09/26/2013 by John Adams, Mavens Consulting</description>
    <fields>
        <fullName>Meeting_MERC__c</fullName>
        <description>One to Many relationship with Meeting
Created by John A Adams 9/30/2013</description>
        <label>Meeting</label>
        <referenceTo>Meeting_MERC__c</referenceTo>
        <relationshipLabel>Agenda Items</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Time_MERC__c</fullName>
        <description>Start date and time of session
Created by John A Adams 10/8/2013</description>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <label>Agenda Item</label>
    <nameField>
        <label>Agenda Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agenda Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Meeting_MERC__c.object
<CustomObject>
</CustomObject>

src/classes/MERC_AgendaBuilderController.cls
/**
 * @author Joseph Ferraro
 *
 * Controller for VF Page that enables users to modify Agenda via a unified UI
 */

public with sharing class MERC_AgendaBuilderController extends GLBL_GenericRelatedListController {
	MERC_TimeZoneCalculator tz = new MERC_TimeZoneCalculator('Agenda_Item_MERC__c');

	public MERC_AgendaBuilderController(ApexPages.StandardSetController controller) {
		super (
			controller, 
			'Meeting_MERC__c', 
			'Agenda_Item_MERC__c', 
			'Meeting_MERC__c',
			new List<String> { 
				'Id', 
				'Name'
			},
			MERC_Util.getFieldSetFieldList('Agenda_Item_MERC__c', 'Agenda_Builder_MERC'),
			'Start_Time_MERC__c'
		);
	}

	List<Sobject> getSobjects(List<GLBL_GenericRelatedListController.GenericSobjectWrapper> children) {
		List<Sobject> returnSobjects = new List<Sobject>();
		for (GLBL_GenericRelatedListController.GenericSobjectWrapper c : children) {
			returnSobjects.add(c.so);
		}
		return returnSobjects;
	}

	public PageReference setTimeZones() {
	    tz.execute(getSobjects(children), false); //sets date/times based on meeting time/zone, for UX purposes
	    if (MERC_Util.getUrlParam('notify') == '1') {
	    	ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, MERC_Util.getUrlParam('msg')));
	    }
	    return null;
	}

	public override PageReference save() {
        tz.execute(getSobjects(children), true); //sets date/times based on UTC, stamps static text with "user-friendly" date/time values
		return super.save();
	}
}