src/objects/Budget_MERC__c.object
<CustomObject>
    <fields>
        <fullName>Meeting_MERC__c</fullName>
        <description>Master-Detail relationship from Budget to Meeting. Create 9/30/2012 by KLorenti.</description>
        <label>Meeting</label>
        <referenceTo>Meeting_MERC__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

src/objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>Account_GLBL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Content</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Budget_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship from Content to Budget. Created 01/17/2014 by KLorenti, Mavens Consulting</description>
        <label>Budget</label>
        <referenceTo>Budget_MERC__c</referenceTo>
        <relationshipLabel>Content</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HCP_Contract_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>HCP Contract</label>
        <referenceTo>HCP_Contract_MERC__c</referenceTo>
        <relationshipLabel>Content</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship to Invoice. Created 12/6/2013 by KLorenti, Mavens Consulting</description>
        <label>Invoice</label>
        <referenceTo>Invoice_MERC__c</referenceTo>
        <relationshipLabel>Content</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meeting_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Meeting</label>
        <referenceTo>Meeting_MERC__c</referenceTo>
        <relationshipLabel>Content</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meeting_Participant_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship from Content to Meeting Participant. Created 01/16/2014 by KLorenti, Mavens Consulting</description>
        <label>Meeting Participant</label>
        <referenceTo>Meeting_Participant_MERC__c</referenceTo>
        <relationshipLabel>Content</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Account_MERC</fullName>
        <active>true</active>
        <label>Account_MERC</label>
    </recordTypes>
    <recordTypes>
        <fullName>Budget_MERC</fullName>
        <active>true</active>
        <label>Budget_MERC</label>
    </recordTypes>
    <recordTypes>
        <fullName>HCP_Contract_MERC</fullName>
        <active>true</active>
        <label>HCP_Contract_MERC</label>
    </recordTypes>
    <recordTypes>
        <fullName>Invoice_MERC</fullName>
        <active>true</active>
        <label>Invoice_MERC</label>
    </recordTypes>
    <recordTypes>
        <fullName>Meeting_MERC</fullName>
        <active>true</active>
        <label>Meeting_MERC</label>
    </recordTypes>
    <recordTypes>
        <fullName>Meeting_Participant_MERC</fullName>
        <active>true</active>
        <label>Meeting_Participant_MERC</label>
    </recordTypes>
</CustomObject>

src/objects/HCP_Contract_MERC__c.object
<CustomObject>
    <description>Contains contract details between Lilly and event speakers. 
Created by John A Adams 10/2/2013</description>
    <label>HCP Contract</label>
    <nameField>
        <displayFormat>CNTR-{000000}</displayFormat>
        <label>HCP Contract #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCP Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice_MERC__c.object
<CustomObject>
    <description>Object to store invoice header information, Integrates with SAP for HCP Payments : MERC : Created on 09/27/2013 by Katy Lorenti, Mavens Consulting</description>
    <fields>
        <fullName>Meeting_MERC__c</fullName>
        <description>Lookup of Meeting 
Created by John A Adams 10/30/2013</description>
        <formula>Meeting_Participant_MERC__r.Meeting_MERC__r.Event_Id_MERC__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Meeting</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meeting_Participant_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to find the meeting Participant this invoice is for.
Created by John A Adams 10/4/2013</description>
        <label>Meeting Participant</label>
        <referenceTo>Meeting_Participant_MERC__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <recordTypes>
        <fullName>Invoice_MERC</fullName>
        <active>true</active>
        <description>Used to create Invoice records</description>
        <label>Invoice</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Meeting_MERC__c.object
<CustomObject>
</CustomObject>

src/objects/Meeting_Participant_MERC__c.object
<CustomObject>
</CustomObject>

src/classes/MERC_ContentVersionHandler.cls
/**
 * @author Joseph Ferraro
 *
 * Trigger handler for Salesforce Content DML.
 * -It ensures that the Content RecordTypeId field is set based on the lookup provided
 */

public with sharing class MERC_ContentVersionHandler implements GLBL_TriggerHandler.HandlerInterface {

	public void handle() {
		if (Trigger.isInsert) {
	    	execute(Trigger.new);
	   	}
	}

	public void execute(list<Sobject> sobjects) {        
		Set<String> mercuryContentRecordTypes = new Set<String>{
			'Invoice_MERC', 'Meeting_MERC', 'HCP_Contract_MERC', 'Account_MERC', 'Meeting_Participant_MERC', 'Budget_MERC'
		};
		List<ContentVersion> documents = (List<ContentVersion>)sobjects;
		Map<String, String> objectTypeToContentRecordId = new Map<String, String>();
		for (RecordType recordType : [Select ID, DeveloperName From RecordType Where SobjectType = 'ContentVersion' and DeveloperName IN :mercuryContentRecordTypes]) {
			objectTypeToContentRecordId.put(recordType.DeveloperName, recordType.Id);
		}

		for (ContentVersion d : documents) {
			if (d.HCP_Contract_MERC__c != null) {
				d.RecordTypeId = objectTypeToContentRecordId.get('HCP_Contract_MERC');
			} else if (d.Invoice_MERC__c != null) {
				d.RecordTypeId = objectTypeToContentRecordId.get('Invoice_MERC');
			} else if (d.Meeting_MERC__c != null) {
				d.RecordTypeId = objectTypeToContentRecordId.get('Meeting_MERC');
			} else if (d.Account_GLBL__c != null) {
				d.RecordTypeId = objectTypeToContentRecordId.get('Account_MERC');
			} else if (d.Meeting_Participant_MERC__c != null) {
				d.RecordTypeId = objectTypeToContentRecordId.get('Meeting_Participant_MERC');
			} else if (d.Budget_MERC__c != null) {
				d.RecordTypeId = objectTypeToContentRecordId.get('Budget_MERC');
			}
		}

	}
}