src/objects/Budget_Line_Item_MERC__c.object
<CustomObject>
    <description>Stores Individual Budget Line Items that roll up to the Budget Header for managing Meeting Budgets : MERC : Created on 09/27/2014 by Katy Lorenti, Mavens Consulting</description>
    <fields>
        <fullName>Budget_MERC__c</fullName>
        <description>Master-Detail relationship to Budget Object. Created 9/27/2013 by KLorenti.</description>
        <label>Budget</label>
        <referenceTo>Budget_MERC__c</referenceTo>
        <relationshipLabel>Budget Line Items</relationshipLabel>
        <relationshipName>Budget_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Meeting_Vendor_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship from Budget Line Item to Meeting Vendor. Created 12/6/2013 by KLorenti, Mavens Consulting</description>
        <label>Vendor</label>
        <referenceTo>Meeting_Vendor_MERC__c</referenceTo>
        <relationshipLabel>Budget Line Items</relationshipLabel>
        <relationshipName>Budget_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Budget Line Item</label>
    <nameField>
        <displayFormat>BL-{000000}</displayFormat>
        <label>Budget Line Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Budget_MERC__c.object
<CustomObject>
    <fields>
        <fullName>Meeting_MERC__c</fullName>
        <description>Master-Detail relationship from Budget to Meeting. Create 9/30/2012 by KLorenti.</description>
        <label>Meeting</label>
        <referenceTo>Meeting_MERC__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

src/objects/Daily_Attendance_TOV_MERC__c.object
<CustomObject>
    <description>Junction object between Meeting Days and Meeting Participants, stores a breakdown of Daily ToV which is picked up by the AODS Interface : MERC : Created on 10/10/2013 by John Adams, Mavens Consulting</description>
    <fields>
        <fullName>Confirm_ToV_Reporting_Change_MERC__c</fullName>
        <defaultValue>false</defaultValue>
        <description>HCP Care to confirm the ToV change if it has already been reported.  Created 01/07/2014 by KLorenti, Mavens Consulting</description>
        <label>Confirm ToV Reporting Change</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Meeting_Day_MERC__c</fullName>
        <description>Master Detail relationship from Daily Attendance to Meeting Day. Created 10/10/2013 by KLorenti.</description>
        <label>Meeting Day</label>
        <referenceTo>Meeting_Day_MERC__c</referenceTo>
        <relationshipLabel>Daily Attendance &amp; TOV</relationshipLabel>
        <relationshipName>Daily_Attendance_TOV</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Meeting_Participant_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master Detail relationship from Daily Attendance to Meeting Participant. Created 10/10/2013 by KLorenti.</description>
        <label>Meeting Participant</label>
        <referenceTo>Meeting_Participant_MERC__c</referenceTo>
        <relationshipLabel>Daily Attendance &amp; TOV</relationshipLabel>
        <relationshipName>Daily_Attendance_TOV_MERC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meeting_Vendor_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Meeting Vendor to retrieve Hotel Room Rates
Created by John A Adams 10/10/2013</description>
        <label>Meeting Vendor</label>
        <referenceTo>Meeting_Vendor_MERC__c</referenceTo>
        <relationshipLabel>Daily Attendance &amp; TOV</relationshipLabel>
        <relationshipName>Daily_Attendance_TOV</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Daily Attendance &amp; TOV</label>
    <nameField>
        <displayFormat>DA-{000000}</displayFormat>
        <label>Attendance #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Attendance &amp; TOV</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Hotel_Allocation_MERC__c.object
<CustomObject>
    <description>Used to track which Hotels are utilized for a Meeting Day and track room consumption. Created 12/5/2013 by KLorenti, Mavens Consulting</description>
    <fields>
        <fullName>Meeting_Day_MERC__c</fullName>
        <description>Master Detail Relationship to Meeting Day. Created 12/5/2013 by KLorenti, Mavens Consulting Changed to a Master Detail relationship.  4/2/2014 J Adams</description>
        <label>Meeting Day</label>
        <referenceTo>Meeting_Day_MERC__c</referenceTo>
        <relationshipLabel>Hotel Allocation</relationshipLabel>
        <relationshipName>Hotel_Allocation</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Meeting_Vendor_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup Relationship to Meeting Vendor to associate a Hotel to Hotel Allocation. Created 12/5/2013 by KLorenti, Mavens Consulting</description>
        <label>Meeting Vendor</label>
        <referenceTo>Meeting_Vendor_MERC__c</referenceTo>
        <relationshipLabel>Hotel Allocation</relationshipLabel>
        <relationshipName>Hotel_Allocations_MERC</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Hotel Allocation</label>
    <nameField>
        <displayFormat>H-{000000}</displayFormat>
        <label>Hotel Allocation #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotel Allocation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Meeting_Day_MERC__c.object
<CustomObject>
    <description>Object to track days of meetings and ToV cost of each day. Created 10/10/2013 by KLorenti.</description>
    <fields>
        <fullName>Confirm_ToV_Reporting_Change_MERC__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Validation checkbox for HCP Care to confirm that the ToV is being updated/corrected. Created 01/07/2014 by KLorenti, Mavens Consulting</description>
        <label>Confirm ToV Reporting Change</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Meeting_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship to Meeting. Created 10/10/2013 by KLorenti</description>
        <label>Meeting</label>
        <referenceTo>Meeting_MERC__c</referenceTo>
        <relationshipLabel>Meeting Days</relationshipLabel>
        <relationshipName>Meeting_Days</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Meeting Day</label>
    <nameField>
        <label>Meeting Day</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Meeting_MERC__c.object
<CustomObject>
</CustomObject>

src/objects/Meeting_Participant_MERC__c.object
<CustomObject>
</CustomObject>

src/objects/Meeting_Vendor_MERC__c.object
<CustomObject>
</CustomObject>

src/objects/Travel_Itinerary_MERC__c.object
<CustomObject>
</CustomObject>

src/classes/MERC_MeetingCurrencyUpdateHandler.cls
/**
 * @author Kyle Thornton
 *
 * this trigger handler processes currency changes to a meeting by propagating the change down to the child
 * Meeting Participant, Meeting Day, Daily TOV, budget, budget line item and Hotel Allocation records.
 */

public with sharing class MERC_MeetingCurrencyUpdateHandler implements GLBL_TriggerHandler.HandlerInterface
{

	public Boolean isActive()
	{
		return MERC_TriggerHandlerStateManager.isActive(MERC_MeetingCurrencyUpdateHandler.class);
	}

	public void handle()
	{
		Set<Id> meetingIdsWithCurrencyChange = new Set<Id>();
		for (Meeting_MERC__c meeting : (List<Meeting_MERC__c>)Trigger.new)
		{
			if (meeting.CurrencyIsoCode != Trigger.oldMap.get(meeting.Id).get('CurrencyIsoCode'))
			{
				meetingIdsWithCurrencyChange.add(meeting.Id);
			}
		}

		List<Meeting_MERC__c> meetingsToProcess = [SELECT Id, CurrencyIsoCode,
		                                                      (SELECT Id, CurrencyIsoCode, Confirm_ToV_Reporting_Change_MERC__c FROM Meeting_Participants_del__r),
		                                                      (SELECT Id, CurrencyIsoCode, Confirm_ToV_Reporting_Change_MERC__c FROM Meeting_Days__r),
		                                                      (SELECT Id, CurrencyIsoCode FROM Budgets__r),
		                                                      (SELECT Id, CurrencyIsoCode, Confirm_ToV_Reporting_Change_MERC__c FROM Meeting_Vendors__r)
		                                                 FROM Meeting_MERC__c
		                                                WHERE Id IN :meetingIdsWithCurrencyChange];

		List<Meeting_Participant_MERC__c> participantsToUpdate = new List<Meeting_Participant_MERC__c>();
		List<Meeting_Day_MERC__c> meetingDaysToUpdate = new List<Meeting_Day_MERC__c>();
		List<Budget_MERC__c> budgetsToUpdate = new List<Budget_MERC__c>();
		List<Meeting_Vendor_MERC__c> vendorsToUpdate = new List<Meeting_Vendor_MERC__c>();



		for (Meeting_MERC__c meeting : meetingsToProcess)
		{
			for (Meeting_Participant_MERC__c participant : meeting.Meeting_Participants_del__r)
			{
				participant.CurrencyIsoCode = meeting.CurrencyIsoCode;
				participant.Confirm_ToV_Reporting_Change_MERC__c = true;
				participantsToUpdate.add(participant);
			}

			for (Meeting_Day_MERC__c meetingDay : meeting.Meeting_Days__r)
			{
				meetingDay.CurrencyIsoCode = meeting.CurrencyIsoCode;
				meetingDay.Confirm_ToV_Reporting_Change_MERC__c = true;
				meetingDaysToUpdate.add(meetingDay);
			}

			for (Budget_MERC__c budget : meeting.Budgets__r)
			{
				budget.CurrencyIsoCode = meeting.CurrencyIsoCode;
				budgetsToUpdate.add(budget);
			}

			for (Meeting_Vendor_MERC__c vendor : meeting.Meeting_Vendors__r)
			{
				vendor.CurrencyIsoCode = meeting.CurrencyIsoCode;
				vendor.Confirm_ToV_Reporting_Change_MERC__c = true;
				vendorsToUpdate.add(vendor);
			}
		}

		List<Travel_Itinerary_MERC__c> itinerariesToUpdate = new List<Travel_Itinerary_MERC__c>();
		for (Travel_Itinerary_MERC__c itinerary : [SELECT Id, CurrencyIsoCode, Meeting_Participant_MERC__r.Meeting_MERC__r.CurrencyIsoCode, Confirm_ToV_Reporting_Change_MERC__c
			                                         FROM Travel_Itinerary_MERC__c
			                                        WHERE Meeting_Participant_MERC__c IN :participantsToUpdate])
		{
			itinerary.CurrencyIsoCode = itinerary.Meeting_Participant_MERC__r.Meeting_MERC__r.CurrencyIsoCode;
			itinerary.Confirm_ToV_Reporting_Change_MERC__c = true;
			itinerariesToUpdate.add(itinerary);
		}

		List<Daily_Attendance_TOV_MERC__c> tovsToUpdate = new List<Daily_Attendance_TOV_MERC__c>();
		for (Daily_Attendance_TOV_MERC__c tov : [SELECT Id, CurrencyIsoCode, Meeting_Day_MERC__r.Meeting_MERC__r.CurrencyIsoCode, Confirm_ToV_Reporting_Change_MERC__c
			                                       FROM Daily_Attendance_TOV_MERC__c
			                                      WHERE Meeting_Day_MERC__c IN :meetingDaysToUpdate])
		{
			tov.CurrencyIsoCode = tov.Meeting_Day_MERC__r.Meeting_MERC__r.CurrencyIsoCode;
			tov.Confirm_ToV_Reporting_Change_MERC__c = true;
			tovsToUpdate.add(tov);
		}

		List<Hotel_Allocation_MERC__c> allocationsToUpdate = new List<Hotel_Allocation_MERC__c>();
		for (Hotel_Allocation_MERC__c allocation : [SELECT Id, CurrencyIsoCode, Meeting_Day_MERC__r.Meeting_MERC__r.CurrencyIsoCode FROM Hotel_Allocation_MERC__c WHERE Meeting_Day_MERC__c IN :meetingDaysToUpdate])
		{
			allocation.CurrencyIsoCode = allocation.Meeting_Day_MERC__r.Meeting_MERC__r.CurrencyIsoCode;
			allocationsToUpdate.add(allocation);
		}

		List<Budget_Line_Item_MERC__c> budgetLineItemsToUpdate = new List<Budget_Line_Item_MERC__c>();
		for (Budget_Line_Item_MERC__c bli : [SELECT Id, CurrencyIsoCode, Budget_MERC__r.Meeting_Merc__r.CurrencyIsoCode FROM Budget_Line_Item_MERC__c WHERE Budget_MERC__c IN :budgetsToUpdate])
		{
			bli.CurrencyIsoCode = bli.Budget_MERC__r.Meeting_Merc__r.CurrencyIsoCode;
			budgetLineItemsToUpdate.add(bli);
		}

		List<SObject> objectsToUpdate = new List<SObject>();
		objectsToUpdate.addAll((List<SObject>)participantsToUpdate);
		objectsToUpdate.addAll((List<SObject>)meetingDaysToUpdate);
		objectsToUpdate.addAll((List<SObject>)budgetsToUpdate);
		objectsToUpdate.addAll((List<SObject>)budgetLineItemsToUpdate);
		objectsToUpdate.addAll((List<SObject>)tovsToUpdate);
		objectsToUpdate.addAll((List<SObject>)vendorsToUpdate);
		objectsToUpdate.addAll((List<SObject>)allocationsToUpdate);
		objectsToUpdate.addAll((List<SObject>)itinerariesToUpdate);
		try
		{
			update objectsToUpdate;
		}
		catch (System.DMLException ex)
		{
			ApexPages.addMessages(ex);
		}
	}
}