src/objects/Budget_MERC__c.object
<CustomObject>
    <fields>
        <fullName>Meeting_MERC__c</fullName>
        <description>Master-Detail relationship from Budget to Meeting. Create 9/30/2012 by KLorenti.</description>
        <label>Meeting</label>
        <referenceTo>Meeting_MERC__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

src/objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>Account_GLBL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Content</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Budget_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship from Content to Budget. Created 01/17/2014 by KLorenti, Mavens Consulting</description>
        <label>Budget</label>
        <referenceTo>Budget_MERC__c</referenceTo>
        <relationshipLabel>Content</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_of_Residence_MERC__c</fullName>
        <description>Capture Country of Residence for HCP. Created 12/3/2013 by KLorenti, Mavens Consulting</description>
        <formula>TEXT(HCP_Contract_MERC__r.Account_MERC__r.Country_of_Residence_GLBL__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country of Residence</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Type_MERC__c</fullName>
        <description>Created to capture types of Documents uploaded. Created 12/2/2013 by KLorenti, Mavens Consulting</description>
        <label>Document Type</label>
        <picklist>
            <picklistValues>
                <fullName>Institutional Notification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Notification agreement for services (filled version by HCP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Notification agreement for sponsorship (filled version by HCP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FMV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HCP Transparency Reporting Consent (filled version by HCP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting Minutes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invitations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting Documents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registration Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Slide Kits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approvals and Supporting Documents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cover Letter for Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Event Contract and Appendices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C2P Documents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MSA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Services Rendered Documents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial Payment Justification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expense Reimbursement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MPC Budget and Invoices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agendas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HCP Exceptions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoice Exceptions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Exceptions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certificate of Attendance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting Participant Notice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registration Confirmation Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship Agreement</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>HCP_Contract_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>HCP Contract</label>
        <referenceTo>HCP_Contract_MERC__c</referenceTo>
        <relationshipLabel>Content</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship to Invoice. Created 12/6/2013 by KLorenti, Mavens Consulting</description>
        <label>Invoice</label>
        <referenceTo>Invoice_MERC__c</referenceTo>
        <relationshipLabel>Content</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meeting_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Meeting</label>
        <referenceTo>Meeting_MERC__c</referenceTo>
        <relationshipLabel>Content</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meeting_Participant_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship from Content to Meeting Participant. Created 01/16/2014 by KLorenti, Mavens Consulting</description>
        <label>Meeting Participant</label>
        <referenceTo>Meeting_Participant_MERC__c</referenceTo>
        <relationshipLabel>Content</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Account_MERC</fullName>
        <active>true</active>
        <label>Account_MERC</label>
    </recordTypes>
    <recordTypes>
        <fullName>Budget_MERC</fullName>
        <active>true</active>
        <label>Budget_MERC</label>
    </recordTypes>
    <recordTypes>
        <fullName>HCP_Contract_MERC</fullName>
        <active>true</active>
        <label>HCP_Contract_MERC</label>
    </recordTypes>
    <recordTypes>
        <fullName>Invoice_MERC</fullName>
        <active>true</active>
        <label>Invoice_MERC</label>
    </recordTypes>
    <recordTypes>
        <fullName>Meeting_MERC</fullName>
        <active>true</active>
        <label>Meeting_MERC</label>
    </recordTypes>
    <recordTypes>
        <fullName>Meeting_Participant_MERC</fullName>
        <active>true</active>
        <label>Meeting_Participant_MERC</label>
    </recordTypes>
</CustomObject>

src/objects/Invoice_MERC__c.object
<CustomObject>
    <description>Object to store invoice header information, Integrates with SAP for HCP Payments : MERC : Created on 09/27/2013 by Katy Lorenti, Mavens Consulting</description>
    <fields>
        <fullName>Meeting_MERC__c</fullName>
        <description>Lookup of Meeting 
Created by John A Adams 10/30/2013</description>
        <formula>Meeting_Participant_MERC__r.Meeting_MERC__r.Event_Id_MERC__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Meeting</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meeting_Participant_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to find the meeting Participant this invoice is for.
Created by John A Adams 10/4/2013</description>
        <label>Meeting Participant</label>
        <referenceTo>Meeting_Participant_MERC__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <recordTypes>
        <fullName>Invoice_MERC</fullName>
        <active>true</active>
        <description>Used to create Invoice records</description>
        <label>Invoice</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Mercury_Settings_MERC__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Custom Settings for the Mercury Project mostly related to the operation of the Customer Search Tool, Veeva integration, Budget and Invoice processing.</description>
    <fields>
        <fullName>Invoice_File_Prefix_MERC__c</fullName>
        <defaultValue>&quot;MercuryInvoice-&quot;</defaultValue>
        <description>Determines the prefix of file names sent for processing. This value is expected &amp; used by the Informatica &amp; SAP integrations.</description>
        <inlineHelpText>Determines the prefix of file names sent for processing. Used by the Informatica &amp; SAP integrations.</inlineHelpText>
        <label>Invoice File Prefix</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Mercury Settings</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Procurement_Library_MERC__c</fullName>
        <description>Used only for MPC users.  This defines the MPC&apos;s company that the user works for and therefore which Content Library the Invoices (associated to Budgets) are assigned to.  Creates a firewall between MPCs and Procurement Invoices within Country.  Oliver Dunford 9th June 2014.</description>
        <inlineHelpText>Populated only for MPC users.  This defines the MPC&apos;s company that the user works for and therefore which Content Library the Invoices (associated to Budgets) are assigned to.</inlineHelpText>
        <label>Procurement Library</label>
        <picklist>
            <picklistValues>
                <fullName>Procurement 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Procurement 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Procurement 3</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/MERC_NewContentController.cls
/**
 * @author Joseph Ferraro
 *
 * Controller that enables users to upload documents to Salesforce Content and associate with Mercury objects
 */

public with sharing class MERC_NewContentController {

	private final sObject mysObject;
    private final ApexPages.StandardController stdController;
    private Id recordId;
    public ContentVersion file { get; set; }
    public String sobjectAPIName { get; private set; }
    public String fieldSetAPIName  { get; private set; }
    public Boolean successfulUpload { get; private set; }

    public MERC_NewContentController() {
        this.recordId = (Id)ApexPages.currentPage().getParameters().get('id');
        String objectAPIName = this.recordId.getSObjectType().getDescribe().getName();
        this.mysObject = Database.query('Select Id, Name From '+objectAPIName+' WHERE Id = \''+this.recordId+'\'');
        this.stdController = new ApexPages.StandardController(this.mysObject);
        this.file = new ContentVersion();
        this.successfulUpload = false;
        setContentDefaults();
    }

    public PageReference cancel() {
        return new PageReference('/'+(String)this.mysObject.get('Id'));
    }

    public String getsObjectName() {
        return (String)this.mysObject.get('Name');
    }

    public void setContentDefaults() {
        //set to mercury library (replaced by getLibraryId)
        //try {
        //    this.file.FirstPublishLocationId = [select Id from ContentWorkspace WHERE Name = 'Mercury'].Id;
        //} catch(Exception e) {
        //    throw new MERC_Exception('Insufficient access to the Mercury Content Workspace. Please contact your system administrator.');
        //}

        //set record type and lookup(s)
        this.recordId = (Id)this.mysObject.get('Id');
        String objectAPIName = this.recordId.getSObjectType().getDescribe().getName();
        this.sobjectAPIName = objectAPIName;

        if (objectAPIName == 'Meeting_MERC__c') {
            this.file.Meeting_MERC__c = this.recordId;
            this.file.RecordTypeId = [Select Id From RecordType WHERE DeveloperName = 'Meeting_MERC' AND SobjectType = 'ContentVersion' LIMIT 1].Id;
            this.fieldSetAPIName = 'Meeting_MERC';
        } else if (objectAPIName == 'HCP_Contract_MERC__c') {
            this.file.HCP_Contract_MERC__c = this.recordId;
            this.file.RecordTypeId = [Select Id From RecordType WHERE DeveloperName = 'HCP_Contract_MERC' AND SobjectType = 'ContentVersion' LIMIT 1].Id;
            this.fieldSetAPIName = 'HCP_Contract_MERC';
        } else if (objectAPIName == 'Invoice_MERC__c') {
            this.file.Invoice_MERC__c = this.recordId;
            this.file.RecordTypeId = [Select Id From RecordType WHERE DeveloperName = 'Invoice_MERC' AND SobjectType = 'ContentVersion' LIMIT 1].Id;
            this.fieldSetAPIName = 'Invoice_MERC';
            if (ApexPages.currentPage().getParameters().containsKey('tif') && ApexPages.currentPage().getParameters().get('tif') == '1') {
                this.file.Title = Mercury_Settings_MERC__c.getOrgDefaults().Invoice_File_Prefix_MERC__c + String.valueOf(this.recordId) + '.tif';
                this.file.Document_Type_MERC__c = 'Invoices';
                MERC_InvoiceDocFilterController.deleteOldDocsInContent(new List<Id>{this.recordId},'TIFF');
            }
            if (ApexPages.currentPage().getParameters().containsKey('pdf') && ApexPages.currentPage().getParameters().get('pdf') == '1') {
                this.file.Title = Mercury_Settings_MERC__c.getOrgDefaults().Invoice_File_Prefix_MERC__c + String.valueOf(this.recordId) + '.pdf';
                this.file.Document_Type_MERC__c = 'Invoices';
                MERC_InvoiceDocFilterController.deleteOldDocsInContent(new List<Id>{this.recordId},'PDF');
            }
        } else if (objectAPIName == 'Account') {
            this.file.Account_GLBL__c = this.recordId;
            this.file.RecordTypeId = [Select Id From RecordType WHERE DeveloperName = 'Account_MERC' AND SobjectType = 'ContentVersion' LIMIT 1].Id;
            this.fieldSetAPIName = 'Account_MERC';
        } else if (objectAPIName == 'Meeting_Participant_MERC__c') {
            this.file.Meeting_Participant_MERC__c = this.recordId;
            this.file.RecordTypeId = [Select Id From RecordType WHERE DeveloperName = 'Meeting_Participant_MERC' AND SobjectType = 'ContentVersion' LIMIT 1].Id;
            this.fieldSetAPIName = 'Meeting_Participant_MERC';
        } else if (objectAPIName == 'Budget_MERC__c') {
            this.file.Budget_MERC__c = this.recordId;
            this.file.RecordTypeId = [Select Id From RecordType WHERE DeveloperName = 'Budget_MERC' AND SobjectType = 'ContentVersion' LIMIT 1].Id;
            this.fieldSetAPIName = 'Budget_MERC';
        }
    }

    @TestVisible
    Id getLibraryId(String objectAPIName) {
        String libraryName;
        String country;
        String suffix;
        String recTypeName;

        try {
            if (objectAPIName == 'Budget_MERC__c') {
                country = [SELECT Meeting_MERC__r.Event_Country_MERC__c FROM Budget_MERC__c WHERE Id = :recordId].Meeting_MERC__r.Event_Country_MERC__c;
                suffix  = [SELECT Procurement_Library_MERC__c FROM User WHERE Id=:UserInfo.getUserId()].Procurement_Library_MERC__c;
                if (suffix == null) {
                    libraryName = country + ' - Regional';
                } else {
                    libraryName = country + ' - ' + suffix;
                }
            } else {
                if (objectAPIName == 'Meeting_MERC__c') {
                    country = [SELECT Event_Country_MERC__c FROM Meeting_MERC__c WHERE Id = :recordId].Event_Country_MERC__c;
                    recTypeName = 'Meeting_MERC';
                } else if (objectAPIName == 'HCP_Contract_MERC__c') {
                    country = [SELECT Country_of_Residence_MERC__c FROM HCP_Contract_MERC__c WHERE Id = :recordId].Country_of_Residence_MERC__c;
                    recTypeName = 'HCP_Contract_MERC';
                } else if (objectAPIName == 'Invoice_MERC__c') {
                    Invoice_MERC__c invoice = [SELECT Meeting_Participant_MERC__r.Country_of_Residence_MERC__c FROM Invoice_MERC__c WHERE Id = :recordId];
                    if (invoice.Meeting_Participant_MERC__r.Country_of_Residence_MERC__c != null)
                    {
                        country = invoice.Meeting_Participant_MERC__r.Country_of_Residence_MERC__c;
                        recTypeName = 'Invoice_MERC';
                    }
                } else if (objectAPIName == 'Meeting_Participant_MERC__c') {
                    country = [SELECT Country_of_Residence_MERC__c FROM Meeting_Participant_MERC__c WHERE Id = :recordId].Country_of_Residence_MERC__c;
                    recTypeName='Meeting_Participant_MERC';
                } else if (objectAPIName == 'Account') {
                    country = [SELECT Country_of_Residence_GLBL__c FROM Account WHERE Id = :recordId].Country_of_Residence_GLBL__c;
                    recTypeName = 'Account_MERC';
                }

                suffix  = [SELECT Library_String_MERC__c
                             FROM Content_Library_Lookup_MERC__c
                            WHERE Content_Record_Type_MERC__c=:recTypeName
                              AND Content_Document_Type_MERC__c=:file.Document_Type_MERC__c].Library_String_MERC__c;
                libraryName = country + ' - ' + suffix;
            }

        } catch(Exception e) {

            throw new MERC_Exception('Unable to determine the proper content library.<br/><br/>Error: '+e.getMessage());
        }

        if (country == null) {
            throw new MERC_Exception('Unable to determine the appropriate content library because the country has not been set properly for '+getsObjectName()+' ('+objectAPIName+')');
        }

        Id contentLibraryId;
        try {
            contentLibraryId = [select Id from ContentWorkspace WHERE Name = :libraryName].Id;
        } catch(System.QueryException e) {
            if (e.getMessage().contains('List has no rows for assignment to SObject')) {
                String defaultLibrary = country + ' - Regional';
                try {
                    contentLibraryId = [select Id from ContentWorkspace WHERE Name = :defaultLibrary].Id;
                    ApexPages.addMessage(
                        new ApexPages.Message(ApexPages.Severity.WARNING,
                                                'You do not have permission to upload the document to the Library ' + libraryName
                                                + '. The document has been uploaded to the ' + defaultLibrary
                                                + ' Library. Please contact CMS Cork who can ensure your access is granted and the document is assigned to the correct Library.'));
                } catch (System.QueryException ex) {
                    throw new MERC_Exception('Unable to locate content library with the name: "'+libraryName+'" or "'+ defaultLibrary
                                             +'." They either do not exist or you are not a member of them. Please contact your system administrator.<br/><br/>'
                                             + 'Error: ' + ex.getMessage());
                }
            } else {
                throw e;
            }
        }

        if (suffix == null && objectAPIName == 'Budget_MERC__c') {
            ApexPages.addMessage( new ApexPages.Message(ApexPages.Severity.INFO, 'You have not been granted access to a Procurement Library to upload document against a Budget. This document will be uploaded to: ' + libraryName + '. Please contact a system administrator for assistance with Library access.'));
        }

        return contentLibraryId;
    }

    public PageReference reloadPage() {
        return ApexPages.currentPage();
    }

    public PageReference upload() {
        if (this.file.versionData == null) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Please select a document to upload.'));
            return null;
        }

        if (this.file.versionData.size() == 0) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'The document you have selected to upload contains no data.'));
            return null;
        }

        try {
            this.file.FirstPublishLocationId = getLibraryId(this.sobjectAPIName);
            //for the SAP integration the file needs to be named just right.
            if (sObjectAPIName == 'Invoice_MERC__c') {
                String fileName = Mercury_Settings_MERC__c.getOrgDefaults().Invoice_File_Prefix_MERC__c + String.valueOf(this.recordId);
                if (ApexPages.currentPage().getParameters().containsKey('tif') && ApexPages.currentPage().getParameters().get('tif') == '1') {
                    this.file.PathOnClient =  fileName + '.tif';
                } else if (ApexPages.currentPage().getParameters().containsKey('pdf') && ApexPages.currentPage().getParameters().get('pdf') == '1') {
                    this.file.PathOnClient =  fileName + '.pdf';
                }
            }
            System.debug(this.file);
            insert this.file;
        } catch (Exception e) {
            this.file.versionData = null;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, e.getMessage()));
            return null;
        }

        successfulUpload = true;
        if (ApexPages.getMessages().isEmpty()) {
            return this.stdController.view();
        } else {
            return null;
        }
    }

    // UNUSED CONSTRUCTOR
    // public MERC_NewContentController(ApexPages.StandardController stdController) {
    //     this.stdController = stdController;
    //     if (!Test.isRunningTest()) {
    //         this.stdController.addFields(new List<String>{ 'Id', 'Name' });
    //     }
    //     this.mysObject = (sObject)stdController.getRecord();
    //     this.file = new ContentVersion();
    //     setContentDefaults();
    // }
}