src/objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>Customer_Id_MERC__c</fullName>
        <description>Pull in Customer ID for HCP that document will be attached to. Created 12/6/2013 by KLorenti, Mavens Consulting</description>
        <formula>Account_GLBL__r.Cust_Id_GLBL__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship to Invoice. Created 12/6/2013 by KLorenti, Mavens Consulting</description>
        <label>Invoice</label>
        <referenceTo>Invoice_MERC__c</referenceTo>
        <relationshipLabel>Content</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meeting_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Meeting</label>
        <referenceTo>Meeting_MERC__c</referenceTo>
        <relationshipLabel>Content</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Invoice_Line_Item_MERC__c.object
<CustomObject>
    <description>Object to store invoice line item information. Created on 9/28/2013 by KLorenti</description>
    <fields>
        <fullName>Amount_MERC__c</fullName>
        <description>Amount of Line Item
Created by John A Adams 10/31/2013</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description_MERC__c</fullName>
        <description>Line Item Description
Created by John A Adams 10/4/2013</description>
        <label>Description</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Cost_Center_MERC__c</fullName>
        <formula>Invoice_MERC__r.Cost_Center_MERC__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Invoice Cost Center</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_MERC__c</fullName>
        <description>Master-Detail relationship to Invoice object. Created 9/28/2013 by KLorenti</description>
        <label>Invoice</label>
        <referenceTo>Invoice_MERC__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity_MERC__c</fullName>
        <description>Quantity of line items
Created by John A Adams 10/27/2013</description>
        <label>Quantity</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tax_Amount_MERC__c</fullName>
        <description>Tax Amount (currency, calc based on value &amp; tax rate) 
Created by John A Adams 10/4/2013</description>
        <formula>Amount_MERC__c *(VAT_Rate_MERC__c / 100) + Unit_Price_MERC__c *( VAT_Rate_MERC__c /100)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tax Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_Price_MERC__c</fullName>
        <description>Unit Price of Line Items.
Created by John A Adams 10/27/2013</description>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>VAT_Rate_MERC__c</fullName>
        <description>Tax Rate Percentage
Created by John A Adams 10/4/2013</description>
        <label>VAT Rate %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>IL-{000000}</displayFormat>
        <label>Invoice Line Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice_MERC__c.object
<CustomObject>
    <description>Object to store invoice header information, Integrates with SAP for HCP Payments : MERC : Created on 09/27/2013 by Katy Lorenti, Mavens Consulting</description>
    <fields>
        <fullName>Customer_Id_MERC__c</fullName>
        <description>Customer Id of Beneficiary.  If this this is the HCO, then the HCO Customer Id is populated, otherwise it&apos;s the meeting Participant.   Oliver Dunford 4th Dec 2013</description>
        <formula>IF( OR(ISNULL(HCO_Beneficiary_MERC__c),ISBLANK(HCO_Beneficiary_MERC__c)) ,  Meeting_Participant_MERC__r.Account_MERC__r.Cust_Id_GLBL__c ,  HCO_Beneficiary_MERC__r.Cust_Id_GLBL__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Date_MERC__c</fullName>
        <description>Date Invoice is issued.
Created by John A Adams 10/20/2013</description>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Meeting_MERC__c</fullName>
        <description>Lookup of Meeting 
Created by John A Adams 10/30/2013</description>
        <formula>Meeting_Participant_MERC__r.Meeting_MERC__r.Event_Id_MERC__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Meeting</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mercury_Transaction_Id_MERC__c</fullName>
        <description>Mercury Transaction Id - copy of Invoice SFDC Record ID
Created by John A Adams 10/30/2013</description>
        <formula>CASESAFEID(Id)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mercury Transaction Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Purpose_of_Payment_MERC__c</fullName>
        <description>The purpose of the payment
Created by John A Adams 10/30/2013</description>
        <formula>If ( Meeting_Participant_MERC__r.RecordType.Name = &quot;Service Provider&quot; || Meeting_Participant_MERC__r.RecordType.Name = &quot;Consulting&quot;,
TEXT(Meeting_Participant_MERC__r.Types_of_Service_MERC__c)  &amp; &quot;-&quot; &amp;
TEXT(DAY(DATEVALUE( Meeting_Participant_MERC__r.Meeting_MERC__r.Start_Time_of_Meeting_MERC__c  ))) &amp;
TEXT(MONTH(DATEVALUE(Meeting_Participant_MERC__r.Meeting_MERC__r.Start_Time_of_Meeting_MERC__c  ))) &amp; 
TEXT(YEAR(DATEVALUE(Meeting_Participant_MERC__r.Meeting_MERC__r.Start_Time_of_Meeting_MERC__c ))) &amp;  &quot;-&quot; &amp; Meeting_Participant_MERC__r.Meeting_MERC__r.City_of_Meeting_MERC__c, 

TEXT(Meeting_Participant_MERC__r.Purpose_of_Payment_MERC__c)  &amp; &quot;-&quot; &amp;
TEXT(DAY(DATEVALUE(Meeting_Participant_MERC__r.Meeting_MERC__r.Start_Time_of_Meeting_MERC__c  ))) &amp;
TEXT(MONTH(DATEVALUE(Meeting_Participant_MERC__r.Meeting_MERC__r.Start_Time_of_Meeting_MERC__c  ))) &amp; 
TEXT(YEAR(DATEVALUE(Meeting_Participant_MERC__r.Meeting_MERC__r.Start_Time_of_Meeting_MERC__c ))) &amp;  
&quot;-&quot; &amp; Meeting_Participant_MERC__r.Meeting_MERC__r.City_of_Meeting_MERC__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Purpose of Payment</label>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Meeting_MERC__c.object
<CustomObject>
</CustomObject>

src/classes/MERC_InvoiceXmlController.cls
public with sharing class MERC_InvoiceXmlController {
	
	public Invoice_MERC__c invoice { get; private set; }
	public String now { get{return Datetime.now().format('dd.MM.yyyy');}}
	public String invoiceDate { get { if (invoiceDate == null) return Datetime.now().format('dd.MM.yyyy'); else return invoiceDate; } set; }

	public MERC_InvoiceXmlController(ApexPages.StandardController controller) {
		List<String> fieldNames = new List<String>();
		fieldNames.add('Purpose_of_Payment_MERC__c');
		fieldNames.add('Customer_Id_MERC__c');
		fieldNames.add('Meeting_MERC__c');
		fieldNames.add('Invoice_Date_MERC__c');
        fieldNames.add('Mercury_Transaction_Id_MERC__c');
		if (!Test.isRunningTest()) controller.addFields(fieldNames);
		this.invoice = (Invoice_MERC__c)controller.getRecord();
		
		Datetime dt = Datetime.newInstance(invoice.Invoice_Date_MERC__c, Time.newInstance(1,1,1,1));
		this.invoiceDate = dt.format('dd.MM.yyyy');
	}

	public List<InvoiceLineWrapper> invoiceLines {
		get {
			if (invoiceLines == null) {
				invoiceLines = new List<InvoiceLineWrapper>();
				Integer i = 1;
				for (Invoice_Line_Item_MERC__c lineItem : [Select 
						Name, 
						Quantity_MERC__c,
						Unit_Price_MERC__c,
						Amount_MERC__c,
						Description_MERC__c,
						VAT_Rate_MERC__c,
						Tax_Amount_MERC__c,
						Cost_Element_SAP_Code_MERC__c,
						Invoice_Cost_Center_MERC__c FROM Invoice_Line_Item_MERC__c WHERE Invoice_MERC__c = :this.invoice.Id]) {
					invoiceLines.add(new InvoiceLineWrapper(lineItem, i));
					i++;
				}	
			}
			return invoiceLines; 
		}
		private set;
	}

	public class InvoiceLineWrapper {
		public Integer position { get; private set; }
		public Invoice_Line_Item_MERC__c lineItem { get; private set; }
		public InvoiceLineWrapper(Invoice_Line_Item_MERC__c li, Integer p) {
			this.lineItem = li;
			this.position = p;
		}
	}
	
	public String cdataLines { 
		get {
			if (cdataLines == null) {
				String purpose = (invoice.Purpose_of_Payment_MERC__c != null) ? invoice.Purpose_of_Payment_MERC__c : '';
				String custId = (invoice.Customer_Id_MERC__c != null) ? invoice.Customer_Id_MERC__c : '';
				String meeting = (invoice.Meeting_MERC__c != null) ? invoice.Meeting_MERC__c : '';
				
				cdataLines = '<![CDATA[ <Sideinfo>' +
				'<SINFOINPUTTYPE>ZD_MERCURY</SINFOINPUTTYPE>' +
				'<SINFOPAYMENT>*'+purpose.escapeXml()+'</SINFOPAYMENT>' +
				'<SINFOCUSTID>'+custId.escapeXml()+'</SINFOCUSTID>' +
				'<SINFOTRANSACTID>'+invoice.Mercury_Transaction_Id_MERC__c+'</SINFOTRANSACTID>' +
				'<SINFOMEETID>'+meeting.escapeXml()+'</SINFOMEETID>' +
				'</Sideinfo> ]]>';
				
			}
			return cdataLines;
		}
		private set;
	}

	public String scannedTifSection { 
		get {
			if (scannedTifSection == null) {
				// See if TIF file is attached
				List<ContentVersion> tifObj = [SELECT ContentDocumentId From ContentVersion WHERE Invoice_MERC__c = :invoice.Id AND FileType = 'TIFF' LIMIT 1];
				if (tifObj != null && !tifObj.isEmpty()) {
					// write out XML				
					scannedTifSection = '<ArchiveFile><ID /><EXTID>'+invoice.Mercury_Transaction_Id_MERC__c+'</EXTID><SYSTEM_ID />'+
	    			'<SYSTEM_NAME /><STATUS /><ARCID /><SAPID /><FILENAME>'+invoice.Mercury_Transaction_Id_MERC__c+'.TIF</FILENAME>'+
	    			'<DOKTYP>TIF</DOKTYP></ArchiveFile>';
				}
			}
			return scannedTifSection;
		}
		private set;
	}	
}