src/objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>Meeting_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Meeting</label>
        <referenceTo>Meeting_MERC__c</referenceTo>
        <relationshipLabel>Content</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_1_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product 1</label>
        <referenceTo>Product_Group_GLBL__c</referenceTo>
        <relationshipLabel>Content (Product 1)</relationshipLabel>
        <relationshipName>Content1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_2_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product 2</label>
        <referenceTo>Product_Group_GLBL__c</referenceTo>
        <relationshipLabel>Content (Product 2)</relationshipLabel>
        <relationshipName>Content2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_3_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product 3</label>
        <referenceTo>Product_Group_GLBL__c</referenceTo>
        <relationshipLabel>Content (Product 3)</relationshipLabel>
        <relationshipName>Content3</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Meeting_MERC</fullName>
        <active>true</active>
        <label>Meeting_MERC</label>
    </recordTypes>
</CustomObject>

src/objects/Meeting_MERC__c.object
<CustomObject>
</CustomObject>

src/objects/Meeting_Products_MERC__c.object
<CustomObject>
    <description>Junction object to create many-to-many relationship between Meetings and Products. Created 10/4/2013 by KLorenti.</description>
    <fields>
        <fullName>Meeting_MERC__c</fullName>
        <description>Master Detail Relationship between Products and Meeting. Created 10/4/2013 by KLorenti.</description>
        <label>Meeting</label>
        <referenceTo>Meeting_MERC__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Meeting_Products</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_MERC__c</fullName>
        <description>Master-Detail from Meeting to Product. Created 10/4/2013 by KLorenti.</description>
        <label>Product</label>
        <referenceTo>Product_Group_GLBL__c</referenceTo>
        <relationshipLabel>Meetings</relationshipLabel>
        <relationshipName>Meeting_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Meeting Product</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Product/Topic  #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product_Group_GLBL__c.object
<CustomObject>
    <description>Object to store Product Information, mastered Product Group records from Material ODS : MERC : Created on 09/27/2013 by Katy Lorenti, Mavens Consulting</description>
    <fields>
        <fullName>Cntry_Cd_GLBL__c</fullName>
        <description>Unique code which describes the country which uses the translated names on this record.
Created by John A Adams 11/1/2013</description>
        <label>Country Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Crt_Dt_GLBL__c</fullName>
        <description>This represents the date on which the record was initially created in the Material Master Hub database.
Created by John A Adams 11/1/2013</description>
        <label>ODS Created Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Dialect_Nm_GLBL__c</fullName>
        <description>Language dialect of the translated data.
Created by John A Adams 11/1/2013</description>
        <label>Dialect Name</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grp_Prps_Cd_GLBL__c</fullName>
        <description>Classification of the purpose of a product grouping.   
Created by John A Adams 11/1/2013</description>
        <label>Purpose Code</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lst_Pblsh_Dt_GLBL__c</fullName>
        <description>This represents the date on which information was last published for this record to the Material ODS.  This date will be populated when the record is initially created in the ODS or when it is updated.  This is one of the two fields that would be used for delta detection of changes to the Material ODS.  
Created by John A Adams 11/1/2013</description>
        <label>Last Publish Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Updt_Dt_GLBL__c</fullName>
        <description>This represents the date on which the record was last updated in the Material Master Hub database. 
Created by John A Adams 11/1/2013</description>
        <label>ODS Updated Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Product Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MERC_MeetingContentStampHandlerTest.cls
/**
 * @author : Kyle Thornton
 *
 * Test class for MERC_MeetingContentStampHandler
 */
@isTest
private class MERC_MeetingContentStampHandlerTest {

	static Id workspaceId;
	static String versionData      = 'foo';
	static Blob versionDataBlob    = Blob.valueOf(versionData);
	static Meeting_MERC__c meeting = MERC_TestFactory.insertMeetings(1).get(0);
	static Id meetingRecTypeId     = [Select Id From RecordType WHERE DeveloperName = 'Meeting_MERC' AND SobjectType = 'ContentVersion' LIMIT 1].Id;
	static List<Product_Group_GLBL__c> products;
	static
	{
		workspaceId = [SELECT Id FROM ContentWorkspace WHERE Name = 'Mercury' Limit 1].Id; //we can't create this in a test
		system.assertNotEquals(workspaceId, null, 'The workspace \'Mercury\' does not exist or is not availble to the running user.');

		products = new List<Product_Group_GLBL__c>();
		for (Integer i=0; i<3; i++)
		{
			products.add(new Product_Group_GLBL__c( Name                 = 'Test Product ' + i
				                                  , Cntry_Cd_GLBL__c     = 'ZZ'
				                                  , Crt_Dt_GLBL__c       = Date.today()
				                                  , Dialect_Nm_GLBL__c   = 'English'
				                                  , Grp_Prps_Cd_GLBL__c  = 'MKTP'
				                                  , Lst_Pblsh_Dt_GLBL__c = Date.today()
				                                  , Updt_Dt_GLBL__c      = Date.today())
			);
		}
		insert products;

		List<Meeting_Products_MERC__c> meetingProducts = new List<Meeting_Products_MERC__c>();
		for (Product_Group_GLBL__c pg : products)
		{
			meetingProducts.add(new Meeting_Products_MERC__c(Meeting_MERC__c=meeting.Id, Product_MERC__c=pg.Id));
		}
		insert meetingProducts;
	}

	@isTest static void test_product_fields_are_populated() {

		List<ContentVersion> cvList = new List<ContentVersion>();
		Id libraryId =  [select Id from ContentWorkspace WHERE Name = 'Mercury'].Id;
		for (Integer i=0; i<200; i++)
		{
			ContentVersion cv         = new ContentVersion();
			cv.Title                  = 'foo';
			cv.PathOnClient           = 'foo';
			cv.FirstPublishLocationId = libraryId;
			cv.VersionData            = versionDataBlob;
			cv.RecordTypeID           = meetingRecTypeId;
			cv.Meeting_MERC__c        = meeting.Id;
			cvList.add(cv);
		}
		Test.startTest();
		insert cvList;
		Test.stopTest();

		cvList = [SELECT Id, Product_1_MERC__c, Product_2_MERC__c, Product_3_MERC__c FROM ContentVersion WHERE Id IN :cvList];
		System.assertEquals(200, cvList.size());
		for (ContentVersion cv : cvList)
		{
			System.assert(cv.Product_1_MERC__c != null);
			System.assert(cv.Product_2_MERC__c != null);
			System.assert(cv.Product_3_MERC__c != null);
		}
	}
}