src/objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>Meeting_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Meeting</label>
        <referenceTo>Meeting_MERC__c</referenceTo>
        <relationshipLabel>Content</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_1_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product 1</label>
        <referenceTo>Product_Group_GLBL__c</referenceTo>
        <relationshipLabel>Content (Product 1)</relationshipLabel>
        <relationshipName>Content1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_2_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product 2</label>
        <referenceTo>Product_Group_GLBL__c</referenceTo>
        <relationshipLabel>Content (Product 2)</relationshipLabel>
        <relationshipName>Content2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_3_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product 3</label>
        <referenceTo>Product_Group_GLBL__c</referenceTo>
        <relationshipLabel>Content (Product 3)</relationshipLabel>
        <relationshipName>Content3</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Meeting_MERC</fullName>
        <active>true</active>
        <label>Meeting_MERC</label>
    </recordTypes>
</CustomObject>

src/objects/Meeting_MERC__c.object
<CustomObject>
</CustomObject>

src/objects/Meeting_Products_MERC__c.object
<CustomObject>
    <description>Junction object to create many-to-many relationship between Meetings and Products. Created 10/4/2013 by KLorenti.</description>
    <fields>
        <fullName>Meeting_MERC__c</fullName>
        <description>Master Detail Relationship between Products and Meeting. Created 10/4/2013 by KLorenti.</description>
        <label>Meeting</label>
        <referenceTo>Meeting_MERC__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Meeting_Products</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_MERC__c</fullName>
        <description>Master-Detail from Meeting to Product. Created 10/4/2013 by KLorenti.</description>
        <label>Product</label>
        <referenceTo>Product_Group_GLBL__c</referenceTo>
        <relationshipLabel>Meetings</relationshipLabel>
        <relationshipName>Meeting_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Meeting Product</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Product/Topic  #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MERC_MeetingContentStampHandler.cls
/**
 * @author Kyle Thornton
 *
 * Trigger handler to stamp up to three products on content version in the Product_1_Merc__c, Product_2_Merc__c, Product_3_Merc__c fields
 * when content is associated to a meeting. The products are chosen randomly from the products related list on the meeting but the
 * business assumption is that there are never more than three products.
 */

public with sharing class MERC_MeetingContentStampHandler implements GLBL_TriggerHandler.HandlerInterface
{
	public Boolean isActive()
	{
		return true;
	}
	
	public void handle()
	{
		Id contentTypeId = [Select Id From RecordType WHERE DeveloperName = 'Meeting_MERC' AND SobjectType = 'ContentVersion' LIMIT 1].Id;

		Set<Id> mtgIds = new Set<Id>();
		for (ContentVersion cv : (List<ContentVersion>)Trigger.new)
		{
			if (cv.RecordTypeId == contentTypeId && cv.Meeting_MERC__c != null)
			{
				mtgIds.add(cv.Meeting_MERC__c);
			}
		}

		Map<Id, Meeting_MERC__c> mtgs = new Map<Id, Meeting_MERC__c>([SELECT Id
			                                                               , (SELECT Id, Product_MERC__c FROM Meeting_Products__r)
			                                                            FROM Meeting_MERC__c
			                                                            WHERE ID IN :mtgIds]);
		for (ContentVersion cv : (List<ContentVersion>)Trigger.new)
		{
			if (cv.RecordTypeId == contentTypeId && cv.Meeting_MERC__c != null)
			{
				if (mtgs.containsKey(cv.Meeting_MERC__c))
				{
					Meeting_MERC__c mtg = mtgs.get(cv.Meeting_MERC__c);
					if (mtg.Meeting_Products__r.size() >= 1)
						cv.Product_1_MERC__c = mtg.Meeting_Products__r.get(0).Product_MERC__c;
					if (mtg.Meeting_Products__r.size() >= 2)
						cv.Product_2_MERC__c = mtg.Meeting_Products__r.get(1).Product_MERC__c;
					if (mtg.Meeting_Products__r.size() >= 3)
						cv.Product_3_MERC__c = mtg.Meeting_Products__r.get(2).Product_MERC__c;
				}
			}
		}
	}

}