src/objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>Invoice_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship to Invoice. Created 12/6/2013 by KLorenti, Mavens Consulting</description>
        <label>Invoice</label>
        <referenceTo>Invoice_MERC__c</referenceTo>
        <relationshipLabel>Content</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meeting_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Meeting</label>
        <referenceTo>Meeting_MERC__c</referenceTo>
        <relationshipLabel>Content</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meeting_Participant_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship from Content to Meeting Participant. Created 01/16/2014 by KLorenti, Mavens Consulting</description>
        <label>Meeting Participant</label>
        <referenceTo>Meeting_Participant_MERC__c</referenceTo>
        <relationshipLabel>Content</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Invoice_Line_Item_MERC__c.object
<CustomObject>
    <description>Object to store invoice line item information. Created on 9/28/2013 by KLorenti</description>
    <fields>
        <fullName>Amount_MERC__c</fullName>
        <description>Amount of Line Item
Created by John A Adams 10/31/2013</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice_MERC__c</fullName>
        <description>Master-Detail relationship to Invoice object. Created 9/28/2013 by KLorenti</description>
        <label>Invoice</label>
        <referenceTo>Invoice_MERC__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>IL-{000000}</displayFormat>
        <label>Invoice Line Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice_MERC__c.object
<CustomObject>
    <description>Object to store invoice header information, Integrates with SAP for HCP Payments : MERC : Created on 09/27/2013 by Katy Lorenti, Mavens Consulting</description>
    <fields>
        <fullName>Cost_Center_MERC__c</fullName>
        <description>Cost Centre id entered.
Mercury Transaction Id 
Created by John A Adams 10/30/2013</description>
        <label>Cost Center</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Attached_MERC__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag set by Drawloop when an Invoice has been created and attached.  This is used in validation rule to prevent Submit for Payment being set to Yes when no Invoice is present.
Created by John A Adams 1/6/2014</description>
        <label>Invoice Attached</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Meeting_MERC__c</fullName>
        <description>Lookup of Meeting 
Created by John A Adams 10/30/2013</description>
        <formula>Meeting_Participant_MERC__r.Meeting_MERC__r.Event_Id_MERC__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Meeting</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meeting_Participant_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to find the meeting Participant this invoice is for.
Created by John A Adams 10/4/2013</description>
        <label>Meeting Participant</label>
        <referenceTo>Meeting_Participant_MERC__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submit_for_Payment_MERC__c</fullName>
        <description>Used as final check before Invoice is submitted to SAP.  Created by Oliver Dunford 4th Nov 2013.</description>
        <inlineHelpText>A PDF Invoice must be generated and then uploaded before the record can be submitted for payment.</inlineHelpText>
        <label>Submit for Payment</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Meeting_MERC__c.object
<CustomObject>
</CustomObject>

src/objects/Meeting_Participant_MERC__c.object
<CustomObject>
</CustomObject>

src/classes/MERC_InvoiceXmlWriterTest.cls
/** 
* @author Sean Harrison 
* 
* This is a unit test class for MERC_InvoiceXmlWriter.cls which is intended 
* as a trigger on Invoice_MERC__c
*/
@isTest
private class MERC_InvoiceXmlWriterTest {
	
	static List<Account> accounts;
	static List<Meeting_MERC__c> meetings;
	static List<Meeting_Participant_MERC__c> participants;
	static List<Invoice_MERC__c> invoices;
	static List<Invoice_Line_Item_MERC__c> lineItems;
	static Integer numOfLineItems;

	static {
		accounts = MERC_TestFactory.insertAccounts(1);
		meetings = MERC_TestFactory.insertMeetings(1);
		participants = MERC_TestFactory.insertParticipants(meetings[0].Id, accounts);
		invoices = MERC_TestFactory.insertInvoices(participants);

		numOfLineItems = 2;
		for (Meeting_Participant_MERC__c p : participants) {
			p.Services_Rendered_MERC__c = 'Yes';
		}
		update participants;
		lineItems = MERC_TestFactory.insertInvoiceLineItems(invoices[0].Id,numOfLineItems);
	}

	// exercise the addition (and deletion) of xml files to associated content
	@isTest 
	static void createXMLFiles() {
		RecordType rt = [SELECT Id FROM RecordType WHERE Sobjecttype = 'Invoice_Line_Item_MERC__c' AND DeveloperName = 'Consulting_Project_MERC'];
		lineitems = [SELECT Id, Amount_MERC__c, Consulting_Amount_MERC__c, Invoice_MERC__c FROM Invoice_Line_Item_MERC__c WHERE Id in :lineItems];
		for (Invoice_Line_Item_MERC__c item : lineitems) {
			item.Amount_MERC__c = 100;
			// Fulfill conditions for Populate Ad Hoc Amount_MERC workflow
			item.Consulting_Amount_MERC__c = 99;
			item.RecordTypeId = rt.Id;
		}
		update lineItems;

		Test.startTest();
		List<String> invoiceIds = new List<String>();
		invoices = [SELECT Id, Invoice_Attached_MERC__c, Submit_for_Payment_MERC__c FROM Invoice_MERC__c WHERE Id in :invoices];
		for (Invoice_MERC__c invoice : invoices) {
			invoiceIds.add(invoice.Id);
			invoice.Submit_for_Payment_MERC__c = 'Yes';
			invoice.Invoice_Attached_MERC__c = true;  // tell it a PDF is already present.  "Lie to me and tell me everything is all right" - Jonny Lang 		
		}
		update invoices;

		MERC_InvoiceXmlWriter.writeXml(invoiceIds);

		List<ContentVersion> contentVers = new List<ContentVersion>(
			[SELECT ContentDocumentId From ContentVersion WHERE Invoice_MERC__c in :invoices AND Title like '%.xml%']
			);
		System.assert(!contentVers.isEmpty(), 'no XML files in ContentVersion table');
		System.assertEquals(contentVers.size(),invoices.size(),
			'There seem to be different number of xml files ('+contentVers.size()+') and invoices ('+invoices.size()+')');

		// adding another should delete the old one...
		invoices = [SELECT Cost_Center_MERC__c FROM Invoice_MERC__c WHERE Id in :invoices];
		for (Invoice_MERC__c invoice : invoices) {
			invoice.Cost_Center_MERC__c = '7654321';
		}
		update invoices;

		MERC_InvoiceXmlWriter.writeXml(invoiceIds);

		contentVers = [SELECT ContentDocumentId From ContentVersion WHERE Invoice_MERC__c in :invoices AND Title like '%.xml%'];
		System.assert(!contentVers.isEmpty(), 'no XML files in ContentVersion table');
		System.assertEquals(contentVers.size(),invoices.size(),
			'There seem to be different number of xml files ('+contentVers.size()+') and invoices ('+invoices.size()+')');
	}

	// exercise callout in  MERC_InvoiceXmlWriter.execute()
	@isTest 
	static void testCallout() {

		Set<Id> invoiceIds = new Set<Id>();
		for (Invoice_MERC__c invoice : invoices) {
			invoiceIds.add(invoice.Id);
		}

		MERC_XmlWriterRestResource.RemoteXmlWriterResponse response = new MERC_XmlWriterRestResource.RemoteXmlWriterResponse();
		response.success = true;
		response.message = 'XML writer job successfully queued '+invoiceIds.size()+' jobs';	
		String responseString = JSON.serialize(response);	
		MERC_XmlWriterCalloutMock mock = new MERC_XmlWriterCalloutMock(200, 'OK', responseString, null);

		Test.setMock(HttpCalloutMock.class, mock);
		Test.startTest();
		MERC_InvoiceXmlWriter.execute(invoiceIds, UserInfo.getSessionId());
		Test.stopTest();
	}
}