src/objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>Document_Type_MERC__c</fullName>
        <description>Created to capture types of Documents uploaded. Created 12/2/2013 by KLorenti, Mavens Consulting</description>
        <label>Document Type</label>
        <picklist>
            <picklistValues>
                <fullName>Institutional Notification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Notification agreement for services (filled version by HCP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Notification agreement for sponsorship (filled version by HCP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FMV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HCP Transparency Reporting Consent (filled version by HCP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting Minutes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invitations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting Documents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registration Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Slide Kits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approvals and Supporting Documents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cover Letter for Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Event Contract and Appendices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C2P Documents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MSA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Services Rendered Documents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial Payment Justification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expense Reimbursement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MPC Budget and Invoices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agendas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HCP Exceptions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoice Exceptions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Exceptions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certificate of Attendance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting Participant Notice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registration Confirmation Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship Agreement</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Invoice_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship to Invoice. Created 12/6/2013 by KLorenti, Mavens Consulting</description>
        <label>Invoice</label>
        <referenceTo>Invoice_MERC__c</referenceTo>
        <relationshipLabel>Content</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Invoice_MERC</fullName>
        <active>true</active>
        <label>Invoice_MERC</label>
    </recordTypes>
</CustomObject>

src/objects/Invoice_MERC__c.object
<CustomObject>
    <description>Object to store invoice header information, Integrates with SAP for HCP Payments : MERC : Created on 09/27/2013 by Katy Lorenti, Mavens Consulting</description>
    <fields>
        <fullName>Submit_for_Payment_MERC__c</fullName>
        <description>Used as final check before Invoice is submitted to SAP.  Created by Oliver Dunford 4th Nov 2013.</description>
        <inlineHelpText>A PDF Invoice must be generated and then uploaded before the record can be submitted for payment.</inlineHelpText>
        <label>Submit for Payment</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submitted_for_Payment_Date_MERC__c</fullName>
        <description>Date the integrators can stamp a datetime when the record was successfully picked up and processed. This value is modified by the Informatica integration. Do not change, update, or add validation rules to this field.
Created by John Adams 11/11/2013</description>
        <inlineHelpText>Stamped automatically by SAP integration. Do not edit.</inlineHelpText>
        <label>Submitted for Payment</label>
        <type>DateTime</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <recordTypes>
        <fullName>Credit_Note_MERC</fullName>
        <active>true</active>
        <description>Used to create Credit Notes.</description>
        <label>Credit Note</label>
    </recordTypes>
    <recordTypes>
        <fullName>Invoice_MERC</fullName>
        <active>true</active>
        <description>Used to create Invoice records</description>
        <label>Invoice</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Mercury_Settings_MERC__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Custom Settings for the Mercury Project mostly related to the operation of the Customer Search Tool, Veeva integration, Budget and Invoice processing.</description>
    <fields>
        <fullName>Invoice_File_Prefix_MERC__c</fullName>
        <defaultValue>&quot;MercuryInvoice-&quot;</defaultValue>
        <description>Determines the prefix of file names sent for processing. This value is expected &amp; used by the Informatica &amp; SAP integrations.</description>
        <inlineHelpText>Determines the prefix of file names sent for processing. Used by the Informatica &amp; SAP integrations.</inlineHelpText>
        <label>Invoice File Prefix</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Mercury Settings</label>
</CustomObject>

src/classes/MERC_InvoiceXmlWriter.cls
/* MERC_InvoiceXmlWriter
 *
 * Author: Sean Harrison
 *
 * To be run via a trigger on Mercury invoice records. When submitted for payment, an XML file reflecting
 * this invoice's data & related line items is created in a future call to MERC_XmlWriterRestResource
 * and based on the template at MERC_InvoiceAFIXML.page.
 * <br />
 * Be sure to add a self-referencing Remote Site Setting so the org knows it can callout to itself.
 */ 
public with sharing class MERC_InvoiceXmlWriter implements GLBL_TriggerHandler.HandlerInterface {

	private final Id ACTIVE_INVOICE = [SELECT Id FROM RecordType WHERE SObjectType = 'Invoice_MERC__c' AND DeveloperName = 'Invoice_MERC' LIMIT 1].Id;
	private final Id ACTIVE_CNOTE = [SELECT Id FROM RecordType WHERE SObjectType = 'Invoice_MERC__c' AND DeveloperName = 'Credit_Note_MERC' LIMIT 1].Id;

	public Boolean isActive() {
	    return true;
	}

	public void handle() {
		if (Trigger.isAfter) {
			if (Trigger.isInsert || Trigger.isUpdate) {
		    	Set<Id> invoiceIds = new Set<Id>();
		    	for (Invoice_MERC__c invoice : (List<Invoice_MERC__c>)Trigger.new) {
		    		Boolean createXML = invoice.Submit_for_Payment_MERC__c == 'Yes';
		    		if (Trigger.isUpdate) {
			    		Invoice_MERC__c oldInvoice = (Invoice_MERC__c) Trigger.oldMap.get(invoice.Id);
		    			createXML = createXML && 
		    				oldInvoice.Submitted_for_Payment_Date_MERC__c == null && 
		    				(oldInvoice.RecordTypeId == ACTIVE_INVOICE || oldInvoice.RecordTypeId == ACTIVE_CNOTE);
		    		}
		    		if (createXML) invoiceIds.add(invoice.Id);
		    	}
		    	if (invoiceIds.size() > 0)
		    		if (!Test.isRunningTest()) 
		    			execute(invoiceIds, UserInfo.getSessionId());
		   	}
		}
	}

	@Future(callout=true)
	public static void execute(Set<Id> invoiceIds, String sid) { 
		JSONGenerator gen = JSON.createGenerator(true);
		gen.writeStartObject();
		gen.writeObjectField('invoiceIds', invoiceIds);
		gen.writeEndObject();

		String requestBody = gen.getAsString();

		HttpRequest req = new HttpRequest();
     	req.setEndpoint('https://' + System.URL.getSalesforceBaseURL().getHost()+'/services/apexrest/MERC/Invoice/XmlWriter');
     	req.setMethod('POST');
     	req.setTimeout(120000);
     	req.setBody(requestBody);

		String authorizationHeader = 'Bearer ' + sid;
		system.debug(authorizationHeader);
		req.setHeader('Authorization', authorizationHeader);
		req.setHeader('Content-Type', 'application/json');
		Http http = new Http();
		HTTPResponse res;
		try {
			res = http.send(req);  // TODO - trap timeouts and other errors and let admin know
			System.debug(res.getBody());
		} catch (Exception e) {
			String msg = 'Invoice submitted but XML data was not created successfully. Invoice records affected: '+invoiceIds;
			Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
			List<String> toAddresses = new List<String>{'mercury@mavensconsulting.com'};
			mail.setToAddresses(toAddresses);
			mail.setSubject('SAP Invoice error');
			mail.setHtmlBody(msg+ '<br/><br/>Errors:<br />'+e);
			mail.setPlainTextBody(msg+ '\n\nErrors:\n\n'+e);
			Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });			
		}
	}

	public static void writeXml(List<String> invoiceIds) {
		// RestRequest req = RestContext.request;
        // RestResponse res = RestContext.response;
       	String filePrefix = '';
        Mercury_Settings_MERC__c settings = Mercury_Settings_MERC__c.getOrgDefaults();
		if (settings.Id != null && settings.Invoice_File_Prefix_MERC__c != null) filePrefix = settings.Invoice_File_Prefix_MERC__c;

       	Id recordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Invoice_MERC' And SobjectType = 'ContentVersion'].Id;
       	Id workspaceId = [SELECT Id FROM ContentWorkspace WHERE Name = 'Mercury' Limit 1].Id;
       	List<ContentVersion> xmlFiles = new List<ContentVersion>();
       	for (String invoiceId : invoiceIds) {
       		PageReference xmlFile = Page.MERC_InvoiceAFIXML;
       		xmlFile.getParameters().put('id', invoiceId);
       		Blob b = (!Test.isRunningTest()) ? xmlFile.getContent() : Blob.valueOf('<blah></blah>');
       		
       		ContentVersion invoiceXml = new ContentVersion();
       		invoiceXml.Title = filePrefix+invoiceId.substring(0, 15)+'.xml';
       		invoiceXml.PathOnClient = filePrefix+invoiceId.substring(0, 15)+'.xml';
       		invoiceXml.FirstPublishLocationId = workspaceId;
       		invoiceXml.Document_Type_MERC__c = 'Invoices';  // TODO - Custom Settings! Align with LOOP
       		invoiceXml.RecordTypeId = recordTypeId;
       		invoiceXml.Invoice_MERC__c = invoiceId;
       		invoiceXml.VersionData = b; 
       		xmlFiles.add(invoiceXml);
       	}
        insert xmlFiles;

        //delete any other xml-related documents on this invoice
        Set<Id> contentDocumentIds = new Set<Id>();
        for (ContentVersion cv : [SELECT ContentDocumentId From ContentVersion WHERE Invoice_MERC__c in :invoiceIds AND Title like '%.xml%' AND Id not in :xmlFiles])
            contentDocumentIds.add(cv.ContentDocumentId);
        try {
        	delete [SELECT ID FROM ContentDocument WHERE Id in :contentDocumentIds];
        } catch (Exception e) {
        	System.debug('\n\n\nMERC_InvoiceXmlWriter - '+e.getMessage()+'\n\n\n\n');
        }
	}
}