src/objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>Account_Archive_Date__c</fullName>
        <description>One year from date of document upload.  Created 01/16/2014 by Klorenti, Mavens Consultant</description>
        <formula>Upload_Date_MERC__c + 365</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Archive Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Account_GLBL__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Content</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Reference_Number_MERC__c</fullName>
        <description>When content has been approved for usage within the Meeting, it should be uploaded with an Approval Reference Number. Oliver Dunford 6th Nov 2013.</description>
        <label>Approval Reference Number</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Archive_Date_MERC__c</fullName>
        <description>Populate Date the document is to be Archived. Created 12/3/2013 by KLorenti, Mavens Consulting</description>
        <label>Archive Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Budget_Archive_Date_MERC__c</fullName>
        <description>One year from Budget Date. Created 01/16/2014 by KLorenti, Mavens Consulting</description>
        <formula>Budget_MERC__r.Budget_Date_MERC__c + 365</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Budget Archive Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Budget_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship from Content to Budget. Created 01/17/2014 by KLorenti, Mavens Consulting</description>
        <label>Budget</label>
        <referenceTo>Budget_MERC__c</referenceTo>
        <relationshipLabel>Content</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Code_MERC__c</fullName>
        <description>Populates Retention Code based on Document Type. Created 01/15/2014 by KLorenti, Mavens Consulting</description>
        <formula>CASE( Document_Type_MERC__c,
&quot;Institutional Notification&quot;,&quot;ICO210&quot;,
&quot;Notification agreement for services (filled version by HCP)&quot;,&quot;ICO210&quot;,
&quot;Notification agreement for sponsorship (filled version by HCP)&quot;,&quot;ICO210&quot;,
&quot;FMV&quot;,&quot;ICO210&quot;,
&quot;Service Rendered Documents&quot;,&quot;ICO210&quot; ,
&quot;HCP Transparency Reporting Consent (filled version by HCP)&quot;,&quot;ICO210&quot;,
&quot;CV&quot;,&quot;ICO210&quot;,
&quot;HCP Related Items&quot; ,&quot;ICO210&quot;,
&quot;HCP Exceptions&quot;,&quot;ICO210&quot;,
&quot;Invitations&quot;,&quot;MKT100&quot;,
&quot;Meeting Documents&quot;,&quot;MKT100&quot;,
&quot;Registration Form&quot;,&quot;MKT100&quot;,
&quot;Slide Kits&quot;,&quot;MKT100&quot;,
&quot;Approvals and Supporting Documents&quot;,&quot;MKT100&quot;,
&quot;Agendas&quot;,&quot;MKT100&quot;,
&quot;Meeting Exceptions&quot;,&quot;MKT100&quot;,
&quot;Cover Letter for Contract&quot;,&quot;LEG500&quot;,
&quot;Single Event Contract and Appendices&quot;,&quot;LEG500&quot;,
&quot;C2P Documents&quot;,&quot;LEG500&quot;,
&quot;MSA&quot;,&quot;LEG500&quot;,
&quot;Work Order&quot;,&quot;LEG500&quot;,
&quot;Services Rendered Documents&quot;,&quot;LEG500&quot;,
&quot;Partial Payment Justification&quot;,&quot;LEG500&quot;,
&quot;Contract Exceptions&quot;,&quot;LEG500&quot;,
&quot;Invoices&quot;,&quot;ACT100&quot;, 
&quot;Expense Reimbursement&quot;,&quot;ACT100&quot;,
&quot;MPC Budget and Invoices&quot;,&quot;ACT100&quot;,
&quot;Invoice Exceptions&quot;,&quot;ACT100&quot;,
&quot;Certificate of Attendance&quot;,&quot;MKT100&quot;,
&quot;Meeting Participant Notice&quot;,&quot;MKT100&quot;,
&quot;Registration Confirmation Details&quot;,&quot;MKT100&quot;,
&quot;Sponsorship Agreement&quot;,&quot;MKT100&quot;,
&quot;Proof of Consulting Services&quot;,&quot;MKT100&quot;,
&quot;None&quot;)</formula>
        <label>Retention Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Archive_Date_MERC__c</fullName>
        <description>One year from Contract Expiration Date. Created 01/17/2014 by KLorenti, Mavens Consulting</description>
        <formula>HCP_Contract_MERC__r.Contract_Expiration_Date_MERC__c + 365</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contract Archive Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_End_Date_MERC__c</fullName>
        <description>Capture End Date of Contract when uploading documents to HCP Contract. Created 12/3/2013 by KLorenti, Mavens Consulting</description>
        <formula>IF(HCP_Contract_MERC__r.RecordType.Name = &quot;Master Service Agreement&quot;, 
HCP_Contract_MERC__r.MSA_End_Date_MERC__c, 
HCP_Contract_MERC__r.Contract_Expiration_Date_MERC__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Start_Date_MERC__c</fullName>
        <description>Populate the Contract Start Date based on the type of Contract.  If a MSA then use the MSA Start Date.  If a Single Event to Work Order then populate with the Meeting Start Date.  Created by John A Adams 4/21/2014</description>
        <formula>IF(HCP_Contract_MERC__r.RecordType.Name = &quot;Master Service Agreement&quot;, 
HCP_Contract_MERC__r.MSA_Start_Date_MERC__c,  HCP_Contract_MERC__r.Meeting_Name_MERC__r.Date_of_Event_MERC__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Country_of_Residence_MERC__c</fullName>
        <description>Capture Country of Residence for HCP. Created 12/3/2013 by KLorenti, Mavens Consulting</description>
        <formula>TEXT(HCP_Contract_MERC__r.Account_MERC__r.Country_of_Residence_GLBL__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country of Residence</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Id_MERC__c</fullName>
        <description>Pull in Customer ID for HCP that document will be attached to. Created 12/6/2013 by KLorenti, Mavens Consulting</description>
        <formula>Account_GLBL__r.Cust_Id_GLBL__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expose_on_Portal_MERC__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows the content to be available on the Portal. Created 01/13/2014 by KLorenti, Mavens Consulting</description>
        <label>Expose on Portal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship to Invoice. Created 12/6/2013 by KLorenti, Mavens Consulting</description>
        <label>Invoice</label>
        <referenceTo>Invoice_MERC__c</referenceTo>
        <relationshipLabel>Content</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Invoice_MERC</fullName>
        <active>true</active>
        <label>Invoice_MERC</label>
    </recordTypes>
</CustomObject>

src/objects/Invoice_Line_Item_MERC__c.object
<CustomObject>
    <description>Object to store invoice line item information. Created on 9/28/2013 by KLorenti</description>
    <fields>
        <fullName>Invoice_MERC__c</fullName>
        <description>Master-Detail relationship to Invoice object. Created 9/28/2013 by KLorenti</description>
        <label>Invoice</label>
        <referenceTo>Invoice_MERC__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>IL-{000000}</displayFormat>
        <label>Invoice Line Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice_MERC__c.object
<CustomObject>
    <description>Object to store invoice header information, Integrates with SAP for HCP Payments : MERC : Created on 09/27/2013 by Katy Lorenti, Mavens Consulting</description>
    <fields>
        <fullName>Credit_Note_Invoice_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created by John A Adams 11/5/2013</description>
        <label>Credit Note Invoice</label>
        <referenceTo>Invoice_MERC__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Id_MERC__c</fullName>
        <description>Customer Id of Beneficiary.  If this this is the HCO, then the HCO Customer Id is populated, otherwise it&apos;s the meeting Participant.   Oliver Dunford 4th Dec 2013</description>
        <formula>IF( OR(ISNULL(HCO_Beneficiary_MERC__c),ISBLANK(HCO_Beneficiary_MERC__c)) ,  Meeting_Participant_MERC__r.Account_MERC__r.Cust_Id_GLBL__c ,  HCO_Beneficiary_MERC__r.Cust_Id_GLBL__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Submit_for_Payment_MERC__c</fullName>
        <description>Used as final check before Invoice is submitted to SAP.  Created by Oliver Dunford 4th Nov 2013.</description>
        <inlineHelpText>A PDF Invoice must be generated and then uploaded before the record can be submitted for payment.</inlineHelpText>
        <label>Submit for Payment</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submitted_for_Payment_Date_MERC__c</fullName>
        <description>Date the integrators can stamp a datetime when the record was successfully picked up and processed. This value is modified by the Informatica integration. Do not change, update, or add validation rules to this field.
Created by John Adams 11/11/2013</description>
        <inlineHelpText>Stamped automatically by SAP integration. Do not edit.</inlineHelpText>
        <label>Submitted for Payment</label>
        <type>DateTime</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <recordTypes>
        <fullName>Credit_Note_Locked_MERC</fullName>
        <active>true</active>
        <description>Indicates a locked credit note</description>
        <label>Credit Note Locked</label>
    </recordTypes>
    <recordTypes>
        <fullName>Credit_Note_MERC</fullName>
        <active>true</active>
        <description>Used to create Credit Notes.</description>
        <label>Credit Note</label>
    </recordTypes>
    <recordTypes>
        <fullName>Invoice_Locked_MERC</fullName>
        <active>true</active>
        <description>Record Type for a locked Invoice</description>
        <label>Invoice Locked</label>
    </recordTypes>
    <recordTypes>
        <fullName>Invoice_MERC</fullName>
        <active>true</active>
        <description>Used to create Invoice records</description>
        <label>Invoice</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Meeting_Participant_MERC__c.object
<CustomObject>
    <fields>
        <fullName>Submitted_for_Payment_Date_MERC__c</fullName>
        <description>Stores the Invoice Information populated via Process Builder for parties without Invoice access : MERC : Created on 20/04/2015 by Oliver Dunford, Mavens Consulting</description>
        <inlineHelpText>Includes Fees and/or Expenses</inlineHelpText>
        <label>Submitted for Payment Date/Time</label>
        <type>DateTime</type>
    </fields>
</CustomObject>

src/classes/MERC_InvoiceCreditNoteController.cls
public with sharing class MERC_InvoiceCreditNoteController {

	public RecordType newInvoiceRecType { get; private set; }

    public Invoice_MERC__c invoice { get; private set; }
    transient private List<Invoice_Line_Item_MERC__c> lineItems = new List<Invoice_Line_Item_MERC__c>();
    transient private List<ContentVersion> files               = new List<ContentVersion>();

    /*----- The extension constructor initializes the private member variable
            mysObject by using the getRecord method from the standard controller. -----*/
    public MERC_InvoiceCreditNoteController(ApexPages.StandardController stdController) {
        invoice = (Invoice_MERC__c)stdController.getRecord();
        invoice = [Select Id, RecordTypeId, Name FROM Invoice_MERC__c WHERE Id =:invoice.Id];

        /*----- a map from the current record type to the type that should be created -----*/
        Map<String, String> existingToNewRecTypeMap = new Map<String, String>{ 'Invoice_Locked_MERC'     => 'Credit_Note_MERC',
                                                                               'Credit_Note_Locked_MERC' => 'Invoice_MERC'};

        /*----- create a map of Invoice record types by Id-----*/
        Map<Id, RecordType> recordTypeMap = new Map<Id, RecordType>([SELECT Id, Name, DeveloperName FROM RecordType WHERE SObjectType = 'Invoice_MERC__c']);


        /*----- use the prior to maps to figure out what the record type will be for the new Invoice/Credit Note Record -----*/
        if (recordTypeMap.containsKey(invoice.RecordTypeId) && existingToNewRecTypeMap.containsKey(recordTypeMap.get(invoice.RecordTypeId).DeveloperName))
        {
            newInvoiceRecType = [SELECT Id, toLabel(Name), DeveloperName
                                   FROM RecordType
                                  WHERE SObjectType   = 'Invoice_MERC__c'
                                    AND DeveloperName = :existingToNewRecTypeMap.get(recordTypeMap.get(invoice.RecordTypeId).DeveloperName)
                                  LIMIT 1];
        } else {
            ApexPages.addMessage( new ApexPages.Message( ApexPages.Severity.ERROR, 'This invoice/credit note cannot be cloned. Please contact an administrator.'));
        }

        /*----- if we successfully sorted out what the new record type will be we can carry on -----*/
        if (newInvoiceRecType != null)
        {
            /*----- Just need this for a count. Don't want to overwhelm the view state -----*/
            lineItems = [SELECT Id FROM Invoice_Line_Item_MERC__c WHERE Invoice_MERC__c = :invoice.Id];
            files = [SELECT Id FROM ContentVersion WHERE Invoice_MERC__c = :invoice.Id];
        }
    }

    public Integer getLineItemCount() {
        return lineItems.size();
    }

    public Integer getContentCount() {
        return files.size();
    }

    public PageReference createNewInvoice() {
        System.savePoint sp = Database.setSavePoint();

        String invSoqlQuery = 'SELECT Id';
        for (Schema.FieldSetMember fsm : Schema.SObjectType.Invoice_MERC__c.fieldSets.Invoice_Clone_Field_Set.getFields())
        {
            invSoqlQuery += ', ' + fsm.getFieldPath();
        }
        invSoqlQuery += ' FROM Invoice_MERC__c WHERE Id = \'' + invoice.Id + '\'';

        Invoice_MERC__c oldInvoice = Database.query(invSoqlQuery);

        Invoice_MERC__c newInvoice                    = oldInvoice.clone();
        newInvoice.Submit_for_Payment_MERC__c         = 'No';
        newInvoice.Submitted_for_Payment_Date_MERC__c = null;
        newInvoice.RecordTypeId                       = newInvoiceRecType.Id;
        newInvoice.Credit_Note_Invoice_MERC__c        = newInvoiceRecType.DeveloperName == 'Credit_Note_MERC' ? invoice.Id : null;

        try {
            insert newInvoice;
        } catch (System.DMLException ex) {
            Database.rollback(sp);
            ApexPages.addMessages(ex);
            return null;
        }

        String soqlQuery = 'SELECT Id';
        for (Schema.FieldSetMember fsm : Schema.SObjectType.Invoice_Line_Item_MERC__c.fieldSets.Invoice_Clone_Field_Set.getFields())
        {
            soqlQuery += ', ' + fsm.getFieldPath();
        }
        soqlQuery += ' FROM Invoice_Line_Item_MERC__c WHERE Invoice_MERC__c = \'' + invoice.Id + '\'';

        lineItems = Database.query(soqlQuery);

        List<Invoice_Line_Item_MERC__c> newLineItems = lineItems.deepClone();
        for (Invoice_Line_Item_MERC__c li : newLineItems) {
            li.Invoice_MERC__c = newInvoice.Id;
        }

        try {
            insert newLineItems;
        } catch(System.DMLException ex) {
            Database.rollback(sp);
            ApexPages.addMessages(ex);
            return null;
        }

        if (newInvoiceRecType.DeveloperName == 'Credit_Note_MERC') {

            /*----- query for files, skip Expose_on_Portal_MERC__c as it throws errors, FirstPublishLocationId: we aren't allowed to set it-----*/
            files = [SELECT Account_Archive_Date__c, Account_GLBL__c, Approval_Reference_Number_MERC__c, Archive_Date_MERC__c, Budget_Archive_Date_MERC__c, Budget_MERC__c, Checksum, Code_MERC__c,
                            ContentDocumentId, ContentModifiedById, ContentModifiedDate, ContentSize, ContentUrl, Contract_Archive_Date_MERC__c, Contract_End_Date_MERC__c, Contract_Start_Date_MERC__c,
                            Country_of_Residence_MERC__c, CreatedById, CreatedDate, CurrencyIsoCode, Customer_Id_MERC__c, Description, Document_Type_MERC__c, FeaturedContentBoost, FeaturedContentDate,
                            FileType, HCP_Contract_MERC__c, HCP_Name_MERC__c, Id, Invoice_Archive_Date_MERC__c, Invoice_MERC__c, IsDeleted, IsLatest, LastModifiedById, LastModifiedDate,
                            Library_Name_MERC__c, Meeting_Archive_Date_MERC__c, Meeting_City_MERC__c, Meeting_Country_MERC__c, Meeting_MERC__c, Meeting_Participant_MERC__c, Meeting_Start_Date_MERC__c,
                            NegativeRatingCount, Origin, OwnerId, Participant_Name_MERC__c, PathOnClient, PositiveRatingCount, Product_1_MERC__c, Product_2_MERC__c, Product_3_MERC__c, PublishStatus,
                            RatingCount, ReasonForChange, RecordTypeId, SystemModstamp, TagCsv, Title, Upload_Date_MERC__c, VersionData, VersionNumber
                       FROM ContentVersion
                      WHERE Invoice_MERC__c = :invoice.id];

            List<ContentVersion> newFiles = files.deepClone();
            for (ContentVersion file : newFiles) {
                file.Invoice_MERC__c = newInvoice.Id;
                file.ReasonForChange = 'Cloned from Invoice to Credit Note.';
            }

            try {
                insert newFiles;
            } catch(System.DMLException ex) {
                Database.rollback(sp);
                ApexPages.addMessages(ex);
                return null;
            }
        }

        PageReference invPage = new ApexPages.StandardController(newInvoice).view();
        invPage.setRedirect(true);
        return invPage;
    }
}