src/objects/CST_App_Settings_CUST__c.object
<CustomObject>
    <description>Holds application-wide settings for the Customer Search Tool</description>
    <fields>
        <fullName>Record_Type_Ids_CUST__c</fullName>
        <description>Do not edit. This field filled programmatically based on the record type names in Record_Types_CUST</description>
        <inlineHelpText>Do not edit. This field filled programmatically based on the record type names in Record_Types_CUST</inlineHelpText>
        <label>Record Type Ids</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Record_Types_CUST__c</fullName>
        <description>Comma-delmited list of record types to include in CST search results</description>
        <inlineHelpText>A comma-delimited list of Account record types to include for searching. Entries should match RecordType.DeveloperName when viewing the schema directly or the &quot;Record Type Name&quot; when viewing Record Type Detail UI.  E.g. HCP_GLBL,Non_HCP_GLBL,HCO_GLBL</inlineHelpText>
        <label>Record Types</label>
        <type>TextArea</type>
    </fields>
    <label>CST App Settings</label>
    <nameField>
        <displayFormat>CSTAPP-{0000}</displayFormat>
        <label>CST App Settings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CST App Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CUST_RecordTypeIdLookupTest.cls
@isTest
private class CUST_RecordTypeIdLookupTest {

	// create an apps setting entry List
	// create three record types
		static Id hcpRecordTypeId = [Select ID From RecordType Where SObjectType = 'Account' and DeveloperName = 'HCP_GLBL'].ID;
	
	static String rtName1;
	static String rtName2;
	static String rtName3;
	static String rt1;
	static String rt2;
	static String rt3;
	static List<CST_App_Settings_CUST__c> settings;
	
	static {
		rtName1 = 'HCP_GLBL';
		rtName2 = 'Non_HCP_MERC';
		rtName3 = 'Employee_GLBL';
    	// NOTE: Assumes existence of certain Lilly Account types
    	rt1 = [Select ID From RecordType Where SObjectType = 'Account' and DeveloperName = :rtName1].ID;
    	rt2 = [Select ID From RecordType Where SObjectType = 'Account' and DeveloperName = :rtName2].ID;
    	rt3 = [Select ID From RecordType Where SObjectType = 'Account' and DeveloperName = :rtName3].ID;
    	settings = new List<CST_App_Settings_CUST__c>();	
	}
	
	// test update
	static testMethod void testDataExists() {
		System.assert(rt1 != null);
		System.assert(rt2 != null);
		System.assert(rt3 != null);
	}

    static testMethod void oneName() {
    	Test.startTest();
	    init(rtName1);
		insert settings;
		
		CST_App_Settings_CUST__c cst = [SELECT Record_Type_Ids_CUST__c FROM CST_App_Settings_CUST__c WHERE Id = :settings.get(0).Id];
		String result = cst.Record_Type_Ids_CUST__c;
        System.assert(result!=null, 'The RTID list appears to be null.');
        System.assertEquals(result, rt1, 'Expected '+rt1+' but got '+result);
    }
    
    // test error
    
    static void init(String s) {
    	
    	for (Integer i=0;i<200;i++) {
    		CST_App_Settings_CUST__c cst = new CST_App_Settings_CUST__c(Record_Types_CUST__c=s);
   			settings.add(cst);
    	}
    }    
}