src/objects/CST_User_Settings_CUST__c.object
<CustomObject>
    <description>Holds user authorization settings for the Customer Search Tool. Every row reflects a single User/Country/Level combination. Users with access to multiple countries will have multiple rows in this table : MERC, CUST : Created on 02/11/2014 by Sean Harrison, Mavens Consulting</description>
    <fields>
        <fullName>Access_Status_CUST__c</fullName>
        <description>Contains the status of the access request</description>
        <inlineHelpText>Pending: Waiting on Approval
Denied: Manager denied Request
Approved: Access granted
Under Review: Under Audit Review
Expired: Access expired before it was reviewed</inlineHelpText>
        <label>Access Status</label>
        <picklist>
            <picklistValues>
                <fullName>New Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Audit_Date_CUST__c</fullName>
        <description>The date that the audit began</description>
        <inlineHelpText>When the audit began.</inlineHelpText>
        <label>Audit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CST_User_CUST__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is a lookup to an Account record containing information for an Lilly employee or designate. Adding an Account here will authorize this user to utilized the Customer Search Tool</description>
        <inlineHelpText>This field is a lookup to an Account record containing information for an Lilly employee or designate. Adding an Account here will authorize this user to utilized the Customer Search Tool</inlineHelpText>
        <label>CST User</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CST User Settings</relationshipLabel>
        <relationshipName>CST_User_Settings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>CST User Settings</label>
    <nameField>
        <displayFormat>CSTUS-{000000}</displayFormat>
        <label>CST User Settings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CST User Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CUST_UserSettingsUnderReviewBatchTest.cls
/**
  @author: Aakash Bajpai
   @Created Date: 07-Dec-2015
  @Description: For Updating the Access status to 'Under review' for CST User settings object.
*/
@isTest
private class CUST_UserSettingsUnderReviewBatchTest {
  static List<Account> accounts = MERC_TestFactory.insertEmployeeAccounts(2);
    @isTest static void testUserSettingsUnderReviewBatch() {
    Test.startTest();
    List<CST_User_Settings_CUST__c> settings = new List<CST_User_Settings_CUST__c>{
        new CST_User_Settings_CUST__c(Access_Status_CUST__c='Approved',CST_User_CUST__c=accounts.get(0).Id, Audit_Date_CUST__c=Date.Today()),
        new CST_User_Settings_CUST__c(Access_Status_CUST__c='Approved',CST_User_CUST__c=accounts.get(1).Id, Audit_Date_CUST__c=Date.Today())
    };
    insert settings;
    
    CUST_UserSettingsUnderReviewBatchable b = new CUST_UserSettingsUnderReviewBatchable();
    database.executeBatch(b);    
    Test.stopTest();
    
    }
    @isTest static void test_schedule() {
    Test.startTest();
    String CRON_EXP = '0 0 9 1-15 * ?';

        // Schedule the test job
        String jobId = System.schedule('testScheduledApex',
                        CRON_EXP,
                         new CUST_UserSettingsUnderReviewScheduler());

    // Get the information from the CronTrigger API object
    CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime
             FROM CronTrigger WHERE id = :jobId];

    // Verify the expressions are the same
    System.assertEquals(CRON_EXP, ct.CronExpression);

    // Verify the job has not run
    System.assertEquals(0, ct.TimesTriggered);
    
    Test.stopTest();
  }
  
}