src/objects/CST_User_Settings_CUST__c.object
<CustomObject>
    <description>Holds user authorization settings for the Customer Search Tool. Every row reflects a single User/Country/Level combination. Users with access to multiple countries will have multiple rows in this table : MERC, CUST : Created on 02/11/2014 by Sean Harrison, Mavens Consulting</description>
    <fields>
        <fullName>Access_Status_CUST__c</fullName>
        <description>Contains the status of the access request</description>
        <inlineHelpText>Pending: Waiting on Approval
Denied: Manager denied Request
Approved: Access granted
Under Review: Under Audit Review
Expired: Access expired before it was reviewed</inlineHelpText>
        <label>Access Status</label>
        <picklist>
            <picklistValues>
                <fullName>New Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Audit_Date_CUST__c</fullName>
        <description>The date that the audit began</description>
        <inlineHelpText>When the audit began.</inlineHelpText>
        <label>Audit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CST_User_CUST__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is a lookup to an Account record containing information for an Lilly employee or designate. Adding an Account here will authorize this user to utilized the Customer Search Tool</description>
        <inlineHelpText>This field is a lookup to an Account record containing information for an Lilly employee or designate. Adding an Account here will authorize this user to utilized the Customer Search Tool</inlineHelpText>
        <label>CST User</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CST User Settings</relationshipLabel>
        <relationshipName>CST_User_Settings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Status_CUST__c</fullName>
        <description>The last status for this record. This is used to notify the users of status changes, and is cleared after that notification is sent.</description>
        <label>Last Status</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date_CUST__c</fullName>
        <description>The start date of the access, will reset every 6 or so months</description>
        <inlineHelpText>When Access was granted.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>CST User Settings</label>
    <nameField>
        <displayFormat>CSTUS-{000000}</displayFormat>
        <label>CST User Settings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CST User Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CUST_UserSettingStatusUpdateTest.cls
/**
 * @author Kyle Thornton
 *
 * Test class for the CUST_UserSettingStatusUpdateTest
 */
@isTest
private class CUST_UserSettingStatusUpdateTest {

	static Account employee;
	static {
		Id acctEmpRecTypeId = [SELECT Id from RecordType WHERE SObjectType='Account' AND DeveloperName='Employee_GLBL' limit 1].Id;
		employee = new Account(lastname='testemployee', RecordTypeId=acctEmpRecTypeId);
		insert employee;
	}
	@isTest static void test_method_one() {
		CST_User_Settings_CUST__c setting = new CST_User_Settings_CUST__c(Access_Status_CUST__c='Under Review', CST_User_CUST__c=employee.id);
		insert setting;
		setting.Access_Status_CUST__c = 'Approved';
		update setting;

		setting = [SELECT Id, Audit_Date_CUST__c, Start_Date_CUST__c, Last_Status_CUST__c FROM CST_User_Settings_CUST__c WHERE Id=:setting.id];
		System.assertEquals('Under Review', setting.Last_Status_CUST__c);
		System.assertEquals(Date.today(), setting.Start_Date_CUST__c);
		System.assertEquals(Date.Today().addMonths(5).toStartOfMonth().addDays(14), setting.Audit_Date_CUST__c);

	}
}