src/objects/CST_User_Settings_CUST__c.object
<CustomObject>
    <description>Holds user authorization settings for the Customer Search Tool. Every row reflects a single User/Country/Level combination. Users with access to multiple countries will have multiple rows in this table : MERC, CUST : Created on 02/11/2014 by Sean Harrison, Mavens Consulting</description>
    <fields>
        <fullName>Access_Status_CUST__c</fullName>
        <description>Contains the status of the access request</description>
        <inlineHelpText>Pending: Waiting on Approval
Denied: Manager denied Request
Approved: Access granted
Under Review: Under Audit Review
Expired: Access expired before it was reviewed</inlineHelpText>
        <label>Access Status</label>
        <picklist>
            <picklistValues>
                <fullName>New Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CST_User_CUST__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is a lookup to an Account record containing information for an Lilly employee or designate. Adding an Account here will authorize this user to utilized the Customer Search Tool</description>
        <inlineHelpText>This field is a lookup to an Account record containing information for an Lilly employee or designate. Adding an Account here will authorize this user to utilized the Customer Search Tool</inlineHelpText>
        <label>CST User</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CST User Settings</relationshipLabel>
        <relationshipName>CST_User_Settings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>CST User Settings</label>
    <nameField>
        <displayFormat>CSTUS-{000000}</displayFormat>
        <label>CST User Settings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CST User Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CUST_MonthlyProcessSchedulerTest.cls
/**
 *  @author Kyle Thornton
 *
 * Test class for the CUST_MonthlyProcessScheduler
 */
@isTest
private class CUST_MonthlyProcessSchedulerTest {
	static CST_User_Settings_CUST__c setting;
	static {
		Id acctEmpRecTypeId = [SELECT Id from RecordType WHERE SObjectType='Account' AND DeveloperName='Employee_GLBL' limit 1].Id;
		Account employee = new Account(lastname='testemployee', RecordTypeId=acctEmpRecTypeId);
		insert employee;
		setting = new CST_User_Settings_CUST__c(Access_Status_CUST__c='Under Review', CST_User_CUST__c=employee.id);
		insert setting;
	}

	@isTest static void test_method_one() {
		Test.startTest();
		String CRON_EXP = '0 0 0 3 9 ? 2032';

      	// Schedule the test job
      	String jobId = System.schedule('testScheduledApex',
      									CRON_EXP,
         								new CUST_MonthlyProcessScheduler());

		// Get the information from the CronTrigger API object
		CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime
		 				FROM CronTrigger WHERE id = :jobId];

		// Verify the expressions are the same
		System.assertEquals(CRON_EXP, ct.CronExpression);

		// Verify the job has not run
		System.assertEquals(0, ct.TimesTriggered);

		// Verify the next time the job will run
		System.assertEquals('2032-09-03 00:00:00',
		String.valueOf(ct.NextFireTime));

   		Test.stopTest();

   		// Verify the job has run
		//System.assertEquals(1, ct.TimesTriggered);
   		//System.assertEquals('Expired', [SELECT Id, Access_Status_CUST__c FROM CST_User_Settings_CUST__c WHERE Id=:setting.Id].Access_Status_CUST__c);
	}
}