src/objects/Daily_Attendance_TOV_MERC__c.object
<CustomObject>
    <description>Junction object between Meeting Days and Meeting Participants, stores a breakdown of Daily ToV which is picked up by the AODS Interface : MERC : Created on 10/10/2013 by John Adams, Mavens Consulting</description>
    <fields>
        <fullName>Est_Food_Bev_ToV_MERC__c</fullName>
        <formula>IF(ISPICKVAL(Status_MERC__c,&quot;Attended&quot;), Meeting_Day_MERC__r.Daily_Food_Beverage_Amount_MERC__c, 
		(IF(
			(ISPICKVAL(Status_MERC__c,&quot;No Show&quot;) &amp;&amp; 
			(ISPICKVAL(Meeting_Participant_MERC__r.Meeting_MERC__r.Participant_ToV_Final_MERC__c , &quot;Yes&quot;)) &amp;&amp; 
			(Meeting_Day_MERC__r.Daily_Food_Beverage_Amount_MERC__c &gt; 0) &amp;&amp; 
			(Status_Change_Post_ToV_Final_MERC__c = TRUE))
		,0, NULL)
	)
)</formula>
        <label>Food and Beverage ToV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Est_Grp_Grnd_Transp_MERC__c</fullName>
        <description>Stores all Group Ground Transportation ToV for meetings : MERC : Created on 23/07/2014 by Oliver Dunford, Mavens Consulting</description>
        <formula>IF(ISPICKVAL(Status_MERC__c,&quot;Attended&quot;), Meeting_Day_MERC__r.Daily_Ground_Trans_Amount_MERC__c, 
		(IF(
			(ISPICKVAL(Status_MERC__c,&quot;No Show&quot;) &amp;&amp; 
			(ISPICKVAL(Meeting_Participant_MERC__r.Meeting_MERC__r.Participant_ToV_Final_MERC__c , &quot;Yes&quot;)) &amp;&amp; 
			(Meeting_Day_MERC__r.Daily_Ground_Trans_Amount_MERC__c &gt; 0) &amp;&amp; 
			(Status_Change_Post_ToV_Final_MERC__c = TRUE))
		,0, NULL)
	)
)</formula>
        <label>Group Ground Transportation ToV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Est_Hotel_ToV_MERC__c</fullName>
        <description>Captures ToV for Hotels at a Day Level.  Set via custom development based upon Travel Itinerary record and relationship to Meeting Hotel Vendor/Room Rate.  Jan 7th Oliver Dunford</description>
        <label>Hotel ToV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Est_Indv_Transfer_MERC__c</fullName>
        <description>Total for all Individual Travel ToV will be captured here, driven from Individual Travel ToV Records : MERC : Created on 23/07/2014 by Oliver Dunford, Mavens Consulting</description>
        <label>Individual Travel ToV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Est_Reg_Amt_ToV_MERC__c</fullName>
        <formula>IF(ISPICKVAL(Meeting_Participant_MERC__r.Status_MERC__c,&quot;Attended&quot;), Meeting_Day_MERC__r.Daily_Registration_Amount_MERC__c, 
		(IF(
			(ISPICKVAL(Meeting_Participant_MERC__r.Status_MERC__c,&quot;No Show&quot;) &amp;&amp; 
			(ISPICKVAL(Meeting_Participant_MERC__r.Meeting_MERC__r.Participant_ToV_Final_MERC__c , &quot;Yes&quot;)) &amp;&amp; 
			(Meeting_Day_MERC__r.Daily_Registration_Amount_MERC__c &gt;= 0) &amp;&amp; 
			(Status_Change_Post_ToV_Final_MERC__c = TRUE))
		,0, NULL)
	)
)</formula>
        <label>Registration Amount ToV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Meeting_Participant_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master Detail relationship from Daily Attendance to Meeting Participant. Created 10/10/2013 by KLorenti.</description>
        <label>Meeting Participant</label>
        <referenceTo>Meeting_Participant_MERC__c</referenceTo>
        <relationshipLabel>Daily Attendance &amp; TOV</relationshipLabel>
        <relationshipName>Daily_Attendance_TOV_MERC</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Daily Attendance &amp; TOV</label>
    <nameField>
        <displayFormat>DA-{000000}</displayFormat>
        <label>Attendance #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Attendance &amp; TOV</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/HCP_Contract_EVNT__c.object
<CustomObject>
    <description>Contains contract details between Lilly and event speakers. 
Created by John A Adams 10/2/2013</description>
    <fields>
        <fullName>Account_EVNT_MVN__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship between HCP Contracts and Accounts
Created by John A Adams 10/9/2013</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>HCP Contracts</relationshipLabel>
        <relationshipName>HCP_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>HCP Contract</label>
    <nameField>
        <displayFormat>CNTR-{000000}</displayFormat>
        <label>HCP Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCP Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/HCP_Contract_MERC__c.object
<CustomObject>
    <description>Contains contract details between Lilly and event speakers. 
Created by John A Adams 10/2/2013</description>
    <fields>
        <fullName>Account_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship between HCP Contracts and Accounts
Created by John A Adams 10/9/2013</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>HCP Contracts</relationshipLabel>
        <relationshipName>HCP_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Request_Status_MERC__c</fullName>
        <description>Records the status of the contract.
Created by John A Adams 10/8/2013</description>
        <label>Contract Request Status</label>
        <picklist>
            <picklistValues>
                <fullName>Contract request submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HCP IP in progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HCP IP received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FMV in progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FMV completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract in progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract signed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MSA_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship to associate a Work Order to an MSA. Oliver Dunford 12th Nov.</description>
        <label>MSA</label>
        <referenceTo>HCP_Contract_MERC__c</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>HCP_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>HCP Contract</label>
    <nameField>
        <displayFormat>CNTR-{000000}</displayFormat>
        <label>HCP Contract #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCP Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Meeting_Participant_MERC__c.object
<CustomObject>
</CustomObject>

src/classes/MERC_MeetingParticipantRollups.cls
/*
	MERC_MeetingParticipantRollups
	@author : Kyle Thornton, Mavens Consulting
	@created : 13 Jul 2015
	@description : This class will take a list of participants and calculate rollups for TOV
	               from child Daily Attendance records and also count Contracts.
	               This class implements the Queueable interface which allows other queueable
	               jobs to be called. It will call the GLBL_AccountRollups class passing in
	               the accounts for each of the meeting participants.
	@modified by :
	@modified date :

*/
public class MERC_MeetingParticipantRollups implements Queueable {

	private Set<Id> participantIds;
	@TestVisible private MERC_AccountRollups accountRollup;

	public MERC_MeetingParticipantRollups(Set<Id> theParticipantIds) {
		participantIds = theParticipantIds;
	}

	public void execute(QueueableContext context) {
		Integer MAX_ATTEMPTS = 3;
		List<Meeting_Participant_MERC__c> participants;
		Integer attempts = MAX_ATTEMPTS;
		//query for participants, may need to retry attempt if records are locked by another asynchronous process
		while (attempts > 0) {
			try {
				attempts--;
				participants = [SELECT Id,
									   Account_MERC__c,
									   Total_Hotel_ToV_MERC__c,
									   Total_Food_Beverage_ToV_MERC__c,
									   Total_Ground_Transporation_ToV_MERC__c,
									   Total_Individual_Transport_ToV_MERC__c,
									   Total_Registration_ToV_MERC__c,
									   Number_of_Contracts_MERC__c,
									   Number_of_Completed_Contracts_MERC__c,
									   (SELECT Est_Hotel_ToV_MERC__c,
									   		   Est_Food_Bev_ToV_MERC__c,
									   		   Est_Grp_Grnd_Transp_MERC__c,
									   		   Est_Indv_Transfer_MERC__c,
									   		   Est_Reg_Amt_ToV_MERC__c
									   	  FROM Daily_Attendance_TOV_MERC__r),
									   (SELECT Contract_Request_Status_MERC__c
									   	  FROM HCP_Contracts__r)
							      FROM Meeting_Participant_MERC__c
							     WHERE Id IN :participantIds
							     FOR UPDATE];
				attempts = 0;
			} catch (System.QueryException qEx) {
				if (!qEx.getMessage().contains('Record Currently Unavailable') || attempts == 0) {
	               	attempts = 0;  // exit on any other exception
					throw qEx;  // throw exception after MAX_ATTEMPTS attempts
				}
			}
		}

		Set<Id> participantAccountIds = new Set<Id>();

		for (Meeting_Participant_MERC__c participant : participants) {
			//add the account id to the set of participant account ids
			participantAccountIds.add(participant.Account_MERC__c);

			//Calculate TOV; Start each out as null
			participant.Total_Hotel_ToV_MERC__c            = null;
		    participant.Total_Food_Beverage_ToV_MERC__c    = null;
		    participant.Total_Ground_Transporation_ToV_MERC__c = null;
		    participant.Total_Individual_Transport_ToV_MERC__c  = null;
		    participant.Total_Registration_ToV_MERC__c     = null;

			for (Daily_Attendance_TOV_MERC__c attendance : participant.Daily_Attendance_TOV_MERC__r) {
				//Hotel TOV
				if (attendance.Est_Hotel_ToV_MERC__c != null) {
					if (participant.Total_Hotel_ToV_MERC__c == null) {
						participant.Total_Hotel_ToV_MERC__c = 0;
					}
					participant.Total_Hotel_ToV_MERC__c += attendance.Est_Hotel_ToV_MERC__c;
				}

				//Food & Beverage TOV
			    if (attendance.Est_Food_Bev_ToV_MERC__c != null) {
			    	if (participant.Total_Food_Beverage_ToV_MERC__c == null) {
			    		participant.Total_Food_Beverage_ToV_MERC__c = 0;
			    	}
			    	participant.Total_Food_Beverage_ToV_MERC__c += attendance.Est_Food_Bev_ToV_MERC__c;
			    }

			    //Ground Transporation TOV
			    if (attendance.Est_Grp_Grnd_Transp_MERC__c != null) {
			    	if (participant.Total_Ground_Transporation_ToV_MERC__c == null) {
			    		participant.Total_Ground_Transporation_ToV_MERC__c = 0;
			    	}
			    	participant.Total_Ground_Transporation_ToV_MERC__c += attendance.Est_Grp_Grnd_Transp_MERC__c;
			    }

			    //Individual Travel TOV
			    if (attendance.Est_Indv_Transfer_MERC__c != null) {
			    	if (participant.Total_Individual_Transport_ToV_MERC__c == null) {
			    		participant.Total_Individual_Transport_ToV_MERC__c = 0;
			    	}
			    	participant.Total_Individual_Transport_ToV_MERC__c += attendance.Est_Indv_Transfer_MERC__c;
			    }

			    //Registration TOV
			    if (attendance.Est_Reg_Amt_ToV_MERC__c != null) {
			    	if (participant.Total_Registration_ToV_MERC__c == null) {
			    		participant.Total_Registration_ToV_MERC__c = 0;
			    	}
			    	participant.Total_Registration_ToV_MERC__c += attendance.Est_Reg_Amt_ToV_MERC__c;
			    }
			}


			//Total Number of HCP Contracts
			participant.Number_of_Contracts_MERC__c = participant.HCP_Contracts__r.size();

			//Total Number of Completed HCP Contacts
			participant.Number_of_Completed_Contracts_MERC__c = 0;
			for (HCP_Contract_MERC__c contract : participant.HCP_Contracts__r) {
				if (contract.Contract_Request_Status_MERC__c == 'Completed') {
					participant.Number_of_Completed_Contracts_MERC__c++;
				}
			}
		}

		//Mercury has a lot going on and occassionaly the system will run into locked rows.
		MERC_TriggerHandlerStateManager.deactivateAll();

		//update participants, may need to retry attempt if records are locked by another asynchronous process
		attempts = MAX_ATTEMPTS;
		while(attempts > 0) {
			try {
				attempts--;
				update participants;
				attempts = 0;
			} catch (System.DmlException dmlEx) {
	       	    if (!dmlEx.getMessage().contains('UNABLE_TO_LOCK_ROW') || attempts == 0) {
	               	attempts = 0;  // exit on any other exception
					throw dmlEx;  // throw exception after MAX_ATTEMPTS
				}
	       	} // end of catch
		} // end of while retry loop


		participantAccountIds.remove(null);

		//unit tests will fail if chained
		if (!participantAccountIds.isEmpty() && !Test.isRunningTest() && Limits.getQueueableJobs() < Limits.getLimitQueueableJobs()) {
			System.enqueueJob(new MERC_AccountRollups(participantAccountIds));
		}
	}
}