src/objects/Daily_Attendance_TOV_MERC__c.object
<CustomObject>
    <description>Junction object between Meeting Days and Meeting Participants, stores a breakdown of Daily ToV which is picked up by the AODS Interface : MERC : Created on 10/10/2013 by John Adams, Mavens Consulting</description>
    <fields>
        <fullName>Meeting_Participant_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master Detail relationship from Daily Attendance to Meeting Participant. Created 10/10/2013 by KLorenti.</description>
        <label>Meeting Participant</label>
        <referenceTo>Meeting_Participant_MERC__c</referenceTo>
        <relationshipLabel>Daily Attendance &amp; TOV</relationshipLabel>
        <relationshipName>Daily_Attendance_TOV_MERC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status_MERC__c</fullName>
        <description>Used to report across daily meeting attendance for HCP&apos;s. Oliver Dunford 6th Nov  2013.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Daily Attendance &amp; TOV</label>
    <nameField>
        <displayFormat>DA-{000000}</displayFormat>
        <label>Attendance #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Attendance &amp; TOV</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Meeting_Participant_MERC__c.object
<CustomObject>
</CustomObject>

src/classes/MERC_ParticipantStatusCalculator.cls
public with sharing class MERC_ParticipantStatusCalculator implements GLBL_TriggerHandler.HandlerInterface {
	
	public void handle() {
		execute((List<Daily_Attendance_TOV_MERC__c>)Trigger.new);
	}

	public void execute(List<Daily_Attendance_TOV_MERC__c> tovRecords) {        
		
		Set<Id> meetingParticipantIds = new Set<Id>();
		for (Daily_Attendance_TOV_MERC__c tov : tovRecords) {
			meetingParticipantIds.add(tov.Meeting_Participant_MERC__c);
		}

		List<Meeting_Participant_MERC__c> participantsToUpdate = new List<Meeting_Participant_MERC__c>();
		for (Meeting_Participant_MERC__c p : [SELECT 
													Id, 
													(SELECT ID, Status_MERC__c FROM Daily_Attendance_TOV_MERC__r) 
														FROM Meeting_Participant_MERC__c 
															WHERE ID in :meetingParticipantIds]) {
			Integer numberOfNoShows = 0;
			Integer numberOfAttended = 0;

			for (Daily_Attendance_TOV_MERC__c tov : p.Daily_Attendance_TOV_MERC__r) {
				if (tov.Status_MERC__c == 'Attended') {
					numberOfAttended++;
					break;
				} else if (tov.Status_MERC__c == 'No Show') {
					numberOfNoShows++;
				}
			}
			if (numberOfAttended > 0) {
				p.Status_MERC__c = 'Attended';
			} else if (numberOfNoShows == p.Daily_Attendance_TOV_MERC__r.size()) {
				p.Status_MERC__c = 'No Show';
			}
			participantsToUpdate.add(p);
		}

		if (Trigger.isAfter)
			update participantsToUpdate;
	}
}