src/objects/Daily_Attendance_TOV_MERC__c.object
<CustomObject>
    <description>Junction object between Meeting Days and Meeting Participants, stores a breakdown of Daily ToV which is picked up by the AODS Interface : MERC : Created on 10/10/2013 by John Adams, Mavens Consulting</description>
    <fields>
        <fullName>Est_Food_Bev_ToV_MERC__c</fullName>
        <formula>IF(ISPICKVAL(Status_MERC__c,&quot;Attended&quot;), Meeting_Day_MERC__r.Daily_Food_Beverage_Amount_MERC__c, 
		(IF(
			(ISPICKVAL(Status_MERC__c,&quot;No Show&quot;) &amp;&amp; 
			(ISPICKVAL(Meeting_Participant_MERC__r.Meeting_MERC__r.Participant_ToV_Final_MERC__c , &quot;Yes&quot;)) &amp;&amp; 
			(Meeting_Day_MERC__r.Daily_Food_Beverage_Amount_MERC__c &gt; 0) &amp;&amp; 
			(Status_Change_Post_ToV_Final_MERC__c = TRUE))
		,0, NULL)
	)
)</formula>
        <label>Food and Beverage ToV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Est_Grnd_Transp_MERC__c</fullName>
        <description>Combined both Group and Individual Travel ToV for reporting into AODS : MERC : Created on 23/07/2014 by Oliver Dunford, Mavens Consulting</description>
        <formula>/* If both are not null then add them together/*
/* but if at least one of them is null then check if Individual transfer is null, if it&apos;s not, then return it*/
/* if individual transfer is null then group ground might not be. if it isn&apos;t return it, if not both are null and return null */
IF ( NOT(ISBLANK(Est_Indv_Transfer_MERC__c)) &amp;&amp;  NOT(ISBLANK(Est_Grp_Grnd_Transp_MERC__c)) &amp;&amp; (TEXT(Meeting_Participant_MERC__r.Status_MERC__c) = &quot;Attended&quot;),
     Est_Indv_Transfer_MERC__c + Est_Grp_Grnd_Transp_MERC__c,
     IF ( NOT(ISBLANK(Est_Indv_Transfer_MERC__c)) &amp;&amp; (TEXT(Meeting_Participant_MERC__r.Status_MERC__c) = &quot;Attended&quot;),
          Est_Indv_Transfer_MERC__c,
          IF ( NOT(ISBLANK(Est_Grp_Grnd_Transp_MERC__c)),
               Est_Grp_Grnd_Transp_MERC__c,
               null
          )
     )
)</formula>
        <label>Ground Transportation TOV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Est_Hotel_ToV_MERC__c</fullName>
        <description>Captures ToV for Hotels at a Day Level.  Set via custom development based upon Travel Itinerary record and relationship to Meeting Hotel Vendor/Room Rate.  Jan 7th Oliver Dunford</description>
        <label>Hotel ToV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Est_Reg_Amt_ToV_MERC__c</fullName>
        <formula>IF(ISPICKVAL(Meeting_Participant_MERC__r.Status_MERC__c,&quot;Attended&quot;), Meeting_Day_MERC__r.Daily_Registration_Amount_MERC__c, 
		(IF(
			(ISPICKVAL(Meeting_Participant_MERC__r.Status_MERC__c,&quot;No Show&quot;) &amp;&amp; 
			(ISPICKVAL(Meeting_Participant_MERC__r.Meeting_MERC__r.Participant_ToV_Final_MERC__c , &quot;Yes&quot;)) &amp;&amp; 
			(Meeting_Day_MERC__r.Daily_Registration_Amount_MERC__c &gt;= 0) &amp;&amp; 
			(Status_Change_Post_ToV_Final_MERC__c = TRUE))
		,0, NULL)
	)
)</formula>
        <label>Registration Amount ToV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Meeting_Day_MERC__c</fullName>
        <description>Master Detail relationship from Daily Attendance to Meeting Day. Created 10/10/2013 by KLorenti.</description>
        <label>Meeting Day</label>
        <referenceTo>Meeting_Day_MERC__c</referenceTo>
        <relationshipLabel>Daily Attendance &amp; TOV</relationshipLabel>
        <relationshipName>Daily_Attendance_TOV</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Meeting_Participant_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master Detail relationship from Daily Attendance to Meeting Participant. Created 10/10/2013 by KLorenti.</description>
        <label>Meeting Participant</label>
        <referenceTo>Meeting_Participant_MERC__c</referenceTo>
        <relationshipLabel>Daily Attendance &amp; TOV</relationshipLabel>
        <relationshipName>Daily_Attendance_TOV_MERC</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Daily Attendance &amp; TOV</label>
    <nameField>
        <displayFormat>DA-{000000}</displayFormat>
        <label>Attendance #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Attendance &amp; TOV</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Meeting_Day_MERC__c.object
<CustomObject>
    <description>Object to track days of meetings and ToV cost of each day. Created 10/10/2013 by KLorenti.</description>
    <label>Meeting Day</label>
    <nameField>
        <label>Meeting Day</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Meeting_Participant_MERC__c.object
<CustomObject>
</CustomObject>

src/classes/MERC_TOVCalculator.cls
public with sharing class MERC_TOVCalculator implements GLBL_TriggerHandler.HandlerInterface {
	
	public void handle() {
		if (Trigger.isInsert || Trigger.isUpdate || Trigger.isUndelete) {
	    	execute(Trigger.new);
	   	} else if (Trigger.isDelete) {
	   		execute(Trigger.old);
	   	}
	}

	void execute(List<SObject> sobjects) {
		List<Sobject> detailSobjects; //these should be Daily_Attendance_TOV_MERC__c records

		String triggeredSobjectAPIName = MERC_Util.getSobjectAPIName(sobjects.get(0));
		
		if (triggeredSobjectAPIName == 'Meeting_Day_MERC__c') {
			detailSobjects = [Select ID, Meeting_Participant_MERC__c FROM Daily_Attendance_TOV_MERC__c WHERE Meeting_Day_MERC__c in :sobjects];
		} else if (triggeredSobjectAPIName == 'Daily_Attendance_TOV_MERC__c') {
			detailSobjects = sobjects;
		}

		List<GLBL_RollupSummaryUtility.fieldDefinition> fieldDefinitions = 
			new List<GLBL_RollupSummaryUtility.fieldDefinition> {
		            new GLBL_RollupSummaryUtility.fieldDefinition(
		            	'SUM', 'Est_Hotel_ToV_MERC__c', 'Total_Hotel_TOV_MERC__c'), 
		            new GLBL_RollupSummaryUtility.fieldDefinition(
		            	'SUM', 'Est_Food_Bev_ToV_MERC__c', 'Total_Food_Beverage_ToV_MERC__c'),
		            new GLBL_RollupSummaryUtility.fieldDefinition(
		            	'SUM', 'Est_Other_ToV_MERC__c', 'Total_Other_ToV_MERC__c'),
		            new GLBL_RollupSummaryUtility.fieldDefinition(
		            	'SUM', 'Est_Reg_Amt_ToV_MERC__c', 'Total_Registration_ToV_MERC__c'),
		            new GLBL_RollupSummaryUtility.fieldDefinition(
		            	'SUM', 'Est_Grnd_Transp_MERC__c', 'Total_Ground_Transporation_ToV_MERC__c')
		        };
		         
        GLBL_RollupSummaryUtility.rollUpTrigger(fieldDefinitions, detailSobjects, 
        'Daily_Attendance_TOV_MERC__c', 'Meeting_Participant_MERC__c', 'Meeting_Participant_MERC__c', '');
	}
}