src/objects/FMV_Settings_MERC__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Stores the Fair Market Value rates for Speakers by Tier and Year. John A Adams 9/29/2013</description>
    <fields>
        <fullName>Country_Code_MERC__c</fullName>
        <description>Fair Market Value rate Country.
Created by John A Adams 9/29/2013</description>
        <label>Country Code</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Maximum_Hourly_Rate_MERC__c</fullName>
        <description>Stores the maximum hourly rate for a Country in the FMV list.</description>
        <label>Maximum Hourly Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minimum_Hourly_Rate_MERC__c</fullName>
        <description>Hourly rate for the Country and Tier.
Created by John A Adams 9/29/2013</description>
        <label>Minimum Hourly Rate</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tier_Value_MERC__c</fullName>
        <description>Speakers tier number within country.
Created by John A Adams 9/29/2013</description>
        <label>Tier Value</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>FMV Settings</label>
</CustomObject>

src/objects/Meeting_Participant_MERC__c.object
<CustomObject>
</CustomObject>

src/classes/MERC_ParticipantFMVCalculator.cls
public with sharing class MERC_ParticipantFMVCalculator implements GLBL_TriggerHandler.HandlerInterface {
	
	public void handle() {
		if (Trigger.isInsert || Trigger.isUpdate ) {
	    	execute(Trigger.new);
	   	}
	}

	void execute(List<Sobject> sobjects) {
		List<Meeting_Participant_MERC__c> participants = (List<Meeting_Participant_MERC__c>)sobjects;
		
		Set<String> countries = new Set<String>();
		for (Meeting_Participant_MERC__c p : participants) {
			countries.add(p.Country_of_Residence_MERC__c);
		}

		Map<String, List<FMV_Settings_MERC__c>> fmvMap = new Map<String, List<FMV_Settings_MERC__c>>();
		for (FMV_Settings_MERC__c fmvSetting : [SELECT 
													Country_Code_MERC__c, 
													Tier_Value_MERC__c,
													Minimum_Hourly_Rate_MERC__c, 
													Maximum_Hourly_Rate_MERC__c
														FROM FMV_Settings_MERC__c 
															WHERE Country_Code_MERC__c in :countries]) {
			if (fmvMap.containsKey(fmvSetting.Country_Code_MERC__c)) {
				List<FMV_Settings_MERC__c> fmvList = fmvMap.get(fmvSetting.Country_Code_MERC__c);
				fmvList.add(fmvSetting);
				fmvMap.put(fmvSetting.Country_Code_MERC__c, fmvList);
			} else {
				List<FMV_Settings_MERC__c> fmvList = new List<FMV_Settings_MERC__c>{fmvSetting};
				fmvMap.put(fmvSetting.Country_Code_MERC__c, fmvList);
			}
		}

		for (Meeting_Participant_MERC__c p : participants) {
			if (p.Service_Provider_Tier_MERC__c == null) continue;
			if (p.Country_of_Residence_MERC__c == null) continue;

			Integer participantTierValue = p.Service_Provider_Tier_MERC__c.intValue();
			List<FMV_Settings_MERC__c> fmvSettings = fmvMap.get(p.Country_of_Residence_MERC__c);
			
			if (fmvSettings != null) {
				for (FMV_Settings_MERC__c fmvSetting : fmvSettings) {
					Integer fmvTierValue = fmvSetting.Tier_Value_MERC__c.intValue();
					if (fmvTierValue == participantTierValue) {
						p.Minimum_Rate_MERC__c = fmvSetting.Minimum_Hourly_Rate_MERC__c;
						p.Maximum_Rate_MERC__c = fmvSetting.Maximum_Hourly_Rate_MERC__c;
						break;
					}
				}
			}
		}


	}
}