src/objects/GLBL_Form_Template__c.object
<CustomObject>
    <description>Stored template information related to each form; Contains details like whether its launch pad assessment or not, whether a form is active or not</description>
    <label>Form Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GLBL_Form_Template_Answer_Option__c.object
<CustomObject>
    <description>Entity that stores the information related to &apos;Answer&apos; and its properties associated with each &apos;Question&apos; appearing on form</description>
    <fields>
        <fullName>Answer_option__c</fullName>
        <description>Stores options of an answer related to each question</description>
        <label>Answer option</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Score_A__c</fullName>
        <description>The assigned Force.com score for this answer option: Created by J Mohanan Pillai</description>
        <inlineHelpText>The assigned Force.com score for this answer option</inlineHelpText>
        <label>Force.com score</label>
        <picklist>
            <picklistValues>
                <fullName>-10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Score_B__c</fullName>
        <description>The assigned SharePoint score for this answer option: Created by J Mohanan Pillai</description>
        <inlineHelpText>The assigned SharePoint score for this answer option</inlineHelpText>
        <label>SharePoint score</label>
        <picklist>
            <picklistValues>
                <fullName>-10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Score_C__c</fullName>
        <description>The assigned LillyCloud score for this answer option: Created by J Mohanan Pillai</description>
        <inlineHelpText>The assigned LillyCloud score for this answer option</inlineHelpText>
        <label>LillyCloud score</label>
        <picklist>
            <picklistValues>
                <fullName>-10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Score_D__c</fullName>
        <description>The assigned Web Hosting score for this answer option: Created by J Mohanan Pillai</description>
        <inlineHelpText>The assigned Web Hosting score for this answer option</inlineHelpText>
        <label>Web Hosting score</label>
        <picklist>
            <picklistValues>
                <fullName>-10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Score_E__c</fullName>
        <description>The assigned Business Strategic / Custom score for this answer option: Created by J Mohanan Pillai</description>
        <inlineHelpText>The assigned Business Strategic / Custom score for this answer option</inlineHelpText>
        <label>Business Strategic / Custom score</label>
        <picklist>
            <picklistValues>
                <fullName>-10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Form Template Answer Option</label>
    <nameField>
        <displayFormat>FTA-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Template Answer Option</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GLBL_Form_Template_Question__c.object
<CustomObject>
    <description>Stores questions related to each form</description>
    <label>Form Template Question</label>
    <nameField>
        <displayFormat>FTQ-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Template Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MICO_Project__c.object
<CustomObject>
    <description>Business Description: This object can be used to record projects in multi-project programs

Used In: Mission Control App</description>
    <label>Project mico</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_LPAD_AssessmentPageController.cls
/*
*@ Class Name                                                    : Test_LPAD_AssessmentPageController
*@ Description                                                   : Test class for Assessment Page 																   
*@ CreatedBy                                                     : Jayalakshmi Mohananpillai
*@ CreatedOn                                                     : 09-10-2014
*@ Modification Log                                              :                                      
*/

@isTest(seeAllData=false)
public with sharing class Test_LPAD_AssessmentPageController {
	
	/* 
          * @Method Name                    :  testAssessmentPage
          * @Description                    :  Method to test assessment page functionality
          * @Return Type                    :  void
          * @Param                          :  
                                            
    */ 
    public static testmethod void testAssessmentPage(){
    	
    	//Create Lpad User
    	User LpadUser1 = GLBL_TestDataUtilityClass.createLPADUser();
    	
    	
        
    	
    	system.runas(LpadUser1){
    		
	    	// Creating Form Template	
			GLBL_Form_Template__c  formTempTest = GLBL_TestDataUtilityClass.createFormTemplateForTest();
			insert formTempTest;
		    
		    // Variable to hold list of Template questions
	        List<GLBL_Form_Template_Question__c> listFormTempQuest = new List<GLBL_Form_Template_Question__c>();
	        
			// Creating form Template Question
	        for (integer i=0; i<10; i++){
	             GLBL_Form_Template_Question__c formTempQst = GLBL_TestDataUtilityClass.createFormTemplateQuestionForTest(formTempTest.id);
	             listFormTempQuest.add(formTempQst);
	        } 
	        insert listFormTempQuest;
	        
	        // Variable to hold list of answer options per question
	        List<GLBL_Form_Template_Answer_Option__c> listformTempAns = new list<GLBL_Form_Template_Answer_Option__c>();
	        //Creating Answer options
	        for(GLBL_Form_Template_Question__c formQuest : listFormTempQuest){
	        	for(integer j=0; j<3; j++){
	        		GLBL_Form_Template_Answer_Option__c formTempAns = GLBL_TestDataUtilityClass.createFormTemplateAnswerOptionForTest(formQuest.id);
	        		formTempAns.Answer_option__c = 'Sample';
	        		formTempAns.Score_A__c = '1';
	        		formTempAns.Score_B__c = '2' ;
	        		formTempAns.Score_C__c = '3';
	        		formTempAns.Score_D__c = '4';
	        		formTempAns.Score_E__c = '5';
	        		listformTempAns.add(formTempAns);
	        	}
	        }        
	        insert listformTempAns;
	        
	        Test.startTest();
	    		LPAD_AssessmentPageController assessCntrl = new LPAD_AssessmentPageController();
	    		List<GLBL_Form_Template_Question__c> listformTempQuestions = assessCntrl.fetchlistFormTemplateQuestion();
	    		//fetches the active questions in the form template that is active in the org
	    		system.assertequals(listformTempQuestions.size(),listFormTempQuest.size());
	    		system.assertequals(assessCntrl.mapSelectOption.size(),listFormTempQuest.size());
	    		
	    		assessCntrl.nameproject = 'ScoreE Project';
	    		
	    		assessCntrl.ans = 'Sample';
	    		assessCntrl.QuestionIDNew = listFormTempQuest[0].id;	    		
	    		assessCntrl.renderHelpAndCalculate();	    		
	    		
	    		// End user chooses answer equal to none
	    		assessCntrl.ans = 'None';
	    		assessCntrl.QuestionIDNew = listFormTempQuest[1].id;
	    		assessCntrl.renderHelpAndCalculate();
	    		
	    		assessCntrl.createProjectonSubmit();
	    		/* assert to check that the max score is for Area E hence its associated assessment 
	    		   results from custom label gets displayed to end user taking the assessment */
	    		system.assertEquals(assessCntrl.assessmentResultMessage,System.Label.LPAD_AssessmentPage_Result_Message_for_non_Force);
	    		system.assertEquals(assessCntrl.assessmentResultHeading,System.Label.LPAD_AssessmentPage_Score_E_Result_Heading);
	    		
	    		/* assert to check whether a project with the name supplied as is created on assessment submission */
	    		MICO_Project__c projectCreated = [Select id,Name FROM MICO_Project__c WHERE Name =: 'ScoreE Project' ];
	    		system.assertEquals(projectCreated.Name,assessCntrl.nameproject);
	    		 
	    	Test.stopTest();
    		
    	}
    	
    	
    } 
    
    
    /* 
          * @Method Name                    :  testAssessmentPageScoreAMax
          * @Description                    :  Method to test assessment page functionality
          * @Return Type                    :  void
          * @Param                          :  
                                            
    */ 
    public static testmethod void testAssessmentPageScoreAMax(){
    	
    	//Create Lpad User
    	User LpadUser1 = GLBL_TestDataUtilityClass.createLPADUser();
    	
    	
        
    	
    	system.runas(LpadUser1){
    		
	    	// Creating Form Template	
			GLBL_Form_Template__c  formTempTest = GLBL_TestDataUtilityClass.createFormTemplateForTest();
			insert formTempTest;
		    
		    // Variable to hold list of Template questions
	        List<GLBL_Form_Template_Question__c> listFormTempQuest = new List<GLBL_Form_Template_Question__c>();
	        
			// Creating form Template Question
	        for (integer i=0; i<10; i++){
	             GLBL_Form_Template_Question__c formTempQst = GLBL_TestDataUtilityClass.createFormTemplateQuestionForTest(formTempTest.id);
	             listFormTempQuest.add(formTempQst);
	        } 
	        insert listFormTempQuest;
	        
	        // Variable to hold list of answer options per question
	        List<GLBL_Form_Template_Answer_Option__c> listformTempAns = new list<GLBL_Form_Template_Answer_Option__c>();
	        //Creating Answer options
	        for(GLBL_Form_Template_Question__c formQuest : listFormTempQuest){
	        	for(integer j=0; j<3; j++){
	        		GLBL_Form_Template_Answer_Option__c formTempAns = GLBL_TestDataUtilityClass.createFormTemplateAnswerOptionForTest(formQuest.id);
	        		formTempAns.Answer_option__c = 'Sample';
	        		formTempAns.Score_A__c = '5';
	        		formTempAns.Score_B__c = '4' ;
	        		formTempAns.Score_C__c = '3';
	        		formTempAns.Score_D__c = '2';
	        		formTempAns.Score_E__c = '1';
	        		listformTempAns.add(formTempAns);
	        	}
	        }        
	        insert listformTempAns;
	        
	        Test.startTest();
	    		LPAD_AssessmentPageController assessCntrl = new LPAD_AssessmentPageController();
	    		List<GLBL_Form_Template_Question__c> listformTempQuestions = assessCntrl.fetchlistFormTemplateQuestion();
	    		/*fetches the active questions in the form template that is active in the org : as many selectoption
	    		  records gets created as many question records supplied from form template */
	    		system.assertequals(listformTempQuestions.size(),listFormTempQuest.size());
	    		system.assertequals(assessCntrl.mapSelectOption.size(),listFormTempQuest.size());
	    		
	    		assessCntrl.nameproject = 'ScoreA Project';
	    		
	    		assessCntrl.ans = 'Sample';
	    		assessCntrl.QuestionIDNew = listFormTempQuest[0].id;	    		
	    		assessCntrl.renderHelpAndCalculate();	    		
	    		
	    		// End user chooses answer equal to none
	    		assessCntrl.ans = 'None';
	    		assessCntrl.QuestionIDNew = listFormTempQuest[1].id;
	    		assessCntrl.formTemplateAnswer = NULL;
	    		assessCntrl.renderHelpAndCalculate();
	    		
	    		assessCntrl.createProjectonSubmit();
	    		/* assert to check that the max score is for Area A hence its associated assessment 
	    		   results from custom label gets displayed to end user taking the assessment */
	    		system.assertEquals(assessCntrl.assessmentResultMessage,System.Label.LPAD_AssessmentPage_Result_Message_for_Force);
	    		system.assertEquals(assessCntrl.assessmentResultHeading,System.Label.LPAD_AssessmentPage_Score_A_Result_Heading);
	    		
	    		/* assert to check whether a project with the name supplied as is created on assessment submission */
	    		MICO_Project__c projectCreated = [Select id,Name FROM MICO_Project__c WHERE Name =: 'ScoreA Project' ];
	    		system.assertEquals(projectCreated.Name,assessCntrl.nameproject);
	    		 
	    	Test.stopTest();
    		
    	}
    }	
    
    /* 
          * @Method Name                    :  testAssessmentPageScoreCMax
          * @Description                    :  Method to test assessment page functionality
          * @Return Type                    :  void
          * @Param                          :  
                                            
    */ 
    public static testmethod void testAssessmentPageScoreCMax(){
    	
    	//Create Lpad User
    	User LpadUser1 = GLBL_TestDataUtilityClass.createLPADUser();
    	
    	
        
    	
    	system.runas(LpadUser1){
    		
	    	// Creating Form Template	
			GLBL_Form_Template__c  formTempTest = GLBL_TestDataUtilityClass.createFormTemplateForTest();
			insert formTempTest;
		    
		    // Variable to hold list of Template questions
	        List<GLBL_Form_Template_Question__c> listFormTempQuest = new List<GLBL_Form_Template_Question__c>();
	        
			// Creating form Template Question
	        for (integer i=0; i<10; i++){
	             GLBL_Form_Template_Question__c formTempQst = GLBL_TestDataUtilityClass.createFormTemplateQuestionForTest(formTempTest.id);
	             listFormTempQuest.add(formTempQst);
	        } 
	        insert listFormTempQuest;
	        
	        // Variable to hold list of answer options per question
	        List<GLBL_Form_Template_Answer_Option__c> listformTempAns = new list<GLBL_Form_Template_Answer_Option__c>();
	        //Creating Answer options
	        for(GLBL_Form_Template_Question__c formQuest : listFormTempQuest){
	        	for(integer j=0; j<3; j++){
	        		GLBL_Form_Template_Answer_Option__c formTempAns = GLBL_TestDataUtilityClass.createFormTemplateAnswerOptionForTest(formQuest.id);
	        		formTempAns.Answer_option__c = 'Sample';
	        		formTempAns.Score_A__c = '3';
	        		formTempAns.Score_B__c = '4' ;
	        		formTempAns.Score_C__c = '5';
	        		formTempAns.Score_D__c = '2';
	        		formTempAns.Score_E__c = '1';
	        		listformTempAns.add(formTempAns);
	        	}
	        }        
	        insert listformTempAns;
	        
	        Test.startTest();
	    		LPAD_AssessmentPageController assessCntrl = new LPAD_AssessmentPageController();
	    		List<GLBL_Form_Template_Question__c> listformTempQuestions = assessCntrl.fetchlistFormTemplateQuestion();
	    		//fetches the active questions in the form template that is active in the org
	    		system.assertequals(listformTempQuestions.size(),listFormTempQuest.size());
	    		system.assertequals(assessCntrl.mapSelectOption.size(),listFormTempQuest.size());
	    		
	    		assessCntrl.nameproject = 'ScoreC Project';
	    		
	    		assessCntrl.ans = 'Sample';
	    		assessCntrl.QuestionIDNew = listFormTempQuest[0].id;	    		
	    		assessCntrl.renderHelpAndCalculate();	    		
	    		
	    		// End user chooses answer equal to none
	    		assessCntrl.ans = 'None';
	    		assessCntrl.QuestionIDNew = listFormTempQuest[1].id;
	    		assessCntrl.formTemplateAnswer = NULL;
	    		assessCntrl.renderHelpAndCalculate();
	    		
	    		assessCntrl.createProjectonSubmit();
	    		/* assert to check that the max score is for Area C hence its associated assessment 
	    		   results from custom label gets displayed to end user taking the assessment */
	    		system.assertEquals(assessCntrl.assessmentResultMessage,System.Label.LPAD_AssessmentPage_Result_Message_for_non_Force);
	    		system.assertEquals(assessCntrl.assessmentResultHeading,System.Label.LPAD_AssessmentPage_Score_C_Result_Heading);
	    		
	    		/* assert to check whether a project with the name supplied as is created on assessment submission */
	    		MICO_Project__c projectCreated = [Select id,Name FROM MICO_Project__c WHERE Name =: 'ScoreC Project' ];
	    		system.assertEquals(projectCreated.Name,assessCntrl.nameproject);
	    		 
	    	Test.stopTest();
    		
    	}
    }	
}