src/objects/GLBL_Form_Execution__c.object
<CustomObject>
    <description>A form execution Object storing the snapshot of form template</description>
    <fields>
        <fullName>Execution_Status__c</fullName>
        <label>Execution Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Form Execution</label>
    <nameField>
        <displayFormat>FE-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Executions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/GLBL_Form_Execution_Question_Answer__c.object
<CustomObject>
    <description>Stores the snapshot of answers chosen by the front end user for the question in the form</description>
    <fields>
        <fullName>Response_Text__c</fullName>
        <label>Response Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Source_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the reference id of the question related</description>
        <label>Source Question</label>
        <referenceTo>GLBL_Form_Template_Question__c</referenceTo>
        <relationshipLabel>Form Execution Question &amp; Answers</relationshipLabel>
        <relationshipName>Form_Execution_Question_Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Form Execution Question &amp; Answer</label>
    <nameField>
        <displayFormat>FEQA-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Execution Question &amp; Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/GLBL_Form_Template__c.object
<CustomObject>
    <description>Stored template information related to each form; Contains details like whether its launch pad assessment or not, whether a form is active or not</description>
    <label>Form Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GLBL_Form_Template_Answer_Option__c.object
<CustomObject>
    <description>Entity that stores the information related to &apos;Answer&apos; and its properties associated with each &apos;Question&apos; appearing on form</description>
    <label>Form Template Answer Option</label>
    <nameField>
        <displayFormat>FTA-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Template Answer Option</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GLBL_Form_Template_Question__c.object
<CustomObject>
    <description>Stores questions related to each form</description>
    <label>Form Template Question</label>
    <nameField>
        <displayFormat>FTQ-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Template Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Test_FORM_FormExecutionPageController.cls
/* Test class for FORM_FormExecutingPageController */


@isTest(seeAllData = false)
public with sharing class Test_FORM_FormExecutionPageController {

    public static testmethod void testFormExecutionPage(){
        
        //create form template 
        List<GLBL_Form_Template__c> lstFrmTemplates = FORM_DataFactory.createTemplates(1);
        lstFrmTemplates[0].Approval_Status__c = FORM_Constants.APPROVAL_STATUS ;
        update lstFrmTemplates[0];
        
        // create few questions of various type
        List<GLBL_Form_Template_Question__c> lstFrmCurrencyQuestions = FORM_DataFactory.createCurrencyQuestions(2,lstFrmTemplates[0]);
        List<GLBL_Form_Template_Question__c> lstFrmFreeTextQuestions = FORM_DataFactory.createFreeTextQuestions(2,lstFrmTemplates[0]);
        List<GLBL_Form_Template_Question__c> lstFrmNumberQuestions   = FORM_DataFactory.createNumberQuestions(2,lstFrmTemplates[0]);
        List<GLBL_Form_Template_Question__c> lstFrmPicklistQuestions   = FORM_DataFactory.createPicklistQuestions(1,lstFrmTemplates[0]);
        
        //create options for picklist question
        List<GLBL_Form_Template_Answer_Option__c> lstFrmPicklistQuestionOptions = FORM_DataFactory.createAnswerOptions(4,lstFrmPicklistQuestions[0]);       
        
        //Execute form template as form Executor user
        //User frmExecutor = FORM_DataFactory.createUser('FORM_Form_Executor');
        
        //system.runas(frmExecutor){            
        // TO DO implement runas as the sharing class gets completed as for now templates are private and a from executor will not be able to execute it unless shared to them  
            
            // create form executions
            List<GLBL_Form_Execution__c> lstFrmExecutions = FORM_DataFactory.createExecutions(1,lstFrmTemplates[0]);
            system.debug('====lstFrmExecutions' + lstFrmExecutions);
            
            //create form execution question answers
            List<GLBL_Form_Template_Question__c> masterLstFrmQuestions = new list<GLBL_Form_Template_Question__c>();
            masterLstFrmQuestions.addall(lstFrmCurrencyQuestions);
            masterLstFrmQuestions.addall(lstFrmFreeTextQuestions);
            masterLstFrmQuestions.addall(lstFrmNumberQuestions);
            masterLstFrmQuestions.addall(lstFrmPicklistQuestions);
            
            List<GLBL_Form_Execution_Question_Answer__c> lstFrmExecQuestionAnswer = new List<GLBL_Form_Execution_Question_Answer__c>();
            for(GLBL_Form_Template_Question__c frmQuest : masterLstFrmQuestions){
                GLBL_Form_Execution_Question_Answer__c frmExecQA = FORM_DataFactory.createFormExecutionQuestionAnswer(lstFrmExecutions[0],frmQuest);
                lstFrmExecQuestionAnswer.add(frmExecQA);
            }
            
                        
            PageReference formPage = Page.FORM_FormExecutionPage;
            formPage.getParameters().put('templateId', lstFrmTemplates[0].id);
            formPage.getParameters().put('executionId', lstFrmExecutions[0].Id);
            formPage.getParameters().putAll(ApexPages.currentPage().getParameters());
            test.setCurrentPage(formPage);
            
            FORM_FormExecutionPageController formController = new FORM_FormExecutionPageController();
            
            //Testing Remote Method call
            FORM_FormExecutionPageController.remoteSaveAnswer('Ans',lstFrmExecQuestionAnswer[2].id);
            //testing whether answer is stamped or not
            GLBL_Form_Execution_Question_Answer__c frmQAnswerStamped = [SELECT id, Response_Text__c,Source_Question__c
                                                                        FROM GLBL_Form_Execution_Question_Answer__c
                                                                        WHERE id =: lstFrmExecQuestionAnswer[2].id];
            system.debug('++++ answer' + frmQAnswerStamped.Response_Text__c)  ;
                                                                    
            //system.assertEquals('AnswerFreeText',frmQAnswerStamped.Response_Text__c);
                                                                        
            //Saving the form
            formController.SaveForm();
            system.assertEquals(true,formController.isFormSaved);
            
            //Cancel the form
            formController.cancelForm();
            system.assertEquals(true,formController.isFormcancelled);
            system.assertEquals( FORM_Constants.APPROVAL_STATUS_CANCELLED, formController.formExecution.Execution_Status__c);
            
            //Submit the form
            formController.submitForm();
            system.assertEquals(true,formController.isFormSubmitted);
            system.assertEquals( FORM_Constants.APPROVAL_STATUS_COMPLETE, formController.formExecution.Execution_Status__c);
            
            
        //}
    }
}