src/objects/GLBL_GSO_Content__c.object
<CustomObject>
    <description>Generic content object used to store content that can be exposed as part of other apps e.g. content Launchpad Success Stories</description>
    <fields>
        <fullName>Business_Area__c</fullName>
        <description>Which part of the business will use this new functionality the most?</description>
        <inlineHelpText>Which part of the business will use this new functionality the most?</inlineHelpText>
        <label>Business Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Value__c</fullName>
        <description>What is the business value that can be gained from your project?</description>
        <inlineHelpText>What is the business value that can be gained from your project?</inlineHelpText>
        <label>Business Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>The main text of the content that you are uploading</description>
        <inlineHelpText>The main text of the content that you are uploading</inlineHelpText>
        <label>Description</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Detail_Image_URL__c</fullName>
        <description>The detail image to be associated with your content.</description>
        <inlineHelpText>The detail image to be associated with your content.</inlineHelpText>
        <label>Detail Image</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Icon_Image_URL__c</fullName>
        <description>The icon image to be associated with your content.</description>
        <inlineHelpText>The icon image to be associated with your content.</inlineHelpText>
        <label>Icon Image</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Innovation__c</fullName>
        <description>What is the most revolutionary aspect of your project?</description>
        <inlineHelpText>What is the most revolutionary aspect of your project?</inlineHelpText>
        <label>Innovation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Other_Comments__c</fullName>
        <description>Please enter any further details or commentary about your project that has not been covered by the other fields (optional).</description>
        <inlineHelpText>Please enter any further details or commentary about your project that has not been covered by the other fields (optional).</inlineHelpText>
        <label>Other Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <description>Use this field to order your content if it is used externally in assessments, forms, or websites. The content marked with 1 will be given highest priority, followed by 2 and so on.</description>
        <inlineHelpText>Use this field to order your content if it is used externally in assessments, forms, or websites. The content marked with 1 will be given highest priority, followed by 2 and so on.</inlineHelpText>
        <label>Sequence Number</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User_Base__c</fullName>
        <description>Who will be the users of this new functionality?</description>
        <inlineHelpText>Who will be the users of this new functionality?</inlineHelpText>
        <label>User Base</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>GSO Content</label>
    <nameField>
        <label>GSO Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GSO Content</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LPAD_SuccessStoryDetailPageController.cls
public with sharing class LPAD_SuccessStoryDetailPageController {
	
	// variable declarations
	public String successStoryId {get; set;}
	public GLBL_GSO_Content__c successStory;
	
	/**
	 * Constructor
	 */
	public LPAD_SuccessStoryDetailPageController () {
		
		successStoryId = ApexPages.currentPage().getParameters().get('id');
	}
	
	public GLBL_GSO_Content__c getSuccessStory () {
		
		if (successStory == null) {
			try {
				successStory = [SELECT Id, Name, Description__c, Sequence_Number__c,Business_Area__c, Business_Value__c,
				                       User_Base__c,Innovation__c,Other_Comments__c,Icon_Image_URL__c,Detail_Image_URL__c
								FROM GLBL_GSO_Content__c 
								WHERE Id = :successStoryId][0];
			}
			catch (Exception e) {
				System.debug('Error: could not query for success story ' + successStoryId + '\n' +e);
				successStory = new GLBL_GSO_Content__c();
			}		
		}
		
		return successStory;
	}
	
}