src/objects/GLBL_GSO_Content__c.object
<CustomObject>
    <description>Generic content object used to store content that can be exposed as part of other apps e.g. content Launchpad Success Stories</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Confirm whether this content should be considered up to date, &apos;live&apos; information. Uncheck this box if it has expired, or is not fit for purpose.</description>
        <inlineHelpText>Confirm whether this content should be considered up to date, &apos;live&apos; information. Uncheck this box if it has expired, or is not fit for purpose.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>The main text of the content that you are uploading</description>
        <inlineHelpText>The main text of the content that you are uploading</inlineHelpText>
        <label>Description</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Process_Step_Image_URL__c</fullName>
        <description>The Cirrus process step image to be associated with your content.</description>
        <inlineHelpText>The Cirrus process step image to be associated with your content.</inlineHelpText>
        <label>Process Step Image</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <description>The type of content are you adding.</description>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The type of content are you adding.</inlineHelpText>
        <label>Record Type Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <description>Use this field to order your content if it is used externally in assessments, forms, or websites. The content marked with 1 will be given highest priority, followed by 2 and so on.</description>
        <inlineHelpText>Use this field to order your content if it is used externally in assessments, forms, or websites. The content marked with 1 will be given highest priority, followed by 2 and so on.</inlineHelpText>
        <label>Sequence Number</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>GSO Content</label>
    <nameField>
        <label>GSO Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GSO Content</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LPAD_CirrusProcessPageController.cls
public with sharing class LPAD_CirrusProcessPageController {
	
	// variable declarations
	public static final Integer RECORD_LIMIT = 20;
	public static final String RECORD_TYPE = 'Cirrus Process Step';
	public List<GLBL_GSO_Content__c> processSteps;
	
	/**
	 * Constructor
	 */
	public LPAD_CirrusProcessPageController () {
		
	}
	
	/**
	 * Get content records where type = success story
	 */
	public List<GLBL_GSO_Content__c> getProcessSteps() {
		if (processSteps == null) {
			
			try {
				processSteps = [	SELECT Id, Name, Description__c, Process_Step_Image_URL__c, Sequence_Number__c 
									FROM GLBL_GSO_Content__c 
									WHERE Record_Type_Name__c = :RECORD_TYPE
										AND Active__c = true
									ORDER BY Sequence_Number__c ASC, CreatedDate DESC
									LIMIT :RECORD_LIMIT];
			}
			catch (Exception e) {
				System.debug('Error: could not query list of process steps!\n' +e);
				processSteps = new List<GLBL_GSO_Content__c>();
			}

		}
		return processSteps;
	}
}