src/objects/HCP_Contract_MERC__c.object
<CustomObject>
    <description>Contains contract details between Lilly and event speakers. 
Created by John A Adams 10/2/2013</description>
    <fields>
        <fullName>Contract_Request_Status_MERC__c</fullName>
        <description>Records the status of the contract.
Created by John A Adams 10/8/2013</description>
        <label>Contract Request Status</label>
        <picklist>
            <picklistValues>
                <fullName>Contract request submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HCP IP in progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HCP IP received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FMV in progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FMV completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract in progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract signed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>HCP Contract</label>
    <nameField>
        <displayFormat>CNTR-{000000}</displayFormat>
        <label>HCP Contract #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCP Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MERC_HCPContractCancellation.cls
/**
 * @author Vijay Garg: Dated 14-JAN-2016 for US-39525
 *
 * Trigger handler that ensures DocuSign envelope Cancellation after HCP Contract status chagned to Cancelled or Completed
 */
public with sharing class MERC_HCPContractCancellation implements GLBL_TriggerHandler.HandlerInterface {
    
    public Boolean isActive() {
        return true;
    }

    public void handle() {
        if (Trigger.isUpdate ) {
            execute(Trigger.new);
        }
    }
    
    public void execute(List<SObject> sobjects) {
        String contractRequestStatus;
        String docuSignEnvelopeIdOld;
       
        ID UserId = userinfo.getProfileId();

        List<Profile> profileList = [Select Name from Profile where Id =: UserId ]; //Profile for User Performing DML Operation on HCP Contract

        for( HCP_Contract_MERC__c hcpContract: (List<HCP_Contract_MERC__c>)sobjects){
            //We have to void the DocuSign Envelope for old envelop id in case we click on 'Request Signature' button
            HCP_Contract_MERC__c oldHCPContract = (HCP_Contract_MERC__c)Trigger.oldMap.get(hcpContract.id);
            
            try{
                contractRequestStatus = hcpContract.Contract_Request_Status_MERC__c;
                docuSignEnvelopeIdOld = oldHCPContract.Docusign_Envelope_Id_MERC__c;
              
                if (( contractRequestStatus == 'Contract Cancelled' || ( contractRequestStatus == 'Completed' && profileList[0].Name != 'Mercury Integration Docusign - Platform')) && docuSignEnvelopeIdOld != null ) {
                    MERC_DocusignService.voidEnvelope(docuSignEnvelopeIdOld, contractRequestStatus);
                }
            }catch(Exception e){
                hcpContract.addError('There was a problem while voiding HCP Contract in Docusign'); //DocuSign Error message to be displayed
            }
        }
    }
}