src/objects/Invoice_MERC__c.object
<CustomObject>
    <description>Object to store invoice header information, Integrates with SAP for HCP Payments : MERC : Created on 09/27/2013 by Katy Lorenti, Mavens Consulting</description>
    <fields>
        <fullName>Meeting_MERC__c</fullName>
        <description>Lookup of Meeting 
Created by John A Adams 10/30/2013</description>
        <formula>Meeting_Participant_MERC__r.Meeting_MERC__r.Event_Id_MERC__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Meeting</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meeting_Participant_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to find the meeting Participant this invoice is for.
Created by John A Adams 10/4/2013</description>
        <label>Meeting Participant</label>
        <referenceTo>Meeting_Participant_MERC__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Meeting_MERC__c.object
<CustomObject>
</CustomObject>

src/objects/Meeting_Participant_MERC__c.object
<CustomObject>
</CustomObject>

src/classes/MERC_InvoiceInvalidationControllerTest.cls
/**
 * @author Kyle Thornton
 *
 * Unit test for MERC_InvoiceInvalidationController
 */
 @isTest
private class MERC_InvoiceInvalidationControllerTest {

	static User testUser = MERC_TestFactory.getRunningUser();

	@isTest static void test_method_one() {
		Meeting_MERC__c meeting = MERC_TestFactory.insertMeetings(1).get(0);
		List<Account> accounts = MERC_TestFactory.insertAccounts(1);
		List<Meeting_Participant_MERC__c> participants = MERC_TestFactory.insertParticipants(meeting.Id, accounts);
		Invoice_MERC__c invoice = MERC_TestFactory.insertInvoices(participants).get(0);

		System.runAs(testUser) {
			ApexPages.StandardController stdController = new ApexPages.StandardController(invoice);
			MERC_InvoiceInvalidationController controller = new MERC_InvoiceInvalidationController(stdController);

			Test.startTest();
			PageReference ref = controller.redirect();
			Test.stopTest();

			System.assertNotEquals(null, ref);
			System.assertEquals(invoice.id, ref.getParameters().get('id'));
		}
	}

}