src/objects/Invoice_Line_Item_MERC__c.object
<CustomObject>
    <description>Object to store invoice line item information. Created on 9/28/2013 by KLorenti</description>
    <fields>
        <fullName>Amount_MERC__c</fullName>
        <description>Amount of Line Item
Created by John A Adams 10/31/2013</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>IL-{000000}</displayFormat>
        <label>Invoice Line Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MERC_InvoiceLineItemRollupStamp.cls
/*
 * @author David Andrew Helmer
 *
 * Trigger handler that Stamps the Consulting_Amount_MERC__c on 

MERC_Consulting_Contracted_Amount_Rollup__c to avoid Conversion issues
 */

public with sharing class MERC_InvoiceLineItemRollupStamp implements 

GLBL_TriggerHandler.HandlerInterface {
    public MERC_InvoiceLineItemRollupStamp() {
        
    }

    public Boolean isActive() {
        return true;
    }

    public void handle() {
        stampRollupFields(Trigger.new);
    }

    private void stampRollupFields(List<Sobject> sobjects){
        List<Invoice_Line_Item_MERC__c> lineItems = 

(List<Invoice_Line_Item_MERC__c>)sobjects;      
        for(Invoice_Line_Item_MERC__c lineItem : lineItems){
                lineItem.MERC_Consulting_Contracted_Amount_Rollup__c = lineItem.Amount_MERC__c;
                
        }
    }
}