src/objects/IRIS_Assessment__c.object
<CustomObject>
    <description>Used to store the different types of Assessments which are independent of any submission</description>
    <label>Assessment</label>
    <nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IRIS_Assessment_Data__c.object
<CustomObject>
    <description>Stores all the rating against a question.</description>
    <fields>
        <fullName>Rating__c</fullName>
        <description>Stores the rating for the assessment question</description>
        <label>Rating</label>
        <picklist>
            <picklistValues>
                <fullName>1 - Red</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Orange</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Yellow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Light Green</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 - Green</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Assessment Data</label>
    <nameField>
        <displayFormat>AD-{0000}</displayFormat>
        <label>Assessment Data</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IRIS_Submission__c.object
<CustomObject>
    <description>Track and Mange document submissions</description>
    <fields>
        <fullName>Decision_Taken__c</fullName>
        <description>Used to store weather a record is approve or reject.</description>
        <inlineHelpText>Final result of the submission that has been assessed; options include Approve or Reject</inlineHelpText>
        <label>Decision</label>
        <picklist>
            <picklistValues>
                <fullName>Approve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reject</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Current workflow status of Local Document</description>
        <inlineHelpText>System generated description of the state of the document; status options include:  Submitted, In Progress, Awaiting Translation, Pending Decision, Approved, or Rejected</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting translation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending decision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <description>The policy requirement for which the document is referencing</description>
        <inlineHelpText>Specific type of document that is being submitted for review</inlineHelpText>
        <label>Sub-Category</label>
        <picklist>
            <controllingField>COE_Category__c</controllingField>
            <picklistValues>
                <fullName>Anti-bribery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anti-corruption</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conflicts of Interest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealing with Suppliers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EIC Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Message</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gifts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grants and Donations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HCP Transparency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hospitality and Entertainment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual HCP Sponsorships</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interactions with External Parties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interactions with Government and Public Officials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Investigation Procedure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meetings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partnering with External Organizations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Political Financial Support and Involvement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promotional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promotion of Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Providing Samples</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Policy Research and Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Relations Activities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red Book</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Safety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scientific Exchange</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Speaker Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship of Independent Meetings</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Compliance Submission</label>
    <nameField>
        <displayFormat>IS-{0000}</displayFormat>
        <label>Compliance Submission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Submissions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IRIS_Submission_Assessment__c.object
<CustomObject>
    <description>Represents the assessment taken on a submitted document</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Represents the current status of the assessment</description>
        <inlineHelpText>The status of the Submission Assessment</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In-Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Submission Assessment</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Submission Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/IRIS_Test_ApprovalHistoryExtnCont.cls
/*
*  Classname : Iriss_Test_ApprovalHistoryExtnCont 
*   Created By: Deloitte USI    
*   Created Date: 19-Mar-2014
*   Description: This class is the test class for the submission form functionality.
*   Version : 0.1 
*   Change Log
*   Version     Description                         Updated By
*    
*/
@isTest

public with sharing class IRIS_Test_ApprovalHistoryExtnCont {
    private static IRIS_Submission__c oSubmission{set;get;}
    private static IRIS_Assessment__c oAssessment{set;get;}
    
    static void createTestData()
    {
        oSubmission = IRIS_Test_Setup.createSubmission();
        oAssessment = Iris_Test_Setup.createAssessment(oSubmission.Sub_Category__c);
        Iris_Test_Setup.createAssessQuestions(oAssessment,Iris_Test_Setup.createQuestions(5));
        
        Test.setCurrentPage(Page.IRIS_Assessment);
            ApexPages.currentPage().getParameters().put('retURL', '/'+oSubmission.Id);  
            IRIS_Assessment_ExtensionController controller = new IRIS_Assessment_ExtensionController(new ApexPages.StandardController(
                                                        new IRIS_Submission_Assessment__c()));
        if(controller.lstAssessData!=null ){
        for(IRIS_Assessment_Data__c assessData : controller.lstAssessData)
        {
          assessData.Rating__c = '5 - Green';
        }
        }
        //calling the Submit for Approval method to save and submit the Submission Assessment
        controller.doSubmitForApproval();
    
}
    
    static testMethod void testApprovalHistory() {
        system.runas(IRIS_Utility.CreateUserForTestMethods()){
            createTestData();
            Test.startTest();
            Test.setCurrentPage(Page.Iris_Approval_History);
            Apexpages.currentPage().getParameters().put('id',oSubmission.id); 
            IRIS_ApprovalHistory_ControllerExtension controller = new IRIS_ApprovalHistory_ControllerExtension(new ApexPages.StandardController(oSubmission));
            controller.doApprove();
            Test.stopTest();
            IRIS_Submission__c oSub = [Select id, Decision_Taken__c, Status__c From IRIS_Submission__c Where id =: oSubmission.id];
            System.Assertequals(oSub.Status__c, Iris_Constants.SUBMISSION_STATUS_PENDING_DECISION );
        }
    }

}