src/objects/IRIS_Assessment__c.object
<CustomObject>
    <description>Used to store the different types of Assessments which are independent of any submission</description>
    <label>Assessment</label>
    <nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IRIS_Submission__c.object
<CustomObject>
    <description>Track and Mange document submissions</description>
    <fields>
        <fullName>COE_Assessor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person who assesses the Local Document</description>
        <inlineHelpText>Individual within the COE responsible for completing the assessment of the document; system generated once assessment is complete</inlineHelpText>
        <label>COE Assessor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Iriss_Submissions2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Current workflow status of Local Document</description>
        <inlineHelpText>System generated description of the state of the document; status options include:  Submitted, In Progress, Awaiting Translation, Pending Decision, Approved, or Rejected</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting translation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending decision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <description>The policy requirement for which the document is referencing</description>
        <inlineHelpText>Specific type of document that is being submitted for review</inlineHelpText>
        <label>Sub-Category</label>
        <picklist>
            <controllingField>COE_Category__c</controllingField>
            <picklistValues>
                <fullName>Anti-bribery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anti-corruption</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conflicts of Interest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealing with Suppliers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EIC Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Message</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gifts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grants and Donations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HCP Transparency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hospitality and Entertainment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual HCP Sponsorships</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interactions with External Parties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interactions with Government and Public Officials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Investigation Procedure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meetings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partnering with External Organizations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Political Financial Support and Involvement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promotional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promotion of Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Providing Samples</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Policy Research and Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Relations Activities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red Book</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Safety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scientific Exchange</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Speaker Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship of Independent Meetings</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Compliance Submission</label>
    <nameField>
        <displayFormat>IS-{0000}</displayFormat>
        <label>Compliance Submission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Submissions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IRIS_Submission_Assessment__c.object
<CustomObject>
    <description>Represents the assessment taken on a submitted document</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Represents the current status of the assessment</description>
        <inlineHelpText>The status of the Submission Assessment</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In-Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Submission Assessment</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Submission Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/IRIS_Test_Submission_TriggerHandler.cls
/*
*  Classname : Iriss_Test_Submission_Trigger_Helper
*   Created By: Deloitte USI    
*   Created Date: 19-Mar-2014
*   Description: This class is the test class for the testing that the COE Assessor field is populated when the record has been accepted by the COE Assessor 
*   Version : 0.1 
*   Change Log
*   Version     Description                         Updated By
*    
*/
@isTest
private class IRIS_Test_Submission_TriggerHandler {
  
  private static IRIS_Submission__c oSubmission{set;get;}
  private static IRIS_Assessment__c oAssessment{set;get;}
  private static IRIS_Submission_Assessment__c oSubAssess{set;get;}
  
  static void createTestData(){
    oSubmission = Iris_Test_Setup.createSubmission();
    oAssessment = Iris_Test_Setup.createAssessment(oSubmission.Sub_Category__c);
    Iris_Test_Setup.createAssessQuestions(oAssessment,Iris_Test_Setup.createQuestions(5));
  }
  
    static testMethod void testAssignAssessor() {
    system.runas(IRIS_Utility.CreateUserForTestMethods()){
      createTestData();
        // verify that the submission is assigned to a queue
        IRIS_Submission__c oSub = [Select ownerId, COE_Assessor__c, Status__c from IRIS_Submission__c where id=: oSubmission.id];
        String sOwnerId = oSub.ownerId;
        System.assert(!sOwnerId.startsWith('005'));
        System.assertEquals(osub.COE_Assessor__c , null);
        System.assertNotEquals(oSub.Status__c , Iris_Constants.SUBMISSION_STATUS_IN_PROGRESS);
        
        // now assign the submission to Assessor by updating the owner id
        User assessor = Iris_Test_Setup.newAssessorUser();
        oSub.OwnerId = assessor.id;
        update oSub;
        
        // verify that the owner has changed and the COE Assessor has been assigned
        oSub = [Select ownerId, COE_Assessor__c, Status__c from IRIS_Submission__c where id=: oSubmission.id];
        sOwnerId = oSub.ownerId;
        System.assert(sOwnerId.startsWith('005'));
        System.assertEquals(osub.COE_Assessor__c , assessor.id);
        System.assertEquals(oSub.Status__c , Iris_Constants.SUBMISSION_STATUS_IN_PROGRESS);
    }
    }
}