src/objects/IRIS_Access_Buttons__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Used to control the visibility of buttons on the visualforce page. The controllers of the VF pages refer this custom setting to control the visibility buttons on their respective page.</description>
    <fields>
        <fullName>Approve_Reject__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approve/Reject</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Back__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Back</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Save_as_Draft__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Save as Draft</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Submit_for_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Submit for Approval</label>
        <type>Checkbox</type>
    </fields>
    <label>IRIS_Access_Buttons</label>
</CustomObject>

src/objects/IRIS_Country__c.object
<CustomObject>
    <description>Stores all the country.</description>
    <label>Country</label>
    <nameField>
        <label>Country</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IRIS_Region__c.object
<CustomObject>
    <description>Stores all the region.</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IRIS_Submission__c.object
<CustomObject>
    <description>Track and Mange document submissions</description>
    <fields>
        <fullName>COE_Category__c</fullName>
        <description>Type of policy applicable to the Local Document</description>
        <inlineHelpText>General description of the type of document that is being submitted</inlineHelpText>
        <label>COE Category</label>
        <picklist>
            <picklistValues>
                <fullName>Compliance Messaging Materials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR Investigations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local E&amp;C Procedures</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country_Text__c</fullName>
        <description>Used to store the selected country.</description>
        <inlineHelpText>The countries for which the submission is related</inlineHelpText>
        <label>Country</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Document_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person who owns the document and is responsible for the content</description>
        <inlineHelpText>Name of the person who is responsible for the document; typically it is a leader that is accountable</inlineHelpText>
        <label>Document Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Iriss_Submissions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Intended_Audience__c</fullName>
        <description>Audience for which the local document applies (Global, Regional, Local)</description>
        <inlineHelpText>Geographic scope of the document
Local: Specify one or more countries to which this document applies
Regional: Specify one or more regions to which this document applies
Global: Document applies worldwide</inlineHelpText>
        <label>Intended Audience</label>
        <picklist>
            <picklistValues>
                <fullName>Local</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>The local document is written in this language</description>
        <inlineHelpText>Language that the document is currently written in</inlineHelpText>
        <label>Language</label>
        <picklist>
            <picklistValues>
                <fullName>English</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Arabic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulgarian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese Simplified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese Traditional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Czech</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dutch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>French</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>German</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greek</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hungarian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indonesian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Italian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japanese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Korean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Polish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portuguese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Romanian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Russian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Slovak</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spanish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turkish</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region_Text__c</fullName>
        <description>Used to store the selected regions.</description>
        <inlineHelpText>The regions for which the submission is related</inlineHelpText>
        <label>Region</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <description>The policy requirement for which the document is referencing</description>
        <inlineHelpText>Specific type of document that is being submitted for review</inlineHelpText>
        <label>Sub-Category</label>
        <picklist>
            <controllingField>COE_Category__c</controllingField>
            <picklistValues>
                <fullName>Anti-bribery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anti-corruption</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conflicts of Interest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealing with Suppliers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EIC Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Message</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gifts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grants and Donations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HCP Transparency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hospitality and Entertainment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual HCP Sponsorships</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interactions with External Parties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interactions with Government and Public Officials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Investigation Procedure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meetings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partnering with External Organizations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Political Financial Support and Involvement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promotional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promotion of Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Providing Samples</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Policy Research and Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Relations Activities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red Book</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Safety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scientific Exchange</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Speaker Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship of Independent Meetings</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Compliance Submission</label>
    <nameField>
        <displayFormat>IS-{0000}</displayFormat>
        <label>Compliance Submission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Submissions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IRIS_Submission_Region__c.object
<CustomObject>
    <description>Junction object between Region and Compliance Submission.</description>
    <fields>
        <fullName>Compliance_Submission__c</fullName>
        <description>Stores compliance Submission record.</description>
        <label>Compliance Submission</label>
        <referenceTo>IRIS_Submission__c</referenceTo>
        <relationshipLabel>Submission Regions</relationshipLabel>
        <relationshipName>Submission_Regions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store reference to the region object.</description>
        <label>Region</label>
        <referenceTo>IRIS_Region__c</referenceTo>
        <relationshipLabel>Submission Regions</relationshipLabel>
        <relationshipName>Submission_Regions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Submission Region</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Submission Region Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission Regions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/IRIS_Test_SubmissionRegion_TriggHandler.cls
/*
*  Classname : Iriss_Test_Submission_Region_Trigger
*   Created By: Deloitte USI    
*   Created Date: 27-Mar-2014
*   Description: This class is the test class for the submission region trigger.
*   Version : 0.1 
*   Change Log
*   Version     Description                         Updated By
*/    
@isTest
private class IRIS_Test_SubmissionRegion_TriggHandler{
  private static IRIS_Region__c region1{set;get;}
    private static IRIS_Region__c region2{set;get;}
    
    private static list<IRIS_Country__c> lstCountries1{set;get;}
    private static list<IRIS_Country__c> lstCountries2{set;get;}
    
    private static IRIS_Submission__c oSubmission{set;get;}
  
  static Attachment createAttachment(){
      Attachment attach=new Attachment();     
        attach.Name='Unit Test Attachment';
        attach.body=Blob.valueOf('Unit Test Attachment Body');
        return attach;
    }
  
    static void createRegionCountryData(){
        system.runas(IRIS_Utility.CreateUserForTestMethods()){
            region1 = Iris_Test_Setup.createRegion('testRegionName1');
            region2 = Iris_Test_Setup.createRegion('testRegionName2');
            
            lstCountries1 = Iris_Test_Setup.createCountries(new List<String>{'testCountry1','testCountry2','testCountry3'});
            lstCountries2 = Iris_Test_Setup.createCountries(new List<String>{'testCountry4','testCountry5','testCountry6'});
            //adding a common country
            lstCountries2.add(lstCountries1[0]);
            
            Iris_Test_Setup.createRegionCountryMapping(region1, lstCountries1);
            Iris_Test_Setup.createRegionCountryMapping(region2, lstCountries2);
        }
    }
  
    static void createRegionalSubmission() {
      system.runas(IRIS_Utility.CreateUserForTestMethods()){
      // create test data for country, region and their mapping
       createRegionCountryData();
       List<IRIS_Access_Buttons__c> lbutton=new List<IRIS_Access_Buttons__c>();
        
      
        IRIS_Access_Buttons__c testbutton1=new IRIS_Access_Buttons__c(Name='System Administrator',Approve_Reject__c=true,Back__c=true,Save_as_Draft__c=true,Submit_for_Approval__c=true);
        
        IRIS_Access_Buttons__c testbutton2=new IRIS_Access_Buttons__c(Name='    IRIS_Submission_Hybrid_Profile',Approve_Reject__c=true,Back__c=true,Save_as_Draft__c=true,Submit_for_Approval__c=true);
        
        IRIS_Access_Buttons__c testbutton3=new IRIS_Access_Buttons__c(Name='    IRIS_Submission_Assessment_Profile',Approve_Reject__c=true,Back__c=true,Save_as_Draft__c=true,Submit_for_Approval__c=true);
        
        IRIS_Access_Buttons__c testbutton4=new IRIS_Access_Buttons__c(Name='IRIS_Submission_Approval_Profile',Approve_Reject__c=true,Back__c=true,Save_as_Draft__c=true,Submit_for_Approval__c=true);
        
        IRIS_Access_Buttons__c testbutton5=new IRIS_Access_Buttons__c(Name='    IRIS_Submission_Affiliate_Profile',Approve_Reject__c=true,Back__c=true,Save_as_Draft__c=true,Submit_for_Approval__c=true);
        
        IRIS_Access_Buttons__c testbutton6=new IRIS_Access_Buttons__c(Name='    Application Administrator',Approve_Reject__c=true,Back__c=true,Save_as_Draft__c=true,Submit_for_Approval__c=true);
        
        lbutton.add(testbutton1);
        lbutton.add(testbutton2);
        lbutton.add(testbutton3);
        lbutton.add(testbutton4);
        lbutton.add(testbutton5);
        lbutton.add(testbutton6);
        
        
        insert lbutton;
        // invoking the page
        Test.setCurrentPage(Page.Iris_Submission_Form);
        IRIS_Submission_FormControllerExtension controller = new IRIS_Submission_FormControllerExtension(new ApexPages.StandardController(new IRIS_Submission__c()));
        // setting up the fields on the submission form
        controller.oSubmission.COE_Category__c = IRIS_Submission__c.COE_Category__c.getDescribe().getPicklistValues()[0].getValue();
        controller.oSubmission.Sub_Category__c = IRIS_Submission__c.Sub_Category__c.getDescribe().getPicklistValues()[0].getValue();
        controller.oSubmission.Document_Owner__c = UserInfo.getUserId();
        controller.oSubmission.Language__c = IRIS_Submission__c.Language__c.getDescribe().getPicklistValues()[0].getValue();
        controller.oSubmission.Intended_Audience__c = Iris_Constants.SUBMISSION_INTENDED_AUDIENCE_REGIONAL;
        controller.checkAudience();
        // setting the region name and region ids
        controller.oSubmission.Region_Text__c = region1.name + ';' +region2.name;
        controller.selectedRegionIds = region1.id + ';' +region2.id;
        // setting the file count 
        controller.FileCount = '1';
        controller.ChangeCount();
        //uploading the document
        Attachment attach = createAttachment();
        controller.allFileList.add(attach);
        controller.doSubmit();
        oSubmission = controller.oSubmission;
        }
    }
    
    static testMethod void testSubRegionUpdate() {
    system.runas(IRIS_Utility.CreateUserForTestMethods()){
      // create test data for country, region and their mapping
       createRegionCountryData();
       
       // creating the Submission Country records
       createRegionalSubmission();
        List<IRIS_Submission_Region__c> lstSubRegions = [select Region__c from IRIS_Submission_Region__c
                                   where Compliance_Submission__c = : oSubmission.id];
            //System.debug('&&&lstSubRegions'+lstSubRegions);
        System.debug('&&&oSubmission'+oSubmission.id);
    // system.assert(lstSubRegions != null && lstSubRegions.size()>0 , 'Submission country is not created');
     // updating the country on the Submission Country
     IRIS_Submission_Region__c subRegion = lstSubRegions[0];
     subRegion.Region__c = region2.id;
     oSubmission = [Select Country_Text__c,Region_Text__c 
                                from IRIS_Submission__c where id = : oSubmission.id];
     Test.startTest();
     IRIS_Submission_Region_Trigger_Helper.hasTakenCareOf = null;
     update subRegion;
     Test.stopTest();
     IRIS_Submission__c queriedSubmission = [Select Country_Text__c,Region_Text__c 
                                from IRIS_Submission__c where id = : oSubmission.id];
     system.assertNotEquals(oSubmission.Country_Text__c , queriedSubmission.Country_Text__c);
     system.assertNotEquals(oSubmission.Region_Text__c , queriedSubmission.Region_Text__c);
     }
    }
    
    static testMethod void testSubRegionDelete() {
    system.runas(IRIS_Utility.CreateUserForTestMethods()){
       // creating the Submission Country records
       createRegionalSubmission();
        List<IRIS_Submission_Region__c> lstSubRegions = [select Region__c from IRIS_Submission_Region__c
                                   where Compliance_Submission__c = : oSubmission.id];
                                 
        System.debug('&&&lstSubRegions'+lstSubRegions);
        System.debug('&&&oSubmission'+oSubmission.id);
        
    // system.assert(lstSubRegions != null && lstSubRegions.size()>0 , 'Submission country is not created');
     // updating the country on the Submission Country
     IRIS_Submission_Region__c subRegion = lstSubRegions[0];
     oSubmission = [Select Country_Text__c,Region_Text__c 
                                from IRIS_Submission__c where id = : oSubmission.id];
     Test.startTest();
     IRIS_Submission_Region_Trigger_Helper.hasTakenCareOf = null;
     delete subRegion;
     Test.stopTest();
     IRIS_Submission__c queriedSubmission = [Select Country_Text__c,Region_Text__c 
                                from IRIS_Submission__c where id = : oSubmission.id];
     system.assertNotEquals(oSubmission.Country_Text__c , queriedSubmission.Country_Text__c);
     system.assertNotEquals(oSubmission.Region_Text__c , queriedSubmission.Region_Text__c);
     }
    }
}