src/objects/IRIS_Submission__c.object
<CustomObject>
    <description>Track and Mange document submissions</description>
    <fields>
        <fullName>Country_Text__c</fullName>
        <description>Used to store the selected country.</description>
        <inlineHelpText>The countries for which the submission is related</inlineHelpText>
        <label>Country</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Region_Text__c</fullName>
        <description>Used to store the selected regions.</description>
        <inlineHelpText>The regions for which the submission is related</inlineHelpText>
        <label>Region</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Compliance Submission</label>
    <nameField>
        <displayFormat>IS-{0000}</displayFormat>
        <label>Compliance Submission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Submissions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IRIS_Submission_Country__c.object
<CustomObject>
    <description>Junction object between country and Compliance Submission.</description>
    <fields>
        <fullName>Compliance_Submission__c</fullName>
        <description>Used to store the Compliance Submission object.</description>
        <label>Compliance Submission</label>
        <referenceTo>IRIS_Submission__c</referenceTo>
        <relationshipLabel>Submission Countries</relationshipLabel>
        <relationshipName>Submission_Countries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Country_Name__c</fullName>
        <formula>Country__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store reference to the country object.</description>
        <label>Country</label>
        <referenceTo>IRIS_Country__c</referenceTo>
        <relationshipLabel>Submission Countries</relationshipLabel>
        <relationshipName>Submission_Countries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Submission Country</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Submission Country Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/IRIS_Submission_Country_Trigger_Helper.cls
/*
*  Classname : Iriss_Submission_Country_Trigger_Helper
*   Created By: Deloitte USI    
*   Created Date: 25-Mar-2014
*   Description: This class is used by trigger Iriss_Submission_Country_BD_BU to update the Country text field on the respective Submissions
*   Version : 0.1 
*   Change Log
*   Version     Description                         Updated By
*    
*/

public with sharing class IRIS_Submission_Country_Trigger_Helper{
    
    private List<IRIS_Submission_Country__c> lstUpdatedSubCountries{set;get;} 
    private set<Id> setSubIds{set;get;}
    private map<id,IRIS_Submission__c> mapSubId_SubRec{set;get;}
    public static boolean hasTakenCareOf{set;get;} 
    
    public void updateCountryTextField(List<IRIS_Submission_Country__c> lstSubCountries , map<id,IRIS_Submission_Country__c> oldMapSubCountry){
        // get only the submission countries which have the Country updated
        getUpdatedSubCountries(lstSubCountries , oldMapSubCountry);
        if(lstUpdatedSubCountries != null && lstUpdatedSubCountries.size()>0){
            mapSubId_SubRec = new Map<id,IRIS_Submission__c>([Select Country_Text__c,Region_Text__c 
                                                                from IRIS_Submission__c where id in : setSubIds]);
            //re-calculating the Submission regions before updating the Submissions
            Iris_Utility.recalculateSubRegion(mapSubId_SubRec.keySet() , mapSubId_SubRec.values());
            // refrshing the Region Text field on submission
            Iris_Utility.refreshRegionTextField(mapSubId_SubRec);
            
            String sCountryText;
            for(IRIS_Submission_Country__c subCountry : lstUpdatedSubCountries){
                sCountryText = mapSubId_SubRec.get(subCountry.Compliance_Submission__c).Country_Text__c;
                if(subCountry.Country_Name__c !=null && subCountry.Country_Name__c !=''){
                sCountryText = sCountryText.replace(oldMapSubCountry.get(subCountry.id).Country_Name__c,
                                                         subCountry.Country_Name__c);
                }
                sCountryText = sCountryText.removeEnd(';');
                mapSubId_SubRec.get(subCountry.Compliance_Submission__c).Country_Text__c = Iris_Utility.sortTheString(sCountryText);
            }
            Database.SaveResult[] updateResults = Database.update(mapSubId_SubRec.values() , false);
            if (updateResults != null){
                for (integer i = 0 ; i<updateResults.size(); i++){
                    if (!updateResults[i].isSuccess()){
                        for(Database.Error err : updateResults[i].getErrors())
                        {
                            mapSubId_SubRec.values()[i].addError(err.getMessage());
                        }
                    }
                }
            }
        }   
    }
    
    /* 
     * Method name : removeCountryTextField
     * Description : This method is used to remove country from the text field when the related list is deleted.
     * Param - lstSubCountries : list of Countries
     * Returns :  null
    */
    
    public void removeCountryTextField(List<IRIS_Submission_Country__c> lstSubCountries){
        setSubIds = new Set<Id>();
        for(IRIS_Submission_Country__c subCountry : lstSubCountries){
            setSubIds.add(subCountry.Compliance_Submission__c);
        }
        mapSubId_SubRec = new Map<id,IRIS_Submission__c>([Select Country_Text__c,Region_Text__c 
                                                            from IRIS_Submission__c where id in : setSubIds]);
        
        //re-calculating the Submission regions before updating the Submissions
        Iris_Utility.recalculateSubRegion(mapSubId_SubRec.keySet() , mapSubId_SubRec.values());
        // refrshing the Region Text field on submission
        Iris_Utility.refreshRegionTextField(mapSubId_SubRec);
        
        String sCountryText;
        for(IRIS_Submission_Country__c subCountry : lstSubCountries){
            sCountryText = mapSubId_SubRec.get(subCountry.Compliance_Submission__c).Country_Text__c;
            if(subCountry.Country_Name__c !=null && subCountry.Country_Name__c !=''){
            sCountryText = sCountryText.remove(subCountry.Country_Name__c);
            }
            sCountryText = sCountryText.removeStart(';');
            sCountryText = sCountryText.removeEnd(';');
            sCountryText = sCountryText.replace(';;',';');
            mapSubId_SubRec.get(subCountry.Compliance_Submission__c).Country_Text__c = Iris_Utility.sortTheString(sCountryText);
        }
        Database.SaveResult[] updateResults = Database.update(mapSubId_SubRec.values() , false);
        if (updateResults != null){
            for (integer i = 0 ; i<updateResults.size(); i++){
                if (!updateResults[i].isSuccess()){
                    for(Database.Error err : updateResults[i].getErrors())
                    {
                        mapSubId_SubRec.values()[i].addError(err.getMessage());
                    }
                }
            }
        }
    }
    
    /* 
     * Method name : getUpdatedSubCountries
     * Description : This method is used to update countries in the country text field when related list is updated .
     * Param - lstSubCountries : list of Countries, oldMapSubCountry: map of id's and countries.
     * Returns :  lstUpdatedSubCountries : list of updated countries.
    */
    
    private List<IRIS_Submission_Country__c> getUpdatedSubCountries(List<IRIS_Submission_Country__c> lstSubCountries , 
                                                                            map<id,IRIS_Submission_Country__c> oldMapSubCountry){
        lstUpdatedSubCountries = new List<IRIS_Submission_Country__c>();
        setSubIds = new Set<Id>();
        for(IRIS_Submission_Country__c subCountry : lstSubCountries){
            if(subCountry.Country__c != oldMapSubCountry.get(subCountry.id).Country__c){
                lstUpdatedSubCountries.add(subCountry);
                setSubIds.add(subCountry.Compliance_Submission__c);
            }
        }
        return lstUpdatedSubCountries;
    }
    
}