src/objects/IRIS_Submission__c.object
<CustomObject>
    <description>Track and Mange document submissions</description>
    <fields>
        <fullName>COE_Assessor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person who assesses the Local Document</description>
        <inlineHelpText>Individual within the COE responsible for completing the assessment of the document; system generated once assessment is complete</inlineHelpText>
        <label>COE Assessor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Iriss_Submissions2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Current workflow status of Local Document</description>
        <inlineHelpText>System generated description of the state of the document; status options include:  Submitted, In Progress, Awaiting Translation, Pending Decision, Approved, or Rejected</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting translation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending decision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Compliance Submission</label>
    <nameField>
        <displayFormat>IS-{0000}</displayFormat>
        <label>Compliance Submission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Submissions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/IRIS_Submission_TriggerHandler.cls
/*
*  Classname : Iriss_Submission_Trigger_Helper
*   Created By: Deloitte USI    
*   Created Date: 21-Feb-2014
*   Description: This class is used by trigger Iriss_Submission_AssignApprover to populate COE Assessor when the assessor
                 assigns the submission to himself/herself.
*   Version : 0.1 
*   Change Log
*   Version     Description                         Updated By
*    
*/

public class IRIS_Submission_TriggerHandler
{
    /* 
     * Method name : AssignAssessor
     * Description : This method is used to update the COE Assessor field when the Submission record is accepted 
     *                  and then change the status to in progress.
     * Param - lstSubmission: list of Submissions, oldSubMap: old map of id's and Submissions.
     * Returns :  void
    */
    public static void AssignAssessor(List<IRIS_Submission__c> lstSubmission, Map<Id, IRIS_Submission__c> oldSubMap)
    {
        String newOwnerId;
        String oldOwnerId;
        for(IRIS_Submission__c oSubmission : lstSubmission)
        {
            if(oSubmission.COE_Assessor__c == null)
            {
                newOwnerId = oSubmission.OwnerId;
                oldOwnerId = oldSubMap.get(oSubmission.id).ownerId;
                // update the COE Assessor and the status only when the record is accepted i.e the owner is changed from a queue to COE Assessor
                if(newOwnerId.startsWith('005') && newOwnerId != oldOwnerId)
                {
                    oSubmission.COE_Assessor__c = newOwnerId;
                    oSubmission.Status__c = IRIS_Constants.SUBMISSION_STATUS_IN_PROGRESS;
                }
            }
        }
    }

}