src/objects/IRIS_Assessment__c.object
<CustomObject>
    <description>Used to store the different types of Assessments which are independent of any submission</description>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Describes if the assessment is active or not</description>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Assessment</label>
    <nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IRIS_Assessment_Questions__c.object
<CustomObject>
    <description>Stores the relation between an assessment and a question</description>
    <fields>
        <fullName>Assessment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to assessment.</description>
        <label>Assessment</label>
        <referenceTo>IRIS_Assessment__c</referenceTo>
        <relationshipLabel>Assessment Questions</relationshipLabel>
        <relationshipName>Assessment_Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Number__c</fullName>
        <description>Represents the number associated with the question</description>
        <formula>Question__r.Question_Number__c</formula>
        <label>Ref</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Represent the actual question</description>
        <label>Question</label>
        <referenceTo>IRIS_Question__c</referenceTo>
        <relationshipLabel>Assessment Questions</relationshipLabel>
        <relationshipName>Assessment_Questions_Junction</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <description>Stores the sequence of the question on an assessment.</description>
        <label>Sequence</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Score__c</fullName>
        <defaultValue>5</defaultValue>
        <description>Stores the total score for a question.</description>
        <label>Total Score</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Assessment Question</label>
    <nameField>
        <displayFormat>AQ-{0000}</displayFormat>
        <label>Assessment Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IRIS_Country__c.object
<CustomObject>
    <description>Stores all the country.</description>
    <label>Country</label>
    <nameField>
        <label>Country</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IRIS_Question__c.object
<CustomObject>
    <description>Stores all the Questions. (not specific to an Assessment)</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked if the question is active.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question_Number__c</fullName>
        <description>Represents the number associated with a question.
For example &quot;G-001&quot;</description>
        <label>Ref</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Stores the questions of a particular Category.</description>
        <label>Question</label>
        <type>TextArea</type>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IRIS_Region__c.object
<CustomObject>
    <description>Stores all the region.</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IRIS_Region_Country__c.object
<CustomObject>
    <description>Junction object between country and Region Stores countries for a region.</description>
    <fields>
        <fullName>Country__c</fullName>
        <description>Stores country from country object.</description>
        <label>Country</label>
        <referenceTo>IRIS_Country__c</referenceTo>
        <relationshipLabel>Region Country Mappings</relationshipLabel>
        <relationshipName>Region_Country_Mappings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Stores the region from region object.</description>
        <label>Region</label>
        <referenceTo>IRIS_Region__c</referenceTo>
        <relationshipLabel>Region Country Mappings</relationshipLabel>
        <relationshipName>Region_Country_Mappings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Region Country Mapping</label>
    <nameField>
        <displayFormat>RCM-{0000}</displayFormat>
        <label>Region Country Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Region Country Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IRIS_Submission__c.object
<CustomObject>
    <description>Track and Mange document submissions</description>
    <fields>
        <fullName>COE_Category__c</fullName>
        <description>Type of policy applicable to the Local Document</description>
        <inlineHelpText>General description of the type of document that is being submitted</inlineHelpText>
        <label>COE Category</label>
        <picklist>
            <picklistValues>
                <fullName>Compliance Messaging Materials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR Investigations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local E&amp;C Procedures</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Document_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person who owns the document and is responsible for the content</description>
        <inlineHelpText>Name of the person who is responsible for the document; typically it is a leader that is accountable</inlineHelpText>
        <label>Document Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Iriss_Submissions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_Submitter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person submitting the document</description>
        <inlineHelpText>Defaults to the person who is submitting the document for review and approval</inlineHelpText>
        <label>Document Submitter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Iriss_Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Intended_Audience__c</fullName>
        <description>Audience for which the local document applies (Global, Regional, Local)</description>
        <inlineHelpText>Geographic scope of the document
Local: Specify one or more countries to which this document applies
Regional: Specify one or more regions to which this document applies
Global: Document applies worldwide</inlineHelpText>
        <label>Intended Audience</label>
        <picklist>
            <picklistValues>
                <fullName>Local</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Current workflow status of Local Document</description>
        <inlineHelpText>System generated description of the state of the document; status options include:  Submitted, In Progress, Awaiting Translation, Pending Decision, Approved, or Rejected</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting translation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending decision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <description>The policy requirement for which the document is referencing</description>
        <inlineHelpText>Specific type of document that is being submitted for review</inlineHelpText>
        <label>Sub-Category</label>
        <picklist>
            <controllingField>COE_Category__c</controllingField>
            <picklistValues>
                <fullName>Anti-bribery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anti-corruption</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conflicts of Interest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealing with Suppliers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EIC Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Message</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gifts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grants and Donations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HCP Transparency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hospitality and Entertainment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual HCP Sponsorships</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interactions with External Parties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interactions with Government and Public Officials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Investigation Procedure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meetings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partnering with External Organizations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Political Financial Support and Involvement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promotional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promotion of Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Providing Samples</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Policy Research and Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Relations Activities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red Book</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Safety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scientific Exchange</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Speaker Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship of Independent Meetings</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Compliance Submission</label>
    <nameField>
        <displayFormat>IS-{0000}</displayFormat>
        <label>Compliance Submission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Submissions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/IRIS_Test_Setup.cls
@isTest
public class IRIS_Test_Setup {
    
    public static IRIS_Region__c createRegion(String regionName)
    {
        IRIS_Region__c testRegion = new IRIS_Region__c(name=regionName);
        insert testRegion;
        return testRegion;
    }
    
    public static List<IRIS_Country__c> createCountries(List<String> lstCountryNames)
    {
        List<IRIS_Country__c> lstCountries = new List<IRIS_Country__c>();
        for(String countryName : lstCountryNames)
        {
            lstCountries.add(new IRIS_Country__c(name=countryName));    
        }
        insert lstCountries;
        return lstCountries;
    }
    
    public static List<IRIS_Region_Country__c> createRegionCountryMapping(IRIS_Region__c region, List<IRIS_Country__c> lstCountries)
    {
        List<IRIS_Region_Country__c> lstCountryRegion = new List<IRIS_Region_Country__c>();
        for(IRIS_Country__c country : lstCountries)
        {
            lstCountryRegion.add(new IRIS_Region_Country__c(Country__c=country.id, Region__c=region.id));
        }
        insert lstCountryRegion;
        return lstCountryRegion;
    }

    public static IRIS_Submission__c createSubmission() {
        IRIS_Submission__c oSubmission = new IRIS_Submission__c();
        oSubmission.COE_Category__c = 'HR Investigations';
        oSubmission.Sub_Category__c = 'General Message';
        oSubmission.Intended_Audience__c = IRIS_Constants.SUBMISSION_INTENDED_AUDIENCE_GLOBAL;
        oSubmission.Document_Owner__c = UserInfo.getUserId();
        oSubmission.Document_Submitter__c = UserInfo.getUserId();
        oSubmission.Status__c = IRIS_Constants.SUBMISSION_STATUS_SUBMITTED;
        insert oSubmission;
        return oSubmission;
    }
    
    public static List<IRIS_Question__c> createQuestions(integer iCount)
    {
        List<IRIS_Question__c> lstQuestions = new List<IRIS_Question__c>();
        for(integer i = 1; i<=iCount; i++)
        {
            lstQuestions.add(new IRIS_Question__c(Active__c=true, Question__c='This is question '+i,
                                                     Question_Number__c='QuesNo.'+i));
        }
        insert lstQuestions;
        return lstQuestions;
    }
    
    public static IRIS_Assessment__c createAssessment(String assessmentName)
    {
        IRIS_Assessment__c assessment = new IRIS_Assessment__c(isActive__c=true, name=assessmentName);
        insert assessment;
        return assessment;
    }
    
    public static List<IRIS_Assessment_Questions__c> createAssessQuestions(IRIS_Assessment__c assess, List<IRIS_Question__c> lstQues)
    {
        List<IRIS_Assessment_Questions__c> lstAssessQues = new List<IRIS_Assessment_Questions__c>();
        IRIS_Assessment_Questions__c assessQues;
        Double iCount = 1.0;
        for(IRIS_Question__c ques : lstQues)
        {
            assessQues = new IRIS_Assessment_Questions__c();
            assessQues.Assessment__c = assess.id;
            assessQues.Question__c = ques.id;
            assessQues.Total_Score__c = 5.0;
            assessQues.Sequence__c = iCount;
            iCount++;
            lstAssessQues.add(assessQues);
        }
        insert lstAssessQues;
        return lstAssessQues;   
    }
    
    public static User newAffiliateUser(){
        Profile oProfile = [SELECT Id FROM Profile WHERE Name=:IRIS_Constants.PROFILE_AFFILIATE_NAME]; 
        User oUser = new User(Alias = 'affuser', Email='testAffiliateUser@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', ProfileId = oProfile.Id, 
        TimeZoneSidKey='America/Los_Angeles', UserName='affiliateuser_test@testorg.com');
        insert oUser;
        return oUser;
    }
    
    public static User newAssessorUser(){
        Profile oProfile = [SELECT Id FROM Profile WHERE Name='System administrator'];
        PermissionSet oPerSer = [SELECT Id FROM PermissionSet WHERE Name=: IRIS_Constants.PROFILE_ASSESSOR_NAME];
        system.debug('oProfile '+oProfile );
        User oUser = new User(Alias = 'assuser', Email='testAssessorUser@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US',  ProfileId =oProfile.id,
        TimeZoneSidKey='America/Los_Angeles', UserName='assessoruser_test@testorg.com', FirstName = 'Assessor');
        insert oUser;
        //List<PermissionSetAssignment> lPermissionSetAssign = [SELECT Assignee.name, PermissionSet.name,PermissionSetId FROM PermissionSetAssignment where PermissionSet.Name=: IRIS_Constants.PROFILE_ASSESSOR_NAME' and AssigneeId =: oUserId Limit 1];
        PermissionSetAssignment pSA=new PermissionSetAssignment(AssigneeId =oUser.id, PermissionSetId=oPerSer.Id );
        return oUser;
    }
}