src/objects/IRIS_Submission__c.object
<CustomObject>
    <description>Track and Mange document submissions</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Current workflow status of Local Document</description>
        <inlineHelpText>System generated description of the state of the document; status options include:  Submitted, In Progress, Awaiting Translation, Pending Decision, Approved, or Rejected</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting translation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending decision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Compliance Submission</label>
    <nameField>
        <displayFormat>IS-{0000}</displayFormat>
        <label>Compliance Submission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Submissions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IRIS_Submission_Assessment__c.object
<CustomObject>
    <description>Represents the assessment taken on a submitted document</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Represents the current status of the assessment</description>
        <inlineHelpText>The status of the Submission Assessment</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In-Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submission__c</fullName>
        <description>Stores the associated submission record.</description>
        <label>Submission</label>
        <referenceTo>IRIS_Submission__c</referenceTo>
        <relationshipLabel>Submission Assessments</relationshipLabel>
        <relationshipName>Assessments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Submission Assessment</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Submission Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/IRIS_ApprovalHistory_ControllerExtension.cls
/*
*    Classname : Iriss_ApprovalHistoryExtensionController
*    Created By: Deloitte USI    
*    Created Date: 05-Mar-2014
*    Description: This class is used an extension for the Iriss_Approval_History page
*    Version : 0.1 
*    Change Log
*    Version     Description                         Updated By
*    
*/

public with sharing class IRIS_ApprovalHistory_ControllerExtension {

    public list<ProcessInstance> histories{get;set;}
    public IRIS_Submission__c oSubmission;

    public IRIS_ApprovalHistory_ControllerExtension (ApexPages.StandardController controller) {
        oSubmission = (IRIS_Submission__c)controller.getRecord();
        getApprovalHistory();
    }
    
    /* 
         * Method name : getApprovalHistory
         * Description : This method is used to retrive values form ProcessInstance object.
         * Param - No parameter 
         * Returns :  void
    */
    
    public void getApprovalHistory()
    {
        // querying the ProcessInstance object to get the approvals which need decesion.
        histories =  [select status , (select StepStatus,OriginalActor.Name , Actor.Name, CreatedDate 
                                                   from Steps
                                                   order by createdDate desc),
                                        (Select createdDate,OriginalActor.Name , Actor.Name
                                                   From Workitems
                                                   order by createdDate desc) 
                                       from ProcessInstance
                                       where targetobjectId = :oSubmission.id                                            
                                       order by createdDate desc limit :Limits.getLimitQueryRows()];
        
    }
    
    /* 
         * Method name : doApprove
         * Description : This method is used for redirecting to the Assessment page.
         * Param - No parameter 
         * Returns :  void
    */
    
    public PageReference doApprove(){
    
        // querying the submission assessment related to the compliance submission record
        IRIS_Submission_Assessment__c subAsses = [SELECT id FROM IRIS_Submission_Assessment__c 
                                                   WHERE Submission__c =:oSubmission.id and 
                                                        Status__c =: IRIS_Constants.SUBMISSION_ASSESSMENT_STATUS_COMPLETED
                                                   order by createddate desc limit 1];
        if(subAsses != null)
        {
            PageReference conPage = new PageReference('/apex/IRIS_Assessment_Approval?id='+subAsses.id);
            return conPage ;
        }
        return null;    
    }

}