src/objects/LookupRollupSummary_GLBL__c.object
<CustomObject>
    <description>Object defines a the fields on a child object to roll up to a parent object using Lookup Rollup functionality.

MERC : Created on 2014-05-27 by Joe Ferraro, Mavens Consulting</description>
    <fields>
        <fullName>Active_GLBL__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>For Realtime rollups can only be set when the Child Apex Trigger has been deployed.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AggregateOperation_GLBL__c</fullName>
        <inlineHelpText>Rollup operation.</inlineHelpText>
        <label>Aggregate Operation</label>
        <picklist>
            <picklistValues>
                <fullName>Sum</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Max</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Min</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Count</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>AggregateResultField_GLBL__c</fullName>
        <inlineHelpText>API name of the field that will store the result of the rollup on the Parent Object, e.g. AnnualRevenue</inlineHelpText>
        <label>Aggregate Result Field</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CalculateJobId_GLBL__c</fullName>
        <inlineHelpText>This field is used by the system when using the Calculate button to track if a calculation job is already running. Clear this field if the system reports the calculate job is already running and you known this is not the case.</inlineHelpText>
        <label>Calculate Job Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CalculationMode_GLBL__c</fullName>
        <inlineHelpText>Realtime mode requires an Apex Trigger to be deployed for the Child Object. Click Manage Child Trigger button to deploy.</inlineHelpText>
        <label>Calculation Mode</label>
        <picklist>
            <picklistValues>
                <fullName>Realtime</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Developer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ChildObject_GLBL__c</fullName>
        <inlineHelpText>API name of the Child Object, e.g. Opportunity</inlineHelpText>
        <label>Child Object</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldToAggregate_GLBL__c</fullName>
        <inlineHelpText>API name of the field on the Child Object that contains the value to rollup, e.g. Amount</inlineHelpText>
        <label>Field to Aggregate</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentObject_GLBL__c</fullName>
        <inlineHelpText>API name of the Parent Object, e.g. Account</inlineHelpText>
        <label>Parent Object</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RelationshipCriteriaFields_GLBL__c</fullName>
        <inlineHelpText>If you have specified a relationship criteria, you must confirm the fields referenced by it here on separate lines, for example for criteria StageName = &apos;Won&apos; list StageName in this field. You do not need to specify the Field to Aggregate field however.</inlineHelpText>
        <label>Relationship Criteria Fields</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>RelationshipCriteria_GLBL__c</fullName>
        <inlineHelpText>SOQL WHERE clause applied when querying Child Object records, e.g. Amount &gt; 200</inlineHelpText>
        <label>Relationship Criteria</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RelationshipField_GLBL__c</fullName>
        <inlineHelpText>API name of the Lookup field on the Child Object relating to the Parent Object, e.g. AccountId</inlineHelpText>
        <label>Relationship Field</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TreatZeroAsNull_GLBL__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If true, a zero calculation will be stamped as null</description>
        <inlineHelpText>If true, a zero calculation will be stamped as null</inlineHelpText>
        <label>TreatZeroAsNull</label>
        <type>Checkbox</type>
    </fields>
    <label>Lookup Rollup Summary</label>
    <nameField>
        <label>Lookup Rollup Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lookup Rollup Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GLBL_RollupSummariesSelector.cls
/**
 * Copyright (c) 2013, Andrew Fawcett
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 *   are permitted provided that the following conditions are met:
 *
 * - Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 * - Neither the name of the Andrew Fawcett, nor the names of its contributors
 *      may be used to endorse or promote products derived from this software without
 *      specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 *  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 *  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 *  THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 *  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 *  OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 *  OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 *  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**/

/**
 * Various queries for the Lookup Rollup Summary custom object
 **/
public with sharing class GLBL_RollupSummariesSelector extends GLBL_SObjectSelector
{
	public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField> {
			LookupRollupSummary_GLBL__c.Name,
			LookupRollupSummary_GLBL__c.Active_GLBL__c,
			LookupRollupSummary_GLBL__c.AggregateOperation_GLBL__c,
			LookupRollupSummary_GLBL__c.AggregateResultField_GLBL__c,
			LookupRollupSummary_GLBL__c.CalculationMode_GLBL__c,
			LookupRollupSummary_GLBL__c.ChildObject_GLBL__c,
			LookupRollupSummary_GLBL__c.FieldToAggregate_GLBL__c,
			LookupRollupSummary_GLBL__c.ParentObject_GLBL__c,
			LookupRollupSummary_GLBL__c.RelationshipCriteria_GLBL__c,
			LookupRollupSummary_GLBL__c.RelationshipCriteriaFields_GLBL__c,
			LookupRollupSummary_GLBL__c.RelationshipField_GLBL__c,
			LookupRollupSummary_GLBL__c.CalculateJobId_GLBL__c,
			LookupRollupSummary_GLBL__c.TreatZeroAsNull_GLBL__c
		};
	}

	public Schema.SObjectType getSObjectType()
	{
		return LookupRollupSummary_GLBL__c.sObjectType;
	}

	public List<LookupRollupSummary_GLBL__c> selectById(Set<ID> idSet)
	{
		return (List<LookupRollupSummary_GLBL__c>) selectSObjectsById(idSet);
	}
	/**
	 * Returns active lookup rollup summary definitions for thr given calculation mode and child object
	 **/
	public List<LookupRollupSummary_GLBL__c> selectActiveByChildObject(GLBL_RollupSummaries.CalculationMode calculationMode, Set<String> childObjectNames)
	{
		return selectActiveByChildObject(new List<GLBL_RollupSummaries.CalculationMode> { calculationMode }, childObjectNames);
	}

	/**
	 * Returns active lookup rollup summary definitions for thr given calculation modes and child object
	 **/
	public List<LookupRollupSummary_GLBL__c> selectActiveByChildObject(List<GLBL_RollupSummaries.CalculationMode> calculationModes, Set<String> childObjectNames)
	{
		assertIsAccessible();
		List<String> calculationModeNames = new List<String>();
		for(GLBL_RollupSummaries.CalculationMode calculationMode : calculationModes)
			calculationModeNames.add(calculationMode.name());

		return Database.query(String.format(
			'select {0} from {1} where CalculationMode_GLBL__c in :calculationModeNames and ChildObject_GLBL__c in :childObjectNames and Active_GLBL__c = true order by ParentObject_GLBL__c, RelationshipField_GLBL__c',
				new List<String>{getFieldListString(),
					getSObjectName(),
					getOrderBy()}));
	}
}