src/objects/LookupRollupSummary_GLBL__c.object
<CustomObject>
    <description>Object defines a the fields on a child object to roll up to a parent object using Lookup Rollup functionality.

MERC : Created on 2014-05-27 by Joe Ferraro, Mavens Consulting</description>
    <fields>
        <fullName>Active_GLBL__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>For Realtime rollups can only be set when the Child Apex Trigger has been deployed.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Lookup Rollup Summary</label>
    <nameField>
        <label>Lookup Rollup Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lookup Rollup Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GLBL_RollupCalculateControllerTest.cls
/**
 * @author Kyle Thornton
 *
 * Unit tests for the GLBL_RollupCalculateController class
 */
@isTest
private class GLBL_RollupCalculateControllerTest {

	@isTest static void test_should_runCalculateJob() {
		MERC_TestFactory.loadDeclarativeRollupSummaries();
		LookupRollupSummary_GLBL__c lookup = [SELECT Id FROM LookupRollupSummary_GLBL__c limit 1];

		Test.startTest();
		ApexPages.StandardController stdController = new ApexPages.StandardController(lookup);
		GLBL_RollupCalculateController controller = new GLBL_RollupCalculateController(stdController);

		controller.runCalculateJob();
		Test.stopTest();

		System.assertEquals('Calculate job started for this lookup.', ApexPages.getMessages().get(2).getSummary());
	}

	@isTest static void test_should_catch_error_on_runCalculateJob() {
		MERC_TestFactory.loadDeclarativeRollupSummaries();
		LookupRollupSummary_GLBL__c lookup = [SELECT Id, Active_GLBL__c FROM LookupRollupSummary_GLBL__c limit 1];
		lookup.Active_GLBL__c = false;
		update lookup;

		Test.startTest();
		ApexPages.StandardController stdController = new ApexPages.StandardController(lookup);
		GLBL_RollupCalculateController controller = new GLBL_RollupCalculateController(stdController);
		System.assertEquals(null, controller.runCalculateJob());
		Test.stopTest();

		System.assertEquals('The rollup must be Active before you can run a Calculate job.', ApexPages.getMessages().get(2).getSummary());
	}
}