src/objects/Meeting_Day_MERC__c.object
<CustomObject>
    <description>Object to track days of meetings and ToV cost of each day. Created 10/10/2013 by KLorenti.</description>
    <fields>
        <fullName>Date_MERC__c</fullName>
        <description>Date of the Meeting Day. Created 10/10/2013 by KLorenti.</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Meeting_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship to Meeting. Created 10/10/2013 by KLorenti</description>
        <label>Meeting</label>
        <referenceTo>Meeting_MERC__c</referenceTo>
        <relationshipLabel>Meeting Days</relationshipLabel>
        <relationshipName>Meeting_Days</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Meeting Day</label>
    <nameField>
        <label>Meeting Day</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Meeting_MERC__c.object
<CustomObject>
</CustomObject>

src/objects/Meeting_Participant_MERC__c.object
<CustomObject>
</CustomObject>

src/objects/Meeting_Vendor_MERC__c.object
<CustomObject>
</CustomObject>

src/objects/Travel_Itinerary_MERC__c.object
<CustomObject>
</CustomObject>

src/classes/MERC_MeetingParticipantStressTest.cls
@isTest
private class MERC_MeetingParticipantStressTest {

	static List<Meeting_MERC__c> meetings;
	static List<Account> accounts;
	static List<Meeting_Day_MERC__c> meetingDays;
	static List<Meeting_Participant_MERC__c> participants;
	static List<Meeting_Vendor_MERC__c> hotels;
	static MERC_DailyAttendanceController controller;
	static List<Travel_Itinerary_MERC__c> hotelItineraries;
	static Meeting_MERC__c meeting;

	static {
		//accounts = MERC_TestFactory.insertAccounts(100); //insert 100 accounts
		accounts = [SELECT ID, FirstName, LastName, RecordTypeId, PersonEmail FROM Account WHERE RecordTypeId = :MERC_TestFactory.hcpRecordTypeId limit 100];
		meetings = MERC_TestFactory.insertMeetings(1); //insert 1 meetings
		meeting = meetings.get(0);
		meetingDays = MERC_TestFactory.insertMeetingDays(meeting.Id, 3); //insert 3 days
		hotels = MERC_TestFactory.insertHotelsForMeeting(2, meeting.Id);
		participants = MERC_TestFactory.insertParticipants(meeting.Id, accounts);
		hotelItineraries = MERC_TestFactory.insertHotelItineraries(participants, meetingDays.get(0).Date_MERC__c, meetingDays.get(2).Date_MERC__c);
	}

	@isTest static void run_stress_test() {
		MERC_TestFactory.insertParticipants(meetings.get(0).Id, accounts);
	}

}