src/objects/Meeting_Email_Send_MERC__c.object
<CustomObject>
    <description>Junction object used for custom ExactTarget Email integration for Meetings</description>
    <fields>
        <fullName>Send_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Email</label>
        <type>Checkbox</type>
    </fields>
    <label>Meeting Email Send</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Meeting Email Send #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Email Sends</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MeetingEmailSendTriggerImpl.cls
public without sharing class MeetingEmailSendTriggerImpl {
    public MeetingEmailSendTriggerImpl() {}

    public void doAfterInsert (Meeting_Email_Send_MERC__c[] newSends, Map<Id, Meeting_Email_Send_MERC__c> newSendsMap) {
        List<Meeting_Email_Send_MERC__c> filteredSends = filterSends(null, newSends, newSendsMap);
        if (filteredSends.size() > 0) {
            MeetingEmailSendFutureProcessor.handleSendDefinitionProcessForMeetingEmailSend(filteredSends[0].Id);
        }
    }

    public void doAfterUpdate (Meeting_Email_Send_MERC__c[] oldSends, Meeting_Email_Send_MERC__c[] newSends, Map<Id, Meeting_Email_Send_MERC__c> newSendsMap) {
        List<Meeting_Email_Send_MERC__c> filteredSends = filterSends(oldSends, newSends, newSendsMap);
        if (filteredSends.size() > 0) {
            MeetingEmailSendFutureProcessor.handleSendDefinitionProcessForMeetingEmailSend(filteredSends[0].Id);
        }
    }

    @TestVisible
    private List<Meeting_Email_Send_MERC__c> filterSends(Meeting_Email_Send_MERC__c[] oldSends, Meeting_Email_Send_MERC__c[] newSends, Map<Id, Meeting_Email_Send_MERC__c> newSendsMap) {
        List<Meeting_Email_Send_MERC__c> retVal = new List<Meeting_Email_Send_MERC__c>();

        if (oldSends == null) {
            for (Meeting_Email_Send_MERC__c mes : newSends) {
                if (mes.Send_Email__c) {
                    retVal.add(mes);
                }
            }
        } else {
            for (Meeting_Email_Send_MERC__c oldMES : oldSends) {
                Meeting_Email_Send_MERC__c currMES = newSendsMap.get(oldMES.Id);
                if (oldMES.Send_Email__c == false && currMES.Send_Email__c == true) {
                    retVal.add(currMES);
                }
            }
        }

        return retVal;
    }
}