src/objects/Meeting_MERC__c.object
<CustomObject>
</CustomObject>

src/objects/Team_Member_MERC__c.object
<CustomObject>
    <fields>
        <fullName>Role_MERC__c</fullName>
        <description>Tracks Role of Team Members for a Meeting. Created 9/30/2013 by KLorenti.</description>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Budget Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Facing Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Budget Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Host Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International Event Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local CMS Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local CMS Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting Planning Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onsite Attendance Checker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary Meeting Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel Agent</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/MERC_PrimaryMeetingOwnerHandler.cls
/**
 * @author Kyle Thornton
 *
 * Trigger handler that adds a mercury user to the meeting team as a Primary Meeting Owner
 *   when they create a new meeting.
 */

public with sharing class MERC_PrimaryMeetingOwnerHandler implements GLBL_TriggerHandler.HandlerInterface{

	public void handle()
    {
    	List<Team_Member_MERC__c> primaryOwnerTeamMembers = new List<Team_Member_MERC__c>();
    	for (Meeting_MERC__c m : (List<Meeting_MERC__c>)Trigger.new)
    	{
    		if (m.Source_MERC__c == 'Mercury')
    		{
				Team_Member_MERC__c teamMember = new Team_Member_MERC__c();
				teamMember.User_MERC__c        = m.CreatedById;
				teamMember.Role_MERC__c        = 'Primary Meeting Owner';
				teamMember.Meeting_MERC__c     = m.id;
    			primaryOwnerTeamMembers.add(teamMember);
    		}
    	}

    	insert primaryOwnerTeamMembers;
    }
}