src/objects/Meeting_Email_Send_MERC__c.object
<CustomObject>
    <description>Junction object used for custom ExactTarget Email integration for Meetings</description>
    <fields>
        <fullName>ET_Dedupe_Subscribers_MERC__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ET Dedupe Subscribers</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ET_Email_ID_MERC__c</fullName>
        <label>ET Email ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ET_From_Email_MERC__c</fullName>
        <label>ET From Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ET_From_Name_MERC__c</fullName>
        <label>ET From Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ET_Send_Definition_MERC__c</fullName>
        <label>ET Send Definition</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ET_Subject_MERC__c</fullName>
        <label>ET Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Send_Number_MERC__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Email Send Number</label>
        <referenceTo>et4ae5__SendDefinition__c</referenceTo>
        <relationshipLabel>Meeting Email Sends</relationshipLabel>
        <relationshipName>Meeting_Email_Sends</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Incomplete_MERC__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Incomplete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Meeting_MERC__c</fullName>
        <label>Meeting</label>
        <referenceTo>Meeting_MERC__c</referenceTo>
        <relationshipLabel>Meeting Email Sends</relationshipLabel>
        <relationshipName>Meeting_Email_Sends</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Retry_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Retry Count</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Retry_Date__c</fullName>
        <label>Retry Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Send_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Send_Status__c</fullName>
        <label>Send Status</label>
        <picklist>
            <picklistValues>
                <fullName>Create Sender Profile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Create Send Definition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Start Send Definition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Send Status</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Send Created</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Meeting Email Send</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Meeting Email Send #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Email Sends</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Meeting_MERC__c.object
<CustomObject>
</CustomObject>

src/classes/Test_MeetingEmailSendFutureProcessor.cls
@isTest
private class Test_MeetingEmailSendFutureProcessor {

    private static Meeting_Email_Send_MERC__c setup() {
        et4ae5__configuration__c etConfig = TestUtils.CreateEtConfig();
        etConfig.et4ae5__Root_Rest_API_URL__c = 's1.qa1';
        etConfig.et4ae5__Auth_API_URL__c = 'www.testauthurl.com/Auth.svc';
        insert etConfig;
        
        MERC_TriggerHandlerStateManager.deactivate(MERC_PrimaryMeetingOwnerHandler.class);
        List<Meeting_MERC__c> meetings = TestUtils.CreateMeetings(1);
        insert meetings;
        
        Meeting_Email_Send_MERC__c meetingEmailSend = TestUtils.createMeetingEmailSend(meetings[0].Id, 1)[0];
        
        setupMeetingEmailSends(meetingEmailSend);
        return meetingEmailSend;
    }
    
    private static void setupMeetingEmailSends(Meeting_Email_Send_MERC__c meetingEmailSend) {
        meetingEmailSend.ET_From_Name_MERC__c = 'Eli Lilly';
        meetingEmailSend.ET_From_Email_MERC__c = 'cmseurope@lilly.com';
        meetingEmailSend.ET_Dedupe_Subscribers_MERC__c = false;
        meetingEmailSend.ET_Email_ID_MERC__c = '1234';
        meetingEmailSend.ET_Subject_MERC__c = 'Test Subject';
        //Set Send Email to false to avoid triggering the callout in the trigger
        meetingEmailSend.Send_Email__c = false;
    }
    
    private static void testOneStepSendError(string sendStatus) {
    	Meeting_Email_Send_MERC__c meetingEmailSend = setup();

        meetingEmailSend.Send_Status__c = sendStatus;
        insert meetingEmailSend;
        
        Mock_ETSendAndAuthorize mockSend = new Mock_ETSendAndAuthorize();
        mockSend.returnError = true;
        
        Test.startTest();
            Test.setMock(HttpCalloutMock.class, mockSend);
            MeetingEmailSendFutureProcessor.handleSendDefinitionProcessForMeetingEmailSend(meetingEmailSend.Id);
        Test.stopTest();
       
        meetingEmailSend = [SELECT Retry_Date__c, Email_Send_Number_MERC__c, Send_Status__c
                            FROM Meeting_Email_Send_MERC__c 
                            WHERE Id=: meetingEmailSend.Id];
                            
        system.assertNotEquals(meetingEmailSend.Retry_Date__c, null);
        system.assertEquals(meetingEmailSend.Email_Send_Number_MERC__c, null);
        system.assertEquals(meetingEmailSend.Send_Status__c, sendStatus);
    }
    
    private static testmethod void test_MeetingEmailSendFutureProcessor_sendSuccesfully() {
        Meeting_Email_Send_MERC__c meetingEmailSend = setup();

        insert meetingEmailSend;
        
        Mock_ETSendAndAuthorize mockSend = new Mock_ETSendAndAuthorize();
        mockSend.sendCheckStatusResponseComplete = true;
        Test.startTest();
            Test.setMock(HttpCalloutMock.class, mockSend);
            MeetingEmailSendFutureProcessor.handleSendDefinitionProcessForMeetingEmailSend(meetingEmailSend.Id);
        Test.stopTest();
       
        meetingEmailSend = [SELECT Incomplete_MERC__c, Retry_Date__c, Email_Send_Number_MERC__c, Send_Status__c
                            FROM Meeting_Email_Send_MERC__c 
                            WHERE Id=: meetingEmailSend.Id];
                            
        system.assertEquals(meetingEmailSend.Incomplete_MERC__c, false);
        system.assertEquals(meetingEmailSend.Retry_Date__c, null);
        system.assertNotEquals(meetingEmailSend.Email_Send_Number_MERC__c, null);
        system.assertEquals(meetingEmailSend.Send_Status__c, 'Email Send Created');
    }
    
    public static testmethod void test_MeetingEmailSendFutureProcessor_checkSendStatusStillProcessing() {
    	Meeting_Email_Send_MERC__c meetingEmailSend = setup();

        meetingEmailSend.Send_Status__c = 'Check Send Status';
        meetingEmailSend.ET_Send_Definition_MERC__c = 'abc';
        insert meetingEmailSend;
        
        Test.startTest();
            Test.setMock(HttpCalloutMock.class, new Mock_ETSendAndAuthorize());
            MeetingEmailSendFutureProcessor.handleSendDefinitionProcessForMeetingEmailSend(meetingEmailSend.Id);
        Test.stopTest();
       
        meetingEmailSend = [SELECT Incomplete_MERC__c, Retry_Date__c, Email_Send_Number_MERC__c, Send_Status__c
                            FROM Meeting_Email_Send_MERC__c 
                            WHERE Id=: meetingEmailSend.Id];
                            
        system.assertEquals(meetingEmailSend.Incomplete_MERC__c, false);
        system.assertNotEquals(meetingEmailSend.Retry_Date__c, null);
        system.assertNotEquals(meetingEmailSend.Email_Send_Number_MERC__c, null);
        system.assertEquals(meetingEmailSend.Send_Status__c, 'Check Send Status');
    }
    
    public static testmethod void test_MeetingEmailSendFutureProcessor_checkSendStatusCompleteExistingETSEnd() {
        Meeting_Email_Send_MERC__c meetingEmailSend = setup();

        meetingEmailSend.Send_Status__c = 'Check Send Status';
        meetingEmailSend.ET_Send_Definition_MERC__c = 'abc';
        insert meetingEmailSend;
        
        et4ae5__SendDefinition__c send = new et4ae5__SendDefinition__c();
        send.et4ae5__SyncComplete__c = true;
        send.et4ae5__TrackingOnly__c = true;
        send.et4ae5__FromName__c = meetingEmailSend.ET_From_Name_MERC__c;
        send.et4ae5__FromEmail__c = meetingEmailSend.ET_From_Email_MERC__c;
        send.et4ae5__DedupeSubscribers__c = meetingEmailSend.ET_Dedupe_Subscribers_MERC__c;
        send.et4ae5__EmailId__c = meetingEmailSend.ET_Email_ID_MERC__c;
        send.et4ae5__Subject__c = meetingEmailSend.ET_Subject_MERC__c;
        send.et4ae5__ETSendDef__c = meetingEmailSend.ET_Send_Definition_MERC__c;
        
        insert send;
        
        meetingEmailSend.Email_Send_Number_MERC__c = send.Id;
        
        update meetingEmailSend;
        Mock_ETSendAndAuthorize mockSend = new Mock_ETSendAndAuthorize();
        mockSend.sendCheckStatusResponseComplete = true;
        
        Test.startTest();
            Test.setMock(HttpCalloutMock.class, mockSend);
            MeetingEmailSendFutureProcessor.handleSendDefinitionProcessForMeetingEmailSend(meetingEmailSend.Id);
        Test.stopTest();
       
        send = [SELECT Id, et4ae5__SendStatus__c FROM et4ae5__SendDefinition__c where Id =: send.Id];
        
        system.assertEquals(send.et4ae5__SendStatus__c, 'Completed');
    }
    
    public static testmethod void test_MeetingEMailSendFutureProcessor_hitMaxRetry() {
    	Meeting_Email_Send_MERC__c meetingEmailSend = setup();

        meetingEmailSend.Retry_Count__c = 1;
        insert meetingEmailSend;
        
        Mock_ETSendAndAuthorize mockSend = new Mock_ETSendAndAuthorize();
        mockSend.returnError = true;
        Test.startTest();
            Test.setMock(HttpCalloutMock.class, mockSend);
            MeetingEmailSendFutureProcessor.handleSendDefinitionProcessForMeetingEmailSend(meetingEmailSend.Id);
        Test.stopTest();
       
        meetingEmailSend = [SELECT Incomplete_MERC__c, Retry_Date__c, Email_Send_Number_MERC__c, Send_Status__c
                            FROM Meeting_Email_Send_MERC__c 
                            WHERE Id=: meetingEmailSend.Id];
                            
        system.assertEquals(meetingEmailSend.Incomplete_MERC__c, true);
        system.assertEquals(meetingEmailSend.Retry_Date__c, null);
        system.assertEquals(meetingEmailSend.Email_Send_Number_MERC__c, null);
        system.assertEquals(meetingEmailSend.Send_Status__c, 'Create Sender Profile');
    }
    
    public static testmethod void test_MeetingEMailSendFutureProcessor_hitMaxRetryCheckSendStatus() {
        Meeting_Email_Send_MERC__c meetingEmailSend = setup();

        meetingEmailSend.Retry_Count__c = 298;
        meetingEMailSend.Send_Status__c = 'Check Send Status';
        insert meetingEmailSend;
        
        Test.startTest();
            Test.setMock(HttpCalloutMock.class, new Mock_ETSendAndAuthorize());
            MeetingEmailSendFutureProcessor.handleSendDefinitionProcessForMeetingEmailSend(meetingEmailSend.Id);
        Test.stopTest();
       
        meetingEmailSend = [SELECT Incomplete_MERC__c, Retry_Date__c, Email_Send_Number_MERC__c, Send_Status__c
                            FROM Meeting_Email_Send_MERC__c 
                            WHERE Id=: meetingEmailSend.Id];
                            
        system.assertEquals(meetingEmailSend.Incomplete_MERC__c, true);
        system.assertEquals(meetingEmailSend.Retry_Date__c, null);
        system.assertEquals(meetingEmailSend.Email_Send_Number_MERC__c, null);
        system.assertEquals(meetingEmailSend.Send_Status__c, 'Check Send Status');
    }
    
    public static testmethod void test_MeetingEmailSendFutureProcessor_errorOnCreateSenderProfile() {
    	testOneStepSendError('Create Sender Profile');
    }
    
    public static testmethod void test_MeetingEmailSendFutureProcessor_errorOnCreateSendDefinition() {
        testOneStepSendError('Create Send Definition');
    }
    
    public static testmethod void test_MeetingEmailSendFutureProcessor_errorOnCreateStartSendDefinition() {
        testOneStepSendError('Start Send Definition');
    }
    
    public static testmethod void test_MeetingEmailSendFutureProcessor_errorOnCreateCheckSendStatus() {
        testOneStepSendError('Check Send Status');
    }
    
    //Disable this test as the functionality is disabled
    //public static testmethod void test_MeetingEmailSendFutureProcessor_copyAttachments() {
        //Meeting_Email_Send_MERC__c meetingEmailSend = setup();

        //meetingEmailSend.Send_Status__c = 'Check Send Status';
        //meetingEmailSend.ET_Send_Definition_MERC__c = 'abc';
        //insert meetingEmailSend;	
        
        //Attachment emailSendAttachment = new Attachment();
	    //emailSendAttachment.ParentId = meetingEmailSend.Id;
	    //emailSendAttachment.Body = Blob.valueOf('abc');
	    //emailSendAttachment.Name = 'Attachment';
	    
	    //insert emailSendAttachment;
	    
	    //Test.startTest();
            //Test.setMock(HttpCalloutMock.class, new Mock_ETSendAndAuthorize());
            //MeetingEmailSendFutureProcessor.handleSendDefinitionProcessForMeetingEmailSend(meetingEmailSend.Id);
        //Test.stopTest();
        
        //meetingEmailSend = [SELECT Email_Send_Number_MERC__c FROM Meeting_Email_Send_MERC__c WHERE Id =: meetingEmailSend.Id];
        
        //List<Attachment> emailSendAttachments = [SELECT Id FROM Attachment WHERE ParentId =: meetingEmailSend.Email_Send_Number_MERC__c];
                
        //system.assertEquals(emailSendAttachments.size(), 1);
    //}
    
}