src/objects/Meeting_Day_MERC__c.object
<CustomObject>
    <description>Object to track days of meetings and ToV cost of each day. Created 10/10/2013 by KLorenti.</description>
    <fields>
        <fullName>Date_MERC__c</fullName>
        <description>Date of the Meeting Day. Created 10/10/2013 by KLorenti.</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Meeting_MERC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship to Meeting. Created 10/10/2013 by KLorenti</description>
        <label>Meeting</label>
        <referenceTo>Meeting_MERC__c</referenceTo>
        <relationshipLabel>Meeting Days</relationshipLabel>
        <relationshipName>Meeting_Days</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meeting_Time_Zone_MERC__c</fullName>
        <formula>text(Meeting_MERC__r.Meeting_Time_Zone_MERC__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Meeting Time Zone</label>
        <type>Text</type>
    </fields>
    <label>Meeting Day</label>
    <nameField>
        <label>Meeting Day</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Meeting_MERC__c.object
<CustomObject>
</CustomObject>

src/classes/MERC_MeetingDayNewEditController.cls
public with sharing class MERC_MeetingDayNewEditController {

	private final Meeting_Day_MERC__c meetingDay;
    ApexPages.StandardController stdController;
    MERC_TimeZoneUtility tz = new MERC_TimeZoneUtility(Meeting_Day_MERC__c.sObjectType);

    public MERC_MeetingDayNewEditController(ApexPages.StandardController c) {
        this.meetingDay = (Meeting_Day_MERC__c)c.getRecord();
        this.stdController = c;
        if (this.meetingDay.Id == null) {
            this.meetingDay.Date_MERC__c = meeting.Date_of_Event_MERC__c;
        }
    }

    //sets date/times based on meeting time/zone, for UX purposes
    public void setTimeZones() {
        tz.convertDateTimes(new List<Sobject>{this.meetingDay}, false, meeting.Meeting_Time_Zone_MERC__c);
    }

    public Meeting_MERC__c meeting {
        get {
            if (meeting == null) {
                meeting = [SELECT ID, Name, Date_of_Event_MERC__c, Meeting_Time_Zone_MERC__C FROM Meeting_MERC__c WHERE ID = :this.meetingDay.Meeting_MERC__c];
            }
            return meeting;
        }
        private set;
    }

    public Map<String,String> fieldSetLabels {
    	get {
    		if (fieldSetLabels == null) {
    			fieldSetLabels = MERC_Util.getFieldSetLabels(
	    			Meeting_Day_MERC__c.SobjectType, 
	    			new List<String> {
	    				'Meeting_Day_Daily_Amounts_MERC',
	    				'Meeting_Day_Basic_Information_MERC',
	    				'Meeting_Day_Date_Information_MERC'
	    			}
	    		);
    		}
    		return fieldSetLabels;
    	}
    	private set;
    }

    public PageReference save() {
        try {
            tz.convertDateTimes(new List<Sobject>{this.meetingDay}, true, meeting.Meeting_Time_Zone_MERC__c); //sets date/times based on UTC, stamps static text with "user-friendly" date/time values
            if (this.meetingDay.Id == null) {
                insert this.meetingDay;
            } else {
                update this.meetingDay; 
            }
        } catch(Exception e) {
            ApexPages.addMessages(e); //doesn't show ugly error text
            return null;
        }
        PageReference p = new PageReference('/'+this.meetingDay.Id);
        return p;
    }
}