src/objects/Meeting_MERC__c.object
<CustomObject>
</CustomObject>

src/objects/Team_Member_MERC__c.object
<CustomObject>
    <fields>
        <fullName>Role_MERC__c</fullName>
        <description>Tracks Role of Team Members for a Meeting. Created 9/30/2013 by KLorenti.</description>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Budget Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Facing Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Budget Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Host Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International Event Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local CMS Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local CMS Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting Planning Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onsite Attendance Checker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary Meeting Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel Agent</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/MERC_TeamMemberDeletePMO.cls
public class MERC_TeamMemberDeletePMO  implements GLBL_TriggerHandler.HandlerInterface {

    public static final String PMO = 'Primary Meeting Owner';

    public void handle() {
        if (Trigger.isDelete) {
            execute(Trigger.old);
        }
    }

    public void execute(List<Sobject> sObjects) {        
        List<Team_Member_MERC__c> teamMembers = (List<Team_Member_MERC__c>) sObjects;
        List<Team_Member_MERC__c> teamMembersToProcess = new List<Team_Member_MERC__c>();

        for (Team_Member_MERC__c tm : teamMembers) {
            if (tm.Role_MERC__c == PMO) teamMembersToProcess.add(tm);
        }

        List<Meeting_MERC__c> meetingsToUpdate = new List<Meeting_MERC__c>([
                SELECT Id, Meeting_Owner_Email_MERC__c, Prmry_Mtng_Ownr_Nm_MERC__c FROM Meeting_MERC__c 
                WHERE Id in (SELECT Meeting_MERC__c FROM Team_Member_MERC__c WHERE Id in :teamMembersToProcess)
            ]);
        for (Meeting_MERC__c m : meetingsToUpdate) {
            m.Meeting_Owner_Email_MERC__c = null;
            m.Prmry_Mtng_Ownr_Nm_MERC__c = null;
        }
        update meetingsToUpdate;
    }
}