src/objects/Meeting_MERC__c.object
<CustomObject>
</CustomObject>

src/objects/Meeting_Participant_MERC__c.object
<CustomObject>
</CustomObject>

src/objects/Meeting_Process_MERC__c.object
<CustomObject>
    <description>Groups to-do items for all meeting management functions : MERC : Created on 17/06/2015 by Kyle Thornton, Mavens Consulting</description>
    <fields>
        <fullName>Meeting_Participant_MERC__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Associates the Meeting Process to a specific meeting participant : MERC : Created on 17/06/2015 by Kyle Thornton, Mavens Consulting</description>
        <label>Meeting Participant</label>
        <referenceTo>Meeting_Participant_MERC__c</referenceTo>
        <relationshipLabel>Meeting Processes</relationshipLabel>
        <relationshipName>Meeting_Processes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process_Type_MERC__c</fullName>
        <description>Indicates the type of process : MERC : Created on 17/06/2015 by Kyle Thornton, Mavens Consulting</description>
        <label>Process Type</label>
        <picklist>
            <picklistValues>
                <fullName>Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel Proposal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Meeting Information</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Meeting Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Meeting_Tasks_MERC__c.object
<CustomObject>
    <description>Captures to-do items for all meeting management functions : MERC : Created on 21/04/2015 by Oliver Dunford, Mavens Consulting</description>
    <fields>
        <fullName>Meeting_MERC__c</fullName>
        <description>Pulls down the meeting id. Used in trigger to pass to the lockedrecordhandler : MERC :  Created on 23/04/2015 by Kyle Thornton, Mavens Consulting</description>
        <formula>Meeting_Process_MERC__r.Meeting_Participant_MERC__r.Meeting_MERC__c</formula>
        <label>Meeting</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meeting_Participant_MERC__c</fullName>
        <description>Pulls the meeting partcipant Id down to the Task : MERC : Created on 17/06/2015 by Kyle Thornton, Mavens Consulting</description>
        <formula>Meeting_Process_MERC__r.Meeting_Participant_MERC__c</formula>
        <label>Meeting Participant</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meeting_Process_MERC__c</fullName>
        <description>Relates a meeting task to it&apos;s parent process : MERC : Created on 17/06/2015 by Kyle Thornton, Mavens Consulting</description>
        <label>Meeting Process</label>
        <referenceTo>Meeting_Process_MERC__c</referenceTo>
        <relationshipLabel>Meeting Tasks</relationshipLabel>
        <relationshipName>Meeting_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Process_Type_MERC__c</fullName>
        <description>Indicates the meeting type : MERC : Created on 22/06/2015 by Kyle Thornton, Mavens Consulting</description>
        <formula>TEXT(Meeting_Process_MERC__r.Process_Type_MERC__c)</formula>
        <label>Process Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Status_MERC__c</fullName>
        <description>Stores the Status of each Task, drives automation : MERC : Created on 21/04/2015 by Oliver Dunford, Mavens Consulting</description>
        <inlineHelpText>The Status of the current Meeting Task.  For example, &quot;Completed&quot; would indicate that you have completed a Follow Up task by contacting the HCP.  There may be several Follow Up tasks for each Process.</inlineHelpText>
        <label>Task Status</label>
        <picklist>
            <picklistValues>
                <fullName>Incomplete</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed - Continue Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed - Process Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed - Process Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed - Unresponsive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Meeting Task</label>
    <nameField>
        <label>Meeting Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MERC_MeetingTaskEditorControllerTest.cls
/*
* MERC_MeetingTaskEditorControllerTest
* Description : Test the MeetingTaskEditor controller. The MeetingTaskEditorController 
*               provides functionality for MERC_MeetingTaskEditor.page.
* Author: Rick Locke (Mavens Consulting)
* Created Date: July 13, 2015
*/

@isTest
private class MERC_MeetingTaskEditorControllerTest {


	private static Meeting_MERC__c buildData() {

		//create data necessary for MeetingTaskEditor page.
		Meeting_MERC__c meeting = Merc_TestFactory.insertMeetings(1)[0];
		Account acc = Merc_TestFactory.insertAccounts(1)[0];
		Meeting_Participant_MERC__c participant = Merc_TestFactory.insertParticipants(meeting.Id, new List<Account>{acc})[0];

		Meeting_Process_MERC__c process = new Meeting_Process_MERC__c(
			Meeting_Participant_MERC__c = participant.Id,
			Process_Type_MERC__c = 'Registration'
			);

		insert process;

		List<Meeting_Tasks_MERC__c> tasks = new List<Meeting_Tasks_MERC__c>();

		Meeting_Tasks_MERC__c task0 = new Meeting_Tasks_MERC__c(
			Meeting_Process_MERC__c = process.Id,
			Task_Status_MERC__c = 'Completed - Process Complete'
			);

		tasks.add(task0);

		Meeting_Tasks_MERC__c task1 = new Meeting_Tasks_MERC__c(
			Meeting_Process_MERC__c = process.Id,
			Task_Status_MERC__c = 'Completed - Process Complete'
			);

		tasks.add(task1);

		Meeting_Tasks_MERC__c task2 = new Meeting_Tasks_MERC__c(
			Meeting_Process_MERC__c = process.Id,
			Task_Status_MERC__c = 'Completed - Process Complete'
			);

		tasks.add(task2);

		insert tasks;

		return meeting;

	}

	@isTest static void controllerUsageWithDataTest() {

		Meeting_MERC__c meeting = buildData();

		PageReference pageRef = Page.MERC_MeetingTaskEditor;
		Test.setCurrentPage(pageRef);    

		//Add parameters to page URL
		ApexPages.currentPage().getParameters().put('meetingid', meeting.Id);

		MERC_MeetingTaskEditorController controller = new MERC_MeetingTaskEditorController();

		Meeting_Process_MERC__c filterProcess = controller.filterProcess;
		filterProcess.Process_Type_MERC__c = 'Registration';

		Meeting_Tasks_MERC__c filterTask = controller.filterTask;
		filterTask.Task_Status_MERC__c = 'Completed - Process Complete';

		System.debug('##### getMeetingHeader = ' + controller.getMeetingHeader());
		System.debug('##### getHasPrevious = ' + controller.getHasPrevious());
		System.debug('##### getHasNext = ' + controller.getHasNext());
		System.assertEquals(false, controller.getHasPrevious());
		System.assertEquals(false, controller.getHasNext());

		System.debug('##### meetingTasks.getHasPrevious = ' + controller.meetingTasks.getHasPrevious());
		System.debug('##### meetingTasks.getHasNext = ' + controller.meetingTasks.getHasNext());
		System.debug('##### meetingTasks.getPageNumber' + controller.meetingTasks.getPageNumber());
		System.assertEquals(false, controller.meetingTasks.getHasPrevious());
		System.assertEquals(false, controller.meetingTasks.getHasNext());
		System.assertEquals(1, controller.meetingTasks.getPageNumber());

		System.debug('##### updateTasks = ' + controller.updateTasks());
		pageRef = controller.updateTasks();

		System.debug('##### returnToMeeting = ' + controller.returnToMeeting());
		pageRef = controller.returnToMeeting();

		System.debug('##### updateSelected = ' + controller.updateSelected());
		controller.tasks[0].selected = true;
		controller.updateTask.Task_Status_MERC__c = 'Complete - Unresponsive';
		pageRef = controller.updateSelected();

		controller.tasks[0].selected = true;
		controller.tasks[1].selected = true;
		controller.updateTask.Task_Status_MERC__c = 'Complete - Process Complete';
		pageRef = controller.updateSelected();

		System.debug('##### accountNameSuffix = ' + controller.accountNameSuffix);
		System.assertEquals(controller.meetingProcessSuffix, ' ');
		System.assertEquals(controller.meetingTaskSuffix, ' ');
		System.assertEquals(controller.meetingParticipantSuffix, ' ');
		System.assertEquals(controller.recordTypeSuffix, ' ');
		System.assertEquals(controller.taskStatusSuffix, ' ');
		System.assertEquals(controller.dueDateSuffix, ' ');
		System.assertEquals(controller.accountNameSuffix, '^');

		controller.sortField = 'Meeting_Process_MERC__r.Meeting_Participant_MERC__r.Account_MERC__r.Name';
		System.assertEquals(controller.accountNameSuffix, 'v');		

		controller.sortField = 'Meeting_Process_MERC__r.Meeting_Participant_MERC__r.Account_MERC__r.Name';
		System.assertEquals(controller.accountNameSuffix, '^');		


	}

	@isTest static void parameterMissingTest() {

		PageReference pageRef = Page.MERC_MeetingTaskEditor;
		Test.setCurrentPage(pageRef);    

		MERC_MeetingTaskEditorController controller = new MERC_MeetingTaskEditorController();
	}
}