src/objects/Meeting_MERC__c.object
<CustomObject>
</CustomObject>

src/objects/Meeting_Participant_MERC__c.object
<CustomObject>
</CustomObject>

src/objects/Travel_Itinerary_MERC__c.object
<CustomObject>
    <fields>
        <fullName>Segment_Begin_Timezone_MERC__c</fullName>
        <label>Segment Begin Timezone</label>
        <picklist>
            <picklistValues>
                <fullName>Line Islands Time (Pacific/Kiritimati)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chatham Daylight Time (Pacific/Chatham)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Zealand Daylight Time (Pacific/Auckland)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phoenix Islands Time (Pacific/Enderbury)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fiji Summer Time (Pacific/Fiji)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tonga Time (Pacific/Tongatapu)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Magadan Time (Asia/Kamchatka)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Norfolk Islands Time (Pacific/Norfolk)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lord Howe Daylight Time (Australia/Lord_Howe)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australian Eastern Daylight Time (Australia/Sydney)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solomon Islands Time (Pacific/Guadalcanal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australian Central Daylight Time (Australia/Adelaide)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australian Eastern Standard Time (Australia/Brisbane)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australian Central Standard Time (Australia/Darwin)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Korean Standard Time (Asia/Seoul)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japan Standard Time (Asia/Tokyo)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hong Kong Time (Asia/Hong_Kong)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Malaysia Time (Asia/Kuala_Lumpur)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Philippine Time (Asia/Manila)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China Standard Time (Asia/Shanghai)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Singapore Standard Time (Asia/Singapore)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taipei Standard Time (Asia/Taipei)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australian Western Standard Time (Australia/Perth)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indochina Time (Asia/Bangkok)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indochina Time (Asia/Ho_Chi_Minh)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Western Indonesia Time (Asia/Jakarta)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Myanmar Time (Asia/Rangoon)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh Time (Asia/Dhaka)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nepal Time (Asia/Kathmandu)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India Standard Time (Asia/Colombo)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Segment_End_Timezone_MERC__c</fullName>
        <label>Segment End Timezone</label>
        <picklist>
            <picklistValues>
                <fullName>Line Islands Time (Pacific/Kiritimati)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chatham Daylight Time (Pacific/Chatham)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Zealand Daylight Time (Pacific/Auckland)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phoenix Islands Time (Pacific/Enderbury)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fiji Summer Time (Pacific/Fiji)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tonga Time (Pacific/Tongatapu)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Magadan Time (Asia/Kamchatka)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Norfolk Islands Time (Pacific/Norfolk)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lord Howe Daylight Time (Australia/Lord_Howe)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australian Eastern Daylight Time (Australia/Sydney)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solomon Islands Time (Pacific/Guadalcanal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australian Central Daylight Time (Australia/Adelaide)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australian Eastern Standard Time (Australia/Brisbane)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australian Central Standard Time (Australia/Darwin)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Korean Standard Time (Asia/Seoul)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japan Standard Time (Asia/Tokyo)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hong Kong Time (Asia/Hong_Kong)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Malaysia Time (Asia/Kuala_Lumpur)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Philippine Time (Asia/Manila)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China Standard Time (Asia/Shanghai)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Singapore Standard Time (Asia/Singapore)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taipei Standard Time (Asia/Taipei)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australian Western Standard Time (Australia/Perth)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indochina Time (Asia/Bangkok)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indochina Time (Asia/Ho_Chi_Minh)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Western Indonesia Time (Asia/Jakarta)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Myanmar Time (Asia/Rangoon)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh Time (Asia/Dhaka)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nepal Time (Asia/Kathmandu)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India Standard Time (Asia/Colombo)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/MERC_TravelItineraryNewEditController.cls
/**
 * @author Joseph Ferraro
 *
 * Controller to enable user to create/edit travel itineraries
 * we're overriding so we can control UX as it relates to Date/Times
 */

public with sharing class MERC_TravelItineraryNewEditController extends GLBL_BaseEditController {

	MERC_TimeZoneUtility tz = new MERC_TimeZoneUtility(Travel_Itinerary_MERC__c.sObjectType);
    String customObjectId;

    public Boolean provideSaveAndNew {get{return provideSaveAndNew!=null && provideSaveAndNew;} private set;}

	public MERC_TravelItineraryNewEditController(ApexPages.StandardController controller) {
		super(controller, Travel_Itinerary_MERC__c.SobjectType);

		// if the time zones have not been set yet, set according to user's locale
        String vfUrl = Apexpages.currentPage().getUrl().toLowerCase();
        if (vfUrl.contains('/apex/merc_travelitinerarynewedit')) {

            if (MERC_Util.getUrlParam('clone') == '1') {
                this.mySobject.put('Id', null);
            }

            if (this.mySobject.get('Meeting_Participant_MERC__c') != null && this.mySobject.get('Account_MERC__c') == null) {
                String meetingParticipantId = (String)this.mySobject.get('Meeting_Participant_MERC__c');
                this.mySobject.put('Account_MERC__c', [SELECT Account_MERC__c FROM Meeting_Participant_MERC__c WHERE ID = :meetingParticipantId].Account_MERC__c);
            }

            Schema.DescribeFieldResult meetingTimeZoneFieldDescribe = Meeting_MERC__c.Meeting_Time_Zone_MERC__c.getDescribe();
            String userTimeZoneDefault = MERC_Util.getTimeZonePicklistValueForCurrentUser(meetingTimeZoneFieldDescribe);
            if (this.mySobject.get('Segment_Begin_Timezone_MERC__c') == null)
                this.mySobject.put('Segment_Begin_Timezone_MERC__c', userTimeZoneDefault);
            if (this.mySobject.get('Segment_End_Timezone_MERC__c') == null)
                this.mySobject.put('Segment_End_Timezone_MERC__c', userTimeZoneDefault);
		}

        // need Custom Object ID to redirect user to Record Type selection screen
        provideSaveAndNew = Apexpages.currentPage().getParameters().keySet().contains('ent');
        customObjectId = Apexpages.currentPage().getParameters().get('ent');
	}

	public Map<String,String> fieldSetLabels {
    	get {
    		if (fieldSetLabels == null) {
    			fieldSetLabels = MERC_Util.getFieldSetLabels(
	    			Travel_Itinerary_MERC__c.SobjectType,
	    			new List<String> {
	    				'Date_Time_Information_Edit_MERC',
	    				'Date_Time_Information_View_MERC'
	    			}
	    		);
    		}
    		return fieldSetLabels;
    	}
    	private set;
    }

    public void setTimeZones() {
        tz.convertDateTimes(new List<Sobject>{this.mySobject}, false); //sets date/times based on meeting time/zone, for UX purposes
    }

    public override PageReference save() {
        return insertTheSObject(false);
    }

    public PageReference saveAndNew() {
        return insertTheSObject(true);
    }

    private PageReference insertTheSObject(Boolean saveAndNew) {
        try {
            tz.convertDateTimes(new List<Sobject>{this.mySobject}, true); //sets date/times based on UTC
            if (this.mySobject.Id == null) {
                insert this.mySobject;
            } else {
                update this.mySobject;
            }
        } catch(Exception e) {
            setTimeZones();
            ApexPages.addMessages(e); //TODO: doesn't show ugly error text
            return null;
        }
        PageReference p = (saveAndNew)
            ? buildSaveAndNewURL()
            : new PageReference('/'+this.mySobject.Id);
        return p;
    }

    /*
     * Creates a Save and New URL. The trick is returning the user to the Record Type selection screen
     * while retaining a Custom Object ID (that is not available to Apex!) and the previous Meeting
     * Participant and Account field values.
     */
    public PageReference buildSaveAndNewURL() {
        String recTypeSelectURL = '/setup/ui/recordtypeselect.jsp?ent='+customObjectId;
        String save_new_url = '/' + Schema.Sobjecttype.Travel_Itinerary_MERC__c.getKeyPrefix() + '/e?';
        Set<String> keys = new Set<String>{'ent','retURL'};
        for (String key : Apexpages.currentPage().getParameters().keySet()) {
            if (key.startsWith('CF') || keys.contains(key))
                save_new_url += key+'='+Apexpages.currentPage().getParameters().get(key)+'&';
        }

        save_new_url = '&save_new_url='+EncodingUtil.urlEncode(save_new_url.removeEnd('&'), 'UTF-8');
        PageReference pageRef = new PageReference(recTypeSelectURL+save_new_url);
        return pageRef;
    }
}