src/objects/Mercury_Settings_MERC__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Custom Settings for the Mercury Project mostly related to the operation of the Customer Search Tool, Veeva integration, Budget and Invoice processing.</description>
    <fields>
        <fullName>CST_Expire_Cron_Id_CUST__c</fullName>
        <description>Id of the last initiated schedule of expire batch jobs</description>
        <inlineHelpText>Id of the last initiated schedule of expire batch jobs</inlineHelpText>
        <label>Id of Latest CST Expire Cron Job</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CST_Expire_Cron_Name_CUST__c</fullName>
        <description>Name of programatically scheduled batch job to expire old authorizations</description>
        <inlineHelpText>Name of programatically scheduled batch job to expire old authorizations</inlineHelpText>
        <label>Name of CST Expire Cron Job</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CST_Expire_Cron_Sched_CUST__c</fullName>
        <description>Cron expression setting the schedule of expire batch jobs</description>
        <inlineHelpText>Cron expression setting the schedule of expire batch jobs</inlineHelpText>
        <label>Schedule of CST Expire Cron Job</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CST_Notify_Cron_Id_CUST__c</fullName>
        <description>Id of the last initiated schedule of soon-to-expire batch jobs</description>
        <inlineHelpText>Id of the last initiated schedule of soon-to-expire batch jobs</inlineHelpText>
        <label>Id of Latest CST Notify Cron Job</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CST_Notify_Cron_Name_CUST__c</fullName>
        <description>Name of programatically scheduled batch job to notify parties of soon-to-expire authorizations</description>
        <inlineHelpText>Name of programatically scheduled batch job to notify parties of soon-to-expire authorizations</inlineHelpText>
        <label>Name of CST Notify Cron Job</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CST_Notify_Cron_Sched_CUST__c</fullName>
        <description>Cron expression setting the schedule of soon-to-expire batch jobs</description>
        <inlineHelpText>Cron expression setting the schedule of soon-to-expire batch jobs</inlineHelpText>
        <label>Schedule of CST Notify Cron Job</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CST_Review_Cron_Id_CUST__c</fullName>
        <description>Id of the last initiated schedule of Under Review batch jobs</description>
        <inlineHelpText>Id of the last initiated schedule of Under Review batch jobs</inlineHelpText>
        <label>Id of Latest CST &quot;Under Review&quot; Cron Job</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CST_Review_Cron_Name_CUST__c</fullName>
        <description>Name of programatically scheduled batch job to set requests to Under Review</description>
        <inlineHelpText>Name of programatically scheduled batch job to set requests to Under Review</inlineHelpText>
        <label>Name of CST &quot;Under Review&quot; Cron Job</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CST_Review_Cron_Sched_CUST__c</fullName>
        <description>Cron expression setting the schedule of Under Review batch jobs</description>
        <inlineHelpText>Cron expression setting the schedule of Under Review batch jobs</inlineHelpText>
        <label>Schedule of CST &quot;Under Review&quot; Cron Job</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <label>Mercury Settings</label>
</CustomObject>

src/classes/CUST_Scheduler.cls
/**
 *
 * Responsible for starting all schedulable apex jobs for the Customer Search Tool
 */
global with sharing class CUST_Scheduler {

	// Seconds Minutes Hours Day_of_month Month Day_of_week optional_year
	public String EXPIRE_CRON = '0 0 13 1 * ?';
	public String REVIEW_CRON = '0 0 * * * ?';
	public String NOTIFY_CRON = '0 0 13 15 * ?';
	public String EXPIRE_NAME = 'CST Set Access To Expired';
	public String REVIEW_NAME = 'CST Set Access To Under Review';
	public String NOTIFY_NAME = 'CST Set Access To Will Expire';
	private Boolean useSettings = false;
	private Mercury_Settings_MERC__c settings;
	private Map<Id,CronTrigger> jobsToAbort { 
		get { 
			if (jobsToAbort==null) jobsToAbort = checkActiveJobs();
			return jobsToAbort;
		}
		set;
	}

	public CUST_Scheduler() {
		settings = Mercury_Settings_MERC__c.getOrgDefaults();
		if (settings.Id != null) {
			if (settings.CST_Expire_Cron_Name_CUST__c != null) EXPIRE_NAME = settings.CST_Expire_Cron_Name_CUST__c;
			if (settings.CST_Expire_Cron_Sched_CUST__c != null) EXPIRE_CRON = settings.CST_Expire_Cron_Sched_CUST__c;
			if (settings.CST_Notify_Cron_Name_CUST__c != null) NOTIFY_NAME = settings.CST_Notify_Cron_Name_CUST__c;
			if (settings.CST_Notify_Cron_Sched_CUST__c != null) NOTIFY_CRON = settings.CST_Notify_Cron_Sched_CUST__c;
			if (settings.CST_Review_Cron_Name_CUST__c != null) REVIEW_NAME = settings.CST_Review_Cron_Name_CUST__c;
			if (settings.CST_Review_Cron_Sched_CUST__c != null) REVIEW_CRON = settings.CST_Review_Cron_Sched_CUST__c;
			useSettings = true;
		}
	}

    public Map<Id,CronTrigger> checkActiveJobs() {
        List<String> jobIds = new List<String>();
        if (settings.CST_Expire_Cron_Id_CUST__c!=null) jobIds.add(settings.CST_Expire_Cron_Id_CUST__c);
        if (settings.CST_Review_Cron_Id_CUST__c!=null) jobIds.add(settings.CST_Review_Cron_Id_CUST__c);
        if (settings.CST_Notify_Cron_Id_CUST__c!=null) jobIds.add(settings.CST_Notify_Cron_Id_CUST__c);

        Map<Id,CronTrigger> jobTriggers = new Map<Id,CronTrigger>([
            SELECT Id FROM CronTrigger WHERE Id in :jobIds
            ]);
        return jobTriggers;
    }

	public void cronAll() {
		cronExpire();
		cronReview();
		cronNotify();
	}

	public void abortAll() {
		abortExpire();
		abortReview();
		abortNotify();
	}

	public void cronExpire() {
		// CUST_MonthlyProcessScheduler // day 1 monthly  //  CST_Access_To_Expired
		CUST_MonthlyProcessScheduler monthlySetAccessToExpired = new CUST_MonthlyProcessScheduler();
		String jobID = system.schedule(EXPIRE_NAME, EXPIRE_CRON, monthlySetAccessToExpired);

		if (useSettings) {
			settings.CST_Expire_Cron_Id_CUST__c = jobId;
			update settings;
		}
	}

	public void cronReview() {
		// CUST_ProcessScheduler  // hourly //  CST_Access_To_Under_Review
		CUST_ProcessScheduler hourlySetAccessToUnderReview = new CUST_ProcessScheduler();
		String jobID = system.schedule(REVIEW_NAME, REVIEW_CRON, hourlySetAccessToUnderReview);

		if (useSettings) {
			settings.CST_Review_Cron_Id_CUST__c = jobId;
			update settings;
		}
	}

	public void cronNotify() {
		// CUST_UserSettingsWillExpireBatchable  // day 15 montly  
		CUST_UserSettingsWillExpireBatchable monthlyNotifyAccessToExpired = new CUST_UserSettingsWillExpireBatchable();
		String jobID = system.schedule(NOTIFY_NAME, NOTIFY_CRON, monthlyNotifyAccessToExpired);		

		if (useSettings) {
			settings.CST_Notify_Cron_Id_CUST__c = jobId;
			update settings;
		}
	}

	public void abortExpire() {
		if (jobsToAbort.containsKey(settings.CST_Expire_Cron_Id_CUST__c)) System.abortJob(settings.CST_Expire_Cron_Id_CUST__c);
	}

	public void abortReview() {
		if (jobsToAbort.containsKey(settings.CST_Review_Cron_Id_CUST__c)) System.abortJob(settings.CST_Review_Cron_Id_CUST__c);
	}

	public void abortNotify() {
		if (jobsToAbort.containsKey(settings.CST_Notify_Cron_Id_CUST__c)) System.abortJob(settings.CST_Notify_Cron_Id_CUST__c);
	}
}