src/objects/MICO_AC_History__c.object
<CustomObject>
    <description>Business Description: This object is used to automatically keep a track of all changes to Acceptance Criteria on a user story.

Technical Description: Populated by a trigger on User Story this is an enhancement to the standard  user story history functionality as this does not log changes to rich text fields

Used In: Mission Control App</description>
    <fields>
        <fullName>Acceptance_Criteria__c</fullName>
        <inlineHelpText>The old acceptance criteria before this person edited the user story.
To see what the acceptance criteria was changed to, compare this to the next Acceptance Criteria History record.</inlineHelpText>
        <label>Previous Acceptance /Compliance Criteria</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>MICO_User_Story__c</referenceTo>
        <relationshipName>MICO_AC_History</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>User Story AC/CC History</label>
    <nameField>
        <displayFormat>ACH-{0000}</displayFormat>
        <label>AC History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Story AC/CC History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MICO_Project__c.object
<CustomObject>
    <description>Business Description: This object can be used to record projects in multi-project programs

Used In: Mission Control App</description>
    <label>Project mico</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MICO_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Mission Control App</description>
    <fields>
        <fullName>Acceptance_Criteria__c</fullName>
        <description>The Acceptance Criteria for this user story
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>Acceptance Criteria are the specific, testable and complete needs of this user story. They may follow a structure such as &quot;Given When Then&quot; or list out specific attributes and fields as needed. The Acceptance Criteria are used by developers and testers</inlineHelpText>
        <label>Acceptance Criteria</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Compliance_Criteria__c</fullName>
        <description>Compliance / Quality Notes
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>Legal, regulatory or compliance related requirements and observations</inlineHelpText>
        <label>Compliance Criteria</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>The Project responsible for delivering this User Story
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>The Project responsible for delivering this User Story</inlineHelpText>
        <label>Project</label>
        <referenceTo>MICO_Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>MICO_Project_User_Stories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Test_UserStoryTriggerClass.cls
@isTest 
public class Test_UserStoryTriggerClass {

    /*
     * Method name  : Test_UserStoryTriggerClass 
     * @description Function tests the trigger actions on User Story.
     */
    public static testMethod void test_productActions() {
    
    MICO_User_Story__c testRequirement = new MICO_User_Story__c();
    MICO_Project__c testProject = new MICO_Project__c();
    testProject.Name       = 'TestProject';
    insert TestProject;
    
    testRequirement.Project__c = TestProject.id;
    testRequirement.Acceptance_Criteria__c = 'OldAcceptanceCriteria';
    testRequirement.Compliance_Criteria__c = 'OldCC';
    insert testRequirement;
    
    testRequirement.Acceptance_Criteria__c = 'NewAcceptanceCriteria';
    testRequirement.Compliance_Criteria__c = 'NewCC';
    update testRequirement;
        
    MICO_AC_History__c newlyCreatedACHistoryRecord = [Select Acceptance_Criteria__c  from MICO_AC_History__c 
                                                 where User_Story__c = :testRequirement.id
                                                 ORDER BY SystemModStamp DESC NULLS LAST
                                                 LIMIT 1];
    System.assertEquals('OldAcceptanceCriteria', newlyCreatedACHistoryRecord.Acceptance_Criteria__c);

        } 
        
        
     }