src/objects/MICO_Sprint__c.object
<CustomObject>
    <description>Business Description: This object is used to hold details about the sprints or iterations. It includes information about start and end dates, as well as overall capacity.

Used In: Mission Control App</description>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Sprints must be &quot;In Planning&quot; for the sprint planning tool to work
They must be &quot;In Progress&quot; for the burndown to work</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Testing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MICO_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Mission Control App</description>
    <fields>
        <fullName>Allocated_Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The sprint this story has been allocated to. Used for sprint planning and in the burndown
Created on 04/07/2014 by SMills 
MICO</description>
        <inlineHelpText>The sprint that this story has been committed to</inlineHelpText>
        <label>Allocated Sprint</label>
        <referenceTo>MICO_Sprint__c</referenceTo>
        <relationshipLabel>Allocated User Stories</relationshipLabel>
        <relationshipName>MICO_Allocated_User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>As_A__c</fullName>
        <description>Used to define the core role using the piece of functionality described by the user story</description>
        <inlineHelpText>The main user type(s) that this story is for.</inlineHelpText>
        <label>(Deprecated) As a...</label>
        <picklist>
            <picklistValues>
                <fullName>Any User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chatter Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive &amp; Report Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System Administration</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Development_Stage__c</fullName>
        <description>User story status. This drives burndown, kanban and reporting
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>The stage this User Story is at in the Sprint lifecycle. User Stories are &quot;burned&quot; in the Sprint Dashboard when they are set to &quot;Passed (Complete)&quot;</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Cancelled</fullName>
                <color>#663333</color>
            </picklistValues>
            <picklistValues>
                <fullName>Backlog</fullName>
                <color>#999999</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Story Definition</fullName>
                <color>#FF6666</color>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Development</fullName>
                <color>#FFCC66</color>
            </picklistValues>
            <picklistValues>
                <fullName>In Development</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Test Release</fullName>
                <color>#66FF99</color>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Test</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>In Test</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Passed (Complete)</fullName>
                <color>#009900</color>
            </picklistValues>
            <picklistValues>
                <fullName>Production - Ready for Release</fullName>
                <color>#66E9BD</color>
            </picklistValues>
            <picklistValues>
                <fullName>Production - Released</fullName>
                <color>#006600</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Functional_Area__c</fullName>
        <label>Functional Area</label>
        <picklist>
            <picklistValues>
                <fullName>Customer Services</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>Market Access</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing / Multichannel</fullName>
                <color>#A845DC</color>
            </picklistValues>
            <picklistValues>
                <fullName>SFA</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <picklistValues>
                <fullName>Analytics / Insights</fullName>
                <color>#A53711</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>I_Want_To__c</fullName>
        <description>&quot;I want to&quot; part of the user story
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>What the user needs to achieve. 

E.g. 
I want To...Be able to search for customers on different fields (e.g. First Name, Surname, Address, and Product Metrics) in my territory</inlineHelpText>
        <label>I want to...</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>So_that__c</fullName>
        <description>Business Value of this User Story
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>Please enter the business value of this User Story. This helps Developers and Business Analysts understand the important essence of what the user needs to ultimately achieve.

I can easily find my  relevant target customer information</inlineHelpText>
        <label>So that...</label>
        <type>TextArea</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/KanbanBoardCntrl.cls
/****************************************************************************************************************************************** 
* Class Name   : KanbanBoardCntrl
* Description  : This is a class that will show the correct records in the digital Kanban board + make updates    
* Created By   : Deloitte Consulting
* 
*****************************************************************************************************************************************/

public class KanbanBoardCntrl {

    public MICO_Sprint__c spr {get; set;}
    public list <MICO_User_Story__c> Columns1List{get; set;}
    public list <MICO_User_Story__c> BacklogList{get; set;}
    public list <MICO_User_Story__c> AwaitingDev{get; set;}
    public list <MICO_User_Story__c> InDev{get; set;}
    public list <MICO_User_Story__c> AwaitingSAT{get; set;}
    public list <MICO_User_Story__c> InSAT{get; set;}
    public list <MICO_User_Story__c> Done{get; set;}
    public list <MICO_User_Story__c> BPC{get; set;}  
    
    Public List <MICO_User_Story__c> completeUSList;
    Map<String,List<MICO_User_Story__c>> AllocatedSprintUSList ;
    Public string selvalue {get;set;}
    Public string funcSelValue {get;set;}
    public string SprintName;
    public Set <String> sprintNames = new Set<String>();
    public Set <Id> sprintIds = new Set<Id>();
    public List<MICO_Sprint__c> sprintList = new List<MICO_Sprint__c>();
       
    public KanbanBoardCntrl(ApexPages.StandardController controller) {
        spr = new MICO_Sprint__c();
        spr = [select Name, id from MICO_Sprint__c where id =: apexpages.currentpage().getparameters().get('Id')];  
        sprintList = [select Name from MICO_Sprint__c where Status__c = 'In Progress'];    
        for (MICO_Sprint__c sprint : sprintList)
        {
            if (!sprintIds.contains(sprint.Id)){
                sprintNames.add(sprint.Name);
                sprintIds.add(sprint.Id);
            }
        }
        system.debug(sprintNames.size()); 
        SprintName = spr.Name;
        selvalue = SprintName;
        DispUserStories(null);
    }    
    
    public List<SelectOption> getsprintval(){
        List<SelectOption> tempSOPList = new List<SelectOption>();
        tempSOPList.add(new selectOption('All','All'));

        for(String str : sprintNames){
                tempSOPList.add(new SelectOption(str,str));
        }
        return tempSOPList;
    }
    
    // Compose Functional Areas Dropdown
    
    public List<SelectOption> getFuncval(){
        List<SelectOption> tempSOPList = new List<SelectOption>();
        tempSOPList.add(new selectOption('All','All'));
        tempSOPList.add(new selectOption('Customer Services','Customer Services'));        
        tempSOPList.add(new selectOption('Event / Medical','Event / Medical'));       
        tempSOPList.add(new selectOption('Market Access','Market Access'));        
        tempSOPList.add(new selectOption('Marketing / Multichannel','Marketing / Multichannel'));      
        tempSOPList.add(new selectOption('SFA','SFA'));     
        tempSOPList.add(new selectOption('Analytics / Insights','Analytics / Insights'));
        return tempSOPList;
    }
    
  // Display all user stories taking into account filters  
  Public void DispUserStories(string selvalx){
     if(selvalue ==null)
        selvalue ='All';
    if(funcSelValue ==null)
        funcSelValue ='All';
    
    // Find all requirements linked to the available sprint
    List<MICO_User_Story__c> AllocatedSprintUSList  = [Select id, Name, Allocated_Sprint__c , Development_Stage__c, Functional_Area__c, As_A__c, I_Want_To__c, So_that__c, Allocated_Sprint__r.Name from MICO_User_Story__c where Allocated_Sprint__c in: sprintids];
    List<MICO_User_Story__c> TempList = new List<MICO_User_Story__c>();
    List<MICO_User_Story__c> TempList2 = new List<MICO_User_Story__c>();
    
    // Create a subset of user stories based on filters
    if (selvalue == 'All'){
        TempList.addAll (AllocatedSprintUSList);
    }
    else{
        for (MICO_User_Story__c req : AllocatedSprintUSList){
            if (selvalue != null && selvalue != 'All'){
                if (req.Allocated_Sprint__r.Name == selvalue){
                    TempList.add(req);
                }
            }
        }
    }
    
    
    if (funcSelValue == 'All'){
        TempList2 = Templist;
    }
    else{
        for (MICO_User_Story__c req : TempList){
            if (funcSelValue != null && funcSelValue != 'All'){
                if (req.Functional_Area__c == funcSelValue){
                    TempList2.add(req);
                }
            }
        }
   }
    
    
    
    BacklogList = new list <MICO_User_Story__c>();
    AwaitingDev = new list <MICO_User_Story__c>();
    InDev = new list <MICO_User_Story__c>();
    AwaitingSAT = new list <MICO_User_Story__c>();
    InSAT = new list <MICO_User_Story__c>();
    Done = new list <MICO_User_Story__c>();
    BPC = new list <MICO_User_Story__c>();
    
    // Compose a list per status
    for(MICO_User_Story__c req : TempList2){
        if(req.Development_Stage__c.contains('Backlog'))
            BacklogList.add(req);
        else if(req.Development_Stage__c.contains('Awaiting Dev'))
            AwaitingDev.add(req);
        else if(req.Development_Stage__c.contains('In Dev'))
            Indev.add(req);
        else if(req.Development_Stage__c.contains('Review'))
            Indev.add(req);
        else if(req.Development_Stage__c.contains('Awaiting Release'))
            Indev.add(req);
        else if(req.Development_Stage__c.contains('Awaiting SAT'))
            AwaitingSAT.add(req);
        else if(req.Development_Stage__c.contains('In Test'))
            InSAT.add(req);
        else if(req.Development_Stage__c.contains('Done'))
            Done.add(req);
        else if(req.Development_Stage__c.contains('BPC'))
            BPC.add(req);
    }
  }
  
  // Method to change user story selection after changing dropdown values
  Public void filteredVal(){
    
    if(selvalue != null && selValue != 'All')
        DispUserStories(selvalue);
        
     else if(selvalue == null || selValue == 'All')
         DispUserStories(null);
    
    }  
 
 public void updateUserStoriesSprint(){
     String  UpdateSwing     = Apexpages.currentPage().getParameters().get('UpdateSwing');
     String  userStroyID     = Apexpages.currentPage().getParameters().get('UserStoryID');
     MICO_User_Story__c req = new MICO_User_Story__c(id=userStroyID);
     
     if(UpdateSwing == 'AwaitingDevUS')
         req.Development_Stage__c = '5.3 Sprint Team - Awaiting Development';
     else if(UpdateSwing == 'InDevUS')
         req.Development_Stage__c = '5.4 Sprint Team - In Development';
     else if(UpdateSwing == 'BacklogUS')
         req.Development_Stage__c = '5.1 Sprint Team - Sprint Backlog';
     else if(UpdateSwing == 'AwaitingSATUS')
         req.Development_Stage__c = '5.7. Sprint - Awaiting SAT';
     else if(UpdateSwing == 'InSATUS')
         req.Development_Stage__c = '5.8. Sprint - In Test';
     else if(UpdateSwing == 'DoneUS')
         req.Development_Stage__c = '5.9. Done';
          else if(UpdateSwing == 'BPC')
         req.Development_Stage__c = '5.2 Sprint Team - With BPC';
     update req;
     }
     public void addChatterComment(){
        String  chatterComment  = Apexpages.currentPage().getParameters().get('ChatterComment');
        String  userStroyID     = Apexpages.currentPage().getParameters().get('UserStoryID');
        
        if( chatterComment != '' &  userStroyID != ''){
            try{
                FeedItem post = new FeedItem();
                post.ParentId = userStroyID; //user stroy id.
                post.Body = chatterComment;  //chatter comment.
                insert post;
            }catch (System.Dmlexception e){
                System.debug(e);                
            }   
            
        }
        
    } 
}