src/objects/MICO_BurnDown2__c.object
<CustomObject>
    <description>Business Description: This captures sprint progress and is used for the creation of burndown charts as part of Agile reporting

Used In: Mission Control App</description>
    <fields>
        <fullName>Actual_burndown__c</fullName>
        <label>Actual Burndown</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_velocity__c</fullName>
        <label>Current Velocity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Optimum_burndown__c</fullName>
        <description>Populated by the Burndown class called by pressing the &quot;Create Burndown&quot; button on sprint</description>
        <label>Optimum Burndown</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Points_Complete__c</fullName>
        <label>Points Complete</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Projected_burndown__c</fullName>
        <label>Projected Burndown</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <label>Sprint</label>
        <referenceTo>MICO_Sprint__c</referenceTo>
        <relationshipLabel>Burndown Stats</relationshipLabel>
        <relationshipName>MICO_Burndown_Stats</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Burndown Stat</label>
    <nameField>
        <label>BS Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Burndown Stats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MICO_Project__c.object
<CustomObject>
    <description>Business Description: This object can be used to record projects in multi-project programs

Used In: Mission Control App</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project mico</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MICO_Sprint__c.object
<CustomObject>
    <description>Business Description: This object is used to hold details about the sprints or iterations. It includes information about start and end dates, as well as overall capacity.

Used In: Mission Control App</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_Working_Days_in_Sprint__c</fullName>
        <description>Populated by workflow. Not displayed on page layout.</description>
        <inlineHelpText>The number of working days in this sprint</inlineHelpText>
        <label>Number Working Days in Sprint</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>MICO_Project__c</referenceTo>
        <relationshipLabel>Sprints</relationshipLabel>
        <relationshipName>MICO_Sprints</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Sprints must be &quot;In Planning&quot; for the sprint planning tool to work
They must be &quot;In Progress&quot; for the burndown to work</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Testing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Working_Days_Through_Sprint__c</fullName>
        <formula>if( Start_Date__c &gt; today(),0,


IF(AND((5 - (CASE(MOD( Start_Date__c - DATE(1900, 1, 6), 7), 0, 0, 1, 5, 2, 5, 3, 4, 4, 3, 5, 2, 6, 1, 0)) &lt; (CASE(MOD( TODAY() - DATE(1900, 1, 6), 7), 0, 0, 1, 0, 2, 1, 3, 2, 4, 3, 5, 4, 6, 5, 0)) ), 
((( TODAY() - Start_Date__c ) + 1) &lt; 7)), 
((CASE(MOD(TODAY() - DATE(1900, 1, 6), 7), 0, 0, 1, 0, 2, 1, 3, 2, 4, 3, 5, 4, 6, 5, 0)) - (5 - (CASE(MOD( Start_Date__c - DATE(1900, 1, 6), 7), 0, 0, 1, 5, 2, 5, 3, 4, 4, 3, 5, 2, 6, 1, 0)))), 
(((FLOOR((( TODAY() - Start_Date__c ) - (CASE(MOD( Start_Date__c - DATE(1900, 1, 6), 7), 0, 0, 1, 6, 2, 5, 3, 4, 4, 3, 5, 2, 6, 1, 0))) / 7)) * 5) + 
(CASE(MOD( Start_Date__c - DATE(1900, 1, 6), 7), 0, 0, 1, 5, 2, 5, 3, 4, 4, 3, 5, 2, 6, 1, 0)) + 
(CASE(MOD( TODAY() - DATE(1900, 1, 6), 7), 0, 0, 1, 0, 2, 1, 3, 2, 4, 3, 5, 4, 6, 5, 0)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The number of working days in to the sprint we are today</inlineHelpText>
        <label>Working Days Through Sprint</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MICO_Test_Script_Burndown_Stat__c.object
<CustomObject>
    <description>Business Description: This captures Test Script approval progress and is used for the creation of burndown charts as part of Agile reporting</description>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <label>Sprint</label>
        <referenceTo>MICO_Sprint__c</referenceTo>
        <relationshipLabel>Test Script Burndown Stats</relationshipLabel>
        <relationshipName>Test_Script_Burndown_Stats</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Test_Script_Approved__c</fullName>
        <label>Total Test Script Approved</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Test_Scripts__c</fullName>
        <label>Total Test Scripts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Test Script Burndown Stat</label>
    <nameField>
        <label>TSBS  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Script Burndown Stats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MICO_Test_Templates__c.object
<CustomObject>
    <description>Business Description: This object is used by a Test Manager or Test Script Writer to create a master test script. This master test script can then be copied to different users to execute by adding those users to the &quot;Testers&quot; related list.

Used In: Mission Control App</description>
    <fields>
        <fullName>Development_Stage__c</fullName>
        <formula>Text(User_Story__r.Development_Stage__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Development Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>User_Story__r.Project__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <formula>User_Story__r.Allocated_Sprint__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sprint</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>MICO_User_Story__c</referenceTo>
        <relationshipName>MICO_Test_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Test Script Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MICO_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Mission Control App</description>
    <fields>
        <fullName>Allocated_Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The sprint this story has been allocated to. Used for sprint planning and in the burndown
Created on 04/07/2014 by SMills 
MICO</description>
        <inlineHelpText>The sprint that this story has been committed to</inlineHelpText>
        <label>Allocated Sprint</label>
        <referenceTo>MICO_Sprint__c</referenceTo>
        <relationshipLabel>Allocated User Stories</relationshipLabel>
        <relationshipName>MICO_Allocated_User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>This field is used to capture the status of the approval process in User stories: Created on 06/11/2014 by Preeti Grover:MICO</description>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Development_Stage__c</fullName>
        <description>User story status. This drives burndown, kanban and reporting
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>The stage this User Story is at in the Sprint lifecycle. User Stories are &quot;burned&quot; in the Sprint Dashboard when they are set to &quot;Passed (Complete)&quot;</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Cancelled</fullName>
                <color>#663333</color>
            </picklistValues>
            <picklistValues>
                <fullName>Backlog</fullName>
                <color>#999999</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Story Definition</fullName>
                <color>#FF6666</color>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Development</fullName>
                <color>#FFCC66</color>
            </picklistValues>
            <picklistValues>
                <fullName>In Development</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Test Release</fullName>
                <color>#66FF99</color>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Test</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>In Test</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Passed (Complete)</fullName>
                <color>#009900</color>
            </picklistValues>
            <picklistValues>
                <fullName>Production - Ready for Release</fullName>
                <color>#66E9BD</color>
            </picklistValues>
            <picklistValues>
                <fullName>Production - Released</fullName>
                <color>#006600</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>The Project responsible for delivering this User Story
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>The Project responsible for delivering this User Story</inlineHelpText>
        <label>Project</label>
        <referenceTo>MICO_Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>MICO_Project_User_Stories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Story_Points_Total__c</fullName>
        <description>Total Story Points for this story. Sums SFDC and Other Story point fields
Created on 01/07/2014 by SMills 
MICO</description>
        <formula>nullvalue(value(text( Story_Points__c )), 0)  + nullvalue(value(text(  Story_Points_Other__c)),0)</formula>
        <inlineHelpText>The total level of complexity as estimated in Story Points related to delivering this User Story. Includes both SFDC Story Points and Other Story Points</inlineHelpText>
        <label>Story Points Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/automateBurnDown.cls
/****************************************************************************************************************************************** 
* Class Name   : automateBoornDown
* Description  : This is a class that will both create the initial burndown records + updated them when user stories are closed    
* Created By   : Deloitte Consulting
* 
*****************************************************************************************************************************************/

Global class automateBurnDown {
    
    //calculate optimal burndown for a given day in a given sprint
    private static decimal optimalBurndown(MICO_Sprint__c sprint, Decimal totalPoints, Integer daysIntoSprint){
         Decimal optimalPointsPerDay = totalPoints/(sprint.Number_Working_Days_in_Sprint__c);
         Decimal burndown = totalPoints - (optimalPointsPerDay * daysIntoSprint);
         
         if(burndown < 0)
            burndown = 0;   
         
         return burndown;
    }          
          
    /**
     * @description :- populates the burndown object with a row for each date within the sprint 
                    that is a working day (ie exclude weekends) with sprint name, date, 
                    and project fields populated and fields for actual burndown, 
                    optimum burndown, current velocity and projected burndown left blank
     * @param :- Sprint Id
     */       
     WebService static void generateSprintBurndown(String sprintId){
           // Query the Sprint object 
            MICO_Sprint__c currentsprint = [select Name,Start_Date__c, End_Date__c,Number_Working_Days_in_Sprint__c, Project__c , Project__r.Name from MICO_Sprint__c where id =: sprintId];

           list<date> datelist = new list<date>();
           
              
              // Local Variables 
              date startDate = currentsprint.Start_Date__c;
              date endDate   = currentsprint.End_Date__c;
              integer numberDaysBet = startDate.daysBetween(endDate);
              MICO_BurnDown2__c burndown;
              Map<Date,MICO_BurnDown2__c> mapburnDown = new map<Date,MICO_BurnDown2__c>();
              
              list<MICO_User_Story__c> userStoryList = [select Allocated_Sprint__c,Allocated_Sprint__r.Start_Date__c,
                                                           Allocated_Sprint__r.End_Date__c,Development_Stage__c, Story_Points_Total__c 
                                                           From MICO_User_Story__c where Allocated_Sprint__c =: sprintId];
              
              Decimal totalpoints = 0;
              
              for (MICO_User_Story__c userStory : userStoryList ){
                   totalpoints = totalpoints + userStory.Story_Points_Total__c; 
              }                                             
          
              // Query all the BurnDown records for the selected Sprint
              list<MICO_BurnDown2__c> presentburnDown = [select Name, Date__c,Sprint__c from MICO_BurnDown2__c where Sprint__c =: currentsprint.Id];
              
              // Putting the Date of Burndown object as key and BurnDown object as value
              for(MICO_BurnDown2__c bDown : presentburnDown){
                  mapburnDown.put(bDown.Date__c , bDown);
              }
            
            //Lists of objects to insert and update
            list<MICO_BurnDown2__c> burnDownlist = new list<MICO_BurnDown2__c>();
            list<MICO_BurnDown2__c> burndownsToUpdate = new list<MICO_BurnDown2__c>();
            
               
              // Filtering the weekdays and creating BurnDown Objects only for Weekdays
              Integer j = 0; //days through sprint
              for (Integer i= 0 ; i <= numberDaysBet; i++ ){
                   Date tempstart = startdate.addDays(i);
                   date weekStart = tempstart.toStartofWeek();
                   integer dayOfWeek = weekStart.daysBetween(tempstart);
                   
                   // If selcted day is not Saturday and Sunday
                   if (dayOfWeek != 5 && dayOfWeek != 6){
                        j = j + 1;
                        if(!(mapburnDown.containsKey(tempstart) && mapburnDown.get(tempstart).Sprint__c == currentsprint.id)){
                            //Create the new BurnDown Object with following Values
                            burndown = new MICO_BurnDown2__c();
                            burndown.Name = currentsprint.Name +' Burndown';
                            burndown.Date__c = tempstart;
                            burndown.Project__c = currentsprint.Project__r.Name;
                            burndown.Sprint__c  = currentsprint.Id;
                            burndown.Optimum_burndown__c = optimalBurndown(currentsprint, totalpoints, j);
                            // Add to the list
                            burnDownlist.add(burndown);
                        }else{
                            //Burndown object already exists
                            burndown = mapburnDown.get(tempstart);
                            burndown.Optimum_burndown__c = optimalBurndown(currentsprint, totalpoints, j);
                            burndownsToUpdate.add(burndown);
                        }
                    } 
               }
               // Insert the list
               try{
                 insert burnDownlist;
                 update burndownsToUpdate;
               }
               catch(DMLException e) {
               } 
        }
                 
    /**
     * @description :- populates the burndown object with a row for each date within the sprint 
                       that is a working day (ie exclude weekends) with Optimum_burndown__c ,Current_velocity__c
                       ,Projected_burndown__c and Actual_burndown__c fields
     * @param :- Sprint Id
     **/  
       
    WebService static void updateSprintBurndown(String sprintId){ 
            list<MICO_BurnDown2__c> updateburndown2List = new list<MICO_BurnDown2__c>();   // Empty list to be updated later
            // Query All the User Story in the current Sprint
            list<MICO_User_Story__c> userStoryList = [select Allocated_Sprint__c,Allocated_Sprint__r.Start_Date__c,Allocated_Sprint__r.Number_Working_Days_in_Sprint__c,
                                                           Allocated_Sprint__r.End_Date__c,Development_Stage__c, Story_Points_Total__c
                                                           From MICO_User_Story__c where Allocated_Sprint__c =: sprintId and Allocated_Sprint__r.Status__c = 'In Progress'];
            
            //Query All the BurnDown Records in the Sprint selected
            list<MICO_BurnDown2__c> burndown2List = [Select Actual_burndown__c,Current_velocity__c, 
                                                              Date__c,Optimum_burndown__c,Project__c,
                                                              Projected_burndown__c,Sprint__c ,Sprint__r.Working_Days_Through_Sprint__c,
                                                              Sprint__r.Number_Working_Days_in_Sprint__c,Sprint__r.End_Date__c 
                                                              From MICO_BurnDown2__c where Sprint__c =: sprintId  and Sprint__r.Status__c = 'In Progress' Order by Date__c asc];
            
            map<Date, Integer> datemap = new map<Date, Integer>();
            Integer i = 0;
               
            // Adding the working days passed with the Date as the key to the map 
            for(MICO_BurnDown2__c burndown : burndown2List){
                datemap.put(burndown.Date__c,i);
                i = i+1;
            }
              
            //Calculate totals
            Decimal totalcompletepoints = 0;
            Decimal totalpoints = 0;    
            for(MICO_User_Story__c userStory : userStoryList ){
                // Calculate total complete points
                if (userStory.Development_Stage__c == System.Label.Burn_Status){
                    totalcompletepoints = totalcompletepoints + userStory.Story_Points_Total__c;
                }
                // Calculate TotalPoints
                totalpoints = totalpoints + userStory.Story_Points_Total__c ;
            }
            Decimal velocity = 0;
            Decimal actualburn = 0;
            Integer dayOfSprint = 0;
            Integer actualDayOfSprint = 0;         
            for(MICO_BurnDown2__c burndown2 : burndown2List){ //looping in order of date ASC
                dayOfSprint++;
                if(date.today() == burndown2.Date__c){ //update actual burndown for today
                    actualburn = totalpoints - totalcompletepoints;
                    burndown2.Actual_burndown__c = actualburn;
                    burndown2.Points_Complete__c = totalcompletepoints;
                    //work-around for graphing limits:
                    //We need to differentiate between ZERO and NULL. 
                    //When creating the summary graph, the sum of the nulls is incorrectly calculated as ZERO
                    //Step A: filter out the zeros from the graph
                    //Step B (here): fudge data so that zero is reported at 0.01, causing it to be graphed and showing the complete sprint
                    if(actualburn==0){
                        burndown2.Actual_burndown__c = 0.01;
                    } 
                    
                    velocity = totalcompletepoints / dayOfSprint;
                    burndown2.Current_velocity__c = totalcompletepoints/(burndown2.Sprint__r.Working_Days_Through_Sprint__c);
                    actualDayOfSprint = dayOfSprint;
                }
                    
                // Add the BurnDown record to the list
                updateburndown2List.add(burndown2);
            } 
                 
            // Update the list
            try{
                update  updateburndown2List;
            }catch(DMLException e) {
            }
        }
        
     /**
     * @description :- populates the test script burndown object with a row for each date within the sprint 
                       that is a working day (ie exclude weekends) with sprint name, date, 
                       and Total Test Scripts and Total Test Scripts approved.
     * @param :- Sprint Id
     */       
     WebService static void generateTestScriptBurndown(String sprintId){
     	
     	  // Query the Sprint object 
            MICO_Sprint__c currentsprint = [select Name,Start_Date__c, End_Date__c,Number_Working_Days_in_Sprint__c, Project__c , Project__r.Name from MICO_Sprint__c where id =: sprintId];

           list<date> datelist = new list<date>();
           
              
              // Local Variables 
              date startDate = currentsprint.Start_Date__c;
              date endDate   = currentsprint.End_Date__c;
              integer numberDaysBet = startDate.daysBetween(endDate);
              integer totalTestScripts = 0 ;
              integer totalTestScriptsApproved = 0 ;
              
              MICO_Test_Script_Burndown_Stat__c testScriptburndown;
              Map<Date,MICO_Test_Script_Burndown_Stat__c> maptestScriptburndown = new map<Date,MICO_Test_Script_Burndown_Stat__c>();
              
              list<MICO_Test_Templates__c> testScriptList = [select User_Story__r.Allocated_Sprint__c,User_Story__r.Allocated_Sprint__r.Start_Date__c,
                                                               User_Story__r.Allocated_Sprint__r.End_Date__c,Approval_Status__c
                                                               From MICO_Test_Templates__c where User_Story__r.Allocated_Sprint__c =: sprintId];
                                                           
             // Query all the BurnDown records for the selected Sprint
              list<MICO_Test_Script_Burndown_Stat__c> presentTestScriptburnDown = [select Name, Date__c,Sprint__c from MICO_Test_Script_Burndown_Stat__c where Sprint__c =: currentsprint.Id];
              
               for (MICO_Test_Templates__c testScript : testScriptList ){
               	   if(testScript.Approval_Status__c == 'Approved'){
               	   	totalTestScriptsApproved = totalTestScriptsApproved + 1 ;
               	   }
                   totalTestScripts = totalTestScripts + 1; 
              }    
              
              
              // Putting the Date of Burndown object as key and BurnDown object as value
              for(MICO_Test_Script_Burndown_Stat__c bDown : presentTestScriptburnDown){
              	  maptestScriptburndown.put(bDown.Date__c , bDown);
              } 
              
            //Lists of objects to insert and update
            list<MICO_Test_Script_Burndown_Stat__c> testScriptburnDownlist = new list<MICO_Test_Script_Burndown_Stat__c>();
            list<MICO_Test_Script_Burndown_Stat__c> testScriptburndownsToUpdate = new list<MICO_Test_Script_Burndown_Stat__c>(); 
            
             // Filtering the weekdays and creating BurnDown Objects only for Weekdays
              Integer j = 0; //days through sprint
              for (Integer i= 0 ; i <= numberDaysBet; i++ ){
                   Date tempstart = startdate.addDays(i);
                   date weekStart = tempstart.toStartofWeek();
                   integer dayOfWeek = weekStart.daysBetween(tempstart);
                   
                   // If selcted day is not Saturday and Sunday
                   if (dayOfWeek != 5 && dayOfWeek != 6){
                        j = j + 1;
                        if(!(maptestScriptburndown.containsKey(tempstart) && maptestScriptburndown.get(tempstart).Sprint__c == currentsprint.id)){
                            //Create the new BurnDown Object with following Values
                            testScriptburndown = new MICO_Test_Script_Burndown_Stat__c();
                            testScriptburndown.Name = currentsprint.Name +'Test Script Burndown';
                            testScriptburndown.Date__c = tempstart;
                            testScriptburndown.Sprint__c  = currentsprint.Id;
                            testScriptburndown.Total_Test_Scripts__c = totalTestScripts;
                            // Add to the list
                            testScriptburnDownlist.add(testScriptburndown);
                        }else{
                            //Burndown object already exists
                            testScriptburndown = maptestScriptburndown.get(tempstart);
                            testScriptburndown.Total_Test_Scripts__c = totalTestScripts;
                            testScriptburndownsToUpdate.add(testScriptburndown);
                        }
                    } 
               }
               // Insert the list
               try{
                 insert testScriptburnDownlist;
                 update testScriptburndownsToUpdate;
               }
               catch(DMLException e) {
               }
               
               try{
               	updateTestScriptSprintBurndown(sprintId);
               } 
               catch(DMLException e) {
               } 
                                                       
         }
         
       /**
	     * @description :- populates the burndown object with a row for each date within the sprint 
	                       that is a working day (ie exclude weekends) with Total Test Scripts and 
	                       Total Test Scripts approved fields
	     * @param :- Sprint Id
       **/   
       WebService static void updateTestScriptSprintBurndown(String sprintId){ 
       	
       	 list<MICO_Test_Script_Burndown_Stat__c> updateTestScriptburndownList = new list<MICO_Test_Script_Burndown_Stat__c>();   // Empty list to be updated later
       	 
       	 //Query The Test Script Object
       	 list<MICO_Test_Templates__c> testScriptList = [select User_Story__r.Allocated_Sprint__c,User_Story__r.Allocated_Sprint__r.Start_Date__c,
                                                               User_Story__r.Allocated_Sprint__r.End_Date__c,Approval_Status__c
                                                               From MICO_Test_Templates__c where User_Story__r.Allocated_Sprint__c =: sprintId and User_Story__r.Allocated_Sprint__r.Status__c = 'In Progress'];
                                                               
        //Query All the BurnDown Records in the Sprint selected
         list<MICO_Test_Script_Burndown_Stat__c> presentTestScriptburnDown = [select Name, Date__c,Sprint__c,Total_Test_Script_Approved__c,Total_Test_Scripts__c from MICO_Test_Script_Burndown_Stat__c where Sprint__c =: sprintId Order by Date__c asc];                                                       
       	 
       	 map<Date, Integer> datemap = new map<Date, Integer>();
            Integer i = 0;
               
            // Adding the working days passed with the Date as the key to the map 
            for(MICO_Test_Script_Burndown_Stat__c burndown : presentTestScriptburnDown){
                datemap.put(burndown.Date__c,i);
                i = i+1;
            }
            
            //Calculate totals
           integer totalTestScripts = 0 ;
           integer totalTestScriptsApproved = 0 ;
           
            for (MICO_Test_Templates__c testScript : testScriptList ){
               	   if(testScript.Approval_Status__c == 'Approved'){
               	   	totalTestScriptsApproved = totalTestScriptsApproved + 1 ;
               	   }
                   totalTestScripts = totalTestScripts + 1; 
              }
           
             
           for(MICO_Test_Script_Burndown_Stat__c burndown : presentTestScriptburnDown){ //looping in order of date ASC
                if(date.today() == burndown.Date__c){ //update actual burndown for today
                    burndown.Total_Test_Scripts__c = totalTestScripts;
                    burndown.Total_Test_Script_Approved__c = totalTestScriptsApproved;
                }
                updateTestScriptburndownList.add(burndown);
           }
           
           try{
             update  updateTestScriptburndownList;
            }catch(DMLException e) {
            }
               
              
       }
     
   }