src/objects/MICO_App__c.object
<CustomObject>
    <description>Business Description: This object is used to store a list of applications, capturing their name, use, technical and business contacts as well as physical location.
Used In: Mission Control App

Created on 04/29/2014 by SMills
MICO</description>
    <label>App</label>
    <nameField>
        <label>App Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MICO_Project__c.object
<CustomObject>
    <description>Business Description: This object can be used to record projects in multi-project programs

Used In: Mission Control App</description>
    <label>Project mico</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MICO_Test_Template_Steps__c.object
<CustomObject>
    <description>Business Description: This object is used to record the individual steps of a test template. Test Templates are the master copy of a Test that can be executed many times by different people.

Used In: Mission Control App</description>
    <fields>
        <fullName>Action__c</fullName>
        <inlineHelpText>The actions needed to perform this test</inlineHelpText>
        <label>Action</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Expected_Result__c</fullName>
        <inlineHelpText>The expected result for this step</inlineHelpText>
        <label>Expected Result</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Test_Script_Step_Number__c</fullName>
        <description>MICO: This field stores the step number of the Test Case Step associated with a Test Script</description>
        <label>Test Script Step Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Test_Script__c</fullName>
        <label>Test Script</label>
        <referenceTo>MICO_Test_Templates__c</referenceTo>
        <relationshipName>MICO_Test_Script_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Tips__c</fullName>
        <inlineHelpText>Hints and Tips for this step</inlineHelpText>
        <label>Tips</label>
        <type>TextArea</type>
    </fields>
    <label>Test Script Step</label>
    <nameField>
        <displayFormat>TSS-{000000}</displayFormat>
        <label>Test Script Step Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Script Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MICO_Test_Templates__c.object
<CustomObject>
    <description>Business Description: This object is used by a Test Manager or Test Script Writer to create a master test script. This master test script can then be copied to different users to execute by adding those users to the &quot;Testers&quot; related list.

Used In: Mission Control App</description>
    <fields>
        <fullName>Development_Stage__c</fullName>
        <formula>Text(User_Story__r.Development_Stage__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Development Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expected_Result__c</fullName>
        <inlineHelpText>The expected result of this test</inlineHelpText>
        <label>Expected Result</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Introduction__c</fullName>
        <inlineHelpText>The introduction to this test script. This will be shown to testers before they start executing the test.</inlineHelpText>
        <label>Introduction</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>User_Story__r.Project__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <inlineHelpText>The title of the test script</inlineHelpText>
        <label>Test Title</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>MICO_User_Story__c</referenceTo>
        <relationshipName>MICO_Test_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Test Script Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MICO_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Mission Control App</description>
    <fields>
        <fullName>Acceptance_Criteria__c</fullName>
        <description>The Acceptance Criteria for this user story
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>Acceptance Criteria are the specific, testable and complete needs of this user story. They may follow a structure such as &quot;Given When Then&quot; or list out specific attributes and fields as needed. The Acceptance Criteria are used by developers and testers</inlineHelpText>
        <label>Acceptance Criteria</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>This field is used to capture the status of the approval process in User stories: Created on 06/11/2014 by Preeti Grover:MICO</description>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Development_Stage__c</fullName>
        <description>User story status. This drives burndown, kanban and reporting
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>The stage this User Story is at in the Sprint lifecycle. User Stories are &quot;burned&quot; in the Sprint Dashboard when they are set to &quot;Passed (Complete)&quot;</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Cancelled</fullName>
                <color>#663333</color>
            </picklistValues>
            <picklistValues>
                <fullName>Backlog</fullName>
                <color>#999999</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Story Definition</fullName>
                <color>#FF6666</color>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Development</fullName>
                <color>#FFCC66</color>
            </picklistValues>
            <picklistValues>
                <fullName>In Development</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Test Release</fullName>
                <color>#66FF99</color>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Test</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>In Test</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Passed (Complete)</fullName>
                <color>#009900</color>
            </picklistValues>
            <picklistValues>
                <fullName>Production - Ready for Release</fullName>
                <color>#66E9BD</color>
            </picklistValues>
            <picklistValues>
                <fullName>Production - Released</fullName>
                <color>#006600</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>I_Want_To__c</fullName>
        <description>&quot;I want to&quot; part of the user story
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>What the user needs to achieve. 

E.g. 
I want To...Be able to search for customers on different fields (e.g. First Name, Surname, Address, and Product Metrics) in my territory</inlineHelpText>
        <label>I want to...</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <description>The priority of this user story, this is used in sprint planning
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>The relative priority of this User Story. 1 is the most important, 99 is the least. This can be used during Sprint Planning</inlineHelpText>
        <label>Priority</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>The Project responsible for delivering this User Story
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>The Project responsible for delivering this User Story</inlineHelpText>
        <label>Project</label>
        <referenceTo>MICO_Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>MICO_Project_User_Stories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Story_Points_Other__c</fullName>
        <description>Story points for non SFDC dev
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>The level of complexity as estimated in Story Points NOT related to force.com development. For example, related to Integration effort</inlineHelpText>
        <label>Story Points (Other)</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Story_Points__c</fullName>
        <description>Story points for SFDC dev
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>The level of complexity as estimated in Story Points related to force.com development</inlineHelpText>
        <label>Story Points SFDC</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Test_MICOManageTestScriptStepsController.cls
@isTest
private class Test_MICOManageTestScriptStepsController {

    static testMethod void Test_theEntireClass() {
        //set up the pre-requisite data
        MICO_App__c app = new MICO_App__c();
        app.Name = 'MICO2';
        insert app;
        
        MICO_Project__c project = new MICO_Project__c();
        project.Name = 'MICOSprints2';
        insert project;
         
        MICO_User_Story__c userstory = new MICO_User_Story__c(
            I_Want_To__c            = 'Test-Description-User-Stroy',
            Acceptance_Criteria__c  = 'Test-Acceptance-Criteria',
            Story_Points__c         = '13',
            Story_Points_Other__c   = '13',
            Development_Stage__c    = 'Backlog' ,
            Priority__c             = 0,
            Project__c              = project.Id);
        insert userstory;
        
        //insert approver
        User approver = new User(
            Alias             = 'aprvr1',
            Email             = 'approver@mico-testscript.com',
            EmailEncodingKey  = 'UTF-8',
            LastName          = 'User',
            FirstName         = 'Approver',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey      = 'en_US',
            ProfileId         = [select Id from Profile where Name = 'GLBL_Chatter Only' limit 1].Id,
            TimeZoneSidKey    = 'America/Chicago',
            Username          = 'stakeholder@mico-test' + Math.round(Math.random() * 10000) + '.com',
            UserRoleId        = null,
            Country           = 'Great Britain');
        insert approver;
        
        MICO_test_templates__c testScript = new MICO_Test_templates__c(
            User_Story__c      = userstory.Id,
            Title__c           = 'My test template title',
            Introduction__c    = 'My test template introduction',
            Approver__c        = approver.Id,
            Approval_Status__c = 'Open');
        insert testScript;
        
        List<MICO_Test_Template_Steps__c> testScriptStepsList = new List<MICO_Test_Template_Steps__c>();
        MICO_Test_Template_Steps__c testScriptStep1 = new MICO_Test_Template_Steps__c(
            Test_Script__c     = testScript.Id,
            Action__c          = 'Test 1',
            Expected_Result__c = 'Test 1',
            Tips__c            = 'Test 1');
        
        MICO_Test_Template_Steps__c testScriptStep2 = new MICO_Test_Template_Steps__c(
            Test_Script__c     = testScript.Id,
            Action__c          = 'Test 2',
            Expected_Result__c = 'Test 2',
            Tips__c            = 'Test 2');
            
        MICO_Test_Template_Steps__c testScriptStep3 = new MICO_Test_Template_Steps__c(
            Test_Script__c     = testScript.Id,
            Action__c          = 'Test 3',
            Expected_Result__c = 'Test 3',
            Tips__c            = 'Test 3');
        
        testScriptStepsList.add(testScriptStep1);
        testScriptStepsList.add(testScriptStep2);
        testScriptStepsList.add(testScriptStep3);
        
        Test.StartTest();
            //Insert the Test Script Steps which will have auto number assigned to them method.
            insert testScriptStepsList;
                        
            //Set the current VF page whose controller is being tested
            PageReference pageRef = Page.MICO_Manage_Test_Script_Steps;
            Test.setCurrentPage(pageRef);          
            //Set the initial page parameter which is passed via URL to the Controller
            ApexPages.currentPage().getParameters().put('testScriptId',testScript.Id);  
            //Invoke the constructor of the controller class by first creating an instance of Standard Controller
            ApexPages.StandardController sc1 = new ApexPages.StandardController(testScriptStep1);
            MICO_Manage_Test_Script_Steps_Controller mtssc = new MICO_Manage_Test_Script_Steps_Controller(sc1);
            
            //Invoke the save method of the Controller without any changes
            mtssc.save();            
            //Invoke the save method of the Controller For Negative Number scenario
            testScriptStepsList[0].Test_Script_Step_Number__c = -1;
            mtssc.testScriptSteps = testScriptStepsList;
            mtssc.save();
            //Invoke the save method of the Controller For 0 scenario
            testScriptStepsList[0].Test_Script_Step_Number__c = 0;
            mtssc.testScriptSteps = testScriptStepsList;
            mtssc.save();
            //Invoke the save method of the Controller For Number larger than steps scenario
            testScriptStepsList[0].Test_Script_Step_Number__c = 4;
            mtssc.testScriptSteps = testScriptStepsList;
            mtssc.save();
            //Invoke the save method of the Controller For Duplicate steps scenario
            testScriptStepsList[0].Test_Script_Step_Number__c = 1;
            testScriptStepsList[1].Test_Script_Step_Number__c = 1;
            testScriptStepsList[2].Test_Script_Step_Number__c = 1;
            mtssc.testScriptSteps = testScriptStepsList;
            mtssc.save();
            //Invoke the save method of the Controller for the Correct data
            testScriptStepsList[0].Test_Script_Step_Number__c = 1;
            testScriptStepsList[1].Test_Script_Step_Number__c = 2;
            testScriptStepsList[2].Test_Script_Step_Number__c = 3;
            mtssc.testScriptSteps = testScriptStepsList;
            mtssc.save();
            
            //Invoke the cancel method
            mtssc.cancel();
        Test.StopTest();
    }
}