src/objects/MICO_Project__c.object
<CustomObject>
    <description>Business Description: This object can be used to record projects in multi-project programs

Used In: Mission Control App</description>
    <label>Project mico</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MICO_Test__c.object
<CustomObject>
    <description>Business Description: This object is used to record the tests which have been executed. 

Each test is a copy of a &quot;Test Template&quot; which has been set up by a Test Manager or other Test Script writer. 

Tests are created by the system automatically when a user is added to the Testers Related list on a Test Template.

Used In: Mission Control App</description>
    <fields>
        <fullName>Introduction__c</fullName>
        <formula>Template__r.Introduction__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>What is the overall aim of this test</inlineHelpText>
        <label>Introduction</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Overall_Test_Comments__c</fullName>
        <inlineHelpText>Overall test comments. 

You should note what happened in the test, e.g. for promotion creation &quot;Succesfully created promotion&quot;.

This can be copy and pasted from the excel file.</inlineHelpText>
        <label>Overall Test Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>MICO_Project__c</referenceTo>
        <relationshipLabel>Test Executions</relationshipLabel>
        <relationshipName>MICO_Test_Executions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The script being executed</inlineHelpText>
        <label>Template</label>
        <referenceTo>MICO_Test_Templates__c</referenceTo>
        <relationshipName>MICO_Test</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Test_Outcome__c</fullName>
        <inlineHelpText>The overall outcome of the test at it&apos;s current stage</inlineHelpText>
        <label>Test Outcome</label>
        <picklist>
            <picklistValues>
                <fullName>Passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passed with minor issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked from testing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Test_Phase__c</fullName>
        <label>Test Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Sprint Test</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>User Acceptance Test</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stability Test</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regression Test</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance Test</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>MICO_User_Story__c</referenceTo>
        <relationshipName>MICO_Tests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Execution</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Test Execution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Executions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MICO_Test_Steps__c.object
<CustomObject>
    <description>Business Description: This object is used to record the test steps which have been executed.

Each Test Step is a copy of a &quot;Test Template Step&quot; which has been set up by a Test Manager or other Test Script writer.

Tests are created by the system automatically when a user is added to the Testers Related list on a Test Template.

Used In: Mission Control App</description>
    <fields>
        <fullName>Outcome__c</fullName>
        <inlineHelpText>What was the result of this step? If it Failed or had minor issues please note what these were.</inlineHelpText>
        <label>Outcome</label>
        <picklist>
            <picklistValues>
                <fullName>Pass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passed with issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Template_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>A link to the template step for this test. Action, Expected, Results, Tips etc are all calculated based on this link</inlineHelpText>
        <label>Template Step</label>
        <referenceTo>MICO_Test_Template_Steps__c</referenceTo>
        <relationshipName>MICO_Test_Step_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <label>Test</label>
        <referenceTo>MICO_Test__c</referenceTo>
        <relationshipName>MICO_Test_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Test Execution Step</label>
    <nameField>
        <label>Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Execution Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MICO_Test_Template_Steps__c.object
<CustomObject>
    <description>Business Description: This object is used to record the individual steps of a test template. Test Templates are the master copy of a Test that can be executed many times by different people.

Used In: Mission Control App</description>
    <fields>
        <fullName>Test_Script__c</fullName>
        <label>Test Script</label>
        <referenceTo>MICO_Test_Templates__c</referenceTo>
        <relationshipName>MICO_Test_Script_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Test Script Step</label>
    <nameField>
        <displayFormat>TSS-{000000}</displayFormat>
        <label>Test Script Step Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Script Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MICO_Test_Templates__c.object
<CustomObject>
    <description>Business Description: This object is used by a Test Manager or Test Script Writer to create a master test script. This master test script can then be copied to different users to execute by adding those users to the &quot;Testers&quot; related list.

Used In: Mission Control App</description>
    <fields>
        <fullName>Development_Stage__c</fullName>
        <formula>Text(User_Story__r.Development_Stage__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Development Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Introduction__c</fullName>
        <inlineHelpText>The introduction to this test script. This will be shown to testers before they start executing the test.</inlineHelpText>
        <label>Introduction</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>User_Story__r.Project__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <inlineHelpText>The title of the test script</inlineHelpText>
        <label>Test Title</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>MICO_User_Story__c</referenceTo>
        <relationshipName>MICO_Test_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Test Script Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MICO_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Mission Control App</description>
    <fields>
        <fullName>Acceptance_Criteria__c</fullName>
        <description>The Acceptance Criteria for this user story
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>Acceptance Criteria are the specific, testable and complete needs of this user story. They may follow a structure such as &quot;Given When Then&quot; or list out specific attributes and fields as needed. The Acceptance Criteria are used by developers and testers</inlineHelpText>
        <label>Acceptance Criteria</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Development_Stage__c</fullName>
        <description>User story status. This drives burndown, kanban and reporting
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>The stage this User Story is at in the Sprint lifecycle. User Stories are &quot;burned&quot; in the Sprint Dashboard when they are set to &quot;Passed (Complete)&quot;</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Cancelled</fullName>
                <color>#663333</color>
            </picklistValues>
            <picklistValues>
                <fullName>Backlog</fullName>
                <color>#999999</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Story Definition</fullName>
                <color>#FF6666</color>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Development</fullName>
                <color>#FFCC66</color>
            </picklistValues>
            <picklistValues>
                <fullName>In Development</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Test Release</fullName>
                <color>#66FF99</color>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Test</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>In Test</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Passed (Complete)</fullName>
                <color>#009900</color>
            </picklistValues>
            <picklistValues>
                <fullName>Production - Ready for Release</fullName>
                <color>#66E9BD</color>
            </picklistValues>
            <picklistValues>
                <fullName>Production - Released</fullName>
                <color>#006600</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>I_Want_To__c</fullName>
        <description>&quot;I want to&quot; part of the user story
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>What the user needs to achieve. 

E.g. 
I want To...Be able to search for customers on different fields (e.g. First Name, Surname, Address, and Product Metrics) in my territory</inlineHelpText>
        <label>I want to...</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <description>The priority of this user story, this is used in sprint planning
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>The relative priority of this User Story. 1 is the most important, 99 is the least. This can be used during Sprint Planning</inlineHelpText>
        <label>Priority</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>The Project responsible for delivering this User Story
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>The Project responsible for delivering this User Story</inlineHelpText>
        <label>Project</label>
        <referenceTo>MICO_Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>MICO_Project_User_Stories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Story_Points_Other__c</fullName>
        <description>Story points for non SFDC dev
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>The level of complexity as estimated in Story Points NOT related to force.com development. For example, related to Integration effort</inlineHelpText>
        <label>Story Points (Other)</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Story_Points__c</fullName>
        <description>Story points for SFDC dev
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>The level of complexity as estimated in Story Points related to force.com development</inlineHelpText>
        <label>Story Points SFDC</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/testTestScriptExtension.cls
/**
 ************** Modification Log****************************
 
 @Modified By : Nitish Kumar 
 @Date :        July 2014
 Description :  US-35861 (Ensure all Test Executions are fully completed)  
 */
@isTest
private class testTestScriptExtension {

    static testMethod void myUnitTest() {
        
        //create a project
        MICO_Project__c pro = new MICO_Project__c();
        pro.Name = 'Test Project';
        insert pro;
        
        MICO_User_Story__c objRequirement =new MICO_User_Story__c(
                                                    I_Want_To__c            = 'Test-Description-User-Story',
                                                    Acceptance_Criteria__c  = 'Test-Acceptance-Criteria',
                                                    Story_Points__c         = '21',
                                                    Story_Points_Other__c   = '21',
                                                    Development_Stage__c    = 'Backlog' ,
                                                    Priority__c             = 0,
                                                    Project__c = pro.Id);
        insert objRequirement;
        //get user
        User tstuser = [select id from user where isActive=true LIMIT 1];
        
        //insert template record
        MICO_test_templates__c TT = new MICO_Test_templates__c (User_Story__c = objRequirement.Id,
													            Title__c = 'My test template title',
													            Introduction__c = 'My test template introduction'		
													        	);
        insert TT;
        
        MICO_test_template_steps__c TTS = new MICO_test_template_steps__c(
        Test_Script__c = TT.id
        );
        insert TTS;
        //insert test record
        MICO_Test__c TestHead = new MICO_Test__c(
                                    Template__c = TT.id,
                                    Test_Phase__c = 'Unit',
                                    user_story__c = objRequirement.Id,
                                    project__c = pro.Id
                                    );
        
        //insert 
        insert testHead;

        //Build Children
        MICO_test_steps__c testSt = new MICO_test_steps__c(
                                                    Name='1.23.4.1',
                                                    test__c = TestHead.id,
                                                    Template_Step__c = TTS.id
                                                    
        );
        
        //insert children
        insert testSt;
        
  
        PageReference pageRef = Page.runTestScript;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('Id', testHead.id);
        
       
        ApexPages.Standardcontroller controller = New ApexPages.StandardController(testHead);
        runTestScriptExtension ext = new runTestScriptExtension(controller);
        system.assertequals(ext.TestSp.size(), 1);

        System.currentPageReference().getParameters().put('testId', testSt.id);
        System.currentPageReference().getParameters().put('testName', testSt.name);
        System.currentPageReference().getParameters().put('req', '');
        ext.addBug();
        ext.Bugs[0].Problem__c = 'bla bla';
        system.assertequals(ext.Bugs.size(),1);
        system.assert(ext.isnewBugs, true);
        
        testSt.Outcome__c = 'Passsed' ;
        update testSt ;
        ext.SaveStep();
        
        TestHead.Overall_Test_Comments__c = 'Passsed' ;
        TestHead.Test_Outcome__c = 'Passsed' ;
        update TestHead ;
        
        ext.Save() ;
        
        ext.AttachFile();
        
    
    }
}