src/objects/MICO_App__c.object
<CustomObject>
    <description>Business Description: This object is used to store a list of applications, capturing their name, use, technical and business contacts as well as physical location.
Used In: Mission Control App

Created on 04/29/2014 by SMills
MICO</description>
    <label>App</label>
    <nameField>
        <label>App Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MICO_Design__c.object
<CustomObject>
    <description>Business Description: This object is used to store designs for user stories. A design can be linked to many user stories and a user story linked to many designs.

Used In: Mission Control App</description>
    <fields>
        <fullName>Apex_Classes__c</fullName>
        <inlineHelpText>A list of apex classes (incuding test classes) used by this design</inlineHelpText>
        <label>Apex Classes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Apex_Trigger__c</fullName>
        <label>Apex Trigger</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>App__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>App</label>
        <referenceTo>MICO_App__c</referenceTo>
        <relationshipLabel>Designs</relationshipLabel>
        <relationshipName>MICO_Designs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>This field will capture the status of approval for design records. It will be auto-populated through the workflow process: Created on 23/07/2014 by Preeti Grover:MICO</description>
        <inlineHelpText>The status of the approval. This is auto populated as the design goes through the process.</inlineHelpText>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Data_Model__c</fullName>
        <label>Data Model</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Fields__c</fullName>
        <label>Fields</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>MICO_Approval_Date__c</fullName>
        <description>This field will capture the date and time when design gets approved: Created on 23/07/2014 by Preeti Grover:MICO</description>
        <inlineHelpText>Date this has been approved by SME</inlineHelpText>
        <label>Approval Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MICO_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will capture the name of the approver for approving designs: Created on 23/07/2014 by Preeti Grover:MICO</description>
        <inlineHelpText>Your signature indicates that the design specifications are technically accurate, address how the computer system requirements are met, meet the requirements of LQP-302-16 and are traceable to one or more requirement.</inlineHelpText>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Designs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Objects__c</fullName>
        <label>Objects</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Other_Components__c</fullName>
        <inlineHelpText>A list of other components related to this design, e.g. SAP scripts etc</inlineHelpText>
        <label>Other Components</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Overview__c</fullName>
        <label>Overview</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Page_Layouts__c</fullName>
        <label>Page Layouts</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>MICO_Project__c</referenceTo>
        <relationshipLabel>Designs</relationshipLabel>
        <relationshipName>MICO_Designs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Visualforce_Pages__c</fullName>
        <inlineHelpText>A list of Visualforce pages used by this design</inlineHelpText>
        <label>Visualforce Pages</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Design</label>
    <nameField>
        <label>Design Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Designs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MICO_Design_History__c.object
<CustomObject>
    <description>Business Description: This object is used to automatically keep a track of all changes to Designs.

Technical Description: Populated by a trigger on Design this is an enhancement to the standard Design history functionality as this does not log changes to rich text fields

Used In: Mission Control App</description>
    <fields>
        <fullName>Apex_Classes__c</fullName>
        <label>Apex Classes</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Apex_Trigger__c</fullName>
        <label>Apex Trigger</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Approval_Date__c</fullName>
        <label>Approval Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Design_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Data_Model__c</fullName>
        <label>Data Model</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Design_Overview__c</fullName>
        <description>The overview before this person edited the Design
To see what the Design overview was changed to, compare this to the next Design History record.</description>
        <label>Design Overview</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Design__c</fullName>
        <label>Design</label>
        <referenceTo>MICO_Design__c</referenceTo>
        <relationshipLabel>Design History</relationshipLabel>
        <relationshipName>Design_History</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Fields__c</fullName>
        <label>Fields</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Objects__c</fullName>
        <label>Objects</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Other_Components__c</fullName>
        <label>Other Components</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Design History</label>
    <nameField>
        <displayFormat>DH-{00000}</displayFormat>
        <label>Design History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Design History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MICO_Project__c.object
<CustomObject>
    <description>Business Description: This object can be used to record projects in multi-project programs

Used In: Mission Control App</description>
    <label>Project mico</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_MICO_DesignTrigger.cls
@isTest
private class Test_MICO_DesignTrigger {

    static testMethod void testDesignHistory() {
    	
    	//set up the pre-requisite data
    	MICO_App__c app = new MICO_App__c();
		MICO_Project__c project = new MICO_Project__c();
		MICO_Design__c design = new MICO_Design__c();
		app.Name = 'MICO';
		project.Name = 'MICOSprints';
		design.Name = 'TestDesign';
		
		insert app;
		insert project;   
		
		//insert approver
		User approver = new User(Alias             = 'aprvr',
							Email             = 'approver@mico-test.com',
							EmailEncodingKey  = 'UTF-8',
							LastName          = 'User',
							FirstName         = 'Approver',
							LanguageLocaleKey = 'en_US',
							LocaleSidKey      = 'en_US',
							ProfileId         = [select Id from Profile where Name = 'GLBL_Chatter Only' limit 1].Id,
							TimeZoneSidKey    = 'America/Chicago',
							Username          = 'stakeholder@mico-test' + Math.round(Math.random() * 10000) + '.com',
							UserRoleId        = null,
							Country           = 'Great Britain');
		insert approver;
		
		design.App__c = app.Id;
		design.Project__c = project.Id;
		design.Overview__c = 'Test';
		design.Data_Model__c = 'Test';
		design.Fields__c = 'Test';
		design.Objects__c = 'Test';
		design.Other_Components__c = 'Test';
		design.Page_Layouts__c = 'Test';
		design.Visualforce_Pages__c = 'Test';
		design.Apex_Classes__c = 'Test';
		design.Apex_Trigger__c = 'Test';
		design.MICO_Approver__c = approver.Id;
		
		insert design;
		
		//run the test
		test.startTest();
		
		design.Approval_Status__c = 'Pending Approval';
		
		update design;
		
		MICO_Design_History__c designHistory = new MICO_Design_History__c();
		designHistory = ([SELECT Id, Design_Overview__c, Data_Model__c, Fields__c,
						  Objects__c, Other_Components__c, Apex_Classes__c , Apex_Trigger__c , 
						  Approver__c, Approval_Date__c 
				   FROM MICO_Design_History__c
				   WHERE Design__c = :design.Id 
				   LIMIT 1])[0];
		
		// check values are copied over
		System.assertEquals(design.Overview__c, designHistory.Design_Overview__c);
		System.assertEquals(design.Data_Model__c, designHistory.Data_Model__c);
		System.assertEquals(design.Fields__c, designHistory.Fields__c);
		System.assertEquals(design.Objects__c, designHistory.Objects__c);
		System.assertEquals(design.Other_Components__c, designHistory.Other_Components__c);
		System.assertEquals(design.Apex_Classes__c, designHistory.Apex_Classes__c);
		System.assertEquals(design.Apex_Trigger__c, designHistory.Apex_Trigger__c);
		System.assertEquals(design.MICO_Approver__c, designHistory.Approver__c);
		
		
		design.Approval_Status__c = 'Approved';
		
		update design;
		
		designHistory = ([SELECT Id, Approval_Date__c 
				   FROM MICO_Design_History__c
				   WHERE Design__c = :design.Id 
				   LIMIT 1])[0];
    	
    	//check approval date is stamped
    	System.assertEquals(design.MICO_Approval_Date__c, designHistory.Approval_Date__c);
    	
    	test.stopTest();
    }	
		
}