src/objects/MICO_Test__c.object
<CustomObject>
    <description>Business Description: This object is used to record the tests which have been executed. 

Each test is a copy of a &quot;Test Template&quot; which has been set up by a Test Manager or other Test Script writer. 

Tests are created by the system automatically when a user is added to the Testers Related list on a Test Template.

Used In: Mission Control App</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>This field will capture the status of approval for Test Execution records. It will be auto-populated through the workflow process: Created on 30/07/2014 by Himanshu Babaria :MICO</description>
        <inlineHelpText>The status of the approval. This is auto populated as the Test Execution goes through the process.</inlineHelpText>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submitter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submitter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Test_Executions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Execution</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Test Execution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Executions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MICO_Test_Templates__c.object
<CustomObject>
    <description>Business Description: This object is used by a Test Manager or Test Script Writer to create a master test script. This master test script can then be copied to different users to execute by adding those users to the &quot;Testers&quot; related list.

Used In: Mission Control App</description>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Test Script Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MICO_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Mission Control App</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>This field is used to capture the status of the approval process in User stories: Created on 06/11/2014 by Preeti Grover:MICO</description>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submitter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submitter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MICO_SubmitForApproval.cls
global class MICO_SubmitForApproval
{
    webservice static void SendEmailMethod(Id localId)
    {
        MICO_User_Story__c micoUserStoryObj = [select Submitter__c, approval_status__c from MICO_User_Story__c where id = : localid];
        micoUserStoryObj.approval_status__c = 'Pending Approval';
        micoUserStoryObj.Submitter__c = UserInfo.getUserId();
        try
        {
            update micoUserStoryObj;
        }
        catch (Exception e)
        {
            System.debug('Exception ' + e);
        }
        System.debug('Submitter' + micoUserStoryObj.Submitter__c);
    }
    
    webservice static void SendEmailMethodTestScript(Id localId)
    {
    
        MICO_Test_Templates__c micoTestTemplateObj=[Select Submitter__c,Approval_Status__c from MICO_Test_Templates__c Where id=:localId];
        micoTestTemplateObj.Approval_Status__c='Pending Approval';
        micoTestTemplateObj.Submitter__c=UserInfo.getUserId();
        try{
            update micoTestTemplateObj;
        }
        catch(Exception e){
             System.debug('Exception ' + e);
        }
    }
    webservice static void SendEmailMethodTestExcecution(Id localId)
    {
    
        MICO_Test__c micoTestTemplateObj=[Select Approval_Status__c from MICO_Test__c Where id=:localId];
        micoTestTemplateObj.Approval_Status__c='Pending Approval';
        micoTestTemplateObj.Submitter__c=UserInfo.getUserId();
        try{
            update micoTestTemplateObj;
        }
        catch(Exception e){
             System.debug('Exception ' + e);
        }
    }
}