src/objects/MICO_Test_Template_History__c.object
<CustomObject>
    <description>Child object for Test Script object to maintain audit trail of Approvals: Created by Preeti Grover on 1/08/2014</description>
    <fields>
        <fullName>Approval_Date__c</fullName>
        <description>date when the test script was approved</description>
        <label>Approval Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>Status of approval request:  Created by Preeti Grover on 01/08/2014: MICO</description>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Name of the approver for this Test Script: Created by Preeti Grover on 01/08/2014: MICO</description>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Test_Scripts_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expected_Result__c</fullName>
        <label>Expected Result</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Test_Script__c</fullName>
        <description>Detail relationship with Test Script: Created by Preeti Grover on 01/08/2014:MICO</description>
        <label>Test Script</label>
        <referenceTo>MICO_Test_Templates__c</referenceTo>
        <relationshipLabel>Test Scripts History</relationshipLabel>
        <relationshipName>Test_Scripts_History</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test Script History</label>
    <nameField>
        <displayFormat>TSA-{0000}</displayFormat>
        <label>Test Script History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MICO_Test_Templates__c.object
<CustomObject>
    <description>Business Description: This object is used by a Test Manager or Test Script Writer to create a master test script. This master test script can then be copied to different users to execute by adding those users to the &quot;Testers&quot; related list.

Used In: Mission Control App</description>
    <fields>
        <fullName>Expected_Result__c</fullName>
        <inlineHelpText>The expected result of this test</inlineHelpText>
        <label>Expected Result</label>
        <type>TextArea</type>
    </fields>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Test Script Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MICO_Test_ScriptTriggerClass.cls
public class MICO_Test_ScriptTriggerClass {
 /*
     * Creates custom Test Execution history records, as we can't do history tracking 
     */
    public static void createNewTestScriptHistoryRecord(Map<Id,MICO_Test_Templates__c> mapTestScript) {
        
        List<MICO_Test_Template_History__c> lstTestScriptHistoryRecords = new List<MICO_Test_Template_History__c>();
        
        try{
            
            for (MICO_Test_Templates__c tempTestScript : mapTestScript.values()) {
            
                MICO_Test_Template_History__c newTestScriptHistoryRecord = new MICO_Test_Template_History__c();
                newTestScriptHistoryRecord.Test_Script__c = tempTestScript.Id;
                newTestScriptHistoryRecord.Approver__c = tempTestScript.Approver__c;
                newTestScriptHistoryRecord.Approval_Date__c = tempTestScript.Approval_Date__c;
                newTestScriptHistoryRecord.Approval_Status__c = tempTestScript.Approval_Status__c;
                newTestScriptHistoryRecord.Expected_Result__c = tempTestScript.Expected_Result__c;
                lstTestScriptHistoryRecords.add(newTestScriptHistoryRecord);
            }
            
            if (!lstTestScriptHistoryRecords.isEmpty()) {
              insert lstTestScriptHistoryRecords;
            }
        }catch(DMLException ex){System.Debug('>>> Error in createNewTestScriptHistoryRecord method of MICO_Test_ScriptTriggerClass class.' + '>>> Error is :: ' + ex.getmessage());}
    }
    
    
    /*
     * Stamps the approval date and approved status on the Test Script History records
     */
    public static void updateApprovalDate(Map<Id,MICO_Test_Templates__c> mapApproval, DateTime approvalDate) {
        try{
            System.Debug('>>> Inside the method');
            //Get the latest Test Script History records to stamp the approval date    
            //Assign Approval date from approved Test Script record to the Test Script History record
             
            //get all related history records
            List<MICO_Test_Template_History__c> lstTestScriptHistoryRecords = [SELECT Id, Approval_Date__c, CreatedDate, Test_Script__c
                                                                            FROM MICO_Test_Template_History__c 
                                                                            WHERE Test_Script__c IN :mapApproval.keySet() 
                                                                            ORDER BY Test_Script__c, CreatedDate ASC];
            
            System.Debug('>>> Query executed');
            //get the latest history for each Test Execution Record
            Map<Id, MICO_Test_Template_History__c> latestTestScriptHistories = new Map<Id, MICO_Test_Template_History__c>();
            for (MICO_Test_Template_History__c historyRecord : lstTestScriptHistoryRecords) {
                latestTestScriptHistories.put(historyRecord.Test_Script__c, historyRecord);
            }
            
            //set the new datestamp
            for (MICO_Test_Template_History__c historyRecord : latestTestScriptHistories.values()) {
                historyRecord.Approval_Date__c = approvalDate;
                historyRecord.Approval_Status__c = 'Approved';
            }
            if (!latestTestScriptHistories.isEmpty()) {
                update latestTestScriptHistories.values();
            }
        }catch(DMLException ex){System.Debug('>>> Error in updateApprovalDate method of MICO_Test_ScriptTriggerClass class.' + '>>> Error is :: ' + ex.getmessage());}
        
    }
        
    /*Update Rejection status on History record*/
    public static void updateRejectionStatus(Map<Id,MICO_Test_Templates__c> mapRejection) {
        try{
            System.Debug('>>> Inside the method');
            //Get the latest Test Script History records to stamp the rejection Status    
            //Assign Rejected status from rejected Test Script record to the Test Script History record
             
            //get all related history records
            List<MICO_Test_Template_History__c> lstTestScriptHistoryRecords = [SELECT Id, CreatedDate, Test_Script__c
                                                                            FROM MICO_Test_Template_History__c 
                                                                            WHERE Test_Script__c IN :mapRejection.keySet() 
                                                                            ORDER BY Test_Script__c, CreatedDate ASC];
            
            System.Debug('>>> Query executed');
            //get the latest history for each Test Execution Record
            Map<Id, MICO_Test_Template_History__c> latestTestScriptHistories = new Map<Id, MICO_Test_Template_History__c>();
            for (MICO_Test_Template_History__c historyRecord : lstTestScriptHistoryRecords) {
                latestTestScriptHistories.put(historyRecord.Test_Script__c, historyRecord);
            }
            
            //set the new status
            for (MICO_Test_Template_History__c historyRecord : latestTestScriptHistories.values()) {
                historyRecord.Approval_Status__c = mapRejection.values().Approval_status__c;
            }
            if (!latestTestScriptHistories.isEmpty()) {
                update latestTestScriptHistories.values();
            }
        }catch(DMLException ex){System.Debug('>>> Error in updateRejectionStatus method of MICO_Test_ScriptTriggerClass class.' + '>>> Error is :: ' + ex.getmessage());}
    }
    
}