src/objects/MICO_Planning_Poker_Session__c.object
<CustomObject>
    <description>Business Description: This object is used as part of the user story estimation process

Used In: Mission Control App</description>
    <label>Planning Poker Session</label>
    <nameField>
        <displayFormat>Session-{0}</displayFormat>
        <label>Planning Poker Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planning Poker Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MICO_Planning_Poker_Session_Content__c.object
<CustomObject>
    <description>Business Description: This object is used as part of the user story estimation process

Used In: Mission Control App</description>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>MICO_User_Story__c</referenceTo>
        <relationshipLabel>Planning Poker Session Contents</relationshipLabel>
        <relationshipName>MICO_Planning_Poker_Session_Contents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Planning Poker Session Content</label>
    <nameField>
        <displayFormat>Content-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planning Poker Session Contents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MICO_Project__c.object
<CustomObject>
    <description>Business Description: This object can be used to record projects in multi-project programs

Used In: Mission Control App</description>
    <label>Project mico</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MICO_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Mission Control App</description>
    <fields>
        <fullName>Project__c</fullName>
        <description>The Project responsible for delivering this User Story
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>The Project responsible for delivering this User Story</inlineHelpText>
        <label>Project</label>
        <referenceTo>MICO_Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>MICO_Project_User_Stories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Test_PlanningPoker.cls
/**
* @author Frank Neezen 
* @date   10/10/2012 
* @description  Test class for Planning Poker. Due to time constraints we are not asserting all data.
*
* Modification Log    :
* ------------------------------------------------------------------------------------------------
* Developer                 Date                    Description
* ---------------         -----------             ----------------------------------------------
* Frank Neezen             10/10/2012             Original Version
*/

@isTest(SeeAllData = false)
public with sharing class Test_PlanningPoker {
    
    
    /******************************************
     * @descroption Test function for the planning poker controller
     * @method  testPlanningPoker
     * @param   none
     * @return  void
     */
     
    static testMethod void testPlanningPoker() {
        
        
        //Create a test uer
        User oUser = runAsUser('PP_User');
        Database.insert(oUser);
        
            //Test enter Session
        System.runAs(oUser){
            //create a project
            MICO_Project__c pro = new MICO_Project__c();
            pro.Name = 'Test Project';
            insert pro;
            
            //Create a user story
            MICO_User_Story__c oUserStory = new MICO_User_Story__c();
            //oUserStory.User_Story__c = 'Test User Story';
            oUserStory.Project__c = pro.Id;
            Database.insert(oUserStory);
            
            //Set US for session generation
            ApexPages.currentPage().getParameters().put('generateSession',oUserStory.Id);
            Controller_PlanningPoker oControllerSession = new Controller_PlanningPoker();
            oControllerSession.generateSession();
        }
        
        //Fetch the session ID
        MICO_Planning_Poker_Session__c oSession = [ Select Id From MICO_Planning_Poker_Session__c ];
        
        //Fetch content
        MICO_Planning_Poker_Session_Content__c oContent = [ Select Id From MICO_Planning_Poker_Session_Content__c ];
            
        //Test enter Session
        System.runAs(oUser){
            ApexPages.currentPage().getParameters().put('id', oSession.Id);
            Controller_PlanningPoker oController = new Controller_PlanningPoker();
            oController.enterSession();
        
        
            //Test set story
            Controller_PlanningPoker.setStory(oContent.Id);
            
            //Test vote
            Controller_PlanningPoker.vote('5',oSession.Id);
            
            //Test re-estimate
            Controller_PlanningPoker.reEstimate(oSession.Id);
            
            //Test set score
            Controller_PlanningPoker.setScore(oSession.Id,'5','SFDC/Veeva','');
            Controller_PlanningPoker.setScore(oSession.Id,'5','Other','');
            
            //Test get data
            Controller_PlanningPoker.PlanningPokerData oData = Controller_PlanningPoker.getData(oSession.Id);
            
            //Test kick user
            Controller_PlanningPoker.kickUser(oUser.Name, oSession.Id);
        }
        
        
    }
    
     /* @name           runAsUser
     * @description     This function returns an Irish admin user, used to change contact details on irish user.
     * @param           String uniqueKey
     * @return          User
     */ 
      public static User runAsUser(String uniqueKey) {
        return new User(
            Alias = uniqueKey,
            Email = uniqueKey + '@tracker.test',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Test' + uniqueKey,
            FirstName = uniqueKey,
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = [select Id from Profile where Name = 'System Administrator' limit 1].Id,
            TimeZoneSidKey = 'Europe/London',
            Username = uniqueKey + '@tracker_' + Math.round(Math.random() * 10000) + '.com'
        );
    }
}