src/objects/MICO_App__c.object
<CustomObject>
    <description>Business Description: This object is used to store a list of applications, capturing their name, use, technical and business contacts as well as physical location.
Used In: Mission Control App

Created on 04/29/2014 by SMills
MICO</description>
    <label>App</label>
    <nameField>
        <label>App Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MICO_Bug__c.object
<CustomObject>
    <description>Business Description: This object is used to track defects (bugs) from being raised to resolved or rejected

Used In: Mission Control App</description>
    <fields>
        <fullName>Problem__c</fullName>
        <label>Problem Summary</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>MavensPM__Project__c</referenceTo>
        <relationshipLabel>Defects</relationshipLabel>
        <relationshipName>MICO_Defects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>User_Story__r.Project__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <label>Defect</label>
    <nameField>
        <displayFormat>DEF-{000000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Defects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MICO_Project__c.object
<CustomObject>
    <description>Business Description: This object can be used to record projects in multi-project programs

Used In: Mission Control App</description>
    <label>Project mico</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MICO_SCM_Commit__c.object
<CustomObject>
    <description>Business Description: This object is used by developers to track what code developments are checked in to the SVN server

Technical Description: This object holds code commit details, populated via a post-commit hook or webhook. Requires SVN server side configuration

Used In: Mission Control App</description>
    <fields>
        <fullName>Body__c</fullName>
        <description>Commit message body</description>
        <inlineHelpText>Commit message body</inlineHelpText>
        <label>Body</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <label>SCM Commit</label>
    <nameField>
        <displayFormat>SCM-{0000000}</displayFormat>
        <label>SCM Commit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCM Commits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MICO_SCM_Commit_Bug_Link__c.object
<CustomObject>
    <description>Business Description: This object is used by developers to track what code developments are related to what Defect. This is populated automatically when a developer commits code to the SVN server and includes the DEF number in their commit comments in the form of DEF-XXXXX

Technical Description: This object holds code commit details, populated via a post-commit hook or webhook. Requires SVN server side configuration

Used In: Mission Control App</description>
    <fields>
        <fullName>Defect__c</fullName>
        <label>Defect</label>
        <referenceTo>MICO_Bug__c</referenceTo>
        <relationshipName>MICO_SCM_Commit_Bug_Link</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SCM_Commit__c</fullName>
        <label>SCM Commit</label>
        <referenceTo>MICO_SCM_Commit__c</referenceTo>
        <relationshipName>MICO_SCM_Commit_Bug_Link</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SCM Commit Defect Link</label>
    <nameField>
        <displayFormat>SCMB-{000000}</displayFormat>
        <label>SCM Commit Bug Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCM Commit Defect Link</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MICO_SCM_Commit_Requirement_Link__c.object
<CustomObject>
    <description>Business Description: This object is used by developers to track what code developments are related to what USer Stories. This is populated automatically when a developer commits code to the SVN server and includes the DEF number in their commit comments in the form of US-XXXXX

Technical Description: This object holds code commit details, populated via a post-commit hook or webhook. Requires SVN server side configuration

Used In: Mission Control App</description>
    <fields>
        <fullName>Requirement__c</fullName>
        <label>User Story</label>
        <referenceTo>MICO_User_Story__c</referenceTo>
        <relationshipName>MICO_SCM_Commit_Requirement_Links</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SCM_Commit__c</fullName>
        <label>SCM Commit</label>
        <referenceTo>MICO_SCM_Commit__c</referenceTo>
        <relationshipName>MICO_SCM_Commit_Requirement_Links</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SCM Commit User Story Link</label>
    <nameField>
        <displayFormat>SCMR-{000000}</displayFormat>
        <label>SCM Commit Requirement Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCM Commit User Story Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MICO_SCM_Commit_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Custom setting to hold configuration for parsing commit details sent from an SCM hosting service e.g. Bitbucket</description>
    <fields>
        <fullName>Defect_Pattern__c</fullName>
        <defaultValue>&quot;DEF-[0-9]{6}&quot;</defaultValue>
        <description>Regular expression for defect refs</description>
        <inlineHelpText>Regular expression for defect refs: Created on 16/07/2014 By SMatharu</inlineHelpText>
        <label>Defect Pattern</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Story_Pattern__c</fullName>
        <defaultValue>&quot;US-[0-9]{6}&quot;</defaultValue>
        <description>Regular expression for user story refs</description>
        <inlineHelpText>Regular expression for user story refs: Created on 16/08/2014 By SMatharu</inlineHelpText>
        <label>User Story Pattern</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>SCM Commit Settings</label>
</CustomObject>

src/objects/MICO_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Mission Control App</description>
    <fields>
        <fullName>App__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The application this user story will enhance
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>The app or application this user story relates to</inlineHelpText>
        <label>App</label>
        <referenceTo>MICO_App__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>The Project responsible for delivering this User Story
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>The Project responsible for delivering this User Story</inlineHelpText>
        <label>Project</label>
        <referenceTo>MICO_Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>MICO_Project_User_Stories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Test_MICO_BitbucketEmailHookManager.cls
@isTest
private class Test_MICO_BitbucketEmailHookManager {

    static testMethod void testHandleInboundEmail() {
    	
    	//set up the pre-requisite data
    	
    	// custom settings
    	MICO_SCM_Commit_Settings__c defaultSetting = new MICO_SCM_Commit_Settings__c();
    	defaultSetting.Name = 'Default';
    	defaultSetting.Defect_Pattern__c = 'DEF-[0-9]{6}';
    	defaultSetting.User_Story_Pattern__c = 'US-[0-9]{6}';
    	insert defaultSetting;
    	
    	// app
		MICO_App__c app = new MICO_App__c();
		app.Name = 'tracker';
		insert app;
		
		// project
		MICO_Project__c project = new MICO_Project__c();
		project.Name = 'tracker';
		insert project;                      
		
		// user story
		MICO_User_Story__c story = new MICO_User_Story__c();
		story.Project__c = project.Id;
		story.App__c = app.Id;
		insert story;
		story = ([SELECT Id, Name
				FROM MICO_User_Story__c
				WHERE Id = :story.Id 
				LIMIT 1])[0];
				
		// defect
		MICO_Bug__c defect = new MICO_Bug__c();
		defect.Project2__c = project.Id;
		defect.Problem__c = 'tracker defect';
		insert defect;
		defect = ([SELECT Id, Name
				FROM MICO_Bug__c
				WHERE Id = :defect.Id 
				LIMIT 1])[0];
    	
    	// email message with 2 commits
        Messaging.Inboundemail email = new Messaging.Inboundemail();
        email.fromAddress = 'commits@tracker.com';
        email.subject = 'Commit details';
        email.plainTextBody = 
        	'3 new commits in Tracker:' + '\n' + 
			'' +  '\n' + 
			'https://bitbucket.org/devservices/tracker/commits/123456/' + '\n' + 
			'Changeset:   123456' + '\n' + 
			'Branch:      None' + '\n' + 
			'User:        tracker' + '\n' + 
			'Date:        2014-07-14 21:45:52' + '\n' + 
			'Summary:     commit message 1, linked to ' + defect.Name + ' and ' + story.Name + '.' + '\n' + 
			'' + '\n' + 
			'Affected #:  1 file' + '\n' + 
			'' + '\n' + 
			'https://bitbucket.org/devservices/tracker/commits/78910/' + '\n' + 
			'Changeset:   78910' + '\n' + 
			'Branch:      None' + '\n' + 
			'User:        tracker' + '\n' + 
			'Date:        2014-07-14 21:46:24' + '\n' + 
			'Summary:     commit message 2' + '\n' + 
			'' + '\n' + 
			'Affected #:  2 files' + '\n' + 
			'' + '\n' +  
			'Repository URL: https://bitbucket.org/devservices/tracker/' + '\n'
        	;
        
        Messaging.Inboundenvelope envelope = new Messaging.Inboundenvelope();
        
        //now run the test
        test.startTest();
        
		// create the email handler
    	MICO_BitbucketEmailHookManager inboundEmailHandler = new MICO_BitbucketEmailHookManager();
    	inboundEmailHandler.handleInboundEmail(email, envelope);
    	
    	//check that 2 commits have been created
    	List<MICO_SCM_Commit__c> commits = [SELECT Id, Body__c FROM MICO_SCM_Commit__c];
    	System.assertEquals(2, commits.size());
    	
    	// check that a link has been created to the bug record
    	MICO_SCM_Commit_Bug_Link__c defectLink = ([SELECT Id, Defect__c, SCM_Commit__c FROM MICO_SCM_Commit_Bug_Link__c])[0];
    	System.assertEquals(defect.Id, defectLink.Defect__c);
        
        // check that a link has been created to the bug record
    	MICO_SCM_Commit_Requirement_Link__c storyLink = ([SELECT Id, Requirement__c, SCM_Commit__c FROM MICO_SCM_Commit_Requirement_Link__c])[0];
    	System.assertEquals(story.Id, storyLink.Requirement__c);
    	
        test.stopTest();
    }
}