src/objects/MICO_Project__c.object
<CustomObject>
    <description>Business Description: This object can be used to record projects in multi-project programs

Used In: Mission Control App</description>
    <label>Project mico</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MICO_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Mission Control App</description>
    <fields>
        <fullName>Acceptance_Criteria__c</fullName>
        <description>The Acceptance Criteria for this user story
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>Acceptance Criteria are the specific, testable and complete needs of this user story. They may follow a structure such as &quot;Given When Then&quot; or list out specific attributes and fields as needed. The Acceptance Criteria are used by developers and testers</inlineHelpText>
        <label>Acceptance Criteria</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>This field is used to capture the status of the approval process in User stories: Created on 06/11/2014 by Preeti Grover:MICO</description>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Compliance_Criteria__c</fullName>
        <description>Compliance / Quality Notes
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>Legal, regulatory or compliance related requirements and observations</inlineHelpText>
        <label>Compliance Criteria</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Compliance_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Business Quality user responsible for this User Story
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>The Business Quality user responsible for this User Story</inlineHelpText>
        <label>Business Quality</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MICO_User_Stories1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Computer_Systems_Quality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Computer Systems Quality User responsible for this User Story
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>The Computer Systems Quality User responsible for this User Story</inlineHelpText>
        <label>Computer Systems Quality</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MICO_User_Stories5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Critical__c</fullName>
        <description>This field is used to capture the criticality information: Created on 06/11/2014 by Preeti Grover:MICO</description>
        <inlineHelpText>Is this User Story considered Quality Critical</inlineHelpText>
        <label>Quality Critical</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Assessed</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GXP__c</fullName>
        <description>This field is used to capture GXP related information: Created on 06/11/2014 by Preeti Grover: MICO</description>
        <inlineHelpText>Is this User Story considered subject to GxP</inlineHelpText>
        <label>GxP</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Assessed</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MICO_Business_Quality_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Please review LQP -302-16 for signature meanings</inlineHelpText>
        <label>Business Quality Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MICO_Computer_Systems_Quality_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Please review LQP -302-16 for signature meanings</inlineHelpText>
        <label>Computer Systems Quality Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MICO_System_Custodian_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Please review LQP -302-16 for signature meanings</inlineHelpText>
        <label>System Custodian Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MICO_System_Owner_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Please review LQP -302-16 for signature meanings</inlineHelpText>
        <label>System Owner Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>The Project responsible for delivering this User Story
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>The Project responsible for delivering this User Story</inlineHelpText>
        <label>Project</label>
        <referenceTo>MICO_Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>MICO_Project_User_Stories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>System_Custodian__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will store the System Custodian information for the app: 
Created on 06/11/2014 by Preeti Grover: MICO</description>
        <inlineHelpText>The System Custodian for the application this User Story is related to. If not set when initially saving the User Story, it should be populated automatically based on the value on the associated App record</inlineHelpText>
        <label>System Custodian</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MICO_User_Stories4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to capture the System owner for the App: Created on 06/11/2014 by Preeti Grover: MICO</description>
        <inlineHelpText>The System Owner for the application this User Story is related to. If not set when initially saving the User Story, it should be populated automatically based on the value on the associated App record</inlineHelpText>
        <label>System Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MICO_User_Stories2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Test_MICO_UserStoryApprovalClass.cls
/*************************************************************************\
    @ Author        : Nitish Kumar
    @ Date          : 25-July-2014
    @ Description   : Test Class for GLBL_LoginAutherizationClass class
****************************************************************************/
@
isTest
private class Test_MICO_UserStoryApprovalClass {


    public static User sysCust;
    public static User sysOwner;
    public static User BysQual;
    public static User SysQual;
    public static list < MICO_Project__Share > projectShare;
    public static MICO_Project__c project;
    public static MICO_User_Story__c testUserStory;



    static testMethod void setupTestData() {

        //Creating the test user for System Custodian
        sysCust = new User();
        sysCust.username = 'sysCust@Test.com.env';
        sysCust.Email = 'sysCust@Test.com';
        sysCust.profileid = UserInfo.getProfileId();
        sysCust.lastname = 'Custodian';
        sysCust.firstname = 'System';
        sysCust.Alias = 'syc';
        sysCust.TimeZoneSidKey = 'America/Los_Angeles';
        sysCust.LocaleSidKey = 'en_US';
        sysCust.EmailEncodingKey = 'UTF-8';
        sysCust.LanguageLocaleKey = 'en_US';
        insert sysCust;

        //Creating the test user for System Owner
        sysOwner = new User();
        sysOwner.username = 'sysOwner@Test.com.env';
        sysOwner.Email = 'sysOwner@Test.com';
        sysOwner.profileid = UserInfo.getProfileId();
        sysOwner.lastname = 'Owner';
        sysOwner.firstname = 'System';
        sysOwner.Alias = 'syo';
        sysOwner.TimeZoneSidKey = 'America/Los_Angeles';
        sysOwner.LocaleSidKey = 'en_US';
        sysOwner.EmailEncodingKey = 'UTF-8';
        sysOwner.LanguageLocaleKey = 'en_US';
        insert sysOwner;

        //Creating the test user for Business Quality
        BysQual = new User();
        BysQual.username = 'BysQual@Test.com.env';
        BysQual.Email = 'BysQual@Test.com';
        BysQual.profileid = UserInfo.getProfileId();
        BysQual.lastname = 'Quality';
        BysQual.firstname = 'Business';
        BysQual.Alias = 'byq';
        BysQual.TimeZoneSidKey = 'America/Los_Angeles';
        BysQual.LocaleSidKey = 'en_US';
        BysQual.EmailEncodingKey = 'UTF-8';
        BysQual.LanguageLocaleKey = 'en_US';
        insert BysQual;

        //Creating the test user for Computer Systems Quality
        SysQual = new User();
        SysQual.username = 'SysQual@Test.com.env';
        SysQual.Email = 'SysQual@Test.com';
        SysQual.profileid = UserInfo.getProfileId();
        SysQual.lastname = 'Quality';
        SysQual.firstname = 'System';
        SysQual.Alias = 'syq';
        SysQual.TimeZoneSidKey = 'America/Los_Angeles';
        SysQual.LocaleSidKey = 'en_US';
        SysQual.EmailEncodingKey = 'UTF-8';
        SysQual.LanguageLocaleKey = 'en_US';
        insert SysQual;

        System.runAs(sysOwner) {

            project = new MICO_Project__c();
            project.Name = 'Test Project';
            insert project;


            testUserStory = new MICO_User_Story__c();
            testUserStory.Project__c = project.id;
            testUserStory.Acceptance_Criteria__c = 'OldAcceptanceCriteria';
            testUserStory.Compliance_Criteria__c = 'OldCC';
            testUserStory.Compliance_Owner__c = BysQual.Id;
            testUserStory.Computer_Systems_Quality__c = SysQual.Id;
            testUserStory.System_Custodian__c = sysCust.Id;
            testUserStory.System_Owner__c = sysOwner.Id;
            testUserStory.GXP__c = 'No';
            testUserStory.Critical__c = 'Yes';
            testUserStory.MICO_Business_Quality_Approved__c = false;
            testUserStory.MICO_Computer_Systems_Quality_Approved__c = false;
            testUserStory.MICO_System_Custodian_Approved__c = false;
            testUserStory.MICO_System_Owner_Approved__c = false;
            testUserStory.Approval_Status__c = 'Open';

            insert testUserStory;
           }
           
           System.runAs(SysQual) {
           testUserStory.Approval_Status__c = 'Pending Approval';
           update testUserStory;
          }
    }

    static testMethod void testApprovalProcess() {

        setupTestData();

        //Negative Scenarios if the status is not equal to Pending approval the button should not be active
        ApexPages.StandardController controller = new ApexPages.StandardController(testUserStory);

        MICO_UserStoryApprovalClass testApprovalClass = new MICO_UserStoryApprovalClass(controller);
        Boolean approveCheck = testApprovalClass.getcheckApproveRejectButton();

        System.assertEquals(approveCheck, false);

        Test.StartTest();
       
        // Postive Case Scenario (Button should be enabled only for System Admin and Custodian)
        System.runAs(sysOwner) {
            Boolean approveChecksysOwner = testApprovalClass.getcheckApproveRejectButton();
            System.assertEquals(approveChecksysOwner, true);
        }

        // Negative Case Scenario (Button should not be enabled only for Business Quality and System Quality User)
        System.runAs(SysQual) {
            Boolean approveCheckSysQual = testApprovalClass.getcheckApproveRejectButton();
            System.assertEquals(approveCheck, false);
        }

        //Setting the Test Page
        testApprovalClass.redirectToApprovalPage();
        PageReference pageRef = Page.MICO_UserStoryApproval;
        Test.setCurrentPageReference(pageRef);

        System.runAs(sysOwner) {
            testApprovalClass.approveUserStory();
            System.assertEquals(true, testUserStory.MICO_System_Owner_Approved__c);
        }

        System.runAs(sysCust) {
            testApprovalClass.approveUserStory();
            System.assertEquals(true, testUserStory.MICO_System_Custodian_Approved__c);
        }

        //Button should be enabled for Business Quality and System Quality User when Sys Custodian and System Owner have approved the story
        //Positive Scenarios
        System.runAs(SysQual) {
            Boolean approveCheckSysQual = testApprovalClass.getcheckApproveRejectButton();
            System.assertEquals(approveCheckSysQual, true);
        }

        System.runAs(SysQual) {
            testApprovalClass.approveUserStory();
            System.assertEquals(true, testUserStory.MICO_Computer_Systems_Quality_Approved__c);
        }

        System.runAs(BysQual) {
            testApprovalClass.approveUserStory();
            System.assertEquals(true, testUserStory.MICO_Business_Quality_Approved__c);
        }
       
        System.runAs(sysOwner) {

            //Changing the status of the enhancement to Pending Approval
            testUserStory.GXP__c = 'No';
            testUserStory.Critical__c = 'No';
            testUserStory.Approval_Status__c = 'Pending Approval';
            update testUserStory;

            Boolean approveChecksysOwner2 = testApprovalClass.getcheckApproveRejectButton();
            System.assertEquals(approveChecksysOwner2, true);

            testApprovalClass.approveUserStory();
            System.assertEquals(true, testUserStory.MICO_System_Owner_Approved__c);
        }


        System.runAs(sysCust) {
            testApprovalClass.approveUserStory();
            System.assertEquals(true, testUserStory.MICO_System_Custodian_Approved__c);
        }
        
        // User story should be approved
         System.assertEquals(true, testUserStory.Approval_Status__c == 'Approved');

        Test.StopTest();
    }

    static testMethod void testRejectionProcess() {
        setupTestData();

        ApexPages.StandardController controller = new ApexPages.StandardController(testUserStory);

        MICO_UserStoryApprovalClass testRejectionClass = new MICO_UserStoryApprovalClass(controller);

        Test.StartTest();
        
        System.runAs(sysOwner) {
            testRejectionClass.rejectUserStory();
            System.assertEquals(false, testUserStory.MICO_System_Owner_Approved__c);
        }
        
        System.assertEquals(true, testUserStory.Approval_Status__c == 'Rejected');

        System.runAs(sysCust) {
            testRejectionClass.rejectUserStory();
            System.assertEquals(false, testUserStory.MICO_System_Custodian_Approved__c);
        }
        
        System.assertEquals(true, testUserStory.Approval_Status__c == 'Rejected');

        System.runAs(SysQual) {
            testRejectionClass.rejectUserStory();
            System.assertEquals(false, testUserStory.MICO_Computer_Systems_Quality_Approved__c);
        }
        
        System.assertEquals(true, testUserStory.Approval_Status__c == 'Rejected');

        System.runAs(BysQual) {
            testRejectionClass.rejectUserStory();
            System.assertEquals(false, testUserStory.MICO_Business_Quality_Approved__c);
        }
        
        System.assertEquals(true, testUserStory.Approval_Status__c == 'Rejected');

        Test.StopTest();
    }


}