src/objects/MICO_Test__c.object
<CustomObject>
    <description>Business Description: This object is used to record the tests which have been executed. 

Each test is a copy of a &quot;Test Template&quot; which has been set up by a Test Manager or other Test Script writer. 

Tests are created by the system automatically when a user is added to the Testers Related list on a Test Template.

Used In: Mission Control App</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>This field will capture the status of approval for Test Execution records. It will be auto-populated through the workflow process: Created on 30/07/2014 by Himanshu Babaria :MICO</description>
        <inlineHelpText>The status of the approval. This is auto populated as the Test Execution goes through the process.</inlineHelpText>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Test Execution</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Test Execution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Executions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MICO_Test_Steps__c.object
<CustomObject>
    <description>Business Description: This object is used to record the test steps which have been executed.

Each Test Step is a copy of a &quot;Test Template Step&quot; which has been set up by a Test Manager or other Test Script writer.

Tests are created by the system automatically when a user is added to the Testers Related list on a Test Template.

Used In: Mission Control App</description>
    <fields>
        <fullName>Test__c</fullName>
        <label>Test</label>
        <referenceTo>MICO_Test__c</referenceTo>
        <relationshipName>MICO_Test_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Test Execution Step</label>
    <nameField>
        <label>Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Execution Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MICO_Test_Template_Steps__c.object
<CustomObject>
    <description>Business Description: This object is used to record the individual steps of a test template. Test Templates are the master copy of a Test that can be executed many times by different people.

Used In: Mission Control App</description>
    <fields>
        <fullName>Test_Script__c</fullName>
        <label>Test Script</label>
        <referenceTo>MICO_Test_Templates__c</referenceTo>
        <relationshipName>MICO_Test_Script_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Test Script Step</label>
    <nameField>
        <displayFormat>TSS-{000000}</displayFormat>
        <label>Test Script Step Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Script Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MICO_Test_Templates__c.object
<CustomObject>
    <description>Business Description: This object is used by a Test Manager or Test Script Writer to create a master test script. This master test script can then be copied to different users to execute by adding those users to the &quot;Testers&quot; related list.

Used In: Mission Control App</description>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Test Script Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MICO_AttachmentTriggerUtility.cls
/*************************************************************************\
    @ Author        : Nitish Kumar
    @ Date          : 22-Aug-2014
    @ Test Class    : 
    @ Description   : The helper class for MICO_AttachmentTrigger.
****************************************************************************/
public with sharing class MICO_AttachmentTriggerUtility {

    /*********************************************************************************************************************
          Method : checkAttachmentonTSStep
          Input Parameters : Set of Id of Test Script Step and map containing the parent id and attachment
          Description : This method will be used to stop the deletion of attachment if the test script has been approved    
         ********************************************************************************************************************/

    public static void checkAttachmentonTSStep(Set < Id > setTestScriptStep, map < Id, Attachment > mapTestScriptStep) {

        //getting the Test Script Step records
        list < MICO_Test_Template_Steps__c > lstTestScriptStep = [Select id, Test_Script__r.Approval_Status__c from MICO_Test_Template_Steps__c where Id IN: setTestScriptStep];

        for (MICO_Test_Template_Steps__c testScriptStep: lstTestScriptStep) {
            if ((testScriptStep.Test_Script__r.Approval_Status__c == 'Approved' || testScriptStep.Test_Script__r.Approval_Status__c == 'Pending Approval') && mapTestScriptStep.containsKey(testScriptStep.id)) {
                //adding the error message if the Test Script has been approved
                mapTestScriptStep.get(testScriptStep.id).addError(Label.MICO_Error_On_Test_Script);
            }
        }
    }

    /*********************************************************************************************************************
          Method : checkAttachmentonTExecution
          Input Parameters : Set of Id of Test Execution and map containing the parent id and attachment
          Description : This method will be used to stop the deletion of attachment if the test script has been approved    
        ********************************************************************************************************************/

    public static void checkAttachmentonTExecution(Set < Id > setTestExecution, map < Id, Attachment > mapTestExecution) {

        //getting the Test Execution records
        list < MICO_Test__c > lstTestExecution = [Select id, Approval_Status__c from MICO_Test__c where Id IN: setTestExecution];

        for (MICO_Test__c testExecution: lstTestExecution) {
            if ((testExecution.Approval_Status__c == 'Approved' || testExecution.Approval_Status__c == 'Pending Approval' ) && mapTestExecution.containsKey(testExecution.id)) {
                //adding the error message if the Test Script has been approved
                mapTestExecution.get(testExecution.id).addError(Label.MICO_Error_On_Test_Execution);
            }
        }
    }

    /*********************************************************************************************************************
       Method : checkAttachmentonTExecutionStep
       Input Parameters : Set of Id of Test Execution Step and map containing the parent id and attachment
       Description : This method will be used to stop the deletion of attachment if the test script has been approved    
     ********************************************************************************************************************/

    public static void checkAttachmentonTExecutionStep(Set < Id > setTestExecutionStep, map < Id, Attachment > mapTestExecutionStep) {

        //getting the Test Execution Step records
        list < MICO_Test_Steps__c > lstTestExecutionStep = [Select id, Test__r.Approval_Status__c from MICO_Test_Steps__c where Id IN: setTestExecutionStep];

        for (MICO_Test_Steps__c testExecutionStep: lstTestExecutionStep) {
            if ((testExecutionStep.Test__r.Approval_Status__c == 'Approved' || testExecutionStep.Test__r.Approval_Status__c == 'Pending Approval')  && mapTestExecutionStep.containsKey(testExecutionStep.id)) {
                //adding the error message if the Test Script has been approved
                mapTestExecutionStep.get(testExecutionStep.id).addError(Label.MICO_Error_On_Test_Execution_Step);
            }
        }

    }

}