src/objects/MICO_Bug__c.object
<CustomObject>
    <description>Business Description: This object is used to track defects (bugs) from being raised to resolved or rejected

Used In: Mission Control App</description>
    <label>Defect</label>
    <nameField>
        <displayFormat>DEF-{000000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Defects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MICO_SCM_Commit__c.object
<CustomObject>
    <description>Business Description: This object is used by developers to track what code developments are checked in to the SVN server

Technical Description: This object holds code commit details, populated via a post-commit hook or webhook. Requires SVN server side configuration

Used In: Mission Control App</description>
    <fields>
        <fullName>Author__c</fullName>
        <description>User that performed the code commit</description>
        <inlineHelpText>User that performed the code commit</inlineHelpText>
        <label>Author</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Body__c</fullName>
        <description>Commit message body</description>
        <inlineHelpText>Commit message body</inlineHelpText>
        <label>Body</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <label>Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <description>Commit message relationships (Defects, User Stories)</description>
        <inlineHelpText>Commit message relationships (Defects, User Stories)</inlineHelpText>
        <label>Related To</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Revision__c</fullName>
        <description>Field will hold the Revision number of the SCM Record</description>
        <inlineHelpText>This number is the Revision number from the Repository when these changes have been committed</inlineHelpText>
        <label>Revision</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <label>SCM Commit</label>
    <nameField>
        <displayFormat>SCM-{0000000}</displayFormat>
        <label>SCM Commit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCM Commits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MICO_SCM_Commit_Bug_Link__c.object
<CustomObject>
    <description>Business Description: This object is used by developers to track what code developments are related to what Defect. This is populated automatically when a developer commits code to the SVN server and includes the DEF number in their commit comments in the form of DEF-XXXXX

Technical Description: This object holds code commit details, populated via a post-commit hook or webhook. Requires SVN server side configuration

Used In: Mission Control App</description>
    <fields>
        <fullName>Defect__c</fullName>
        <label>Defect</label>
        <referenceTo>MICO_Bug__c</referenceTo>
        <relationshipName>MICO_SCM_Commit_Bug_Link</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SCM_Commit__c</fullName>
        <label>SCM Commit</label>
        <referenceTo>MICO_SCM_Commit__c</referenceTo>
        <relationshipName>MICO_SCM_Commit_Bug_Link</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SCM Commit Defect Link</label>
    <nameField>
        <displayFormat>SCMB-{000000}</displayFormat>
        <label>SCM Commit Bug Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCM Commit Defect Link</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MICO_SCM_Commit_Requirement_Link__c.object
<CustomObject>
    <description>Business Description: This object is used by developers to track what code developments are related to what USer Stories. This is populated automatically when a developer commits code to the SVN server and includes the DEF number in their commit comments in the form of US-XXXXX

Technical Description: This object holds code commit details, populated via a post-commit hook or webhook. Requires SVN server side configuration

Used In: Mission Control App</description>
    <fields>
        <fullName>Requirement__c</fullName>
        <label>User Story</label>
        <referenceTo>MICO_User_Story__c</referenceTo>
        <relationshipName>MICO_SCM_Commit_Requirement_Links</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SCM_Commit__c</fullName>
        <label>SCM Commit</label>
        <referenceTo>MICO_SCM_Commit__c</referenceTo>
        <relationshipName>MICO_SCM_Commit_Requirement_Links</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SCM Commit User Story Link</label>
    <nameField>
        <displayFormat>SCMR-{000000}</displayFormat>
        <label>SCM Commit Requirement Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCM Commit User Story Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MICO_SCM_Commit_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Custom setting to hold configuration for parsing commit details sent from an SCM hosting service e.g. Bitbucket</description>
    <fields>
        <fullName>Defect_Pattern__c</fullName>
        <defaultValue>&quot;DEF-[0-9]{6}&quot;</defaultValue>
        <description>Regular expression for defect refs</description>
        <inlineHelpText>Regular expression for defect refs: Created on 16/07/2014 By SMatharu</inlineHelpText>
        <label>Defect Pattern</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Story_Pattern__c</fullName>
        <defaultValue>&quot;US-[0-9]{6}&quot;</defaultValue>
        <description>Regular expression for user story refs</description>
        <inlineHelpText>Regular expression for user story refs: Created on 16/08/2014 By SMatharu</inlineHelpText>
        <label>User Story Pattern</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>SCM Commit Settings</label>
</CustomObject>

src/objects/MICO_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Mission Control App</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MICO_BitbucketEmailHookManager.cls
/**
 * Handles emails from Bitbucket each time a push is made to the repository
 */
global class MICO_BitbucketEmailHookManager implements Messaging.InboundEmailHandler {
	
	global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope envelope) {
		
		// get the email
		Messaging.InboundEmailResult result = new Messaging.InboundEmailresult();
		System.debug('Inbound email message:\n' + email.plainTextBody);
		
		// create the commit records
		List<MICO_SCM_Commit__c> commits = createCommits(email.plainTextBody);
		
		// create the story and defect link records
		createCommitDefectLinks(commits);
		createCommitStoryLinks(commits);
		
		return result;
	}
	
	
	/**
	 * Parse email body and create an SCM Commit record for each Git commit
	 */
	private List<MICO_SCM_Commit__c> createCommits(String commitText) {
		
		List<MICO_SCM_Commit__c> commits = new List<MICO_SCM_Commit__c>();
		
		MICO_StringUtilsLineReader lineReader = new MICO_StringUtilsLineReader(commitText);
		//List<String> newLines = new List<String>();
		
		MICO_SCM_Commit__c commitRecord;
		
		// bool to track if we are in the middle of parsing the summary.
		// we need this in case there are line breaks in the commit message
		Boolean isParsingCommitMessage = false;
		
		// parse each line
		while (lineReader.hasNext()) {
			
		    String line = lineReader.next();
		    System.debug('Parsing line:' + line);
		    
		    if (line.startsWith('https://bitbucket.org')) {
		    	isParsingCommitMessage = false;
		    	commitRecord = new MICO_SCM_Commit__c();
		    	commitRecord.Link__c = line;
		    }
		    else if (line.startsWith('Changeset:')) {
		    	isParsingCommitMessage = false;
		    	commitRecord.Revision__c = line.substring('Changeset:'.length(), line.length());
		    }
		    else if (line.startsWith('Summary:')) {
		    	isParsingCommitMessage = true;
		    	commitRecord.Body__c = line.substring('Summary:'.length(), line.length());
		    	commitRecord.Related_To__c = null;
		    }
		    else if (line.startsWith('User:')) {
		    	isParsingCommitMessage = false;
		    	commitRecord.Author__c = line.substring('User:'.length(), line.length());
		    }
		    else if (line.startsWith('Affected #:')) {
		    	isParsingCommitMessage = false;
		    	commits.add(commitRecord);
		    }
		    else {
		    	if (isParsingCommitMessage) {
		    		commitRecord.Body__c = commitRecord.Body__c + '\n' + line;
		    	}
		    }
		}
		
		insert commits;
		return commits;	
	}
	
	
	/**
	 * Parse the commit messages and create defect links if needed
	 */
	private List<MICO_SCM_Commit_Bug_Link__c> createCommitDefectLinks(List<MICO_SCM_Commit__c> commits) {
		
		List<MICO_SCM_Commit_Bug_Link__c> commitLinks = new List<MICO_SCM_Commit_Bug_Link__c>();
		List<String> defectNames = new List<String>();
		Map<String, MICO_Bug__c> defects = new Map<String, MICO_Bug__c>();
		
		// set up the pattern to look for
		MICO_SCM_Commit_Settings__c defaultSetting = ([SELECT Name, Defect_Pattern__c, User_Story_Pattern__c FROM MICO_SCM_Commit_Settings__c LIMIT 1])[0];
		Pattern p = Pattern.compile(defaultSetting.Defect_Pattern__c);
		
		//1st pass - get a list of all defect names so we can fetch them
		for (MICO_SCM_Commit__c commitRecord : commits) {
			Matcher matcher = p.matcher(commitRecord.Body__c);
			
			// if the pattern is found, add the defect name to the list of defects
			while (matcher.find()) {
				defectNames.add(matcher.group(0));
	        }
		}
		
		//now fetch all those defects and put them in a map by defect name
		for (MICO_Bug__c defect : [SELECT Id, Name FROM MICO_Bug__c WHERE Name IN :defectNames]) {
			defects.put(defect.Name, defect);
		}
		
		//2nd pass - create the link records for the found defects
		for (MICO_SCM_Commit__c commitRecord : commits) {
			Matcher matcher = p.matcher(commitRecord.Body__c);
			
			while (matcher.find()) {
				MICO_Bug__c defect = defects.get(matcher.group(0));
				if (defect != null) {
					MICO_SCM_Commit_Bug_Link__c linkRecord = new MICO_SCM_Commit_Bug_Link__c();
					linkRecord.SCM_Commit__c = commitRecord.Id;
					linkRecord.Defect__c = defect.Id;
					commitLinks.add(linkRecord);
				}
	        }
		}
		
		insert commitLinks;
		return commitLinks;
	}
	
	
	/**
	 * Parse the commit messages and create story links if needed
	 */
	private List<MICO_SCM_Commit_Requirement_Link__c> createCommitStoryLinks(List<MICO_SCM_Commit__c> commits) {
		
		List<MICO_SCM_Commit_Requirement_Link__c> commitLinks = new List<MICO_SCM_Commit_Requirement_Link__c>();
		List<String> storyNames = new List<String>();
		Map<String, MICO_User_Story__c> stories = new Map<String, MICO_User_Story__c>();
		
		// set up the pattern to look for
		MICO_SCM_Commit_Settings__c defaultSetting = ([SELECT Name, Defect_Pattern__c, User_Story_Pattern__c FROM MICO_SCM_Commit_Settings__c LIMIT 1])[0];
		Pattern p = Pattern.compile(defaultSetting.User_Story_Pattern__c);
		
		//1st pass - get a list of all defect names so we can fetch them
		for (MICO_SCM_Commit__c commitRecord : commits) {
			Matcher matcher = p.matcher(commitRecord.Body__c);
			
			// if the pattern is found, add the defect name to the list of defects
			while (matcher.find()) {
				storyNames.add(matcher.group(0));
	        }
		}
		
		//now fetch all those defects and put them in a map by defect name
		for (MICO_User_Story__c story : [SELECT Id, Name FROM MICO_User_Story__c WHERE Name IN :storyNames]) {
			stories.put(story.Name, story);
		}
		
		//2nd pass - create the link records for the found stories
		for (MICO_SCM_Commit__c commitRecord : commits) {
			Matcher matcher = p.matcher(commitRecord.Body__c);
			
			while (matcher.find()) {
				MICO_User_Story__c story = stories.get(matcher.group(0));
				if (story != null) {
					MICO_SCM_Commit_Requirement_Link__c linkRecord = new MICO_SCM_Commit_Requirement_Link__c();
					linkRecord.SCM_Commit__c = commitRecord.Id;
					linkRecord.Requirement__c = story.Id;
					commitLinks.add(linkRecord);
				}
	        }
		}
		
		insert commitLinks;
		return commitLinks;
	}
}