src/objects/MICO_Project__c.object
<CustomObject>
    <description>Business Description: This object can be used to record projects in multi-project programs

Used In: Mission Control App</description>
    <label>Project mico</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MICO_Sprint__c.object
<CustomObject>
    <description>Business Description: This object is used to hold details about the sprints or iterations. It includes information about start and end dates, as well as overall capacity.

Used In: Mission Control App</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>MICO_Project__c</referenceTo>
        <relationshipLabel>Sprints</relationshipLabel>
        <relationshipName>MICO_Sprints</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MICO_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Mission Control App</description>
    <fields>
        <fullName>Allocated_Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The sprint this story has been allocated to. Used for sprint planning and in the burndown
Created on 04/07/2014 by SMills 
MICO</description>
        <inlineHelpText>The sprint that this story has been committed to</inlineHelpText>
        <label>Allocated Sprint</label>
        <referenceTo>MICO_Sprint__c</referenceTo>
        <relationshipLabel>Allocated User Stories</relationshipLabel>
        <relationshipName>MICO_Allocated_User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Development_Stage__c</fullName>
        <description>User story status. This drives burndown, kanban and reporting
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>The stage this User Story is at in the Sprint lifecycle. User Stories are &quot;burned&quot; in the Sprint Dashboard when they are set to &quot;Passed (Complete)&quot;</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Cancelled</fullName>
                <color>#663333</color>
            </picklistValues>
            <picklistValues>
                <fullName>Backlog</fullName>
                <color>#999999</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Story Definition</fullName>
                <color>#FF6666</color>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Development</fullName>
                <color>#FFCC66</color>
            </picklistValues>
            <picklistValues>
                <fullName>In Development</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Test Release</fullName>
                <color>#66FF99</color>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Test</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>In Test</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Passed (Complete)</fullName>
                <color>#009900</color>
            </picklistValues>
            <picklistValues>
                <fullName>Production - Ready for Release</fullName>
                <color>#66E9BD</color>
            </picklistValues>
            <picklistValues>
                <fullName>Production - Released</fullName>
                <color>#006600</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>The Project responsible for delivering this User Story
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>The Project responsible for delivering this User Story</inlineHelpText>
        <label>Project</label>
        <referenceTo>MICO_Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>MICO_Project_User_Stories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Proposed_Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Proposed Sprint. Used in Sprint Planning
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>Following Release Planning this User Story can be proposed for a particular sprint. Stories can the be taken in or rejected from this sprint during the Sprint Planning process, as determined by the Product Owner</inlineHelpText>
        <label>Proposed Sprint</label>
        <referenceTo>MICO_Sprint__c</referenceTo>
        <relationshipLabel>Proposed User Stories</relationshipLabel>
        <relationshipName>MICO_Proposed_User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Release_Completeness__c</fullName>
        <defaultValue>false</defaultValue>
        <description>System field to show release completeness, populated by workflow
Created on 01/07/2014 by SMills 
MICO</description>
        <label>Release Completeness</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Release_Steps_Automated__c</fullName>
        <inlineHelpText>Elements which have to be deployed in an automated way (Eclipse).
Please put N/A when not applicable</inlineHelpText>
        <label>Release Steps (Automated)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Release_Steps_Manual__c</fullName>
        <description>List of manual steps needed to deploy this user story.
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>Deployment steps that aren&apos;t captured by part of the automated metadata deployment process. Please ensure these are clear, concise, complete and specify whether they are pre or post deployment steps.

Put N/A if none are needed</inlineHelpText>
        <label>Release Steps (Manual)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Supporting_BA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Business Analyst responsible for defining the acceptance criteria
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>The Business Analyst responsible for helping define and refine Acceptance Criteria in this User Story</inlineHelpText>
        <label>Business Analyst</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MICO_User_Stories3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Product Owner User responsible for this User Story
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>Business/Product Owner for this User Story</inlineHelpText>
        <label>Product / Process Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MICO_Requirements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Validation_steps__c</fullName>
        <description>Validation Steps for this user story
Created on 06/11/2014 by Preeti Grover: MICO</description>
        <inlineHelpText>For exception cases, please list any specific validation checks that are required to ensure this User Story has been deployed successfully. These will then be run by the Technical Release Team post deployment

If none are needed please put &apos;N/A&quot;</inlineHelpText>
        <label>Validation steps</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <inlineHelpText>The source control tag related to this User Story</inlineHelpText>
        <label>Version</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Test_KanbanBoard.cls
@isTest
public class Test_KanbanBoard{

    public static testmethod void TestControlleroad(){
        //create a project
        MICO_Project__c pro = new MICO_Project__c();
        pro.Name = 'Test Project';
        insert pro;
        
        MICO_Sprint__c sp1 = new MICO_Sprint__c();
        sp1.Name = 'Sprint 1A';
        sp1.Project__c = pro.Id;
        insert sp1;
        
        MICO_User_Story__c Req = new MICO_User_Story__c();
        Req.Proposed_Sprint__c = sp1.Id;
        Req.Allocated_Sprint__c = sp1.Id;
        Req.Development_Stage__c = 'BackLog';
        Req.User__c = UserInfo.getUserId();
        Req.Supporting_BA__c = UserInfo.getUserId();
        Req.Release_Steps_Manual__c= 'N/A';
        Req.Release_Steps_Automated__c = 'N/A';
        Req.Version__c = 'N/A';
        Req.Validation_steps__c = 'N/A';
        Req.Release_Completeness__c = true;
        Req.Project__c = pro.Id;
        insert Req;
        
        PageReference pageRef = Page.DigitalKanban;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', sp1.Id);
        ApexPages.StandardController cnt = new ApexPages.StandardController(Req);
        KanbanBoardCntrl KBC = new KanbanBoardCntrl(cnt);
        KBC.getsprintval();
        KBC.getFuncval();
        ApexPages.currentPage().getParameters().put('UpdateSwing', 'AwaitingDevUS');
        ApexPages.currentPage().getParameters().put('UserStoryID', req.Id);
        
        KBC.updateUserStoriesSprint();
        ApexPages.currentPage().getParameters().put('UpdateSwing', 'InDevUS');
        KBC.updateUserStoriesSprint();
        ApexPages.currentPage().getParameters().put('UpdateSwing', 'BacklogUS');
        KBC.updateUserStoriesSprint();
        ApexPages.currentPage().getParameters().put('UpdateSwing', 'AwaitingSATUS');
        KBC.updateUserStoriesSprint();
        ApexPages.currentPage().getParameters().put('UpdateSwing', 'DoneUS');
        KBC.updateUserStoriesSprint();
        ApexPages.currentPage().getParameters().put('UpdateSwing', 'InSATUS');
        KBC.updateUserStoriesSprint();
        ApexPages.currentPage().getParameters().put('UpdateSwing', 'BPC');
        KBC.updateUserStoriesSprint();
        ApexPages.currentPage().getParameters().put('ChatterComment', 'DoneUS');
        KBC.addChatterComment();
        KBC.filteredVal();
        KBC.selvalue  = sp1.Name;
        KBC.filteredVal();
        KBC.funcSelValue = 'Market Access';
        KBC.DispUserStories(sp1.Name);
        KBC.DispUserStories(null);
        
    } 
}