src/objects/MICO_Bug__c.object
<CustomObject>
    <description>Business Description: This object is used to track defects (bugs) from being raised to resolved or rejected

Used In: Mission Control App</description>
    <fields>
        <fullName>Comments__c</fullName>
        <inlineHelpText>Comments and notes can be used by developers, testers and managers to record comments, questions etc about issues. You should never overwrite others comments but should add yours to the top of the comment section, followed by your name.</inlineHelpText>
        <label>Comments / notes</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Log_Time__c</fullName>
        <label>Log Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Logged_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Logged By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MICO_Defects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>MavensPM__Project__c</referenceTo>
        <relationshipLabel>Defects</relationshipLabel>
        <relationshipName>MICO_Defects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>User_Story__r.Project__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Script_Number__c</fullName>
        <inlineHelpText>If this bug was raised when running a script, please note the script number here</inlineHelpText>
        <label>Script Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sprint2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sprint</label>
        <referenceTo>MICO_Sprint__c</referenceTo>
        <relationshipLabel>Defects</relationshipLabel>
        <relationshipName>MICO_Defects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Raised</fullName>
                <color>#000000</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Triaged</fullName>
                <color>#333333</color>
            </picklistValues>
            <picklistValues>
                <fullName>Parked</fullName>
                <color>#0B24BE</color>
            </picklistValues>
            <picklistValues>
                <fullName>For Discussion</fullName>
                <color>#999999</color>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Development</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>In development</fullName>
                <color>#CC6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for testing</fullName>
                <color>#FFFF66</color>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked from testing</fullName>
                <color>#993399</color>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for sign-off</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Complete</fullName>
                <color>#006600</color>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Consolidated</fullName>
                <color>#006600</color>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - New User Story Required</fullName>
                <color>#006600</color>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - New User Story Created</fullName>
                <color>#006600</color>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Rejected</fullName>
                <color>#006600</color>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Unreplicable</fullName>
                <color>#006600</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Test_Execution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Test Execution</label>
        <referenceTo>MICO_Test__c</referenceTo>
        <relationshipLabel>Defects</relationshipLabel>
        <relationshipName>MICO_Defects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Test_Phase__c</fullName>
        <inlineHelpText>The phase of testing this bug was raised in.

For January testing this will either be System 1 or System 2</inlineHelpText>
        <label>Test Phase</label>
        <picklist>
            <picklistValues>
                <fullName>UAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SAT</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Regression</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>MICO_User_Story__c</referenceTo>
        <relationshipLabel>Defects (User Story)</relationshipLabel>
        <relationshipName>MICO_Story_Defects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Defect</label>
    <nameField>
        <displayFormat>DEF-{000000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Defects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MICO_Test__c.object
<CustomObject>
    <description>Business Description: This object is used to record the tests which have been executed. 

Each test is a copy of a &quot;Test Template&quot; which has been set up by a Test Manager or other Test Script writer. 

Tests are created by the system automatically when a user is added to the Testers Related list on a Test Template.

Used In: Mission Control App</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>MICO_Project__c</referenceTo>
        <relationshipLabel>Test Executions</relationshipLabel>
        <relationshipName>MICO_Test_Executions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>The stage in the test lifecycle. A test case can be Status=Complete and fOutcome=&quot;Failed&quot; if a bug has been raised. Once the bug has been fixed the test case may be set to &quot;Awaiting Retest&quot; by the Test Lead</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Retest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Test_Phase__c</fullName>
        <label>Test Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Sprint Test</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>User Acceptance Test</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stability Test</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regression Test</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance Test</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>MICO_User_Story__c</referenceTo>
        <relationshipName>MICO_Tests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Execution</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Test Execution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Executions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MICO_Test_Bug_Link__c.object
<CustomObject>
    <description>Business Description: This object is used to link defects to the test step they were created from if the defect was raised during the running of a test script.

Used In: Mission Control App</description>
    <fields>
        <fullName>Bug__c</fullName>
        <label>Bug</label>
        <referenceTo>MICO_Bug__c</referenceTo>
        <relationshipName>MICO_Case_Bug_Links</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Test_Script__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Test Script</label>
        <referenceTo>MICO_Test__c</referenceTo>
        <relationshipName>MICO_Bug_Links</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Test_Step_Result__c</fullName>
        <label>Test Step Result</label>
        <referenceTo>MICO_Test_Steps__c</referenceTo>
        <relationshipName>MICO_Case_Bug_Links</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test / Defect Link</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Link No:</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test / Defect Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MICO_Test_Steps__c.object
<CustomObject>
    <description>Business Description: This object is used to record the test steps which have been executed.

Each Test Step is a copy of a &quot;Test Template Step&quot; which has been set up by a Test Manager or other Test Script writer.

Tests are created by the system automatically when a user is added to the Testers Related list on a Test Template.

Used In: Mission Control App</description>
    <fields>
        <fullName>Action__c</fullName>
        <formula>Template_Step__r.Action__c</formula>
        <inlineHelpText>What a user needs to do, including point and click instructions where appropriate</inlineHelpText>
        <label>Action</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <inlineHelpText>Notes and Comments about the test from the tester. This should be populated if a test step is failed in any way</inlineHelpText>
        <label>Actual Results</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Expected_Results__c</fullName>
        <formula>Template_Step__r.Expected_Result__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The result or behaviour that is expected</inlineHelpText>
        <label>Expected Results</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Outcome__c</fullName>
        <inlineHelpText>What was the result of this step? If it Failed or had minor issues please note what these were.</inlineHelpText>
        <label>Outcome</label>
        <picklist>
            <picklistValues>
                <fullName>Pass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passed with issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <label>Test</label>
        <referenceTo>MICO_Test__c</referenceTo>
        <relationshipName>MICO_Test_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Tips__c</fullName>
        <formula>Template_Step__r.Tips__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Hints &amp; Tips for completing this step</inlineHelpText>
        <label>Tips</label>
        <type>Text</type>
    </fields>
    <label>Test Execution Step</label>
    <nameField>
        <label>Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Execution Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MICO_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Mission Control App</description>
    <fields>
        <fullName>Allocated_Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The sprint this story has been allocated to. Used for sprint planning and in the burndown
Created on 04/07/2014 by SMills 
MICO</description>
        <inlineHelpText>The sprint that this story has been committed to</inlineHelpText>
        <label>Allocated Sprint</label>
        <referenceTo>MICO_Sprint__c</referenceTo>
        <relationshipLabel>Allocated User Stories</relationshipLabel>
        <relationshipName>MICO_Allocated_User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>The Project responsible for delivering this User Story
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>The Project responsible for delivering this User Story</inlineHelpText>
        <label>Project</label>
        <referenceTo>MICO_Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>MICO_Project_User_Stories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/runTestScriptExtension.cls
/****************************************************************************************************************************************** 
* Class Name   : runTestScriptExtension
* Description  : functionality for tests
* Created By   : Deloitte Consulting
* 
*****************************************************************************************************************************************/

public with sharing class runTestScriptExtension { 
        
        Public final Id Test = System.currentPageReference().getParameters().get('Id');
        
        Private final MICO_test__c tst;
        
        public Boolean isnewBugs{get;set;}
        
        private list<MICO_Test_Bug_Link__c> BugLink = new list<MICO_Test_Bug_Link__c>();
        private Map<string, id> stepName = new Map<string, id>();
        
        public runTestScriptExtension(ApexPages.StandardController stdController) {
        this.tst = (MICO_test__c)stdController.getRecord();
    }
        
        
        
        Public list<MICO_Bug__c> Bugs {get{
                if(Bugs == null){
                        Bugs = new list<MICO_Bug__c>();
                }
                return Bugs;
                
        }set;
        }
        
        
        Public list<MICO_test_steps__c> TestSp {get{
                if(testSp == null){
                        TestSp = [select id,
                                                        name, 
                                                        Action__c, 
                                                        Expected_Results__c, 
                                                        Tips__c, 
                                                        Outcome__c, 
                                                        Comments__c
                                                        
                                                        from MICO_test_steps__c 
                                                        where test__c = :Test order by Name];
                                                        
                        for(MICO_test_steps__c t : TestSp){
                                stepName.put(t.name, t.id);
                        }
                }
                return TestSp;
        
        
        }set;}
        
          public PageReference addBug(){
                id testId = System.currentPageReference().getParameters().get('Id');

MICO_Test__c test = [Select Id, User_Story__c, User_Story__r.Allocated_Sprint__c, User_Story__r.Project__c from MICO_Test__c where Id =: testId][0];
                string testStepName = System.currentPageReference().getParameters().get('testName');
                isnewBugs = true;
                Bugs.add(new MICO_Bug__c(script_number__c = testStepName, status__c='Raised', User_Story__c= test.User_Story__c, Test_Phase__c = tst.Test_Phase__c, Test_Execution__c = testId, 
                                        project2__c = test.User_Story__r.Project__c, sprint2__c = test.User_Story__r.Allocated_Sprint__c, Logged_By__c = UserInfo.getUserId(),Log_Time__c = system.now()  ));
                
                system.debug(Bugs);
                return null;
        }
        
        Public PageReference Save(){
                update tst;
                update TestSp;  
                if(!bugs.isEmpty()){
                        insert Bugs;
                        for(MICO_Bug__c b: Bugs){
                                id testst = stepName.get(b.script_number__c);
                                BugLink.add(new MICO_Test_Bug_Link__c(Bug__c=b.id, Test_Script__c=tst.id, Test_Step_Result__c=testst));
                        
                        }
                        insert BugLink;
                }
                PageReference savenclose = new PageReference('/'+Test);
                return savenclose;
        }

}