src/objects/MICO_Test_Template_Steps__c.object
<CustomObject>
    <description>Business Description: This object is used to record the individual steps of a test template. Test Templates are the master copy of a Test that can be executed many times by different people.

Used In: Mission Control App</description>
    <fields>
        <fullName>Test_Script__c</fullName>
        <label>Test Script</label>
        <referenceTo>MICO_Test_Templates__c</referenceTo>
        <relationshipName>MICO_Test_Script_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Test Script Step</label>
    <nameField>
        <displayFormat>TSS-{000000}</displayFormat>
        <label>Test Script Step Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Script Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MICO_Test_Templates__c.object
<CustomObject>
    <description>Business Description: This object is used by a Test Manager or Test Script Writer to create a master test script. This master test script can then be copied to different users to execute by adding those users to the &quot;Testers&quot; related list.

Used In: Mission Control App</description>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Test Script Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MICO_Tester__c.object
<CustomObject>
    <description>Business Description: This object is used by a Test Manager or Test Script Writer to assign a Test Template to a user to start testing. When a Test Manager assigns a Test Template to a user with this object this system automatically copies the Test Template and associated Test Template Steps to a Test and Test Steps.

Used In: Mission Control App</description>
    <fields>
        <fullName>Test_Phase__c</fullName>
        <label>Test Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Peer Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regression</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Test_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Test Template</label>
        <referenceTo>MICO_Test_Templates__c</referenceTo>
        <relationshipLabel>Testers</relationshipLabel>
        <relationshipName>MICO_Testers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MICO_Testers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tester</label>
    <nameField>
        <displayFormat>TU-{00000}</displayFormat>
        <label>Tester Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Testers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/test_createTestsForTester.cls
/** 
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class test_createTestsForTester {

    static testMethod void SingleAdd() {
         User tstuser = [select id from user where isActive=true LIMIT 1];
         //insert template record
        MICO_test_templates__c TT = new MICO_Test_templates__c(
            );
        insert TT;
        
        MICO_test_template_steps__c TTS = new MICO_test_template_steps__c(
        Test_Script__c = TT.id
        );
        insert TTS;
         
         
        MICO_Tester__c tster = new MICO_Tester__c(
            Test_Template__c = tt.id, 
            User__c = tstuser.id, 
            Test_Phase__c = 'Unit');
            
        insert tster;
         
         
    }
      static testMethod void MultiAdd() {
      List<User> tstuser = [select id from user where isActive=true AND Profile.Name = 'System Administrator' LIMIT 2];
        MICO_test_templates__c TT = new MICO_Test_templates__c(
            
            );
        insert TT;
        
        MICO_test_template_steps__c TTS = new MICO_test_template_steps__c(
        Test_Script__c = TT.id
        );
        insert TTS;
        
        list<MICO_Tester__c> tster = new List<MICO_Tester__c>();
            for(User u : tstuser){
                tster.add(new MICO_Tester__c(
                Test_Template__c = tt.id, 
                User__c = u.id, 
                Test_Phase__c = 'Unit'));
            }
        insert tster;
        
         
    }
}