src/objects/MICO_Project__c.object
<CustomObject>
    <description>Business Description: This object can be used to record projects in multi-project programs

Used In: Mission Control App</description>
    <label>Project mico</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MICO_Test__c.object
<CustomObject>
    <description>Business Description: This object is used to record the tests which have been executed. 

Each test is a copy of a &quot;Test Template&quot; which has been set up by a Test Manager or other Test Script writer. 

Tests are created by the system automatically when a user is added to the Testers Related list on a Test Template.

Used In: Mission Control App</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>This field will capture the status of approval for Test Execution records. It will be auto-populated through the workflow process: Created on 30/07/2014 by Himanshu Babaria :MICO</description>
        <inlineHelpText>The status of the approval. This is auto populated as the Test Execution goes through the process.</inlineHelpText>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Introduction__c</fullName>
        <formula>Template__r.Introduction__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>What is the overall aim of this test</inlineHelpText>
        <label>Introduction</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>MICO_Project__c</referenceTo>
        <relationshipLabel>Test Executions</relationshipLabel>
        <relationshipName>MICO_Test_Executions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The script being executed</inlineHelpText>
        <label>Template</label>
        <referenceTo>MICO_Test_Templates__c</referenceTo>
        <relationshipName>MICO_Test</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>MICO_User_Story__c</referenceTo>
        <relationshipName>MICO_Tests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Execution</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Test Execution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Executions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MICO_Test_Steps__c.object
<CustomObject>
    <description>Business Description: This object is used to record the test steps which have been executed.

Each Test Step is a copy of a &quot;Test Template Step&quot; which has been set up by a Test Manager or other Test Script writer.

Tests are created by the system automatically when a user is added to the Testers Related list on a Test Template.

Used In: Mission Control App</description>
    <fields>
        <fullName>Template_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>A link to the template step for this test. Action, Expected, Results, Tips etc are all calculated based on this link</inlineHelpText>
        <label>Template Step</label>
        <referenceTo>MICO_Test_Template_Steps__c</referenceTo>
        <relationshipName>MICO_Test_Step_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <label>Test</label>
        <referenceTo>MICO_Test__c</referenceTo>
        <relationshipName>MICO_Test_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Test Execution Step</label>
    <nameField>
        <label>Ref</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Execution Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MICO_Test_Template_Steps__c.object
<CustomObject>
    <description>Business Description: This object is used to record the individual steps of a test template. Test Templates are the master copy of a Test that can be executed many times by different people.

Used In: Mission Control App</description>
    <fields>
        <fullName>Test_Script__c</fullName>
        <label>Test Script</label>
        <referenceTo>MICO_Test_Templates__c</referenceTo>
        <relationshipName>MICO_Test_Script_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Test Script Step</label>
    <nameField>
        <displayFormat>TSS-{000000}</displayFormat>
        <label>Test Script Step Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Script Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MICO_Test_Templates__c.object
<CustomObject>
    <description>Business Description: This object is used by a Test Manager or Test Script Writer to create a master test script. This master test script can then be copied to different users to execute by adding those users to the &quot;Testers&quot; related list.

Used In: Mission Control App</description>
    <fields>
        <fullName>Introduction__c</fullName>
        <inlineHelpText>The introduction to this test script. This will be shown to testers before they start executing the test.</inlineHelpText>
        <label>Introduction</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>User_Story__r.Project__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <inlineHelpText>The title of the test script</inlineHelpText>
        <label>Test Title</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>MICO_User_Story__c</referenceTo>
        <relationshipName>MICO_Test_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Test Script Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MICO_User_Story__c.object
<CustomObject>
    <description>Business Description: This object is used to record User Stories with their acceptance criteria. These are linked to a sprint during sprint planning and delivered throughout the sprint process.

Used In: Mission Control App</description>
    <fields>
        <fullName>Acceptance_Criteria__c</fullName>
        <description>The Acceptance Criteria for this user story
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>Acceptance Criteria are the specific, testable and complete needs of this user story. They may follow a structure such as &quot;Given When Then&quot; or list out specific attributes and fields as needed. The Acceptance Criteria are used by developers and testers</inlineHelpText>
        <label>Acceptance Criteria</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>This field is used to capture the status of the approval process in User stories: Created on 06/11/2014 by Preeti Grover:MICO</description>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Compliance_Criteria__c</fullName>
        <description>Compliance / Quality Notes
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>Legal, regulatory or compliance related requirements and observations</inlineHelpText>
        <label>Compliance Criteria</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>The Project responsible for delivering this User Story
Created on 01/07/2014 by SMills 
MICO</description>
        <inlineHelpText>The Project responsible for delivering this User Story</inlineHelpText>
        <label>Project</label>
        <referenceTo>MICO_Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>MICO_Project_User_Stories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>US Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Test_Mico_AttachmentTrigger.cls
/*************************************************************************\
    @ Author        : Nitish Kumar
    @ Date          : 03-Sept-2014
    @ Description   : Test Class for MICO_AttachmentTrigger
****************************************************************************/
@isTest

private class Test_Mico_AttachmentTrigger {
	
	 public static MICO_Project__c project;
     public static MICO_User_Story__c testUserStory;
     public static MICO_Test_Templates__c testScript;
     public static MICO_Test_Template_Steps__c testScriptStep;
     public static MICO_Test__c testExecution;
     public static MICO_Test_Steps__c testExecutionStep;
     public static list<Attachment> insertAttachment;
     
      static testMethod void setupTestData() {
        
        project = new MICO_Project__c();
        project.Name = 'Test Project';
        insert project;
        
        testUserStory = new MICO_User_Story__c();
        testUserStory.Project__c = project.id;
        testUserStory.Acceptance_Criteria__c = 'OldAcceptanceCriteria';
        testUserStory.Compliance_Criteria__c = 'OldCC';
        testUserStory.Approval_Status__c = 'Open';
        insert testUserStory;
        
        insertAttachment = new list<Attachment>();
      	
      	testScript = new MICO_Test_Templates__c();
      	testScript.User_Story__c = testUserStory.Id ;
      	testScript.Introduction__c = 'Test' ;
      	testScript.Title__c = 'Test' ;
      	testScript.Approval_Status__c = 'Approved';
      	insert testScript;
      	
      	Attachment attachScript =new Attachment();   	
    	attachScript.Name='Test Attachment';
    	Blob bodyBlobScript=Blob.valueOf('Unit Test Attachment Body');
    	attachScript.body=bodyBlobScript;
        attachScript.parentId=testScript.id;
        insertAttachment.add(attachScript);
      	
      	testScriptStep = new MICO_Test_Template_Steps__c();
      	testScriptStep.Test_Script__c = testScript.Id ;
      	insert testScriptStep ;
      	
      	Attachment attachScriptStep =new Attachment();   	
    	attachScriptStep.Name='Test Attachment';
    	Blob bodyBlobScriptStep =Blob.valueOf('Unit Test Attachment Body');
    	attachScriptStep.body=bodyBlobScriptStep;
        attachScriptStep.parentId=testScriptStep.id;
        insertAttachment.add(attachScriptStep);
      	
      	testExecution = new MICO_Test__c();
      	testExecution.User_Story__c = testUserStory.Id ;
      	testExecution.Template__c = testScript.Id ;
      	testExecution.Project__c = project.Id ;
      	testExecution.Approval_Status__c = 'Open';
      	insert testExecution ;
      	
      	Attachment attachExecution =new Attachment();   	
    	attachExecution.Name='Test Attachment';
    	Blob bodyBlobExecution =Blob.valueOf('Unit Test Attachment Body');
    	attachExecution.body=bodyBlobExecution;
        attachExecution.parentId=testExecution.id;
        insertAttachment.add(attachExecution);
      	
      	testExecutionStep = new MICO_Test_Steps__c();
      	testExecutionStep.Test__c = testExecution.Id ;
      	testExecutionStep.Template_Step__c = testScriptStep.Id ;
      	insert testExecutionStep ;
      	
      	Attachment attachExecutionStep =new Attachment();   	
    	attachExecutionStep.Name='Test Attachment';
    	Blob bodyBlobExecutionStep =Blob.valueOf('Unit Test Attachment Body');
    	attachExecutionStep.body=bodyBlobExecutionStep;
        attachExecutionStep.parentId=testExecutionStep.id;
        insertAttachment.add(attachExecutionStep);
        
        insert insertAttachment ;
        
        testExecution.Approval_Status__c = 'Approved';
      	update testExecution ;
      	
      }
      
      static testMethod void testAttachmentTrigger() {
      	
      	setupTestData();
      	
      	Test.StartTest();
      	
      	try{
      	delete insertAttachment;
      	}
      	Catch(Exception ex){
      	}
      	
      	testScript.Approval_Status__c = 'Open';
      	update testScript;
      	
      	testExecution.Approval_Status__c = 'Open';
      	update testExecution ;
      	
      	delete insertAttachment;
      	
      	Test.StopTest();
      	
      }

}