src/objects/MICO_Bug__c.object
<CustomObject>
    <description>Business Description: This object is used to track defects (bugs) from being raised to resolved or rejected

Used In: Mission Control App</description>
    <fields>
        <fullName>Problem__c</fullName>
        <label>Problem Summary</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Raised</fullName>
                <color>#000000</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Triaged</fullName>
                <color>#333333</color>
            </picklistValues>
            <picklistValues>
                <fullName>Parked</fullName>
                <color>#0B24BE</color>
            </picklistValues>
            <picklistValues>
                <fullName>For Discussion</fullName>
                <color>#999999</color>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Development</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>In development</fullName>
                <color>#CC6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for testing</fullName>
                <color>#FFFF66</color>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked from testing</fullName>
                <color>#993399</color>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for sign-off</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Complete</fullName>
                <color>#006600</color>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Consolidated</fullName>
                <color>#006600</color>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - New User Story Required</fullName>
                <color>#006600</color>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - New User Story Created</fullName>
                <color>#006600</color>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Rejected</fullName>
                <color>#006600</color>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Unreplicable</fullName>
                <color>#006600</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Defect</label>
    <nameField>
        <displayFormat>DEF-{000000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Defects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MICO_Related_Bug__c.object
<CustomObject>
    <description>Business Description: This object allows you to link a defect to another one, e.g. where they are duplicated or closely related.

Used In: Mission Control App</description>
    <fields>
        <fullName>Bug__c</fullName>
        <label>Defect</label>
        <referenceTo>MICO_Bug__c</referenceTo>
        <relationshipLabel>Related Defects</relationshipLabel>
        <relationshipName>MICO_Related_Defects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Related_Bug__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Defect</label>
        <referenceTo>MICO_Bug__c</referenceTo>
        <relationshipLabel>Related Defects (Defect)</relationshipLabel>
        <relationshipName>MICO_Related_Defects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Related Defect</label>
    <nameField>
        <displayFormat>BugRel-{00000}</displayFormat>
        <label>Related Bug Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Defects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/test_CreateBugLink.cls
/** 
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class test_CreateBugLink {
    static testMethod void insertTest() {
        //insert new records
        list<MICO_Bug__c> newBugs = new List<MICO_Bug__c>();
        user assi = [select id from user where isActive = true limit 1];
        newBugs.add(new MICO_Bug__c(problem__c = 'test1', status__c = 'raised'));
        newBugs.add(new MICO_Bug__c(problem__c = 'test2', status__c = 'raised'));
        insert newBugs;
        MICO_Related_Bug__c link = new MICO_Related_Bug__c(Related_Bug__c=newBugs[0].id, Bug__c=newBugs[1].id);
        insert link;
        integer inte = [select count() from MICO_Related_Bug__c where Related_Bug__c = :newBugs[0].id or Bug__c=:newBugs[0].id];
        system.assert(inte==2);
    }
      
}