src/objects/MICO_Design__c.object
<CustomObject>
    <description>Business Description: This object is used to store designs for user stories. A design can be linked to many user stories and a user story linked to many designs.

Used In: Mission Control App</description>
    <fields>
        <fullName>Apex_Classes__c</fullName>
        <inlineHelpText>A list of apex classes (incuding test classes) used by this design</inlineHelpText>
        <label>Apex Classes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Apex_Trigger__c</fullName>
        <label>Apex Trigger</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Data_Model__c</fullName>
        <label>Data Model</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Fields__c</fullName>
        <label>Fields</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>MICO_Approval_Date__c</fullName>
        <description>This field will capture the date and time when design gets approved: Created on 23/07/2014 by Preeti Grover:MICO</description>
        <inlineHelpText>Date this has been approved by SME</inlineHelpText>
        <label>Approval Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MICO_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will capture the name of the approver for approving designs: Created on 23/07/2014 by Preeti Grover:MICO</description>
        <inlineHelpText>Your signature indicates that the design specifications are technically accurate, address how the computer system requirements are met, meet the requirements of LQP-302-16 and are traceable to one or more requirement.</inlineHelpText>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Designs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Objects__c</fullName>
        <label>Objects</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Other_Components__c</fullName>
        <inlineHelpText>A list of other components related to this design, e.g. SAP scripts etc</inlineHelpText>
        <label>Other Components</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Overview__c</fullName>
        <label>Overview</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Design</label>
    <nameField>
        <label>Design Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Designs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MICO_Design_History__c.object
<CustomObject>
    <description>Business Description: This object is used to automatically keep a track of all changes to Designs.

Technical Description: Populated by a trigger on Design this is an enhancement to the standard Design history functionality as this does not log changes to rich text fields

Used In: Mission Control App</description>
    <fields>
        <fullName>Apex_Classes__c</fullName>
        <label>Apex Classes</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Apex_Trigger__c</fullName>
        <label>Apex Trigger</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Approval_Date__c</fullName>
        <label>Approval Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Design_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Data_Model__c</fullName>
        <label>Data Model</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Design_Overview__c</fullName>
        <description>The overview before this person edited the Design
To see what the Design overview was changed to, compare this to the next Design History record.</description>
        <label>Design Overview</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Design__c</fullName>
        <label>Design</label>
        <referenceTo>MICO_Design__c</referenceTo>
        <relationshipLabel>Design History</relationshipLabel>
        <relationshipName>Design_History</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Fields__c</fullName>
        <label>Fields</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Objects__c</fullName>
        <label>Objects</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Other_Components__c</fullName>
        <label>Other Components</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Design History</label>
    <nameField>
        <displayFormat>DH-{00000}</displayFormat>
        <label>Design History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Design History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MICO_DesignTriggerClass.cls
public class MICO_DesignTriggerClass { 
  
	/*
	 * Creates custom Design history, as we can't do history tracking on rich text fields.
	 */
	public static void createNewDesignHistoryRecord(Map<Id,MICO_Design__c> mapDesign) {
    
		List<MICO_Design_History__c> lstDesignHistoryRecords = new List<MICO_Design_History__c>();
    
		for (Id DesignId : mapDesign.keySet()) {
		  MICO_Design_History__c newDesignHistoryRecord = new MICO_Design_History__c();
		  newDesignHistoryRecord.Design__c = mapDesign.get(DesignId).Id;
		  newDesignHistoryRecord.Design_Overview__c = mapDesign.get(DesignId).Overview__c;
		  newDesignHistoryRecord.Fields__c = mapDesign.get(DesignId).Fields__c;
		  newDesignHistoryRecord.Data_Model__c = mapDesign.get(DesignId).Data_Model__c;
		  newDesignHistoryRecord.Objects__c = mapDesign.get(DesignId).Objects__c;
		  newDesignHistoryRecord.Apex_Classes__c = mapDesign.get(DesignId).Apex_Classes__c;
		  newDesignHistoryRecord.Apex_Trigger__c = mapDesign.get(DesignId).Apex_Trigger__c;
		  newDesignHistoryRecord.Approver__c = mapDesign.get(DesignId).MICO_Approver__c;
		  newDesignHistoryRecord.Approval_Date__c = mapDesign.get(DesignId).MICO_Approval_Date__c;
		  newDesignHistoryRecord.Other_Components__c = mapDesign.get(DesignId).Other_Components__c;
		  lstDesignHistoryRecords.add(newDesignHistoryRecord);
		}   
    
		if (!lstDesignHistoryRecords.isEmpty()) {
		  insert lstDesignHistoryRecords;
		}
	}
  
	/*
	 * Stamps the approval date on the Design history records
	 */
	public static void updateApprovalDate(Map<Id,MICO_Design__c> mapApproval, DateTime approvalDate) {
     
		//get the latest Design History records to stamp the approval date    
		//Assign Approval date from approved design record to the design history record
		 
		// get all related history records
		List<MICO_Design_History__c> lstDesignHistoryApprovalRecords = [SELECT Id, Approval_Date__c, CreatedDate, Design__c
		 																FROM MICO_Design_History__c 
		 																WHERE Design__c IN :mapApproval.keySet() 
		 																ORDER BY Design__c, CreatedDate ASC];
		
		// get the latest history for each design
		Map<Id, MICO_Design_History__c> latestDesignHistories = new Map<Id, MICO_Design_History__c>();
		for (MICO_Design_History__c historyRecord : lstDesignHistoryApprovalRecords) {
			latestDesignHistories.put(historyRecord.Design__c, historyRecord);
		}
		
		// set the new datestamp
		for (MICO_Design_History__c historyRecord : latestDesignHistories.values()) {
			historyRecord.Approval_Date__c = approvalDate;
		}
	
		update latestDesignHistories.values();
	}
  
}