src/objects/PANG_Project__c.object
<CustomObject>
    <description>Used to group RWE Requests around a common quality</description>
    <fields>
        <fullName>Primary_Therapeutic_Area__c</fullName>
        <description>Indicate the primary therapeutic area for project</description>
        <inlineHelpText>Indicate the primary therapeutic area for project</inlineHelpText>
        <label>Primary Therapeutic Area</label>
        <picklist>
            <picklistValues>
                <fullName>Cardiovascular</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alzheimer’s &amp; Neurodegenerative Diseases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Psychiatry &amp; Pain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Autoimmune</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bone, Muscle, Joint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Urology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diabetes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oncology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Business Unit-Specific</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RWE Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RWE Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PANG_Request__c.object
<CustomObject>
    <description>Used to manage and track requests from RWE customers</description>
    <fields>
        <fullName>Primary_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Previous request by request name</inlineHelpText>
        <label>Primary Request</label>
        <referenceTo>PANG_Request__c</referenceTo>
        <relationshipLabel>Secondary Requests</relationshipLabel>
        <relationshipName>RWE_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Therapeutic_Area__c</fullName>
        <inlineHelpText>Indicate the primary therapeutic area for project</inlineHelpText>
        <label>Primary Therapeutic Area</label>
        <picklist>
            <picklistValues>
                <fullName>Cardiovascular</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alzheimer’s &amp; Neurodegenerative Diseases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Psychiatry &amp; Pain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Autoimmune</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bone, Muscle, Joint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Urology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diabetes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oncology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Business Unit-Specific</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Related_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Research question</inlineHelpText>
        <label>Related Project</label>
        <referenceTo>PANG_Project__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>RWE_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Study_Alias_Project_ID__c</fullName>
        <inlineHelpText>Study Identifier i.e. Study Alias/BCM/BoB ID or IMPACT #</inlineHelpText>
        <label>Study Alias / Project ID</label>
        <length>90</length>
        <type>Text</type>
    </fields>
    <label>RWE Request</label>
    <nameField>
        <label>Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RWE Requests</pluralLabel>
    <recordTypes>
        <fullName>Data_Sourcing</fullName>
        <active>true</active>
        <description>Provides working knowledge of available data resources that could support research question and assessment of potential new data sources.</description>
        <label>Data Sourcing</label>
    </recordTypes>
    <recordTypes>
        <fullName>EXPERT_Exception</fullName>
        <active>true</active>
        <description>This MQS required tool is used to document the rationale for not accepting all key comments during an EXPERT review or to identify protocol amendments that do not require EXPERT review.</description>
        <label>EXPERT Exception</label>
    </recordTypes>
    <recordTypes>
        <fullName>EXPERT_Review</fullName>
        <active>true</active>
        <description>Mandatory EXPERT Review service provides reviews of study designs and scientifically evaluates approaches for validity</description>
        <label>EXPERT Review</label>
    </recordTypes>
    <recordTypes>
        <fullName>EXPERT_Workstream</fullName>
        <active>true</active>
        <description>Submit a proposed workstream to research new methods &amp; analytic capabilities to address gaps</description>
        <label>EXPERT Workstream</label>
    </recordTypes>
    <recordTypes>
        <fullName>EXPERT_or_ACT_Consultation</fullName>
        <active>true</active>
        <description>Consultation request for EXPERT or ACT advice and expertise on study ideas, the right study design, appropriate outcomes and their measurement, analytic methods, scientific implications, etc.</description>
        <label>EXPERT or ACT Consultation</label>
    </recordTypes>
    <recordTypes>
        <fullName>Internal_Real_World_Data_Analysis</fullName>
        <active>true</active>
        <description>Provides data analysis skills and expertise to assist requestors in executing their studies</description>
        <label>Internal Real World Data Analysis</label>
    </recordTypes>
    <recordTypes>
        <fullName>RWE_Strategic_Consultation</fullName>
        <active>true</active>
        <description>(NEW) Consultation request to provide clarifying RWE questions regarding data sources available, best practice methodology and research plans, etc.</description>
        <label>RWE Strategic Consultation</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_PANG_AutoPopulateFieldsOnRequest.cls
/****************************************************************************************************************************************** 
 * Class Name   : Test_PANG_AutoPopulateFieldsOnRequest 
 * Description  : test Class for PANG_AutoPopulateFieldsOnRequest
 * Created By   : Deloitte Consulting
 * 
 *****************************************************************************************************************************************/
@istest(SeeAllData = false)
public class Test_PANG_AutoPopulateFieldsOnRequest {

    /* 
* @Method Name                    :  testAutoPopulateFieldOnRequestConstructor
* @Description                    :  Testing PANG_AutoPopulateFieldsOnRequest for Autopopulation/Insertion .
* @Return Type                    :  void
* @Parameters                     :  None
*/ 

    private static testmethod void testAutoPopulateFieldOnRequestConstructor() {
    
        User u = PANG_TestFactory.getTestingUser();
        PANG_TestFactory.givePermissions(u.id, 'PANG_RWE_Administrator');
        
        System.assertNotEquals(u.id,NULL); 
                
        system.runAs(u){
        
        map<string,id> mRecordTypes = new map<string,id>();
        for (RecordType oRecType: [SELECT id, developername FROM RecordType WHERE SobjectType = 'PANG_Request__c']) {
            mRecordTypes.put(oRecType.developername, oRecType.id);
        }
        
        //Inserting custom settings
        PANG_Request_FieldId_Settings__c p = new PANG_Request_FieldId_Settings__c(SetupOwnerId = UserInfo.getOrganizationId(),Study_Alias_Project_ID__c='123',Business_Unit_Primary__c='123',Primary_Therapeutic_Area__c='123');
        insert p;
        
        System.assertNotEquals(p,NULL); 
        
        test.starttest();

        list<PANG_Project__c> lprojects = PANG_TestFactory.returnStudies(7);
        insert lprojects;
        System.assertEquals(lprojects.size(),7); 
        
        System.assertNotEquals(lprojects.size(),NULL); 
        
        PANG_Request__c req = new PANG_Request__c(Name = 'Test1Request', recordTypeId = mRecordTypes.get('EXPERT_Review'));
        ApexPages.StandardController sc = new ApexPages.standardController(req);
        PANG_AutoPopulateFieldsOnRequest controller = new PANG_AutoPopulateFieldsOnRequest(sc);
        controller.autoPopulateFieldsOnRequest();       
        insert req;
        System.assertNotEquals(req.id,NULL); 
        
        
        PANG_Request__c req8 = new PANG_Request__c(Name = 'Test1Request', recordTypeId = mRecordTypes.get('EXPERT_Review'),Primary_Request__c=req.id);
        ApexPages.StandardController sc8 = new ApexPages.standardController(req8);
        PANG_AutoPopulateFieldsOnRequest controller8 = new PANG_AutoPopulateFieldsOnRequest(sc8);
        controller8.autoPopulateFieldsOnRequest(); 
        
        list<PANG_Request__c> lRequests = new list<PANG_Request__c>();

        lRequests.add( new PANG_Request__c(Name = 'Test1Request', Related_Project__c = lprojects[0].id, recordTypeId = mRecordTypes.get('EXPERT_Review')));
        lRequests.add(new PANG_Request__c(Name = 'Test1Request', Related_Project__c = lprojects[1].id, recordTypeId = mRecordTypes.get('EXPERT_or_ACT_Consultation')));
        lRequests.add(new PANG_Request__c(Name = 'Test1Request', Related_Project__c = lprojects[2].id, recordTypeId = mRecordTypes.get('EXPERT_Workstream')));
        lRequests.add( new PANG_Request__c(Name = 'Test1Request', Related_Project__c = lprojects[3].id, recordTypeId = mRecordTypes.get('Data_Sourcing')));
        lRequests.add( new PANG_Request__c(Name = 'Test1Request', Related_Project__c = lprojects[4].id, recordTypeId = mRecordTypes.get('Internal_Real_World_Data_Analysis')));
        lRequests.add( new PANG_Request__c(Name = 'Test1Request', Related_Project__c = lprojects[5].id, recordTypeId = mRecordTypes.get('RWE_Strategic_Consultation')));
        lRequests.add( new PANG_Request__c(Name = 'Test1Request', Related_Project__c = lprojects[6].id, recordTypeId = mRecordTypes.get('EXPERT_Exception')));
        
        insert lRequests;
        System.assertNotEquals(lRequests.size(),0);
        
        for(integer i=0;i<7;i++){
            ApexPages.StandardController sc1 = new ApexPages.standardController(lRequests[i]);
            PANG_AutoPopulateFieldsOnRequest controller1 = new PANG_AutoPopulateFieldsOnRequest(sc1);
            controller1.autoPopulateFieldsOnRequest();
        }

        test.stoptest();
    }
}

}