src/objects/PANG_Data_Asset__c.object
<CustomObject>
    <description>Inventory of real world data assets</description>
    <fields>
        <fullName>Description_of_Database__c</fullName>
        <label>Description of Database</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <label>RWE Data Asset</label>
    <nameField>
        <label>Data Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RWE Data Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PANG_Project__c.object
<CustomObject>
    <description>Used to group RWE Requests around a common quality</description>
    <label>RWE Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RWE Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PANG_Request__c.object
<CustomObject>
    <description>Used to manage and track requests from RWE customers</description>
    <fields>
        <fullName>Requestor_Functional_Area__c</fullName>
        <description>This is done as we cannot look up this information on the User record</description>
        <inlineHelpText>Functional area of the requestor</inlineHelpText>
        <label>Requestor Functional Area</label>
        <picklist>
            <picklistValues>
                <fullName>CDIO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GPORWE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MEDICAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTHER (BIOMETRICS, REGULATORY ETC.)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Therapeutic_Area_PE__c</fullName>
        <description>Therapeutic Area picklist used only for Partnership Exploration Requests</description>
        <inlineHelpText>Therapeutic Area picklist used only for Partnership Exploration Requests</inlineHelpText>
        <label>Therapeutic Area</label>
        <picklist>
            <picklistValues>
                <fullName>Cardiovascular</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alzheimer’s &amp; Neurodegenerative Diseases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Psychiatry &amp; Pain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Autoimmune</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bone, Muscle, Joint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Urology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diabetes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oncology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Business Unit-Specific</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>RWE Request</label>
    <nameField>
        <label>Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RWE Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_PANG_RWEFinalDeliverablesList.cls
/****************************************************************************************************************************************** 
 * Class Name   : Test_PANG_RWEFinalDeliverablesList
 * Description  : Test Class for PANG_RWEFinalDeliverablesList
 * Created By   : Deloitte Consulting
 * 
 *****************************************************************************************************************************************/
@isTest(seeAllData = false)
public class Test_PANG_RWEFinalDeliverablesList {
    /* 
* @Method Name                    :  test_RWEFinalDeliverablesList
* @Description                    :  Test Method for PANG_RWEFinalDeliverablesList
* @Return Type                    :  void
* @Parameters                     :  None
*/ 
    static testMethod void test_RWEFinalDeliverablesList() {

        User u = PANG_TestFactory.getTestingUser();
        String gname = 'PANG_RWE_Pangaea_Support_Team';
        PANG_TestFactory.assignGroup(u.id,gname);
        System.runAs(u) {

            PANG_Request__c req1;
            req1 = new PANG_Request__c();
            req1.name = 'test request1';
            req1.Requestor_Functional_Area__c = 'DISCOVERY';
            req1.Therapeutic_Area_PE__c = 'Autoimmune';
            insert req1;

            PANG_Data_Asset__c dataasset;
            dataasset = new PANG_Data_Asset__c();
            dataasset.Name = 'test';
            dataasset.Description_of_Database__c = 'test';
            insert dataasset;


            PANG_Project__c proj;
            proj = new PANG_Project__c();
            proj.Name = ' test project1';
            insert proj;


            ContentVersion doc = new ContentVersion();
            string before = 'Test';
            Blob beforeblob = Blob.valueOf(before);
            doc.Title = 'title';
            doc.PathOnClient = 'xyz';
            doc.VersionData = beforeblob;
            insert doc;
            doc.PANG_Request__c = req1.id;
            update doc;
            doc.PANG_Project__c = proj.id;
            update doc;
            doc.PANG_Data_Asset__c = dataasset.id;
            update doc;
            
            System.assertNotEquals(doc.PANG_Request__c, NULL);
            System.assertNotEquals(req1, NULL);
            System.assertNotEquals(doc.PANG_Project__c, NULL);
            System.assertNotEquals(proj, NULL);
            System.assertNotEquals(doc.PANG_Data_Asset__c, NULL);
            System.assertNotEquals(dataasset, NULL);

            test.startTest();
            ApexPages.StandardController stdController = new ApexPages.StandardController(req1);
            PANG_RWEFinalDeliverablesList controller = new PANG_RWEFinalDeliverablesList(stdController);
            ApexPages.StandardController stdController2 = new ApexPages.StandardController(proj);
            PANG_RWEFinalDeliverablesList controller2 = new PANG_RWEFinalDeliverablesList(stdController2);
            ApexPages.StandardController stdController3 = new ApexPages.StandardController(dataasset);
            PANG_RWEFinalDeliverablesList controller3 = new PANG_RWEFinalDeliverablesList(stdController3);
            controller.RequestPage();
            controller2.StudyPage();
            controller3.AssetPage();
            test.stopTest();
            System.assert(true);
        }
    }
}