src/objects/PANG_Data_Asset__c.object
<CustomObject>
    <description>Inventory of real world data assets</description>
    <label>RWE Data Asset</label>
    <nameField>
        <label>Data Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RWE Data Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PANG_Request__c.object
<CustomObject>
    <description>Used to manage and track requests from RWE customers</description>
    <fields>
        <fullName>Requestor_Functional_Area__c</fullName>
        <description>This is done as we cannot look up this information on the User record</description>
        <inlineHelpText>Functional area of the requestor</inlineHelpText>
        <label>Requestor Functional Area</label>
        <picklist>
            <picklistValues>
                <fullName>CDIO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GPORWE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MEDICAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTHER (BIOMETRICS, REGULATORY ETC.)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Request contact</inlineHelpText>
        <label>Requestor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RWE_Requests2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RWE Request</label>
    <nameField>
        <label>Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RWE Requests</pluralLabel>
    <recordTypes>
        <fullName>Data_Sourcing</fullName>
        <active>true</active>
        <description>Provides working knowledge of available data resources that could support research question and assessment of potential new data sources.</description>
        <label>Data Sourcing</label>
    </recordTypes>
    <recordTypes>
        <fullName>EXPERT_Review</fullName>
        <active>true</active>
        <description>Mandatory EXPERT Review service provides reviews of study designs and scientifically evaluates approaches for validity</description>
        <label>EXPERT Review</label>
    </recordTypes>
    <recordTypes>
        <fullName>EXPERT_or_ACT_Consultation</fullName>
        <active>true</active>
        <description>Consultation request for EXPERT or ACT advice and expertise on study ideas, the right study design, appropriate outcomes and their measurement, analytic methods, scientific implications, etc.</description>
        <label>EXPERT or ACT Consultation</label>
    </recordTypes>
    <recordTypes>
        <fullName>Internal_Real_World_Data_Analysis</fullName>
        <active>true</active>
        <description>Provides data analysis skills and expertise to assist requestors in executing their studies</description>
        <label>Internal Real World Data Analysis</label>
    </recordTypes>
    <recordTypes>
        <fullName>RWE_Strategic_Consultation</fullName>
        <active>true</active>
        <description>(NEW) Consultation request to provide clarifying RWE questions regarding data sources available, best practice methodology and research plans, etc.</description>
        <label>RWE Strategic Consultation</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_PANG_CreateRequestController.cls
/* Class Name  : Test_PANG_CreateRequestController
* Description  : Test Class for PANG_CreateRequestController
* Created By   : Deloitte
* Created Date : 4/10/2015
* Modification Log:  
* --------------------------------------------------------------------------------------------------------------------------------------
* Developer                Date                 Modification ID        Description 
* ---------------------------------------------------------------------------------------------------------------------------------------

*/
@
isTest(SeeAllData = false)

public class Test_PANG_CreateRequestController {

    /* 
    * @Method Name                    :  createDataMartWithOutDataAssets
    * @Description                    :  Method to insert datamart project without inhouse data assets 
    * @Return Type                    :  void
    * @Parameters                     :  None
    */      
    static testMethod void createDataMartWithOutDataAssets() {

        User u = PANG_TestFactory.getTestingUser();
        PANG_TestFactory.givePermissions(u.id, 'PANG_RWE_Administrator');

        System.runAs(u) {

            Test.startTest();
            
            list < PANG_Data_Asset__c > lDataAssets = PANG_TestFactory.returnDataAssets(3);
            Insert lDataAssets;

            PageReference pageRef = new pageReference('/apex/PANG_CreateRequests?recTypeName=Internal_Real_World_Data_Analysis');
            Test.setCurrentPage(pageRef);

            PANG_Request__c oRequest = new PANG_Request__c();

            ApexPages.StandardController stdController = new ApexPages.StandardController(oRequest);
            PANG_CreateRequestController controller = new PANG_CreateRequestController(stdController);
            
            controller.displayAcknowledge();
            
            controller.save();

            controller.attachmentBody1 = Blob.valueOf('Test Data1');
            controller.attachmentName1 = 'test1';
            controller.attachmentBody2 = Blob.valueOf('Test Data2');
            controller.attachmentName2 = 'test2';
            controller.attachmentBody3 = Blob.valueOf('Test Data3');
            controller.attachmentName3 = 'test2';

            oRequest = PANG_TestFactory.returnRequests(0, 1)[0];
            
            system.assertEquals(oRequest.id, null);
            controller.save();

            Test.stopTest();
        }
    }

    
        /* 
    * @Method Name                    :  createDataMartWithDataAssets
    * @Description                    :  Method to insert datamart project with inhouse data assets
    * @Return Type                    :  void
    * @Parameters                     :  None
    */  
    static testMethod void createDataMartWithDataAssets() {

        User u = PANG_TestFactory.getTestingUser();
        PANG_TestFactory.givePermissions(u.id, 'PANG_RWE_Administrator');

        System.runAs(u) {

            Test.startTest();

            list < PANG_Data_Asset__c > lDataAssets = PANG_TestFactory.returnDataAssets(3);
            Insert lDataAssets;

            System.assertNotEquals(lDataAssets.size(), 0);

            PageReference pageRef = new pageReference('/apex/PANG_CreateRequests?recTypeName=Internal_Real_World_Data_Analysis');
            Test.setCurrentPage(pageRef);

            PANG_Request__c oRequest = new PANG_Request__c();
            oRequest.name = 'test';
            oRequest.Requestor__c = userinfo.getUserID();
            oRequest.Requestor_Functional_Area__c = 'MEDICAL';
            oRequest.Therapeutic_Area_Primary__c = 'Cardiovascular';

            ApexPages.StandardController stdController = new ApexPages.StandardController(oRequest);
            PANG_CreateRequestController controller = new PANG_CreateRequestController(stdController);

            list < PANG_CreateRequestController.wDataAsset > lwDataAsset = controller.lDisplayAssets;

            lwDataAsset[0].isSelected = true;

            controller.displayAcknowledge();
            
            controller.save();

            controller.isAcknowledgeChecked = true;

            controller.attachmentBody1 = Blob.valueOf('Test Data1');
            controller.attachmentName1 = 'test1';
            controller.attachmentBody2 = Blob.valueOf('Test Data2');
            controller.attachmentName2 = 'test2';
            controller.attachmentBody3 = Blob.valueOf('Test Data3');
            controller.attachmentName3 = 'test2';

            system.assertEquals(oRequest.id, null);
            controller.save();
            Test.stopTest();
        }
    }

    
     /* 
    * @Method Name                    :  createOtherRequests
    * @Description                    :  Method to insert data sourcing request
    * @Return Type                    :  void
    * @Parameters                     :  None
    */ 
    static testMethod void createOtherRequests() {

        User u = PANG_TestFactory.getTestingUser();
        PANG_TestFactory.givePermissions(u.id, 'PANG_RWE_Administrator');

        System.runAs(u) {

            Test.startTest();

            list < string > lRecordtypes = new list < string > ();
            lRecordtypes.add('EXPERT_Review');
            lRecordtypes.add('EXPERT_or_ACT_Consultation');
            lRecordtypes.add('RWE_Strategic_Consultation');
            lRecordtypes.add('Data_Sourcing');

            for (string s: lRecordtypes) {
                PageReference pageRef = new pageReference('/apex/PANG_CreateRequests?recTypeName=' + s);
                Test.setCurrentPage(pageRef);
                PANG_Request__c oRequest = new PANG_Request__c();
                ApexPages.StandardController stdController = new ApexPages.StandardController(oRequest);
                PANG_CreateRequestController controller = new PANG_CreateRequestController(stdController);

                if (s == 'Data_Sourcing') {
                    oRequest.name = 'test';
                    oRequest.Requestor__c = userinfo.getUserID();
                    oRequest.Requestor_Functional_Area__c = 'MEDICAL';
                    oRequest.Therapeutic_Area_Primary__c = 'Cardiovascular';

                    controller.attachmentBody1 = Blob.valueOf('Test Data1');
                    controller.attachmentName1 = 'test1';
                    controller.attachmentBody2 = Blob.valueOf('Test Data2');
                    controller.attachmentName2 = 'test2';
                    controller.attachmentBody3 = Blob.valueOf('Test Data3');
                    controller.attachmentName3 = 'test2';

                    system.assertEquals(oRequest.id, null);
                    controller.save();
                }
            }
            Test.stopTest();
        }
    }

}