src/objects/PANG_Request__c.object
<CustomObject>
    <description>Used to manage and track requests from RWE customers</description>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>ACE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMBU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multiple Regions</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <inlineHelpText>The status of the request</inlineHelpText>
        <label>Request Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RWE Request</label>
    <nameField>
        <label>Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RWE Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_PANG_RequestList.cls
/* Class Name  : Test_PANG_RequestList
* Description  : Test Class for PANG_RequestList
* Created By   : Deloitte
* Created Date : 4/10/2015
* Modification Log:  
* --------------------------------------------------------------------------------------------------------------------------------------
* Developer                Date                 Modification ID        Description 
* ---------------------------------------------------------------------------------------------------------------------------------------

*/
 
@isTest(SeeAllData = false)

public class Test_PANG_RequestList {

    static testMethod void PANG_RequestList() {

        User u = PANG_TestFactory.getTestingUser();
        PANG_TestFactory.givePermissions(u.id, 'PANG_RWE_Administrator');

        System.runAs(u) {

            List < PANG_Request__c > lRequests = PANG_TestFactory.returnRequests(1000, 1000);
            insert lRequests;
            System.assertNotEquals(lRequests.size(), 0);

            Test.startTest();

            ApexPages.StandardSetController stdController = new ApexPages.StandardSetController(lRequests);
            PANG_RequestList controller = new PANG_RequestList();

            //Checking check boxes for filters
            List < PANG_RequestList.wFilterWrapper > lTherapeuticArea = controller.mRequestObjectStructure.get('Therapeutic_Area_Primary__c');
            List < PANG_RequestList.wFilterWrapper > lRecType = controller.mRequestObjectStructure.get('RecordTypeDevName');
            List < PANG_RequestList.wFilterWrapper > lRegion = controller.mRequestObjectStructure.get('Region__c');
            List < PANG_RequestList.wFilterWrapper > lStatus = controller.mRequestObjectStructure.get('Request_Status__c');

            controller.iPageNumber = 50;
            controller.pNoLimit = 10;
            controller.sort();
            controller.sort();
            controller.previousSField = 'Therapeutic_Area_Primary__c';

            system.assertEquals(controller.previousSField, 'Therapeutic_Area_Primary__c');

            controller.sort();
            controller.FetchDataForCriteria();
            controller.getRequests();

            system.assertNotEquals(controller.getRequests().size(), 0);

            controller.GoToPageNumber();
            controller.NextPageSeries();
            controller.PreviousPageSeries();

            lRegion[0].isSelected = true;
            controller.FetchDataForCriteria();

            lTherapeuticArea[0].isSelected = true;
            controller.FetchDataForCriteria();

            lStatus[0].isSelected = true;
            controller.FetchDataForCriteria();

            lRecType[0].isSelected = true;
            controller.FetchDataForCriteria();

            controller.sSearchWord = 'test';
            controller.FetchDataForCriteria();

            system.assertEquals(controller.sSearchWord, 'test');

            Test.stopTest();
        }
    }
}