src/objects/PANG_Project__c.object
<CustomObject>
    <description>Used to group RWE Requests around a common quality</description>
    <fields>
        <fullName>Primary_Therapeutic_Area__c</fullName>
        <description>Indicate the primary therapeutic area for project</description>
        <inlineHelpText>Indicate the primary therapeutic area for project</inlineHelpText>
        <label>Primary Therapeutic Area</label>
        <picklist>
            <picklistValues>
                <fullName>Cardiovascular</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alzheimer’s &amp; Neurodegenerative Diseases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Psychiatry &amp; Pain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Autoimmune</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bone, Muscle, Joint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Urology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diabetes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oncology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Business Unit-Specific</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_ID__c</fullName>
        <inlineHelpText>IMPACT/BoB ID</inlineHelpText>
        <label>Project ID</label>
        <length>90</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>RWE Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RWE Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PANG_Request__c.object
<CustomObject>
    <description>Used to manage and track requests from RWE customers</description>
    <fields>
        <fullName>Primary_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Previous request by request name</inlineHelpText>
        <label>Primary Request</label>
        <referenceTo>PANG_Request__c</referenceTo>
        <relationshipLabel>Secondary Requests</relationshipLabel>
        <relationshipName>RWE_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Therapeutic_Area__c</fullName>
        <inlineHelpText>Indicate the primary therapeutic area for project</inlineHelpText>
        <label>Primary Therapeutic Area</label>
        <picklist>
            <picklistValues>
                <fullName>Cardiovascular</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alzheimer’s &amp; Neurodegenerative Diseases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Psychiatry &amp; Pain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Autoimmune</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bone, Muscle, Joint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Urology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diabetes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oncology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Business Unit-Specific</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>ACE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMBU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multiple Regions</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Related_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Research question</inlineHelpText>
        <label>Related Project</label>
        <referenceTo>PANG_Project__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>RWE_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Request contact</inlineHelpText>
        <label>Requestor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RWE_Requests2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Study_Alias_Project_ID__c</fullName>
        <inlineHelpText>Study Identifier i.e. Study Alias/BCM/BoB ID or IMPACT #</inlineHelpText>
        <label>Study Alias / Project ID</label>
        <length>90</length>
        <type>Text</type>
    </fields>
    <label>RWE Request</label>
    <nameField>
        <label>Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RWE Requests</pluralLabel>
    <recordTypes>
        <fullName>Data_Sourcing</fullName>
        <active>true</active>
        <description>Provides working knowledge of available data resources that could support research question and assessment of potential new data sources.</description>
        <label>Data Sourcing</label>
    </recordTypes>
    <recordTypes>
        <fullName>EXPERT_Exception</fullName>
        <active>true</active>
        <description>This MQS required tool is used to document the rationale for not accepting all key comments during an EXPERT review or to identify protocol amendments that do not require EXPERT review.</description>
        <label>EXPERT Exception</label>
    </recordTypes>
    <recordTypes>
        <fullName>EXPERT_Review</fullName>
        <active>true</active>
        <description>Mandatory EXPERT Review service provides reviews of study designs and scientifically evaluates approaches for validity</description>
        <label>EXPERT Review</label>
    </recordTypes>
    <recordTypes>
        <fullName>EXPERT_Workstream</fullName>
        <active>true</active>
        <description>Submit a proposed workstream to research new methods &amp; analytic capabilities to address gaps</description>
        <label>EXPERT Workstream</label>
    </recordTypes>
    <recordTypes>
        <fullName>EXPERT_or_ACT_Consultation</fullName>
        <active>true</active>
        <description>Consultation request for EXPERT or ACT advice and expertise on study ideas, the right study design, appropriate outcomes and their measurement, analytic methods, scientific implications, etc.</description>
        <label>EXPERT or ACT Consultation</label>
    </recordTypes>
    <recordTypes>
        <fullName>Internal_Real_World_Data_Analysis</fullName>
        <active>true</active>
        <description>Provides data analysis skills and expertise to assist requestors in executing their studies</description>
        <label>Internal Real World Data Analysis</label>
    </recordTypes>
    <recordTypes>
        <fullName>RWE_Strategic_Consultation</fullName>
        <active>true</active>
        <description>(NEW) Consultation request to provide clarifying RWE questions regarding data sources available, best practice methodology and research plans, etc.</description>
        <label>RWE Strategic Consultation</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PANG_AutoPopulateFieldsOnRequest.cls
/****************************************************************************************************************************************** 
* Class Name   : PANG_AutoPopulateFieldsOnRequest 
* Description  : Class to Autopopulate fields from Study Object
* Created By   : Deloitte Consulting
* 
*****************************************************************************************************************************************/
Public with sharing class PANG_AutoPopulateFieldsOnRequest {
    
    Public PANG_Project__c oProject;
    Public PANG_Request__c oRequest;
    Public User uname;
    Public Boolean isFromStudy;
    public String PickValues;
    
    //Loading the constructor the page
    public PANG_AutoPopulateFieldsOnRequest(ApexPages.StandardController controller) {
        
        uname = [select Id, Name from User where Id = : UserInfo.getUserId() LIMIT 1];
        
        If((PANG_Request__c) controller.getRecord() != NULL) {
            
            oRequest = (PANG_Request__c) controller.getRecord();
            
            If(oRequest.Related_Project__c != NULL && oRequest.RWD_Inventory__c == NULL && String.valueOf(oRequest.Related_Project__c) != '') {
                
                oProject = [SELECT id, Business_Unit_Primary__c, Therapeutic_Area_Primary__c, Region__c, Project_ID__c FROM PANG_Project__c WHERE id = : oRequest.Related_Project__c];
                
                isFromStudy = True;
                
            } else if (oRequest.Related_Project__c != NULL) {
                isFromStudy = False;
            }
        }
    }
    
    /* 
* @Method Name                    :  autoPopulateFieldsOnRequest
* @Description                    :  This method populates the Therapeutic area , business unit, study id fields on request considering wheter the request is secondary or coming from study
* @Return Type                    :  pagereference
* @Parameters                     :  None
*/     
    
    public pagereference autoPopulateFieldsOnRequest() {
        
        PANG_Request_FieldId_Settings__c oCustSetting = PANG_Request_FieldId_Settings__c.getOrgDefaults();
        
        String sRecordTypeDeveloperName;
        
        String keyPrefix = PANG_Request__c.sObjectType.getDescribe().getKeyPrefix();
        
        Pagereference p = new pagereference('/' + keyPrefix + '/e?');
        p.getparameters().putall(ApexPages.currentPage().getparameters());
        p.getparameters().put('nooverride', '1');
        p.getparameters().remove('sfdc.override');
        p.getparameters().remove('save_new');
        
        if (oRequest.Primary_Request__c != NULL) {
            p.getparameters().put('saveURL', oRequest.Primary_Request__c);
        } 
        Else If(oRequest.Related_Project__c != NULL) {
            p.getparameters().put('saveURL', oRequest.Related_Project__c);
        } 
        
        if (oRequest.recordtypeid != null) {
            sRecordTypeDeveloperName = [Select developername from RecordType where id = : oRequest.recordtypeid].developername;
            p.getparameters().put('CF' + oCustSetting.Requestor__c + '_lkid', Uname.id);
            p.getparameters().put('CF' + oCustSetting.Requestor__c, Uname.Name);
        }
        if (sRecordTypeDeveloperName == 'EXPERT_Review' && isFromStudy == TRUE) {
            p.getparameters().put(oCustSetting.Study_Alias_Project_ID__c, oProject.Project_ID__c);
            p.getparameters().put(oCustSetting.Business_Unit_Primary__c, oProject.Business_Unit_Primary__c);
            p.getparameters().put(oCustSetting.Primary_Therapeutic_Area__c, oProject.Therapeutic_Area_Primary__c);
            
        } else if (sRecordTypeDeveloperName == 'EXPERT_or_ACT_Consultation' && isFromStudy == TRUE) {
            p.getparameters().put(oCustSetting.Study_Alias_Project_ID__c, oProject.Project_ID__c);
            p.getparameters().put(oCustSetting.Business_Unit_Primary__c, oProject.Business_Unit_Primary__c);
            p.getparameters().put(oCustSetting.Primary_Therapeutic_Area__c, oProject.Therapeutic_Area_Primary__c);
            
        } else if (sRecordTypeDeveloperName == 'EXPERT_Exception' && isFromStudy == TRUE) {
            p.getparameters().put(oCustSetting.Study_Alias_Project_ID__c, oProject.Project_ID__c);
            p.getparameters().put(oCustSetting.Business_Unit_Primary__c, oProject.Business_Unit_Primary__c);
            
        } else if (sRecordTypeDeveloperName == 'EXPERT_Workstream' && isFromStudy == TRUE) {
            p.getparameters().put(oCustSetting.Study_Alias_Project_ID__c, oProject.Project_ID__c);
            p.getparameters().put(oCustSetting.Business_Unit_Primary__c, oProject.Business_Unit_Primary__c);
            
        } else if (sRecordTypeDeveloperName == 'Data_Sourcing' && isFromStudy == TRUE) {
            p.getparameters().put(oCustSetting.Study_Alias_Project_ID__c, oProject.Project_ID__c);
            p.getparameters().put(oCustSetting.Business_Unit_Primary__c, oProject.Business_Unit_Primary__c);
            p.getparameters().put(oCustSetting.Primary_Therapeutic_Area__c, oProject.Therapeutic_Area_Primary__c);
            
        } else if (sRecordTypeDeveloperName == 'Internal_Real_World_Data_Analysis' && isFromStudy == TRUE) {
            p.getparameters().put(oCustSetting.Study_Alias_Project_ID__c, oProject.Project_ID__c);
            p.getparameters().put(oCustSetting.Business_Unit_Primary__c, oProject.Business_Unit_Primary__c);
            p.getparameters().put(oCustSetting.Primary_Therapeutic_Area__c, oProject.Therapeutic_Area_Primary__c);
            
        } else if (sRecordTypeDeveloperName == 'RWE_Strategic_Consultation' && isFromStudy == TRUE) {
            p.getparameters().put(oCustSetting.Study_Alias_Project_ID__c, oProject.Project_ID__c);
            p.getparameters().put(oCustSetting.Business_Unit_Primary__c, oProject.Business_Unit_Primary__c);
            p.getparameters().put(oCustSetting.Primary_Therapeutic_Area__c, oProject.Therapeutic_Area_Primary__c);
        }
        p.setRedirect(true);
        return p;
    }
}