src/objects/PANG_Request__c.object
<CustomObject>
    <description>Used to manage and track requests from RWE customers</description>
    <fields>
        <fullName>Partnership_Sponsor__c</fullName>
        <label>Partnership Sponsor</label>
        <picklist>
            <picklistValues>
                <fullName>SHIRLOC (Diabetes)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PROactive (USHO)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RWE, Inc.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GPORWE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>ACE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMBU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multiple Regions</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RWE Request</label>
    <nameField>
        <label>Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RWE Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_PANG_PartnerShipList.cls
/* Class Name  : Test_PANG_PartnerShipList
* Description  : Test Class for PANG_PartnerShipList
* Created By   : Deloitte
* Created Date : 4/10/2015
* Modification Log:  
* --------------------------------------------------------------------------------------------------------------------------------------
* Developer                Date                 Modification ID        Description 
* ---------------------------------------------------------------------------------------------------------------------------------------

*/
@
isTest(SeeAllData = false)

public class Test_PANG_PartnerShipList {

    static testMethod void test_partnershiplist() {

        User u = PANG_TestFactory.getTestingUser();
        PANG_TestFactory.givePermissions(u.id, 'PANG_RWE_Administrator');

        System.runAs(u) {

            List < PANG_Request__c > lRequests = PANG_TestFactory.returnRequests(1000, 1000);
            insert lRequests;
            System.assertNotEquals(lRequests.size(), 0);

            test.startTest();
            ApexPages.StandardSetController stdController = new ApexPages.StandardSetController(lRequests);
            PANG_PartnerShipList controller = new PANG_PartnerShipList();

            //Checking check boxes for filters
            List < PANG_PartnerShipList.wFilterWrapper > lStatus = controller.mPartnershipStructure.get('Partnership_Status__c');
            List < PANG_PartnerShipList.wFilterWrapper > lSponser = controller.mPartnershipStructure.get('Partnership_Sponsor__c');
            List < PANG_PartnerShipList.wFilterWrapper > lRegion = controller.mPartnershipStructure.get('Region__c');


            controller.iPageNumber = 50;
            controller.pNoLimit = 10;
            controller.sort();
            controller.sort();
            controller.previousSField = 'Partnership_Sponsor__c';

            system.assertEquals(controller.previousSField, 'Partnership_Sponsor__c');

            controller.sort();
            controller.FetchDataForCriteria();
            controller.getPartnerships();

            system.assertNotEquals(controller.getPartnerships().size(), 0);

            controller.GoToPageNumber();
            controller.NextPageSeries();
            controller.PreviousPageSeries();

            lRegion[0].isSelected = true;
            controller.FetchDataForCriteria();

            lStatus[0].isSelected = true;
            controller.FetchDataForCriteria();

            lSponser[0].isSelected = true;
            controller.FetchDataForCriteria();

            controller.sSearchWord = 'test';
            controller.FetchDataForCriteria();

            system.assertEquals(controller.sSearchWord, 'test');

            controller.sPartnershipType = 'Payer';
            controller.FetchDataForCriteria();

            system.assertEquals(controller.sPartnershipType, 'Payer');

            test.stopTest();

        }
    }
}