src/objects/PANG_Data_Asset__c.object
<CustomObject>
    <description>Inventory of real world data assets</description>
    <fields>
        <fullName>Description_of_Database__c</fullName>
        <label>Description of Database</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <label>RWE Data Asset</label>
    <nameField>
        <label>Data Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RWE Data Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_PANG_CreateDataAssetController.cls
/****************************************************************************************************************************************** 
* Class Name   : Test_PANG_CreateDataAssetController 
* Description  : test class for PANG_CreateDataAssetController
* Created By   : Deloitte Consulting
* 
*****************************************************************************************************************************************/
@isTest(SeeAllData=false)
public class Test_PANG_CreateDataAssetController {

    /* 
    * @Method Name                    :  createDataAsset
    * @Description                    :  Test Method for Create Data Asset Controller
    * @Return Type                    :  void
    * @Parameters                     :  None
    */   
    static testMethod void createDataAsset() {
    
    User u = PANG_TestFactory.getTestingUser();
     System.runAs(u) {
        
        Boolean isSaved = false;
        PANG_Data_asset__c oDataAsset = new PANG_Data_asset__c();
        oDataAsset.Name = 'test';
        oDataAsset.Description_of_Database__c = 'test';
        insert oDataAsset;
        System.assertNotEquals(oDataAsset,NULL);      
        Blob b = Blob.valueOf('Test Data');
        Attachment attachment = new Attachment();
        attachment.ParentId = oDataAsset.id;
        attachment.Name = 'Test Attachment for Parent';
        attachment.Body = b;
        insert(attachment);
        System.assertNotEquals(attachment,NULL); 
        Test.startTest(); 
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(oDataAsset);
        PANG_CreateDataAssetController controller = new  PANG_CreateDataAssetController(stdController);
        controller.attachmentBody1 = b;
        controller.attachmentName1 = 'Test Attachment for Parent';
        controller.attachmentBody2 = b;
        controller.attachmentName2 = 'Test Attachment for Parent';
        controller.attachmentBody3 = b;
        controller.attachmentName3 = 'Test Attachment for Parent';
        controller.saveApplicant();
        System.assert(true);
        Test.stopTest();  
    }
    
    }
    
    }