src/objects/PANG_Country__c.object
<CustomObject>
    <description>Inventory of countries paired with their respective region.</description>
    <label>RWE Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RWE Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PANG_Project__c.object
<CustomObject>
    <description>Used to group RWE Requests around a common quality</description>
    <label>RWE Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RWE Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PANG_Related_Country__c.object
<CustomObject>
    <description>Join object relating RWE Countries to RWE Projects and RWE Requests</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <referenceTo>PANG_Country__c</referenceTo>
        <relationshipLabel>Projects / Requests</relationshipLabel>
        <relationshipName>RWE_Request_Countries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>PANG_Project__c</referenceTo>
        <relationshipLabel>Countries</relationshipLabel>
        <relationshipName>RWE_Related_Countries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RWE Related Country</label>
    <nameField>
        <displayFormat>RWE-RC-{000000000}</displayFormat>
        <label>Related Country ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RWE Related Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PANG_Request__c.object
<CustomObject>
    <description>Used to manage and track requests from RWE customers</description>
    <fields>
        <fullName>Requestor_Functional_Area__c</fullName>
        <description>This is done as we cannot look up this information on the User record</description>
        <inlineHelpText>Functional area of the requestor</inlineHelpText>
        <label>Requestor Functional Area</label>
        <picklist>
            <picklistValues>
                <fullName>CDIO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GPORWE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MEDICAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTHER (BIOMETRICS, REGULATORY ETC.)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Therapeutic_Area_PE__c</fullName>
        <description>Therapeutic Area picklist used only for Partnership Exploration Requests</description>
        <inlineHelpText>Therapeutic Area picklist used only for Partnership Exploration Requests</inlineHelpText>
        <label>Therapeutic Area</label>
        <picklist>
            <picklistValues>
                <fullName>Cardiovascular</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alzheimer’s &amp; Neurodegenerative Diseases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Psychiatry &amp; Pain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Autoimmune</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bone, Muscle, Joint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Urology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diabetes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oncology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Business Unit-Specific</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>RWE Request</label>
    <nameField>
        <label>Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RWE Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_PANG_RedirectOnSave.cls
/****************************************************************************************************************************************** 
 * Class Name   : Test_PANG_RedirectOnSave
 * Description  : Test Class for Test_PANG_RedirectOnSave
 * Created By   : Deloitte Consulting
 * 
 *****************************************************************************************************************************************/
@isTest  (SeeAllData = false)
public class Test_PANG_RedirectOnSave {
    /* 
* @Method Name                    :  test_RedirectOnSave
* @Description                    :  Test Method for PANG_RedirectOnSave
* @Return Type                    :  void
* @Parameters                     :  None
*/ 
    static testMethod void test_RedirectOnSave() {
    
        User u = PANG_TestFactory.getTestingUser();
        PermissionSet ps = [Select id From PermissionSet WHERE Name = 'PANG_RWE_Member'];   
        List <PermissionSetAssignment> perSetAsLst = new List <PermissionSetAssignment>();
        
        PermissionSetAssignment psAssignments = new PermissionSetAssignment();
        psAssignments=new PermissionSetAssignment(AssigneeId = u.id,PermissionSetId = ps.id);
        perSetAsLst.add(psAssignments);
        insert perSetAsLst;
        
        System.runAs(u){
            
        PANG_Request__c req1;
        req1 = new PANG_Request__c();
        req1.name = 'test request1';
        req1.Requestor_Functional_Area__c = 'DISCOVERY';
        req1.Therapeutic_Area_PE__c = 'Autoimmune';
        insert req1;
        System.assertNotEquals(req1,null); 
        
        PANG_Project__c proj;
        proj = new PANG_Project__c();
        proj.Name='test';
        insert proj;
        System.assertNotEquals(proj,null); 
        
        PANG_Country__c country;
        country = new PANG_Country__c();
        country.Name='Japan';
        insert country;
        
        PANG_Related_Country__c relcountry;
        relcountry = new PANG_Related_Country__c();
        relcountry.Project__c=proj.id;
        relcountry.Country__c=country.id;
        insert relcountry;
        System.assertNotEquals(relcountry,null);
        
        test.startTest();
        ApexPages.StandardController stdController = new ApexPages.StandardController(req1);
        ApexPages.StandardController stdController1 = new ApexPages.StandardController(relcountry);
        PANG_RedirectOnSave controller = new  PANG_RedirectOnSave(stdController);
        PANG_RedirectOnSave controller1 = new  PANG_RedirectOnSave(stdController1);
        
        controller.onloadFromInventory();
        controller1.onloadFromRequest();
        controller1.onloadFromRequestForResource();
        controller1.onloadFromStudy();
        System.assert(true);
        test.stopTest();
            
        }
    }
}