src/objects/Product_Group_GLBL__c.object
<CustomObject>
    <description>Object to store Product Information, mastered Product Group records from Material ODS : MERC : Created on 09/27/2013 by Katy Lorenti, Mavens Consulting</description>
    <fields>
        <fullName>Cntry_Cd_GLBL__c</fullName>
        <description>Unique code which describes the country which uses the translated names on this record.
Created by John A Adams 11/1/2013</description>
        <label>Country Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Crt_Dt_GLBL__c</fullName>
        <description>This represents the date on which the record was initially created in the Material Master Hub database.
Created by John A Adams 11/1/2013</description>
        <label>ODS Created Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Dialect_Nm_GLBL__c</fullName>
        <description>Language dialect of the translated data.
Created by John A Adams 11/1/2013</description>
        <label>Dialect Name</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grp_Prps_Cd_GLBL__c</fullName>
        <description>Classification of the purpose of a product grouping.   
Created by John A Adams 11/1/2013</description>
        <label>Purpose Code</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lst_Pblsh_Dt_GLBL__c</fullName>
        <description>This represents the date on which information was last published for this record to the Material ODS.  This date will be populated when the record is initially created in the ODS or when it is updated.  This is one of the two fields that would be used for delta detection of changes to the Material ODS.  
Created by John A Adams 11/1/2013</description>
        <label>Last Publish Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Updt_Dt_GLBL__c</fullName>
        <description>This represents the date on which the record was last updated in the Material Master Hub database. 
Created by John A Adams 11/1/2013</description>
        <label>ODS Updated Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Product Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MERC_MeetingProductNewEditTest.cls
@isTest
private class MERC_MeetingProductNewEditTest {
	
	@isTest static void test_should_run_without_error() {

		Product_Group_GLBL__c product = new Product_Group_GLBL__c();
		product.Cntry_Cd_GLBL__c = 'ZZ';
		product.Crt_Dt_GLBL__c = Date.today();
		product.Dialect_Nm_GLBL__c = 'Enlgish';
		product.Grp_Prps_Cd_GLBL__c = 'MKTP';
		product.Lst_Pblsh_Dt_GLBL__c = Date.today();
		product.Updt_Dt_GLBL__c = Date.today();
		insert product;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(product);
        
        //no assertion needed just need to make sure this runs successfully
        MERC_MeetingProductNewEdit meetingPrductNewEdit = new MERC_MeetingProductNewEdit(sc);
	}
}